### ISSUE TITLE
Plots: Improving the Grid

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#1254]
Currently, the grid for the plots is built following these rules:
- No matter the size of the plots, they will arrange themselves in rows as long as they can fit one next to the other
- For large plots, we initially set the width to be 100% of its parent (the whole screen for now) minus its padding (20px). Once the plot has reached a width of 1000px, it will stop growing and align itself in the center until there is enough room for another plot to fit at its side (the parent being at least 2060px [1000px * 2 + 3 * 20px] [max_plot_width * 2 + left_gap + middle_gap + right_gap])
- For regular plots, we initially set the width to be 50% of its parent with a gap of 20px between the two 50% plots. Once the plots have reached a size of 500px, they will stop growing and align themselves in the middle until there is enough room for other plots (1, 2, or more) to fit at their side.
- For small plots, we initially set the width to be 33% of its parent with two gaps of 20px in between the plots. Once the plots have reached a size of 300px, they will stop growing and allow other plots to fit at their side once there is enough room.
- For multi-view plots, they follow the same rules as above, except that their width and max-width are multiplied with the scale of the plot. The scale is calculated by the number of revisions of the plot. If there are two revisions in the plot that is regular size, its width will now be 50% * 2 and its max-width will be 500px * 2.
## Drawbacks from These Current Rules
The bigger the size, the longer it will take for another plot to fit on the row when the plots have reached their max-width. For example, between the window sizes of 1040px and 2060px, the plots will appear pretty much static.
When the window is extra small, small plots might look very small. At a window size of 400px (the user might place multiple web views next to another), a plot would have a width of 106px.
### Media Queries
By using media queries, we could further fine-tune how the plots react when resizing the window. That means that we could have the large plots be 100% of the screen until it reaches 1000px, then the plots could be 50%. With similar rules for the regular and small plots. We could then avoid the max-width and have plots always taking the maximum space, which would make things more fluid.
### Let the User Do the Resizing
We could remove the plots sizes entirely and let the user resize the plots, either individually or all at once. Resizing them individually would allow total control to the user, but it could become a nightmare to manage when there are too many plots. Resizing that way could also be problematic when resizing the web view.
### Allow Zooming
It could also be interesting for the user to see multiple plots at once (small or regular size) and then zoom on a certain plot to analyze. This could be done while applying the current rules and media queries.
## Conclusion
I think that by adding media queries to what we currently have, we could make the current grid much more fluid, all the while continuing to use the current sizes.
The user resizing the plots would be a lot harder to manage for us and possibly the user.
Zooming on a certain plot could be a nice addition in the future.

**Comment by maxagin** [comment]
Great stuff @sroy3 👍 
What you have put together is very helpful. Closing this for now. 
I will be reflecting here:
https://github.com/iterative/design/issues/31
https://github.com/iterative/design/issues/34
