### ISSUE TITLE
Show child count in rows with children

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1265]
We want to display a count of children somewhere in or around each row with children (experiments with checkpoints). This issue doesn't currently have design details, but it's simple enough that a dev design can be implemented before a real one is made and we can adapt if necessary.

![design screenshot](https://user-images.githubusercontent.com/9111807/151627524-b6db01ff-14da-4119-982f-0ff21be76829.png)

Considerations:
- Do we want to show this count on branches counting the amount of experiments as well as experiments counting checkpoints? I'd say probably.

**Comment by mattseddon** [comment]
Closing as duplicate.
