### ISSUE TITLE
Rework `columnOrder` and `columnWidths` from Extension to only come with the first message.

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1266]
In the extension, we use an informal pattern where we store user settings- column order, widths, and sizes in the table and section names and sizes in the plots. Right now, in the experiments table, the extension sends `columnWidths` and `columnOrder` on every data update despite it only ever being used on initialization.

In general terms, the way to solve this is to remove this options data from the standard data message add a new extension-to-webview message that effectively does what our current standard message does, but is only sent once on initialization.

While this isn't necessarily something that needs to be solved, doing so would undoubtedly be more efficient even if not to a significant degree.

**Comment by shcheklein** [comment]
Closing as not a priority for now
