### ISSUE TITLE
Show a limited amount of checkpoints that can optionally be expanded further

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1269]
This Issue tracks the implementation of the feature described by this design:

![design screenshot](https://user-images.githubusercontent.com/9111807/151634653-1e59b067-b175-480d-a1bd-2e6bc7399c07.png)

While not described, my interpretation is that this effectively a third state between fully collapsed and fully expanded, where only the four most recent children are shown (the parent making it a group of 5) and an option to show the rest is presented.
 
From there, the user can either click the control to show the rest of the rows or collapse the row if they're not interested in that row.

A case I'd assume we want is for the state would be reset after a column is collapsed: i.e.:
1. The row is shown with only four children
2. The user expands children so all are visible
3. The user collapses the row
4. The user expands the row, and it's back in the state where only four children are shown

If anyone think the feature should behave differently, please do bring it up and we can discuss

**Comment by maxagin** [comment]
Another option is to give users more tools to organize the content. Example: "Collapse EXPs and checkpoints #2071".
Argument: 
1. User has all the information in front, without making any additional actions, like opening the hidden blocks in every EXP.
2. User decides what to do with the information and applies appropriate actions: group & hide, delete.

I am going to add this ticket to one of the existing stories and close it for now.
Thank you @rogermparent (We miss you!)
