### ISSUE TITLE
Add more info to experiment table cell tooltips

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1383]
#1366 introduced header tooltips for the Experiments table, allowing users to view the full string of a header even when cut off.

We also want tooltips on cells similarly to how Studio does it, but how many features we adopt is something we'll need to sort out.

For reference, here is each type of cell tooltip in Studio I can see on my test repo:

- I've only ever seen Param tooltips show the value of the cell in question, but they're still formatted in a way that would allow for extra fields:
  ![image](https://user-images.githubusercontent.com/9111807/156660348-5bef00cc-6810-49d5-a14d-6d6545487c64.png)

- Metric cells use an extra field to add a delta comparing them to the cell above. Param cells do not, even if they're numbers that theoretically could.
  ![metric number tooltip](https://user-images.githubusercontent.com/9111807/156659705-19f27c5c-b7a0-48f6-ada4-4721e962327a.png)

- Some metrics have full files associated with them, and the resulting tooltips contain even more info like URL, commit, and hash
  ![metric file tooltip](https://user-images.githubusercontent.com/9111807/156659847-2eadaa0d-743b-4e41-a4a6-3fe591ae2390.png)

- Special cells like Commit, Timestamp, and Message have completely different simple tooltips that are more like the header ones in design:
  ![special cell tooltip](https://user-images.githubusercontent.com/9111807/156659492-0a726c4b-d722-456b-82a5-7508f1bbbf29.png)

As far as how that data translates into our project:

- We don't currently have a way to reference the value of the prior row, but we could probably find a way to add that in if we want metric deltas.
- I haven't even seen a file metric before, do we get the kind of info from `exp show` that we need to show the same info? Do we handle them at all currently? I'll have to load this project to see.

Studio tooltips also behave in different ways depending which of two ways they are invoked:

- If the cell is hovered over for around a full second (much longer than other tooltips) the tooltip is non-interactive disappearing as soon as the mouse leaves the cell.
- If the cell is clicked, the tooltip persistently stays up until the user clicks anywhere outside the tooltip (including the cell itself) and is interactive when clicking inside the tooltip- the "click here to copy" text is actually a clickable link that provides an alternate way to copy a cell's contents.

**Comment by mattseddon** [comment]
Should be next step in #1657
