### ISSUE TITLE
Improve how timestamp column formats times

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#1444]
From a discussion with the Studio and DVC teams on Slack, we've come to the following changes beyond #1333 

- [ ] Use a format derived from [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`YYYY-MM-DD`+24h) by default
- [ ] Allow for the user to configure timestamp formatting

For reference, here's a recording of the current timestamps:

https://user-images.githubusercontent.com/9111807/154397331-0b0db4a4-3391-4b64-a31e-82d318882e9c.mp4

Since Javascript's built-in time formatting doesn't include a configurable formatting (at least in the usual `Y/M/D` template sense most people are familiar with), we'll want to introduce a library to handle this- likely `date-fns`, as it's a popular minimal library for date formatting that is also what Studio uses for its date formatting.

---

Related to https://github.com/iterative/vscode-dvc/issues/2031

**Comment by maxagin** [comment]
Timestamp column improvements #2031

**Comment by shcheklein** [comment]
Closing this for, since it's not critical and we've done an iteration recently. Next step should be to add time it took for an experiment to run, not improving this format.
