### ISSUE TITLE
Hide toggle selection icon for empty lists

### ISSUE THREAD

**Issue by yalozhkin** [iterative/vscode-dvc#1564]
Bug

### TODO
- [ ]  Hide toggle selection icon for empty lists [comment](https://github.com/iterative/vscode-dvc/issues/1564#issuecomment-1114399545)

**Comment by maxagin** [comment]
Just a follow-up. This seems like a quick fix. Can we do it?

**Comment by mattseddon** [comment]
Not quick and still low priority.

**Comment by yalozhkin** [comment]
@mattseddon @shcheklein @maxagin please check the proposal for the sorting panel:

<img src=https://user-images.githubusercontent.com/454947/175291112-756680a1-1898-4a79-bcdb-a5da2e9cf306.png width=300>

**Comment by maxagin** [comment]
@yalozhkin thank you so much for the info. Please can you create a separate ticket for proposal for the sorting panel and filters?  Never mind I will do it.  Thanks

**Comment by maxagin** [comment]
Opened a new ticket for now in design repo: Proposed improvements for the sorting panel and filters #22 https://github.com/iterative/design/issues/22
