### ISSUE TITLE
Collect user interactions inventory

### ISSUE THREAD

**Issue by yalozhkin** [iterative/vscode-dvc#1613]
Users and their daily workflows are different so we can't design complex userflows at this stage (_e.g. training a model to reach specific results_). So it seems worthfull focusing on short userflows instead (_e.g. run/stop an exp_, _filter table_).

So we can collect the short userflows (interactions inventory), range them from under-served to well-served and improve. In future, having user research sessions with real workflows, we could also prioritize the interactions inventory.

- [ ] Create a database of interactions
- [ ] Collect all existing interactions
- [ ] Rate them in terms of usability and nativity/consistency

**Comment by maxagin** [comment]
This is something we need to do for every product. Moving it to Design repo https://github.com/iterative/design/issues/20
