### ISSUE TITLE
plots: How to display images and plots per step

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#1640]
Depends on https://github.com/iterative/dvclive/issues/425

In the current demo setup, we override the saved image and plot at the end of each step. 

Unless using checkpoints, this makes it impossible to visualize images and plots logged at previous steps. And even using checkpoints the current UI doesn't easily allow to check the image and plot from previous steps (requires `Apply to workspace` and refreshing the view)

~In order to enable visualizing images from previous steps **with or without checkpoints**, in dvclive we implemented the `log_image` function in a way that images are saved under a `step` subfolder (https://dvc.org/doc/dvclive/api-reference/live/log_image#step-updates).~ (not true anymore, need to reconsider this, edited by @shcheklein)

However, using `log_image` in the VSCode UI produces a noisy output, as each `step` image is displayed in an individual row:

<img width="1039" alt="Captura de Pantalla 2022-05-02 a las 17 49 21" src="https://user-images.githubusercontent.com/12677733/166264809-be4fa65b-b2c0-4f17-bf64-ea0047d33df3.png">

I believe that allowing to display "per-step" images and plots is a relevant scenario for VSCode.

---

In tensorboard, logging an image each step gets rendered using a slider:

![confusion matrix](https://i.stack.imgur.com/PEMTG.gif)
![predictions](https://i.stack.imgur.com/VfOG0.gif)

---

Related https://github.com/iterative/dvc-render/issues/6

**Comment by maxagin** [comment]
@shcheklein please define the impact and urgency of this ticket.

**Comment by shcheklein** [comment]
I think it's a good and important improvement. It's not prioritized still. Let's first do plots, onboarding, etc. Everything that we agreed in the Q planning.

**Comment by shcheklein** [comment]
@daavoo @dberenbaum how do we / do we at all handle this in DVC itself / how about Studio? I think this is similar to the flexible plots, we should come up with a common approach and implement everywhere. Looks like an important change for all the products.

**Comment by daavoo** [comment]
> handle this in DVC itself / how about Studio

We don't handle it in any way in DVC, the HTML is a mess for this scenario.

Images are grouped in a parent folder so at least in VSCode (after https://github.com/iterative/vscode-dvc/issues/1377) and Studio it's easy to hide/show the parent folder from the tree view.

I think we should implement a slider à la TensorBoard, I tried to find something within `vega` but doesn't look like real a possibility. Not sure if we could have some reusable across UIs, but would be great.

The "tricky" part is how to identify when to render with the slider.

**Comment by shcheklein** [comment]
yes, what bothers me a bit that this is essentially a new type of plot. It's like metrics vs data series. Here it's an image vs image series. And either we go an opinionated way and hard code some very specific layout or make it general, introduce a plot subtype.

**Comment by dberenbaum** [comment]
@shcheklein I think it's related to https://github.com/iterative/dvclive/issues/326. If we enforce a DVC approach of keeping one image per step, it should simplify it. I think it's enough for now to be able to compare images across steps/commits like we diff other outputs.

**Comment by shcheklein** [comment]
@dberenbaum @daavoo 

I think this needs an update. Correct me if I'm wrong, but I think DVCLive doesn't produce subfolders for images anymore, right? + was the initial intention in the ticket about non-checkpoint scenario or in general?

**Comment by daavoo** [comment]
> @dberenbaum @daavoo
> 
> I think this needs an update. Correct me if I'm wrong, but I think DVCLive doesn't produce subfolders for images anymore, right? 

Correct.

> + was the initial intention in the ticket about non-checkpoint scenario or in general?

I would personally prefer a solution that doesn't require checkpoints. It is a basic use case covered in other UIs and making checkpoints a requirement on our side feels like a bad direction.

**Comment by shcheklein** [comment]
> I would personally prefer a solution that doesn't require checkpoints. It is a basic use case covered in other UIs and making checkpoints a requirement for this feels like going in the opposite direction of the onboarding efforts

Agreed. What is the best way to do this? I think this experience should be driven by DVCLive, DVC, Studio, and VS Code together. Let's Think first, how would we even collect this data, how we make sure that we don't show it all at once in DVC and Studio and VS Code then.

Any suggestions, ideas?

**Comment by dberenbaum** [comment]
One option is to add a `dvc.yaml` flag like `group/collapse/agg`:

```yaml
plots:
  - dvclive/plots/images/image_dir:
      group: true
```

Any ideas for how to handle these in `dvc plots diff` (across all the products)?

**Comment by shcheklein** [comment]
Assigned three of us, to brainstorm. I don't this is ready for VS Code to start working on. May be we should create even a separate ticket on DVC/DVLive first for this.

**Comment by dberenbaum** [comment]
I'm fine to move it to one of those repos if you prefer @shcheklein.

**Comment by julieg18** [comment]
Started working on the UX of the our "image per step" comparison plots! Here's what we've got so far (all in Storybook for now since backend implementation isn't done yet):

<img width="1095" alt="image" src="https://github.com/iterative/vscode-dvc/assets/43496356/47041ae5-3a99-4cc2-9a67-cae697cb7fb2">

I based the slider off of our `.vega-actions` design that we use for vega smooth plots but we can style it any way we want since this isn't a vega plot.

Mostly Working Demo:

https://github.com/iterative/vscode-dvc/assets/43496356/1ac871cc-fc99-4dd3-803c-9877a57026a8

What do we think? cc @shcheklein

**Comment by dberenbaum** [comment]
Would be great to sync the step slider across all images, but otherwise LGTM!

**Comment by shcheklein** [comment]
> What do we think? cc @shcheklein

I thinks it's a perfect start @julieg18 !
