### ISSUE TITLE
Handle DVC errors gracefully in plots

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#1649]
This depends on https://github.com/iterative/dvc/issues/7692

[Figma specs](https://www.figma.com/file/CycOpuUFNMum7TgUgEPiJu/Errors?node-id=1206%3A40780)

### Motivation 

1. Will be missing data for a specific experiment within one of the plots. This will be most apparent in the comparison table. We need a placeholder and some way to refresh the missing experiment's data.
2. Currently, if an experiment completely fails to load plots data there will be nothing to let the user know the experiment is missing. Add an indicator into the webview's top experiment selection section in order to let the user know that an experiment has something wrong.

### TODO

Will be handled in relation to the: DVC errors that may occur during or after running experiment #1636
- [ ] Placeholder and refresh https://github.com/iterative/vscode-dvc/issues/1649#issuecomment-1128348855 
- [ ] Missing experiment indicator https://github.com/iterative/vscode-dvc/issues/1649#issuecomment-1128387551

**Comment by arcticbear** [comment]
@maxagin 
There must be another red color for showing an error on the label which will be better to read. This one is really tough to read, it's painful for the eyes. A suggestion is to use a more light red tone.

Tooltip aligning by the center is confusing. Currently, all the tooltips are aligned by their left side to the parent element, which is consistent with menus and other elements' behavior.

**Comment by maxagin** [comment]
> There must be another red color for showing an error on the label which will be better to read. @arcticbear 

We are trying to follow the native roles as much as possible - VSCode guidelines 

<img width="791" alt="Screen Shot 2022-07-07 at 1 59 21 AM" src="https://user-images.githubusercontent.com/98249521/177702612-3c9dcf23-e913-4d85-a316-fcf344e7cb36.png">

However, for this particular case, we probably won't use red at all (WIP).

---

>Tooltip aligning by the center is confusing.

The context menus are always aligned by the right side, unless it's very close to the right age of the screen, in this case, the context menu will appear on the left side of the mouse. However, in some rear cases, the context menu appears always on the right side.

Regarding the tooltips with content that can be copied or having other actions such as links will be placed at the center of the element. This is consistent with common interaction patterns including GH and Studio

**Comment by shcheklein** [comment]
When `dvc plots show --json` fails like this:

```
(.venv) ?254 Projects/ensemble-dvc-template % dvc plots show --json
ERROR: unexpected error - Field 'epoch' does not exist in provided data.

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

We handle it in some weird way in VS Code:

<img width="1512" alt="Screen Shot 2022-10-29 at 1 42 08 PM" src="https://user-images.githubusercontent.com/3659196/198851668-d825714b-6582-41c4-b9ad-83d898fc3093.png">
