### ISSUE TITLE
Add dataset/pipeline columns to the table

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1657]
Description: If in files some changes were made, we want to see a sort of alert in the table view. For now we will add only dataset/pipeline columns, but maybe after there will be more to add.

**Comment by mattseddon** [comment]
Next step

Highlight the text inside of each of the data/pipelines column cells that have changed wrt the last commit. This should match the way that we highlight changes within the workspace record: 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/177656950-fef40822-a868-4b22-81cc-a1e269960d3d.png">

**Comment by wolmir** [comment]
If I understood correctly this would be the end result, right?
![Screen Shot 2022-07-12 at 09 30 03](https://user-images.githubusercontent.com/1231848/178490267-56cd32e2-5862-43bb-a55c-4fc16077f308.png)

**Comment by wolmir** [comment]
@shcheklein @maxagin Can you confirm/correct the above please?

**Comment by maxagin** [comment]
@wolmir I think this is good. Just a question, for how long will we display the yellow color (changes made)? How should I know what has been changed if I will change train.py again? Thanks you

**Comment by wolmir** [comment]
Thanks @maxagin. I believe there was an agreement to first just show that there was a change because the commit number of the dependency is different.
I would like to know if the screenshot above makes sense to a DVC user.

**Comment by mattseddon** [comment]
Wolmir, that is what we agreed for the next step.

**Comment by wolmir** [comment]
I opened a draft PR here: https://github.com/iterative/vscode-dvc/pull/2029

I just have to add unit tests for the modifications, but it should all be working.

**Comment by maxagin** [comment]
@wolmir can we close this one as done? Thanks

**Comment by wolmir** [comment]
I believe so, thanks @maxagin !
