### ISSUE TITLE
Add multi-select context menu to experiments webview

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#1663]
Now that we have a context menu available in the experiments webview we need to extend it to handle actions on multiple selected rows:

![image](https://user-images.githubusercontent.com/454947/116602137-fdb73280-a933-11eb-85ce-01a693d1ff96.png)

More details and flows in the Figma [spec](https://www.figma.com/file/heCQb0FrIfreqn8MsIuV59/Table-actions-%E2%80%A2-228?node-id=1%3A2655) and probably in https://github.com/iterative/vscode-dvc/issues/1562.

The only action that I can think of that is applicable to a list of selected experiments is "remove" but I could be wrong.

**Comment by wolmir** [comment]
@maxagin @shcheklein  @mattseddon The context menu is disabled when any experiment is running.
Should the row selection be disabled as well?

**Comment by wolmir** [comment]
@maxagin 
https://user-images.githubusercontent.com/1231848/173673046-6440ca24-c01f-4d34-b51c-95aefb88224f.mov

**Comment by maxagin** [comment]
Great work @wolmir  ! Tiny comment: When you add the select style you may consider not using the border (top/bottom) at all, as they are moving the other rows :) - unwanted movement.

**Comment by maxagin** [comment]
I think that if the exp is running I still want to be able to remove it, but just to remove it. WDYT?

**Comment by mattseddon** [comment]
Discussed on the weekly planning call:

1. Logic in the table should replicate logic shown in the tree (see `collectDeletable`).
2. Can stop a running experiment which is equivalent to deleting it.

**Comment by mattseddon** [comment]
We have a multi-select context menu now.
