### ISSUE TITLE
Show middle state icon for parent Runs, Checkboxes and Stars

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#1714]
Here we are trying to solve the visibility issue when checkboxes, stars and checkpoints are not visible because the experiment is folded.

The goal is to make sure users can be informed about those hidden elements.

[Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/1720-%E2%80%A2-Story%3A-Help-navigate-in-a-lot-of-experiments?node-id=1028%3A20218)

**Comment by wolmir** [comment]
@maxagin Is there a Figma spec for this middle-state?

**Comment by maxagin** [comment]
@wolmir this is what we have discussed yesterday, so we do not have the specs yet, first, we will have to agree on the concept.

**Comment by maxagin** [comment]
More arguments: The life cycle for checkboxes and checkpoints is short, for stars it's long, but they won't be produced massively.

**Comment by maxagin** [comment]
Let's test it with the visuals. Thanks

**Comment by wolmir** [comment]
Ah, got it! Thanks!

**Comment by maxagin** [comment]
Updated:

<img width="942" alt="Screen Shot 2022-06-30 at 4 12 35 PM" src="https://user-images.githubusercontent.com/98249521/176769574-6f9ed6d8-ec45-403f-868a-4130edb8590f.png">

**Comment by shcheklein** [comment]
Sorry, @maxagin  - it looks like a bug to me tbh + experiments will be "jumping" right to left and back, also not good.

**Comment by maxagin** [comment]
> experiments will be "jumping" right to left

Everything is staying exactly in the same position as is.

**Comment by shcheklein** [comment]
> Everything is staying exactly in the same position as is.

yep, you are right. It means that this picture was playing even more tricks with my mind than I thought :)

btw, it also means that if do something (deselect an experiment - quite lightweight action) it might have to disappear from the table

**Comment by maxagin** [comment]
Yes, if you remove Checkbox, Star or Checkpoint from the nested and folded experiments, the row will disappear. However, currently, does not it feels the same when you fold the experiment - when all the checkpoints are disappearing? Do not you think that the goal is to show selected objects, and removing them does not play a significant role in the future interaction?

**Comment by mattseddon** [comment]
Please also consider the implications of https://github.com/iterative/vscode-dvc/issues/1269

**Comment by maxagin** [comment]
Folding and unfolding exp that have nested starred checkpoint

V1

https://user-images.githubusercontent.com/98249521/176787255-f0158307-2aeb-48b2-8200-74355ed15ba5.mov

V2


https://user-images.githubusercontent.com/98249521/176787266-a96efc53-a5f5-4956-9c88-40eb0783bf9c.mov

**Comment by maxagin** [comment]
Another option

https://user-images.githubusercontent.com/98249521/176788566-aaf72de9-1099-4d5c-9daf-90e50d9ab99f.mov

**Comment by wolmir** [comment]
Something like this for the first iteration?

https://user-images.githubusercontent.com/1231848/177645211-416a8202-8f7f-4b41-ab0d-4925fd7f8469.mov

**Comment by maxagin** [comment]
This approach visually feels familiar, but conceptually it's not good I think. However, I am not 100% sure we will have some different concepts. From my latest research, I was not able to find any product that shows nested info/marks at the parent level, meaning any ideas will be too original for this case.

Thank you @wolmir  good stuff !

**Comment by maxagin** [comment]
Just for the record: I think we do not need to inform the user about hidden states.

**Comment by wolmir** [comment]
What are hidden states @maxagin ?

**Comment by maxagin** [comment]
Sorry, @wolmir I confused this ticket with one I have planned to create.

**Comment by maxagin** [comment]
@wolmir , what is left here? I think it's all done. No? Thanks!
