### ISSUE TITLE
Accomodate flexible plots

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#1757]
DVC are about to introduce flexible plots via the `plots diff` command. 

### Example of a flexible plot:

![image](https://user-images.githubusercontent.com/37993418/169924818-f94c0f14-9be7-4b60-ae5e-27cc7f8ff33f.png)

In this particular example, we can see that there are multiple lines for the HEAD commit and multiple lines for the workspace. 

### Current VS Code UI:

![image](https://user-images.githubusercontent.com/37993418/169924663-2a6e0299-13a5-4a33-83d9-e02c26484609.png)

When comparing the two it should become clear that there is an issue. In VS Code we have a single line per experiment. If we had a flexible plot and `exp-84614` (from screenshot) needed to show train vs test (and a line for each) then what would we do? We currently do not show a legend as we want to "globally link" each color back to an individual experiment. We cannot simply show two red lines. We could potentially show one as dashed and the other solid but we should still need to add an indicator somewhere in the view to detail which is which. It also would not be long before we run out of line types. 

In order to accommodate the new plots data we need to do a few things (with different priorities):

 - [x] Make sure no breaking changes - p1
 - [x] Consume new data - p1
 - [x] Update the design to be able to accommodate the new visuals - p2

**Comment by mattseddon** [comment]
Update: We've verified that flexible plots will not be shown in VS Code (and nothing will break) after the PR is merged.

We still need to discuss how we will cater to these plots in VS Code. The initial thought is to go with the different line types but we will still need a way to show this in VS Code. We can maybe bring back the legend specifically for these types of plots. 

If any changes need to be made to the default templates then we should consider #1957.

We should discuss this at the next cross-team planning meeting and talk about priorities 👍🏻.

**Comment by wolmir** [comment]
Would it be possible to divide the color space in two complementary regions? One for each domain?

**Comment by mattseddon** [comment]
> Would it be possible to divide the color space in two complementary regions? One for each domain?

There are potentially more than two domains for each revision. I think line types can handle up to 5 but at that point, the plot is going to be confusing no matter what we do.

**Comment by dberenbaum** [comment]
Update on this: @pared is working on making it possible to determine from the JSON which plots are "flexible" so that it's possible to continue treating the traditional ones the same way and have separate rendering logic for the flexible ones. Then either he or the VS Code team can work on how to render those flexible plots in VS Code.

**Comment by pared** [comment]
We need to conduct some discussion regarding how ideally plots colors overriding works, in both `studio` and `vscode`. Till we know what we stand on flexible plots (linear) will work as follows:
- simple plots will have their colors overriden
- complex plots (the ones sourcing data from multiple sources from single revision) will have their colors assigned by vega.

Example: 
<img width="1221" alt="Screenshot 2022-09-08 at 23 14 14" src="https://user-images.githubusercontent.com/10195618/189623841-05bd45e7-fdf4-425d-bd1d-8804449a4fa8.png">

**Comment by shcheklein** [comment]
Folks, unless I'm missing something, it breaks the product experience. What would be the reason to release it with a broken color schema that might confuse users? We need to introduce additional dimension (line type) to this. If this is not possible we need to start reconsidering the whole approach (that Studio and VS Code take) asap.

**Comment by pared** [comment]
@shcheklein the experience has always been broken - confusion matrix does not comply with color schema. IMHO it's better to let users have working flexible plots. Regarding coloring schema we need to discuss how we would like our plots to behave, both for Studio and vscode (though after looking at both projects it looks to me that use cases are very similar). Only then should we decide what to do with the plots, and start changes.

**Comment by dberenbaum** [comment]
The changes in https://github.com/iterative/dvc/pull/8282 should have all the info needed to introduce an additional line type. An example data point:

```json
          {
            "actual": "1",
            "predicted": "0",
            "dvc_data_version_info": {
              "revision": "exp-3599a",
              "filename": "evaluation/test/plots/confusion_matrix.json"
            },
            "rev": "exp-3599a::evaluation/test/plots/confusion_matrix.json"
          }
 ```

I think the remaining changes should be on how to handle this info on the front end. Is that correct @pared?

**Comment by mattseddon** [comment]
I'll catch up with @pared and see where we're at 👍🏻.

**Comment by pared** [comment]
There are few things to clarify here, some general points:

1. Do we want to colour/adjust lining for other templates? (eg, confusion_matrix, that's why I said its broken, as they do not follow revision colors) - it makes sense to me that in this case coloring does not matter that much, but I need clear guidelines how all currently supported templates should behave. 
2. switching from `rev` to `dvc_data_version_info` will require changes on our templates - `rev` field is hardcoded there, so we will probably need to modify all templates and prepare backward compatibility for dvc versions that do not provide this field
3. Updating coloring is a new way of updating the plots - we used to rely on string anchors, now we will also modify the template as dict - should it be like this? 
4. vscode and studio changes the plots on FE side - we need to decide what are we going to do with that - should we create common library that will allow for this kind of operations?

Taking those point through is necessary, I just thought that we want to make it work, and later adjust to the results of discussion.

**Comment by dberenbaum** [comment]
1. I don't think color makes sense for confusion matrix since there is a scale and it should be consistent across all plots. It would be nice to designate the color of the experiment somewhere like in the subtitle, but I think that's not needed right now.
2. I think it's fine to keep both `rev` and `dvc_data_version_info` for now like you do in https://github.com/iterative/dvc/pull/8282.
3. I would prefer to wait before diving into handling line styles inside DVC, although it would make sense to create an issue and/or start discussion on it.
4. I would prefer to try to create the line styles within VS Code since it seems like the easiest path to get some prototype working, but open to other suggestions.

> IMHO it's better to let users have working flexible plots.

@shcheklein Since users are waiting to be able to see top-level plots in VS Code and Studio, what are your concerns with this approach? What do you have in mind? I think the point from @pared about confusion matrices was that not all plots have colors that align to experiment names, so initially showing flexible plots with colors that don't align to experiment names may be a reasonable first step.

**Comment by dberenbaum** [comment]
Probably worth noting that the best Vega-lite can do here is provide two legends rather than combine the color and dash stroke:

![image](https://user-images.githubusercontent.com/2308172/190248314-861a085e-d908-4e52-83c5-4931667a9d4b.png)

https://github.com/vega/vega-lite/issues/3797

**Comment by shcheklein** [comment]
@pared @dberenbaum 

> @shcheklein Since users are waiting to be able to see top-level plots in VS Code and Studio, what are your concerns with this approach?

no concerns with making top level plots working asap (I was thinking more about flexible plots - multiple lines per experiment). Will we have to break colors for pretty much all plots in this case?

**Comment by mattseddon** [comment]
I have a working prototype:

https://user-images.githubusercontent.com/37993418/190308174-f63647b3-d0f6-4e58-8f76-9c21ed04a2ba.mov

In the prototype, the legend is disabled unless a plot is zoomed. I think this is actually ok but happy to be corrected. The way that I imagine people would use this would be: webview is a dashboard which gives an overview. If I want to interrogate a plot then I need to click on it to see further details. What does everyone else think?

**Comment by shcheklein** [comment]
Looks great, @mattseddon !

Regarding the legend we could pick ideas from the TB:


https://user-images.githubusercontent.com/3659196/190311755-1498ebb2-e28b-4969-83e8-b6165a7f1071.mov


I think that tooltip with metrics is way better compared to what we have (I wonder if we could implement something like this in Vega - cc @daavoo )

Also, we can consider expanding the plots tree in side panel to serve as a legend similar to TB.

**Comment by daavoo** [comment]
> (I wonder if we could implement something like this in Vega - cc @daavoo )

Tooltip with multiple fields can be added, but it won't look as pretty as tensorboard, example:

https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html

**Comment by daavoo** [comment]
> I would prefer to try to create the line styles within VS Code since it seems like the easiest path to get some prototype working, but open to other suggestions.

One downside with this approach is that, as we start getting custom vega rendering logic into VSCode/Studio, it becomes messier for users to use custom templates. It is not clear what things will be ignored/replaced by the UI.

For example, what would happen if a user wants to use flexible plots with a template using facets?

**Comment by dberenbaum** [comment]
Good point, @daavoo. Does VS Code try to override color any time there is a `"color": {"field": "rev"}`? It looks like it is applied pretty aggressively, including the new bar template and custom templates:

<img width="1127" alt="Screen Shot 2022-09-15 at 10 29 48 AM" src="https://user-images.githubusercontent.com/2308172/190431506-7917df7a-d3a7-43da-bfa2-b0ec0deb9d69.png">

Also, is it possible there are more dimensions than exp/git rev and filename @pared?

**Comment by pared** [comment]
It is possible to use `dvc_data_version_info`, as a version reference. In the beginning, we hardcoded `rev` which will need some backward compatibility changes, but yes, it is possible.

**Comment by dberenbaum** [comment]
@pared Can there be additional fields in `dvc_data_version_info` besides `revision` and `filename`?

**Comment by pared** [comment]
Yes, that's why we need to migrate there at some point. `dvc_data_version_info` is a dict, so we can extend it if needed.

**Comment by pared** [comment]
It already also has `field`

**Comment by dberenbaum** [comment]
So we want to color by `revision` and use stroke dash for the combination of any other fields in `dvc_data_version_info`?

**Comment by pared** [comment]
This is an initial idea, but we can go even further and, for example, add different point markings for `field`.

**Comment by mattseddon** [comment]
> For example, what would happen if a user wants to use flexible plots with a template using facets? Or a custom Legend?

These are definitely things that we need to work through but I think we can put them to the side for this iteration. We'd be guessing as to how popular those templates will be. Worst case scenario we can exclude them from changes until we work out how to cater for them.

> So we want to color by revision and use stroke dash for the combination of any other fields in dvc_data_version_info?

I had the same idea as @pared - color for revision, stroke dash for the first varied field in `dvc_data_version_info` (by number of different values) then shape for the second varied field. Won't cater for everything but should get us a long way. 

-------

I've spent nearly the whole day trying to work out how we can display the line type in the sidebar trees. Looks like we can replicate the circles shown in the legend with custom svgs. Here is an example of the correct dashed circle shown in the wrong tree:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/190563411-f33160da-dd25-47df-8651-7ce76fd2f631.png">

By controlling the line types for different values through the scale property we should be able to use this approach to create a custom legend in the plots tree.

I'll now go and build a prototype which will be able to cater for two different custom properties (e.g `filename` and `field`). The one with the most values will be split by line type, the other will be split by shape. I'll take the same approach of loading custom grey svgs for the different available shapes. It looks like these shapes are displayed as black by default which is going to be a problem with a lot of themes:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/190564975-e219093c-191c-4c55-8443-ec3a16328dab.png">

Please LMK if you have any concerns 👍🏻.

**Comment by mattseddon** [comment]
Can we add anchor tags to all the templates for color, strokeDash and shape scales?

**Comment by pared** [comment]
@mattseddon I would need to spend some time researching this 
cc @dberenbaum

**Comment by dberenbaum** [comment]
Loving the excitement here, but can we slow down and decide on an MVP to get flexible plots support? Can we implement the prototype from https://github.com/iterative/vscode-dvc/issues/1757#issuecomment-1247542560?

I think we still need to decide whether to do that formatting from within VS Code or on the DVC side. I'd propose starting on VS Code since we have it working, and opening a separate issue to consider implementing it on the DVC side.

**Comment by pared** [comment]
Just a note that if we won't have it on `dvc` side, soon we will have to duplicate the logic for studio. Even if DVC doesn't need that we probably need to create some js library that will be able to manipulate known templates.

**Comment by mattseddon** [comment]
@dberenbaum both https://github.com/iterative/vscode-dvc/issues/1757#issuecomment-1247542560 & https://github.com/iterative/vscode-dvc/issues/1757#issuecomment-1248949586 rely on the same implementation from DVC (https://github.com/iterative/dvc/pull/8282). I'm only ~2days away from completing the second part of the implementation. 

Asking about further changes is for a future iteration(s).

**Comment by dberenbaum** [comment]
Feel free to use https://github.com/iterative/dvc/issues/7809 to continue discussion on the DVC templates

**Comment by mattseddon** [comment]
Here is the prototype for adding the legend items to the plots tree:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/191900962-84ca646a-bbf9-452f-a252-7fb0c259af57.png">

<img width="1728" alt="Screen Shot 2022-09-23 at 4 08 41 pm" src="https://user-images.githubusercontent.com/37993418/191901040-ead23c48-ff9d-4640-878f-3f7ac6a73980.png">

**Comment by dberenbaum** [comment]
> custom grey svgs for the different available shapes

Looks good @mattseddon! 

I have one suggestion. From what I remember of dataviz principles, having multiple legends like Vega is hard for users to comprehend. It takes me awhile to look at the plot above and figure out what each line means. That's even harder when the info is scattered in the sidebar between Experiments (colors) and Plots (dash styles).

Is it possible to have the plots tree legend combine the colors, dashes, and shapes so that there is an entry for each line?

**Comment by mattseddon** [comment]
@dberenbaum the user can move the trees closer to each other so that they aren't looking in such disperate places:

<img width="1728" alt="Screen Shot 2022-09-26 at 11 25 34 am" src="https://user-images.githubusercontent.com/37993418/192179040-82284343-27c9-4432-b426-4c3de265189c.png">

This is what an entry per line per color would look like in the tree for our example:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/192179008-97e08bae-92f9-4447-bf53-00d03d82cc84.png">
 
IMO even with only a few revisions selected this is already too busy. I would assume that is why Vega provides the legends this way.

WDYT?

**Comment by mattseddon** [comment]
I am having a small issue with the Vega-generated legend after we introduce a shape dimension into the plot:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/192205534-36385e9b-8607-437c-9f76-96a7c3e7e29c.png">

**Comment by dberenbaum** [comment]
In my experience, if there are too many lines to fit in a legend, there are too many lines on the chart. We can go with the approach you are working on and brainstorm other ways to help comprehend, like:

* Tooltips (mentioned above). They are limited in vega lite, but we could at least show some info when hovering over a particular line.
* Putting labels next to the lines in the plot and highlighting on hover: https://vega.github.io/vega-lite/examples/interactive_line_hover.html
* Highlighting on click:  https://vega.github.io/vega/examples/interactive-legend/

**Comment by mattseddon** [comment]
We'll ship this today. The next step will be to get user feedback and revisit the suggestions above.

Thanks, everyone.
