### ISSUE TITLE
SCM doesn't reflect remote status.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#1769]
The SCM section contains action for `dvc push` but it doesn't reflect the [remote status](https://dvc.org/doc/command-reference/status#comparison-against-remote-storage), only [workspace status](https://dvc.org/doc/command-reference/status#local-workspace-status).

I believe showing the remote status is relevant and the lack of it might cause confusion and incorrect workflows for users unfamiliar with DVC.

VSCode could use `dvc status -c` to query for remote status

Example workflow:

---

## 2. I run an experiment.

<img width="451" alt="Captura de Pantalla 2022-05-25 a las 17 22 29" src="https://user-images.githubusercontent.com/12677733/170298831-cbec01e5-24cc-4feb-ab81-a8c52028b3e7.png">

I see changes to dvc-tracked files and git-tracked files. 

## 3. Used to my regular workflow, I stage and commit the git-tracked files.

I get a clear signal by Git SCM that my workspace and remote are out of sync:

<img width="450" alt="Captura de Pantalla 2022-05-25 a las 17 26 59" src="https://user-images.githubusercontent.com/12677733/170299552-35f8d4d6-5cf9-43de-8305-7fbe98a057db.png">

However, the DVC SCM is empty. As I am familiar with Git SCM, I interpret this as there is nothing else to do with dvc.

## 4. I click on the big sync changes button.

---

At this point, if someone clones the repo, it will receive a broken state (regarding DVC tracked files).

**Comment by shcheklein** [comment]
Discussed this with the team. One idea to consider initially is to have a single notification / button / status from which people can understand that some files are missing in the remote storage. Initially it can be even outside the SCM panel. Can be in the status bar?

**Comment by alkatar21** [comment]
I don't use the sync button, but some indicator that the DVC remote is not in sync with the local status would be helpful.

**Comment by mattseddon** [comment]
Could we use `data status --json --granular --unchanged --not-in-remote --no-remote-refresh` for this? 

For the initial implementation, we could let users trigger the remote refresh on demand but ideally, the information would be "auto-updated" whenever the CLI interacted with the remote. E.g. on `exp push`/`push` or `pull` (I could be doing something wrong but it doesn't seem like this is the case).

Is this something that we should start looking at @dberenbaum? We can talk about it tomorrow if that works for you.

**Comment by mattseddon** [comment]
@efiop is the above behaviour expected for `data status`?

**Comment by efiop** [comment]
@mattseddon Not quite sure I get how scm is related here, a bit confused about the whole issue.

**Comment by dberenbaum** [comment]
@efiop Sorry, I asked @mattseddon to ping you. The question is here:

> Could we use `data status --json --granular --unchanged --not-in-remote --no-remote-refresh` for this?
> 
> For the initial implementation, we could let users trigger the remote refresh on demand but ideally, the information would be "auto-updated" whenever the CLI interacted with the remote. E.g. on `exp push`/`push` or `pull` (I could be doing something wrong but it doesn't seem like this is the case).

Can that command (with `--no-remote-refresh`) still have remote info indexed from what's already been pushed/pulled by the user?

**Comment by efiop** [comment]
@dberenbaum Thanks for clarifying! Totally, if `dvc push/pull` was invoked before.

**Comment by mattseddon** [comment]
This is the behaviour that I'm seeing with `3.4.0`:

```
/demo @914b0f67 ❯ dvc data status --json --granular --unchanged --not-in-remote --no-remote-refresh
{                                                                                                                                                                          
  "not_in_remote": [
    "hist.csv",
    "model.pt",
    "training/plots/",
    "training/plots/images/misclassified.jpg",
    "training/plots/sklearn/confusion_matrix.json",
    "training/plots/metrics/train/loss.tsv",
    "training/plots/metrics/train/acc.tsv",
    "training/plots/metrics/test/acc.tsv",
    "training/plots/metrics/test/loss.tsv"
  ],
  "committed": {
    "modified": [
      "hist.csv",
      "model.pt",
      "training/plots/",
      "training/plots/images/misclassified.jpg",
      "training/plots/sklearn/confusion_matrix.json",
      "training/plots/metrics/train/loss.tsv",
      "training/plots/metrics/train/acc.tsv",
      "training/plots/metrics/test/acc.tsv",
      "training/plots/metrics/test/loss.tsv"
    ]
  },
  "unchanged": [
    "data/MNIST/raw/train-labels-idx1-ubyte.gz",
    "data/MNIST/raw/t10k-images-idx3-ubyte.gz",
    "data/MNIST/raw/t10k-labels-idx1-ubyte.gz",
    "data/MNIST/raw/t10k-images-idx3-ubyte",
    "data/MNIST/raw/train-images-idx3-ubyte.gz",
    "data/",
    "data/MNIST/raw/train-images-idx3-ubyte",
    "data/MNIST/raw/t10k-labels-idx1-ubyte",
    "data/MNIST/raw/train-labels-idx1-ubyte"
  ]
}
/demo @914b0f67 !4 ❯ dvc push
9 files pushed
/demo @914b0f67 !4 ❯ dvc data status --json --granular --unchanged --not-in-remote --no-remote-refresh
{                                                                                                                                                                          
  "not_in_remote": [
    "model.pt",
    "hist.csv",
    "training/plots/",
    "training/plots/sklearn/confusion_matrix.json",
    "training/plots/images/misclassified.jpg",
    "training/plots/metrics/train/loss.tsv",
    "training/plots/metrics/train/acc.tsv",
    "training/plots/metrics/test/loss.tsv",
    "training/plots/metrics/test/acc.tsv"
  ],
  "committed": {
    "modified": [
      "model.pt",
      "hist.csv",
      "training/plots/",
      "training/plots/sklearn/confusion_matrix.json",
      "training/plots/images/misclassified.jpg",
      "training/plots/metrics/train/loss.tsv",
      "training/plots/metrics/train/acc.tsv",
      "training/plots/metrics/test/loss.tsv",
      "training/plots/metrics/test/acc.tsv"
    ]
  },
  "unchanged": [
    "data/",
    "data/MNIST/raw/train-images-idx3-ubyte.gz",
    "data/MNIST/raw/t10k-labels-idx1-ubyte",
    "data/MNIST/raw/t10k-labels-idx1-ubyte.gz",
    "data/MNIST/raw/train-images-idx3-ubyte",
    "data/MNIST/raw/t10k-images-idx3-ubyte",
    "data/MNIST/raw/train-labels-idx1-ubyte",
    "data/MNIST/raw/train-labels-idx1-ubyte.gz",
    "data/MNIST/raw/t10k-images-idx3-ubyte.gz"
  ]
}
```

**Comment by efiop** [comment]
@mattseddon Yeah, that's expected. Remote index is currently only automatically updated by push/pull/fetch for cloud versioning. We are ready to do that for regular clouds in `fetch`(and pull), but `push` needs some work https://github.com/iterative/dvc/issues/9333

**Comment by mattseddon** [comment]
For the record, for this issue, we're trying to solve a targeted use case where a user has just run some experiment which has generated some new artefacts. These will initially show up at "not in remote" but after `dvc push` or `dvc exp push origin <exp-name>` it would be good to drop the data from the "not in remote" status. This would enable us to let users know that their remote is not currently up to date.
