### ISSUE TITLE
Experiment Table UI: visually separate baseline from experiments for readability when sorting?

### ISSUE THREAD

**Issue by bobertlo** [iterative/vscode-dvc#1820]
Would be possible to somehow visually separate the baseline commit from the experiments in the table just to help with readability when sorting, since the baseline is not sorted with the experiments?

My main observation is that while It is pretty clear currently how to read the table when sorting by a performance metric, it is less clear when sorting by an input parameter and trying to correlate performance metrics since the baseline commit is not sorted or visually separated.

Maybe there could just be a space like there is between the workspace and the baseline commit? I see this could interfere with with the drop down function though and I am sure there are a lot of other possibilities to consider.

**Comment by maxagin** [comment]
>Would be possible to somehow visually separate the baseline commit from the experiments in the table just to help with readability when sorting, since the baseline is not sorted with the experiments?

Hey @bobertlo. Thank you for your feedback. Please, can you draw a use case? How the visual separation of the baseline will help for the sorting? Also if you can attach a short video of how you are currently using it, would be helpful.

**Comment by bobertlo** [comment]
@maxagin Hey! Sorry I haven't had as much bandwidth lately so it took me a while to get back.

To start out, I’m not convinced the visual separation would be that helpful anymore, mainly because the names are "sticky" and it was more confusing without those elements. Again I usually `exp run` the original parameter value again just to get it to sort in the table. Again, it is not a big deal but maybe if the “folder” that says the branch name was a blank column and there was a “HEAD” entry that sorted it would be better for my OCD but it’s really not a big deal.

@shcheklein mentioned maybe the information being inconvenient to consume from the table could just mean it would be useful to have it somewhere else. The idea of having being able to “star” a couple columns from the table (ie a hyper-parameter and a performance metric) and display those in the “ribbon” seems like it could be really nice (but it would be less helpful I would think if they were not sorted.)

I'm attaching a picture of my workspace since my internet really does not want to send a video. I selected the columns that I am looking at here for clarity, but I usually have everything enabled since when I select between different model directories it all gets reset anyway.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/877465/191404582-a7411240-7364-46ac-aa67-ef287b3e439b.png">

**Comment by maxagin** [comment]
Thank you very much @bobertlo ! This is helpful feedback. 
Regarding the video file you have mentioned, I really would like to have it, would it help if I share with you my email? Thank you!

**Comment by shcheklein** [comment]
Addressing it here #2458 . We'll try to make all commits look a bit different in some way.
