### ISSUE TITLE
Stop toggling the EXP circle on row click

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1845]
### Description
When you click somewhere on the row (for example on the right side) the circle on the left changing. This is a bug. Only click on a circle should be toggling it.

### Screen capture
https://user-images.githubusercontent.com/98249521/172264433-9b204d85-3eca-4585-844b-3237188eaa79.mov

**Comment by wolmir** [comment]
Related: https://github.com/iterative/vscode-dvc/issues/1924#issuecomment-1160675066

**Comment by wolmir** [comment]
Fixed by https://github.com/iterative/vscode-dvc/pull/1906
