### ISSUE TITLE
Reset workspace: why?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1850]
> Extracted from https://github.com/iterative/vscode-dvc/pull/1816#pullrequestreview-993070400

<img width="224" alt="image" src="https://user-images.githubusercontent.com/1477535/172315279-ca710916-dc49-4ed3-8dc8-1534e10c43a6.png">

- [ ] First, I'm using the example-get-started repo on Codespaces and this button doesn't have an effect at all (bug?)

Most importantly, why do we need this? I understand that "Reset workspace" means
```git reset --hard HEAD && git clean -f -d -q && dvc checkout```
So that's 2 Git operations in the DVC panel. We already have a button from `dvc checkout` so why add this shortcut? Probably there's a reason (pros) but here are some more cons in advance:

- It's unclear what it means.
- Operation too complex?
- It's "scary" AND actually dangerous.
- It can be done by other means (terminal).

Finally, if the Git integration doesn't include `git reset` (nor `git clean`), should we?

<img width="363" alt="image" src="https://user-images.githubusercontent.com/1477535/172318588-2a380559-eb1e-4d52-aa8e-a81c9eff058c.png">

**Comment by mattseddon** [comment]
Yes, we have analytics attached to the action. We'll be able to see the usage.

**Comment by mattseddon** [comment]
> What if there are changes to Git-tracked params or metrics files? That's part of the DVC project and especially important to the extension since it focuses on DVC experiments, yet `Reset workspace` silently ignores those unless there are changes in DVC-tracked files.
> 
> > p.s. the official definition of [DVC workspace](https://dvc.org/doc/user-guide/glossary#workspace) includes all Git-tracked files.

Is the suggestion to make the command more aggressive and always blat the workspace? That would be an easy change to make.

**Comment by jorgeorpinel** [comment]
I personally still don't love this button but if we keep

a) Rename **Discard Workspace Changes** and always quash Git changes (or even better specifically Git-tracked inputs/outputs).

b) Rename **Discard DVC-tracked Changes** and only reset DVC-tracked files.

From those options I sort of prefer a' (may be easier once there's full DAG/ pipelining support)

**Comment by mattseddon** [comment]
> I personally still don't love this button but if we keep,
> 
> a) Rename **Discard Workspace Changes** and always quash Git changes (or even better specifically Git-tracked inputs/outputs);
> 
> b) Rename **Discard DVC-tracked Changes** and only reset DVC-tracked files.
> 
> From those options I sort of prefer a' (may be easier once there's full DAG/ pipelining support)

Working on sledgehammer version of A. Can revisit once we get `data:status`.
