### ISSUE TITLE
`lint-staged` breaks markdown links in block quotes

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1881]
Yep the linter in the Git hook keeps breaking it. Could use some help fixing that up. See https://github.com/iterative/vscode-dvc/pull/1816/commits/9e6218a433aeceae908d06b31e7530cffaaa3ca3

_Originally posted by @jorgeorpinel in https://github.com/iterative/vscode-dvc/pull/1816#discussion_r892630365_

**Comment by jorgeorpinel** [comment]
Thanks for the workaround. But what about local vs CI checks consistency?

> Ideally it should use the same linter as the PR checks, which is yarn run lint = yarn turbo run lint --parallel. But auto-fixing, and only on staged files

**Comment by mattseddon** [comment]
> Thanks for the workaround. But what about local vs CI checks consistency? I guess it's not critical for md files but this could affect the code base development too.

CI uses the same config so will exclude that line as well.
