### ISSUE TITLE
tooltips: link "reload this window" to the VS Code command

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1884]
Idk if there are other cases when this is asked but at least when the extension gets ahead of DVC and a CLI update is needed, you get this message, which persists even after updating `dvc`. Some people may not know what "reload this window" means or how to do it, can it be linked to the "Developer: Reload Window" command?

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1477535/173492152-c3f1e7d2-2cef-464c-a886-597e724ae81c.png">

Probably `p3-nice-to-have`

**Comment by mattseddon** [comment]
The UI would have to look like this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/173725514-6fabcba5-2215-4644-a519-ea2189f90720.png">

What I think will happen if we add this button:

1. User opens VS Code.
2. Toast popup shown.
3. User sees button that says "Reload Window".
4. User clicks button without reading the toast.
5. Cycle repeats X times.

I wrote this code, I know why the toast is there and I still just went through that cycle!

**Comment by jorgeorpinel** [comment]
Maybe you just didn't have breakfast 🍞 

Could link "upgrade" to the DVC install docs and "reload" to the action (instead of adding a big red button).

Anyway, it's a UX question at this point. Up to you, thanks

**Comment by mattseddon** [comment]
Those toasts cannot contain links/markdown. The action has to be the button. 

I'll park this for now. Will come back to it if we see a barrage of questions coming through either in issues or on Discord.
