### ISSUE TITLE
dvc-view: keep support panel available

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1885]
Currently it's only visible when DVC or the project are not set up, I think.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/1477535/173501231-79bda17f-07db-4a80-a2b5-9e0439f2b0bb.png">

But it's pretty useful, should it always be there? At the bottom and collapse by default when DVC is active.

**Comment by mattseddon** [comment]
Should be active all the time.

**Comment by mattseddon** [comment]
<img width="1680" alt="Screen Shot 2022-06-14 at 3 48 37 pm" src="https://user-images.githubusercontent.com/37993418/173502661-950bb793-72c5-492c-9472-48973e102bf7.png">

**Comment by mattseddon** [comment]
![Screen Shot 2022-06-14 at 3 48 37 pm (2)](https://user-images.githubusercontent.com/37993418/173502721-1f3af369-6c28-4f58-830b-f1c26da77755.png)

**Comment by jorgeorpinel** [comment]
You're right this is already the case! For some reason scrolling through panels in the side bar doesn't really work (at least in Codespaces). So when all other panels are open this is invisible and hard to reach.
