### ISSUE TITLE
linter: inconsistent/wrong linting in local vs. CI envs

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1896]
Local linting is enforced by a Git hook that runs `lint-staged` (a Yarn package &. command) directly. On the CI, the custom `lint` script is used which uses `turbo` instead. This seems to cause inconsistent results when linting on different envs, causing developer confusion.

- Local inconsistency example: https://github.com/iterative/vscode-dvc/issues/1881
- CI inconsistency (ongoing issue): https://github.com/iterative/vscode-dvc/pull/1889#pullrequestreview-1005342763

> So far I've only noticed this in Markdown files which is not a big deal I suppose, but I suspect that it can easily happen on the code base too.

**Comment by mattseddon** [comment]
Restyled has been disabled. See https://github.com/iterative/vscode-dvc/pull/1898.
