### ISSUE TITLE
Glob pattern '**' does not work with createFileSystemWatcher on Windows

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#1904]
`**` will only look one level deep
`**/**` or `**/*.*` two level deep and so on.
 We need to replace it with something that works recursively on Windows.

Issue found in example repo in this thread:
https://discord.com/channels/485586884165107732/842220310585147452/986436373756141609

**Comment by sroy3** [comment]
Seems like copying the pattern from the [git](https://github.com/microsoft/vscode/blob/9232ebbdcbdea55c27907373d94e3082091ac75f/extensions/git/src/watch.ts#L13) extension work: `new RelativePattern(this.dvcRoot, '**')` instead of `join(this.dvcRoot, '**')`.

**Comment by mattseddon** [comment]
Awesome work
