### ISSUE TITLE
Don't activate extension in non-DVC projects.

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1926]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1477535/174508580-3db3533d-dfb5-4d09-bb96-bf08d46d5ea5.png">

This is not a DVC project.

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1477535/174508596-84164bce-57d6-4355-997c-5bfeaedd3115.png">

Why should the extension be able to access DVC? Shouldn't be active in general I think.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/1477535/174508649-83014730-b723-4bf8-9926-28518926eb6b.png">

This makes it noisy and users may disable or uninstall due to this.

**Comment by jorgeorpinel** [comment]
Hmmm, I guess demo/ is a DVC project. Is that why the extension wants to turn on?

**Comment by shcheklein** [comment]
Yes, I think so. It's related to how it deals with monorepos I think (multiple DVC sub-projects). We should revisit this.

**Comment by jorgeorpinel** [comment]
Yes never mind this is fine 🔥

**Comment by jorgeorpinel** [comment]
Or did you mean to reuse this for monorepo support questions @shcheklein ?
