### ISSUE TITLE
dvc-tracked: subdir project paths are incomplete (monorepo)

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1929]
Opening this repo in VS Code recognizes the [demo project](https://github.com/iterative/vscode-dvc/tree/main/demo) automatically. The data is in demo/data/ . The **DVC Tracked** panel in the File Explorer is missing the `demo/` prefix:

![image](https://user-images.githubusercontent.com/1477535/174525673-58d68b09-29e5-4473-af4b-8e6e7d2da56c.png)

> I wonder what happens if you have more than one DVC project in an actual monorepo.

**Comment by jorgeorpinel** [comment]
Also, and I don't know if this is me doing something wrong, but the DVC panel in Source Control isn't reflecting missing data (I waited a bit, even reloaded the window):

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1477535/174523719-39f3b15e-4749-474c-b772-7c257b922151.png">

The last `dvc status` in the output channel seems fine:

```
[version: 0.3.5, 2022-06-20T04:08:42.036Z, pid: 58963] > dvc status --show-json - COMPLETED (217ms)
```

**Comment by jorgeorpinel** [comment]
Scratch that last part. That was my fault for `rm`ing data/MNIST/raw.dvc 😆

**Comment by mattseddon** [comment]
Yep, this is a bug and should be easy to fix. See https://github.com/iterative/vscode-dvc/issues/1931#issuecomment-1163863235 for more context.
