### ISSUE TITLE
While I was trying to create a new branch in order to answer Max the command failed because the branch name was already taken.

### ISSUE THREAD

**Issue by wolmir** [iterative/vscode-dvc#1934]
While I was trying to create a new branch in order to answer Max the command failed because the branch name was already taken.
But the extension didn't report it.
Maybe it's a bug?

_Originally posted by @wolmir in https://github.com/iterative/vscode-dvc/issues/1924#issuecomment-1160668339_

**Comment by mattseddon** [comment]
This was caused by not registering the commands that interact with the CLI through the normal path. The corresponding commands that run through the palette already have the desired behaviour. Will be a straightforward fix next week.
