### ISSUE TITLE
readme: float banner to a side?

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/vscode-dvc#1937]
So we want both a banner AND this animation this close to one another? The idea of not having to scroll to get the full value proposition can't apply. For now I put the intro paragraph above the gif...

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1477535/173514869-d758b755-6285-44bf-9588-ffc736f4407a.png">

TBH I'm not loving the banner as it is now (it's not horizontal): maybe we can get a square file to float on the left or right side of the title and badges?

_Originally posted by @jorgeorpinel in https://github.com/iterative/vscode-dvc/pull/1816#discussion_r896449536_

**Comment by jorgeorpinel** [comment]
WDYT @maxagin ? Thanks

**Comment by maxagin** [comment]
> not loving the banner as it is now (it's not horizontal)

I also had this concern before. Let me see what I can do. Thank you @jorgeorpinel

**Comment by maxagin** [comment]
Thank you @jorgeorpinel , follow-ups issues are important, so we can have team feedback and better understand what possibly needs to be improved. Next time we will have a good argument when discussing this matter :) and p2 is better than nothing, lol !

**Comment by shcheklein** [comment]
Closing this for now. Let's do this with the next major update.
