### ISSUE TITLE
Support `exp init` command

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#1940]
It would be nice to support https://dvc.org/doc/command-reference/exp/init as part of the extension commands. 

The command is useful for bootstrapping projects and only requires `git init` and `dvc init` which, as far as I have tested, are also the minimum requirements for the extension to load correctly.

Perhaps it could be added as an optional step of the `Setup the Workspace` workflow

**Comment by mattseddon** [comment]
We do have this button available when the CLI is accessible but there is no DVC project in the workspace:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/176062564-5e46a393-848e-49de-bf3c-955deab68be2.png">

Which was inspired by the Source Control welcome view:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/176062666-93bdc286-d8ac-4f34-9304-63c49a652132.png">

The button currently runs `dvc init`. Would moving this to `dvc exp init` be enough? Should we show both options? WDYT?

**Comment by shcheklein** [comment]
I think this a bigger story and can be one the main priorities for Q3. How do we improve the onboarding experience? It can be a wizard (quick pick or a separate webview even), can be some auto capturing of command people run to generate dvc.yaml, improving remotes handling / data codification part, etc.

**Comment by mattseddon** [comment]
Relates to #1531

**Comment by shcheklein** [comment]
Closing this in favor of the future changes to the `dvclive` and onboarding experience.
