### ISSUE TITLE
README: explain integration between VS Code and Studio

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#1947]
Since both product deal with experiments it's not immediately clear what's the difference is and when each of them should be used + we could have an extra mention of Studio in the README.

**Comment by maxagin** [comment]
Would be great to have a sort of description, and motivation for this ticket :)

**Comment by shcheklein** [comment]
@maxagin done, good point. I was considering this as my personal TODO in this case, but clearly it will stay here for a while. Initial source for this is from some Slack discussion.

**Comment by shcheklein** [comment]
Closing in favor of https://github.com/iterative/vscode-dvc/issues/3331
