### ISSUE TITLE
Prompt on applying experiment to workspace

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#1956]
Thanks to @pmrowla and @daavoo for bringing this up. By default, `dvc exp apply` will overwrite files in the workspace unless you use `--no-force`. Since conflicts between experiments are common (for example, changing the same parameter to different values across multiple experiments), this default makes sense in most cases. We found that it was too much work to ask users to constantly have to specify whether they wanted to overwrite.

With VS Code, it might be worth exploring whether to use `--no-force` and prompt the user. Clicking on a prompt is easier than adding a CLI flag, and the extension could even give some option like "Don't show this prompt again" if they find it too annoying.

**Comment by shcheklein** [comment]
> We found that it was too much work to ask users to constantly have to specify whether they wanted to overwrite.

This combination of the prompt and `--no-force` doesn't look like a regular approach to me. It doesn't allow to solve a scenario when I'm automating things - it won't fail, it'll prompt. And there is no option to respond to this prompt automatically, right? + as a user it'll too late for me to learn about `--no-force`, I'll learn about it after I made a mistake (at best). Am I missing something here?

 A better, safer, and quite common alternative (similar to `git checkout`, `git push`, `git pull`, etc) could be to:

- fail fast if there are irreversible changes
- mention that there is `--force` if you'd like to still apply the changes
- add config to apply `--force` automatically
- stash changes (and mention that those are stashed) before applying. So there is always a way to get back.

@dberenbaum wdyt about this approach?

The same logic will apply in VS Code then. It can run, see that there are conflicts, fail fast, show a prompt after that. But also always stash the current workspace and show in the Notification the message.

**Comment by dberenbaum** [comment]
> This combination of the prompt and `--no-force` doesn't look like a regular approach to me.

It's definitely not a regular approach. It went through several iterations but ended up here because the typical approach got too annoying for even the most basic experiment scenarios. Unlike the typical Git commands and workflows, conflicts are an inherent part of exp apply. Almost every time you apply an experiment on top of another, you will get a conflict.

> It doesn't allow to solve a scenario when I'm automating things - it won't fail, it'll prompt. And there is no option to respond to this prompt automatically, right?

There's no prompt. My description above was probably misleading.

> * stash changes (and mention that those are stashed) before applying. So there is always a way to get back.

I like this idea, but I'm not sure we need any of the other bullets above if we have this mechanism and hint. @pmrowla WDYT?

**Comment by pmrowla** [comment]
We already do stash the changes but drop the stash after the `apply` completes. Preserving the stash entry would be a simple change

**Comment by dberenbaum** [comment]
Opened https://github.com/iterative/dvc/issues/7955. In that case, prompting in VS Code should be unnecessary, although VS Code may want to highlight how to recover the dirty workspace since it may still appear to users that their work gets lost.
