### ISSUE TITLE
Walkthroughs: feedback and suggestions (Get Started)

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1958]
- [x]  👉 11. New screenshot style
Let's not change the style for now (seems minor, and there was a reason to keep the shadow - looked better on a dark background, more contrast). It would be great to avoid the full update of all the images. Or do we need / plan to update all the images? (Closing for now, please feel free to reopen it also).

Please also consolidate it with the text update in a single PR.

- [x]  👉 9. Update the DVC: Get Started / Plots Dashboard

First of all, we can update the DVC: Get Started / Plots Dashboard, ~~I think this will be already helpful.~~
We can explicitly mention and show the screenshot of how to select the EXP for Plots.

### The draft

Select `(click the circle beside the experiment name)` ~~one or more~~ `up to 7` experiments `in the table view` to visualize in the Plots Dashboard. 
`screenshot`
Use DVC: Show Plots from the command palette to open it `or open it using the table's row context menu`.

<img width="500" alt="Screen Shot 2022-10-06 at 9 59 17 PM" src="https://user-images.githubusercontent.com/98249521/194450541-6e9291c7-ed21-4991-b0ca-227b902b5c79.png">

Screenshot example (do not use this one):

<img width="500" alt="Screen Shot 2022-10-06 at 9 57 35 PM" src="https://user-images.githubusercontent.com/98249521/194450399-0895976c-081d-4ca9-83f1-751b9198de19.png">

Related to https://github.com/iterative/vscode-dvc/issues/2373

---

- [ ]  👉 8. Opportunity for cross-promotion which can actually be meaningful in terms of user workflow. One of the many possible options. For example, in GetStarted, after Troubleshoot & Support add Collaborate, including information on how you collaborate in DVC Studio.

Message examples:
a.Now you are all set up, please do not forget to learn how our DVC Studio can help you and your team to collaborate on your ML projects…
b.Now you are all set up, please do not forget to create your account in DVC Studio where the collaboration on ML projects is happening

See the discussion here:
https://iterativeai.slack.com/archives/C01APS0FHDM/p1658437149849249

---

- [ ] 👉 2. Would expect to see the same title (correct for all the sections)

<img width="400" alt="Screen Shot 2022-06-29 at 11 11 33 PM" src="https://user-images.githubusercontent.com/98249521/176584832-d635e755-622e-4bd6-9771-6424e34a20c1.png">

> If we decide to rename after all (I'm fine with that) we should rename the file also, and update the package.json

---

- [x]  👉 4. For the Plots we can mention and show screenshot, about how to toggle exp/s in the table :)

---

- [x]  👉 5.  Déjà vu

<img width="400" alt="Screen Shot 2022-06-29 at 11 24 58 PM" src="https://user-images.githubusercontent.com/98249521/176586387-49ffa0fe-a783-4d4f-a926-2ea2b3e02558.png">

---

- [x]  👉 6. I think this is important enough to show a screenshot. WDYT?

<img width="400" alt="Screen Shot 2022-06-29 at 11 27 06 PM" src="https://user-images.githubusercontent.com/98249521/176586608-5b3fa7af-a145-4f85-8683-94c651147e3e.png">

---

- [ ]  👉 7. Very minor: Helpful Resources

<img width="400" alt="Screen Shot 2022-06-29 at 11 30 30 PM" src="https://user-images.githubusercontent.com/98249521/176586941-1ebe72d1-fb29-40dd-a515-88b8cd376431.png">

# To consider

- [x]  👉 1. Why don't we use code snippets instead of just images?

<img width="400" alt="Screen Shot 2022-06-29 at 11 10 37 PM" src="https://user-images.githubusercontent.com/98249521/176584692-e0b2624c-f022-425e-bf6b-d07d221b261b.png">

**Comment by maxagin** [comment]
Overall very helpful information and a well-crafted section, will study it more :). Thank you, folks!

**Comment by mattseddon** [comment]
cc @jorgeorpinel

**Comment by jorgeorpinel** [comment]
> 1. Why don't we use code snippets instead of just images?

Nice to have, not critical. As of now these walkthroughs are written more as quick-read tours rather than follow-along guides. Users can go to the DVCLive (or any other linked) docs to learn how to use them and copy/paste better code from sample blocks.

> 2. Would expect to see the same title

Tend to agree. Doesn't have to be 100% the same always but closer at least.

> 3... why not list all commands

There's a lot and they may change often. Better to let users browse them directly from the Cmd Pallette.

> 4... mention and show screenshot, about how to toggle exp/s in the table

Yes. Good thing to emphasize this in the **Experiments Table** page.

> 5. "using using"

Fixed.

> 6... show a screenshot (bottom tip of Live Plot Update page).

Meaning a code sample? Wouldn't hurt, esp. if it's an existing image repeat (less maintenance).

> 7.

Addressed.

**Comment by maxagin** [comment]
>6... show a screenshot ("enable checkpoints" at the bottom of the Live Plot Update page).

>>Meaning a code sample? Wouldn't hurt, esp. if it's an existing img. repeat (less maintenance).

We have some difficulties explaining how the user should toggle plots in the exp table. This is why I suggested including a screenshot in relation to the underlined text in the IMG below (unable checkpoint).

![image](https://user-images.githubusercontent.com/98249521/177485415-f811de9e-95af-4e2b-b682-ad0def77d901.png)

Thank you @jorgeorpinel !

**Comment by maxagin** [comment]
> Opportunity for cross-promotion which can actually be meaningful in terms of user workflow

> One of the many possible options. For example, in GetStarted, after Troubleshoot & Support add Collaborate, including information on how you collaborate in DVC Studio.
Message examples:
a.Now you are all set up, please do not forget to learn how our DVC Studio can help you and your team to collaborate on your ML projects…
b.Now you are all set up, please do not forget to create your account in DVC Studio where the collaboration on ML projects is happening

https://iterativeai.slack.com/archives/C01APS0FHDM/p1658437149849249

**Comment by maxagin** [comment]
I have updated the ticked and also included the suggestion from  https://github.com/iterative/vscode-dvc/issues/2373 - Update the DVC: Get Started / Plots Dashboard

**Comment by maxagin** [comment]
>  Why don't we use code snippets instead of just images?

@shcheklein would it be the correct way to do this or there is a different way?

```
<pre><code>
Some code
</code></pre>
```

<pre><code>
train:
  cmd: python src/train.py
  deps:
    - data/features
    - src/train.py
  params:
    - epochs
  outs
    - models/predict.h5
  metrics:
    - metrics.json:
        cash: false
</code></pre>

<img width="778" alt="Screen Shot 2022-10-12 at 12 37 22 PM" src="https://user-images.githubusercontent.com/98249521/195399722-b09d24f3-3d72-4bb5-b473-14f6a3a4085a.png">

**Comment by maxagin** [comment]
<pre><code>
1   train:
2     cmd: python src/train.py
3     deps:
4       - data/features
5       - src/train.py
6    params:
7       - epochs
8     outs
9       - models/predict.h5
10     metrics:
11      - metrics.json:
12           cash: false
</code></pre>

**Comment by maxagin** [comment]
Specifying the theme an image is shown to
You can specify the theme an image is displayed for in Markdown by using the HTML `<picture>` element in combination with the prefers-color-scheme media feature. We distinguish between light and dark color modes, so there are two options available. You can use these options to display images optimized for dark or light backgrounds. This is particularly helpful for transparent PNG images.

For example, the following code displays a sun image for light themes and a moon for dark themes:

```
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/25423296/163456776-7f95b81a-f1ed-45f7-b7ab-8fa810d529fa.png">
  <source media="(prefers-color-scheme: light)" srcset="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
  <img alt="Shows an illustrated sun in light mode and a moon with stars in dark mode." src="https://user-images.githubusercontent.com/25423296/163456779-a8556205-d0a5-45e2-ac17-42d089e3c3f8.png">
</picture>
```

**Comment by shcheklein** [comment]
> Specifying the theme an image is shown to
@maxagin what is the source of this information? is it supported in VS Code markdown? 

(overall, I think we should be fine with a single type (dark) images for now to keep it simple - less things to generate and keep taking care of)

**Comment by shcheklein** [comment]
A better solution is to use code blocks:

```yaml
train:
  cmd: python src/train.py
  deps:
    - data/features
    - src/train.py
  params:
    - epochs
  outs
    - models/predict.h5
  metrics:
    - metrics.json:
        cash: false
```

It starts with "```yaml" and end with "```":

<img width="253" alt="Screen Shot 2022-10-12 at 2 54 58 PM" src="https://user-images.githubusercontent.com/3659196/195455284-e759081c-96e7-4dbf-80d7-ba634181e577.png">

**Comment by shcheklein** [comment]
> @jorgeorpinel please point me to the source file with the shadow we use for the images. Example below. Thank you !

It's here, Max: https://www.figma.com/file/hbhgEECgmGaHolFDzq7yVK/VS-Code-Walkthrough?node-id=0%3A1 - feel free to move it around to the right location.

**Comment by maxagin** [comment]
> Specifying the theme an image is shown to
@maxagin what is the source of this information? is it supported in VS Code markdown?

@shcheklein . Here you are:
https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/
