### ISSUE TITLE
`UX` Better `on hover` feedback in experiments

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/vscode-dvc#1960]
<img width="214" alt="image" src="https://user-images.githubusercontent.com/414967/176660005-b88497f0-aafd-487d-95fa-222cea94aaa5.png">

What is happening to me is that I do not "feel" that I am actually interacting with an item of the grid since I do not have any feedback... so I click the row and then... I have one row deselected 

<img width="270" alt="image" src="https://user-images.githubusercontent.com/414967/176660397-180e97ac-eb0d-468e-92dd-c6454ab64346.png">

I need to have that visual feedback to know that the row is able to accept the "right" click.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/414967/176660627-97c97871-13a7-4a8e-8c17-30da6e4bdf62.png">

I have fallen in this UX trap many times

**Comment by DavidGOrtega** [comment]
I would keep the left click to select the row and I would add a checkbox to clearly identify my selection

<img width="775" alt="image" src="https://user-images.githubusercontent.com/414967/176662759-5639c9eb-048e-4c2d-96eb-ff91b205690a.png">

**Comment by mattseddon** [comment]
Related to #1924

**Comment by mattseddon** [comment]
Initial checkboxes implementation merged with #1964. Please follow #1924 for further updates.
