### ISSUE TITLE
Only show relevant columns in experiments table

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#1994]
Similar to `dvc exp show --only-changed`, the experiments table should be able to show (either by default or through some option) only the columns where there are differences between experiments.

**Comment by maxagin** [comment]
Thank you @dberenbaum for bringing this in, I am working on a few new concepts and this may help me to have a better story and more convenient workflow.

I am sharing the ideas. Let's discuss it friendly, please :)

**Only show relevant columns in experiments table**

<img width="1077" alt="Screen Shot 2022-07-06 at 11 22 29 PM" src="https://user-images.githubusercontent.com/98249521/177683984-7cf02dd8-ec5e-4df4-8ea2-10a8d334b6bf.png">

**+ and collapse rows without changes**

<img width="1064" alt="Screen Shot 2022-07-06 at 11 22 45 PM" src="https://user-images.githubusercontent.com/98249521/177684036-f6fdee2e-31d0-44c5-9d78-f7b392bb83c1.png">

**Comment by dberenbaum** [comment]
Thanks @maxagin! I worry those are a bit too specific and inflexible regarding hiding/unhiding only one of rows/columns. Comparing to Studio, they hide rows by default and provide an option to expand to show all, right? I think this could be a sensible default (and probably one we should consider in the CLI also).

The default table could hide redundant columns and rows and provide options to:
1. Show all columns (whether hidden by default or by manual filtering).
2. Show all rows (whether hidden by default or manual filtering).

What is the way to unhide columns now? I can't seem to find it.

**Comment by maxagin** [comment]
> Comparing to Studio, they hide rows by default and provide an option to expand to show all, right?

and

>I think this could be a sensible default

@dberenbaum, you will need to run some exps before having information in the table and plots. No?
`Run exps -> See result -> Adjust interface`
Your needs are changing with the amount of exps you have run. Meaning more exps you have better filtering options you will need.

> What is the way to unhide columns now? I can't seem to find it.

At the GUI level is at the sidebar/columns

> Show all columns (whether hidden by default or by manual filtering).

I do not think we have “unhide all”
 
> Thanks max! I worry those are a bit too specific and inflexible regarding hiding/unhiding only one of rows/columns.

We already providing tools, filters and sorts. What you had mentioned in the current situation is a very specific option to my mind. Not sure, please correct me if I am wrong.
 
> regarding hiding/unhiding only one of rows/columns.

The concept describes the situation when you will hide (unhide) all the rows and columns that were not changed. Conceptually this is a toggle.

**Comment by dberenbaum** [comment]
Sorry @maxagin, I misunderstood your diagrams.

> Your needs are changing with the amount of exps you have run. Meaning more exps you have better filtering options you will need.

Good point, what is "redundant" will change over time since the table is dynamically updated, so it won't make sense to have this option always "on" by default.

> > regarding hiding/unhiding only one of rows/columns.
> 
> The concept describes the situation when you will hide (unhide) all the rows and columns that were not changed. Conceptually this is a toggle.

Yup, makes sense.

> > Thanks max! I worry those are a bit too specific and inflexible regarding hiding/unhiding only one of rows/columns.
> 
> We already providing tools, filters and sorts. What you had mentioned in the current situation is a very specific option to my mind. Not sure, please correct me if I am wrong.

It sounds specific, but it's actually common and a bit different from what you have above and what I see in Studio. In Studio, it is a long-term view, where often many rows are the same or have slight differences, and those changes may appear in different columns over time.

In VS Code, there is active experimentation, so each row is very likely to contain some changes, often on the same subset of columns. For example:

<img width="1070" alt="Screen Shot 2022-07-07 at 1 39 04 PM" src="https://user-images.githubusercontent.com/2308172/177835859-1bea4eaf-f92a-40ec-bc72-9b68938b07c2.png">

In this simplified example, all the blue params columns are the same except for `min_split`, which is the current parameter of interest (in reality, there are often a handful of columns likely to change each time). There are often way too many columns to fit on the screen so this column may be hidden out of view. Users can drag the relevant columns over, so it might not be critical, but finding them if there are many columns could be annoying.

So I guess it's less about showing, hiding, or highlighting, and more about the column order. For example, maybe it would be useful to have an option to reorder columns to show those where any row has a change first, but maybe you can come up with better ideas to solve the problem.

> > What is the way to unhide columns now? I can't seem to find it.
> 
> At the GUI level is at the sidebar/columns

By the way, I still don't understand how to do this 😅 . I'm sure it's my own mental block, but just a note to consider how easy it is to find this option.

**Comment by mattseddon** [comment]
@dberenbaum 

> By the way, I still don't understand how to do this 😅 . I'm sure it's my own mental block, but just a note to consider how easy it is to find this option.

Just in case you are still stuck => See the view container in the sidebar:

https://user-images.githubusercontent.com/37993418/178634176-50806fd2-550b-468a-a1e8-3c18543fe48a.mov

**Comment by wolmir** [comment]
@dberenbaum @maxagin 
Something like this, maybe?


https://user-images.githubusercontent.com/1231848/179824782-b794c219-9124-4c7b-803b-423948dc863a.mov

**Comment by maxagin** [comment]
Great ! 
I think now we are ready for the UI solution iterations. I will update you when it's ready. Thank you, folks!

**Comment by maxagin** [comment]
Hey folks! 
I think the below sketch may be a good solution. Let me know how you feel about it. Thank you !

In relation to - Inform the user about hidden (plots, sidebar) or applied actions with table https://github.com/iterative/vscode-dvc/issues/2075

Concept: We just highlight changes. The user can still see the same table and continue to work with the information.

@dberenbaum  especially would like to ask you for your opinion here:) Thanks!

### Before
<img width="1201" alt="Screen Shot 2022-07-20 at 11 45 00 PM" src="https://user-images.githubusercontent.com/98249521/180125696-477d2bdc-2403-43f4-93b4-e5df75db884e.png">

### After
<img width="1204" alt="Screen Shot 2022-07-20 at 11 45 09 PM" src="https://user-images.githubusercontent.com/98249521/180125730-bfa92b4e-406e-4427-8316-f2f5d972f613.png">

### Same two examples, but in context

<img width="1208" alt="Screen Shot 2022-07-20 at 11 46 42 PM" src="https://user-images.githubusercontent.com/98249521/180125873-7328067b-3038-4883-8a5b-502fcfbaa487.png">

<img width="1209" alt="Screen Shot 2022-07-20 at 11 46 51 PM" src="https://user-images.githubusercontent.com/98249521/180125888-f464b48e-15c1-419c-b2e4-04f1564ab53a.png">

**Comment by dberenbaum** [comment]
Thanks @maxagin! 

What is considered "changed" here?

This seems potentially useful to quickly pick out meaningful values from the table. However, my immediate concern was that those values are often hidden in columns to the right off the screen and potentially spread out, so highlighting won't do much good.

Regarding the problem of the columns being off the screen, if I'm doing hyperparameter tuning, I may be trying a different value every experiment for a few columns and all other columns stay unchanged for every row in the table. I was hoping a solution might allow me in a single step to "snap" or reorder columns and bring them to the left of the screen if any values in that column are unequal (and if more experiments come, I can perform the reordering again based on the updated table values).

Regarding the problem of quickly seeing meaningful values from the table, highlighting seems nice, but it's unclear to me how we identify which values to highlight. It's not always important whether the value has changed from the previous row since often many experiments will be queued and run together and the order won't matter. At my previous company, their internal experiment tracking tool used color gradients to highlight the extreme values in each column ([like conditional formatting in a spreadsheet](https://webapps.stackexchange.com/questions/123033/conditional-formatting-with-color-scale-for-many-rows-independently-once)). I know those are noisy and not that clean looking, but something like that can be a helpful visual aid more than a binary choice of whether the value is interesting or not.

**Comment by maxagin** [comment]
Hi @dberenbaum ! Please see my response below.

> What is considered "changed" here?

High-fidelity UI solution + actions ribbon concept. The logic we discussed is the same. See below for more details.

---

> This seems potentially useful to quickly pick out meaningful values from the table. However, my immediate concern was that those values are often hidden in columns to the right off the screen and potentially spread out, so highlighting won't do much good.

You can hide columns and also change their position in the table already 

**Change position**

https://user-images.githubusercontent.com/98249521/180369357-707f3a4c-a9a9-46df-a0f2-c7816046b158.mov

**Hide**

https://user-images.githubusercontent.com/98249521/180369369-086db1cb-8583-489e-be79-83e816667376.mov


The Show Only Changed will help to adjust the table as you would like to. 
The workflow I can imagine:

a.toggle --only-changed (simplify the view).
b.move and hide columns. Put them near each other beside the exps column, so all the columns with the changes are at the one place close to each other.
c. compare and mark with the stars most interesting, rename and eventually add some descriptions
d. eventually collapse, not interesting rows (with the delete option if the user wants to remove it completely)
e. continue experimenting in the table and comparing Runs in the Plots view

---

> Regarding the problem of the columns being off the screen, if I'm doing hyperparameter tuning, I may be trying a different value every experiment for a few columns and all other columns stay unchanged for every row in the table. I was hoping a solution might allow me in a single step to "snap" or reorder columns and bring them to the left of the screen if any values in that column are unequal 

Good. I thought that it may be good if users can see all the information, but have the option to reorder or hide columns manually, but if you think it’s not important we could hide unchanged columns automatically and show them back if the changes happened in the hidden columns. See below:

**Before**

<img width="1011" alt="Screen Shot 2022-07-22 at 1 39 48 AM" src="https://user-images.githubusercontent.com/98249521/180370672-ac19d8db-3efa-4c93-81f1-641a56e1f1a9.png">


**After**

<img width="1016" alt="Screen Shot 2022-07-22 at 1 36 32 AM" src="https://user-images.githubusercontent.com/98249521/180370519-32398736-7724-4415-9757-0a6dfd9733e3.png">



> (and if more experiments come, I can perform the reordering again based on the updated table values).

This is something that will happen also automatically, based on the above, unless you will toggle the Show Only Changed off. Does it make sense?

---

> Regarding the problem of quickly seeing meaningful values from the table, highlighting seems nice, but it's unclear to me how we identify which values to highlight. It's not always important whether the value has changed from the previous row since often many experiments will be queued and run together and the order won't matter. 

Yeah. It is why I have proposed keeping all the values, so if the “system” is wrong, the user still can see all info and make the decision.
However, we are displaying the exps in the order, so my guess is the oldest (cell value) will be highlighted



> At my previous company, their internal experiment tracking tool used color gradients to highlight the extreme values in each column (like conditional formatting in a spreadsheet). I know those are noisy and not that clean looking, but something like that can be a helpful visual aid more than a binary choice of whether the value is interesting or not.

This is great, but may be very complex to implement. @mattseddon  what do you think about this?

**Comment by mattseddon** [comment]
> > At my previous company, their internal experiment tracking tool used color gradients to highlight the extreme values in each column (like conditional formatting in a spreadsheet). I know those are noisy and not that clean looking, but something like that can be a helpful visual aid more than a binary choice of whether the value is interesting or not.
> 
> This is great, but may be very complex to implement. @mattseddon what do you think about this?

Not impossible but would be painful. We would need a very good reason (or be very brave) to start on this without a lot of data/signal to back it up.

**Comment by dberenbaum** [comment]
> The workflow I can imagine:
> 
> a.toggle --only-changed (simplify the view). b.move and hide columns. Put them near each other beside the exps column, so all the columns with the changes are at the one place close to each other. c. compare and mark with the stars most interesting, rename and eventually add some descriptions d. eventually collapse, not interesting rows (with the delete option if the user wants to remove it completely) e. continue experimenting in the table and comparing Runs in the Plots view

Sorry, I should have been explicit that I'm aware that I can hide and move columns, but I would like it to be easy and quick to get to the relevant info. Those columns of interest may be way off to the right and spread out from each other. This workflow feels like a lot more work for the user than auto-reordering (which is what I meant by "snapping").

> Good. I thought that it may be good if users can see all the information, but have the option to reorder or hide columns manually, but if you think it’s not important we could hide unchanged columns automatically and show them back if the changes happened in the hidden columns.

Yes, this is what I would like to see. I agree that it may be aggressive to hide the columns, so I would prefer to reorder them. No strong opinion on whether we do that automatically or via a toggle.

> >   (and if more experiments come, I can perform the reordering again based on the updated table values).
>
> This is something that will happen also automatically, based on the above, unless you will toggle the Show Only Changed off. Does it make sense?

I thought from the above that "Show Only Changed" highlights changes but doesn't reorder anything?

If we go with the option to reorder columns, then yes, it makes sense.

**Comment by maxagin** [comment]
> Yes, this is what I would like to see. I agree that it may be aggressive to hide the columns, so I would prefer to reorder them. No strong opinion on whether we do that automatically or via a toggle.

Reorder without user permission would not be good. If we hide unchanged columns with the toggle “--only-changed” this is more correct to my mind, as the user requesting this changes by toggle activation.

> I thought from the above that "Show Only Changed" highlights changes but doesn't reorder anything?

Hiding unchanged columns and highlighting changed cell values.

So the mockup below is satisfying our requirements to my mind:

<img width="831" alt="Screen Shot 2022-07-22 at 7 07 31 PM" src="https://user-images.githubusercontent.com/98249521/180579426-7e3d6106-5b3f-4d39-a979-7164947d3df6.png">

**Comment by maxagin** [comment]
@dberenbaum I have put together a document including four possible options with a detailed analysis of each one. Please review the document and let me know what you think would be the best solution for us to follow. 
Have a great weekend!

[Figma ](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments-Table?node-id=1318%3A51417)

@shcheklein  in case you have nothing better to do than browsing GH this beautiful Friday evening :) You are most welcome to share your comments on this issue.

**Comment by dberenbaum** [comment]
Hi @maxagin, sounds good, thanks! It looks like I don't have permission to see the figma doc. Can you check?

**Comment by dberenbaum** [comment]
Thanks @maxagin!

**Thoughts on option 1**

Option 1 does NOT reorder nor hide any columns, right?

If that's true, is a toggle needed? Is it ever helpful to toggle highlighting off?

Option 1 seems like a good start no matter what else we decide to do.

**Option 5 🤣 **

Let me try to better explain what I have in mind, and you can let me know if it makes sense. 

The idea is to reorder changed/unchanged columns using something like an action button. This is not a toggle, nor is it automatic. Instead there is some button to "move changed columns to the left." It reorders the columns and then returns control to the user and does not "stay on" like a toggle.

The workflow would look like:

1. Click the "move changed columns" button to create a useful default view.
2. Manually move and hide columns to further tweak the view.
3. Compare rows and star, label, hide, etc.
4. Continue experimenting.
5. Click the "move changed columns" button again. If there are newly changed columns, they will be moved to the left of any unchanged columns.
6. Continue comparing.

Advantages I see to this approach:
1. It allows users to get to a reasonable view quickly.
2. It doesn't interfere with users' choices of columns to hide.
3. Since it's not a toggle, users can manually reorder columns after without confusion.

**Final thoughts**

Without any reordering, I don't think we address the original request. The step to "manually move and hide columns" to get to a reasonable view still seems painful. It doesn't need to be top priority, but I would like to at least keep the issue open until we have some way to avoid that step.

**Comment by dberenbaum** [comment]
A customer complained that they don't use the extension much because it's hard for them to keep the table looking clean as their project grows and metrics and their names change over time (and between different branches). Even though they can hide columns, they find it hard to maintain the right columns as they work on the project.

**Comment by dberenbaum** [comment]
Not sure if they use something else or just don't use it as much as they would otherwise. We will meet again next week, so I'll make a note to follow up.

**Comment by PythonFZ** [comment]
I was going through the issues here and was looking if this feature has been discussed already.
As an enduser I just wanted give a short report.

I like the idea of `move changed columns` for some customized view on the experiments.
But I'm also using DVC in such a way, that I'm trying to log every possible parameter. (see [ZnTrack](https://github.com/zincware/zntrack) for more information)
Therefore, I often have a lot of parameters that aren't changed at all. This could be a few hundred. Selecting them can be a tedious task so I would be very much in favour of having a `Show only changed` toggle just like `dvc exp show --only-changed` and discussed by [maxagin](https://github.com/maxagin)

**Comment by mattseddon** [comment]
@PythonFZ ICYMI this feature was (finally) implemented in #4402 (see PR for a demo on how it works), please LMK if you have any feedback 🙏🏻.
