### ISSUE TITLE
Bug with selecting exps

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2003]
Select one -> Shift + select one above. Won’t be selected.

https://user-images.githubusercontent.com/98249521/177898638-9029880c-7a1b-476c-aa29-a4f2e516d9b3.mov

**Comment by wolmir** [comment]
@maxagin Can you add more info please? I couldn't reproduce following the steps in the video

**Comment by shcheklein** [comment]
@maxagin please include the extension version also. Can it be that you were trying an older version of it?

**Comment by maxagin** [comment]
Hey @wolmir  were you able to reproduce the issue? Where can I find the extension version? Thanks

**Comment by wolmir** [comment]
@mattseddon @rogermparent Can you guys reproduce this bug in the latest marketplace release?

**Comment by rogermparent** [comment]
I can replicate it on marketplace release
I'll edit in a video soon

**Comment by mattseddon** [comment]
[Q] Did #1986 fix this? It only just got shipped.

**Comment by mattseddon** [comment]
Looks like it did:

https://user-images.githubusercontent.com/37993418/178867286-841f9d9b-ce33-4d9e-b453-095f2945bf94.mov
