### ISSUE TITLE
Add a shadow to the sticky experiments column

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#2017]
![image](https://user-images.githubusercontent.com/9111807/178613700-e2cf5aba-fe6b-42f6-8b6d-c7b97b335845.png)

The strong border between the sticky experiments column and the content under it can be a bit jarring, and we may want to consider giving it a conditional shadow like #2010.

We could also consider another effect, like monday.com's semi-transparent sticky column that slightly shows contents under it and terminates in a normal border line.
![image](https://user-images.githubusercontent.com/9111807/178614285-8505bf17-b034-43ef-a094-7284381b892e.png)

**Comment by maxagin** [comment]
Hey @julieg18 , I have spent some time thinking and sketching the vertical and horizontal shadows on scroll appearance. Please take a look at the [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments-table?node-id=1194%3A34594), I hope this will be helpful. Let me know if you have any questions.

**Comment by julieg18** [comment]
Thanks for the Figma, @maxagin! I noticed that the "Horizontal and vertical shadow on scroll" design shows both the "Experiment" and "workspace" cells being sticky:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/43496356/179506577-c121f522-7b28-4ce0-af31-9122383f279e.png">

But the extension doesn't make the "workspace" row sticky, just the "experiments":

<img width="332" alt="image" src="https://user-images.githubusercontent.com/43496356/179506937-232031ea-1e85-4852-8e5e-82071c7871d3.png">

Did you want me to change the table behavior, making the workspace part sticky, or do I keep the sticky behavior as is?

**Comment by rogermparent** [comment]
I'd say the best way to go about it, particularly in this project, is to make the first PR for the shadows only, and then make a follow-up with sticky workspace row if we want it after some discussion. Both problems are quite different, and a sticky workspace row seems like it'd be significantly more involved than the shadow alone, let alone combining the two.

**Comment by maxagin** [comment]
> Did you want me to change the table behavior, making the workspace part sticky, or do I keep the sticky behavior as is?

We have a ticket for this. Here is a related discussion https://github.com/iterative/vscode-dvc/issues/2032 
Thank you @julieg18 !

**Comment by maxagin** [comment]
@julieg18  , just so if you have not noticed. The default state (before the scroll activation) - the sticky part has no shadow for both, vertical and horizontal. Thanks !
