### ISSUE TITLE
Include the Workspace row into the fixed section along with the table header

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2032]
Include both workspace and main (branch) into the fixed section on top https://github.com/iterative/vscode-dvc/issues/2032#issuecomment-1185097951

Will be done after  https://github.com/iterative/vscode-dvc/issues/2070 completed!

---

https://user-images.githubusercontent.com/98249521/175386685-67d7e96f-6326-46c3-8e1a-5c0a2bdda10d.mov

**Comment by shcheklein** [comment]
Yes, it makes sense. May be even both of them - workspace and main above. Studio does the same- sticks the branch name so that context is not lost. Q - should we stick the experiment if there a lot of checkpoints and we scrolling them (again, similar to Studio).

**Comment by maxagin** [comment]
> Q - should we stick the experiment if there a lot of checkpoints and we scrolling them (again, similar to Studio).

Sticky rows

https://user-images.githubusercontent.com/98249521/179147250-1ac9e6e3-ca49-4261-bc49-437d4b399561.mov
