### ISSUE TITLE
Prevent text from highlighting while resizing columns

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2034]
Can we disable some styles when resizing the columns? and for similar cases: when the user works with something, other info blocks should not be affected. 

Please think about similar cases and list them below. Thanks, folks!

https://user-images.githubusercontent.com/98249521/177383836-44d796ab-fe34-4a7e-a785-a3ed8ce44675.mov

**Comment by shcheklein** [comment]
@rogermparent I remember we were discussing this? Do we have a ticket for this by chance?

**Comment by rogermparent** [comment]
You're right that we talked about it, but I couldn't find a ticket nor an item in any of the recent exp table stories

**Comment by rogermparent** [comment]
Regarding the title, I think the solution to this specific problem will be more in the JS side like #1723 as opposed to styling, we don't want users to have these same highlights invisibly if we can help it

**Comment by maxagin** [comment]
> You're right that we talked about it, but I couldn't find a ticket nor an item in any of the recent exp table stories

This was a part of https://github.com/iterative/vscode-dvc/issues/1562 
Thank you @rogermparent

**Comment by maxagin** [comment]
> The other solution would be to disable selection only while resizing.

I think this would work just fine for now.
