### ISSUE TITLE
Select and apply star, appears with a small delay

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2035]
I have noticed that a little delay exists when clicking on the star or checkbox. It is not a bug, but do you think we can improve this by making the response happen faster? Thanks

**Comment by shcheklein** [comment]
Can be related to #2036 cc @wolmir ?

**Comment by maxagin** [comment]
I have noticed VSCode, in general, has controls that sometimes behave with a small delay, however, some controls do not have it.

**Comment by mattseddon** [comment]
I am unable to recreate:

https://user-images.githubusercontent.com/37993418/189040421-a5fa8cff-8dba-4256-9ba1-f6fc23765f26.mov

**Comment by maxagin** [comment]
This is weird because on my end it's happening all the time with stars.


https://user-images.githubusercontent.com/98249521/189161523-6b09c16d-fb5b-44a0-8a36-cdf0fb355a80.mov
