### ISSUE TITLE
When applying a star to the exp, some strange styles appear on the sidebar

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2036]
https://user-images.githubusercontent.com/98249521/179128304-0a47be1f-288b-458d-a6c8-d53bbb5ad1fa.mov

**Comment by shcheklein** [comment]
Interesting, seems like it tries to run a progress bar or something?

**Comment by mattseddon** [comment]
Those are progress bars they will be triggered whenever the tree is being updated/loading. They are feature of VS Code.
