### ISSUE TITLE
Show a tooltip if the user trying to toggle exp and 7 expS are already toggled 

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2041]
TODO:

- [ ] https://github.com/iterative/vscode-dvc/issues/2041#issuecomment-1185195522
- [ ] Figure out side bar mechanics for this

--------

I think we can show a notification `You can toggle maximum 7 experiments` if the user trying to toggle a new exp (we have a max 7). Because I kinda thought that this is a bug.

https://user-images.githubusercontent.com/98249521/175383474-d21f3912-e450-4240-b584-fb840fdbc585.mov

**Comment by maxagin** [comment]
> @mattseddon Once a user is aware that they can only select 7 this no longer becomes an issue. Following the UX guidelines diagram I would take this path:
![image](https://user-images.githubusercontent.com/37993418/178629687-719c6ac0-d06d-4284-8f14-12e63851e45b.png)
FYI https://code.visualstudio.com/api/ux-guidelines/notifications contains full guidelines on notifications.

**Comment by shcheklein** [comment]
> Once a user is aware that they can only select 7 

How can we make them aware? 

Can there be some very light-weight / non-intrusive reaction (like show a tooltip similar to the one we show on hover) - I don't think it can do any harm

**Comment by shcheklein** [comment]
@maxagin any specific reason it was assigned to me? :)

**Comment by maxagin** [comment]
Do not remember now @shcheklein . Probably by mistake.

**Comment by dberenbaum** [comment]
👍 I find this confusing. It always takes me a minute to remember why clicking another experiment doesn't work and feels like it's broken until I remember this -- how is a new user supposed to know?
