### ISSUE TITLE
Explicitly show the running experiment progress

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2043]
Would be helpful somehow to show the running experiments' progress. Every time I run an exp I feel like there is an endless process.

**Comment by maxagin** [comment]
> @mattseddon There is currently no way to get discrete progress information out of the CLI. The user can proxy progress by:
a.Being familiar with the experiments they are running (they should be).
b.Having the DVC terminal open which displays the CLI output (this opens by default).

I think we need to make sure to show the response on the GUI level. One of the options is to rely on the Step value. Below is an example. Please let me know WDYT?

<img width="773" alt="Screen Shot 2022-07-15 at 2 02 42 PM" src="https://user-images.githubusercontent.com/98249521/179284431-c8f5ab83-3a66-4169-ad0e-02ca35f46be5.png">

**Comment by shcheklein** [comment]
I'm not sure I understand the concept. The problem itself is clear, there is no simple / reliable solution to this. If we decide to do this by a step - then people can just follow the column with it.

**Comment by maxagin** [comment]
Sorry @shcheklein , I was not clear enough, let me explain what I meant to say by mentioning steps. 
The progress is running only in the first column.

![Untitled-1](https://user-images.githubusercontent.com/98249521/179338334-f1cf8a4f-aae8-4faf-beda-02c7d4b35486.jpg)

**Comment by shcheklein** [comment]
@maxagin there is not reliable way to get this number `8` and not reliable way to get the total number of steps.

 I think it's better for users to just keep an eye on the column itself.

**Comment by maxagin** [comment]
@shcheklein, so you are saying there is no way we can break a process into some parts somehow, so we could show a progress line? Thanks

**Comment by shcheklein** [comment]
> so you are saying there is no way we can break a process into some parts somehow, so we could show a progress line? Thanks

Yep
