### ISSUE TITLE
Configure accuracy of displayed by default cell values

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2044]
Avoid displaying cell values that are different from the real ones. Here we will try to brainstorm and find the right way if it exists.

**Comment by maxagin** [comment]
`Maxim`

Find a way to show the user that the displayed in cell value is different from the real one. Accuracy? Does it make sense?

<img width="769" alt="Screen Shot 2022-06-27 at 9 15 11 PM" src="https://user-images.githubusercontent.com/98249521/176066497-62d9e9cd-cd17-4345-a677-9639412c3da0.png">

`Ivan`

It makes sense, but not to any reasonable extent that would justify complicating what we show in the cells.

`Matt`

Why would we want to do this? I only need to see part of the value to make a decision unless two are very close and then I can investigate further with the tooltips. I would only need the full number if I was going to publish it.

**Comment by maxagin** [comment]
> @mattseddon Why would we want to do this? I only need to see part of the value to make a decision unless two are very close and then I can investigate further with the tooltips. I would only need the full number if I was going to publish it.

Scenario: I know I would like to see three numbers by default, but you may want to see four numbers. There are some users that would like to see seven numbers or just two it really depends on what the user does I think.
This means this is something that better be adjustable by the user, in the settings for example.

**Comment by shcheklein** [comment]
That can be a per column setting (format of a column) - string, scientific, precision, etc. I think this is a meaningful requirement.

**Comment by shcheklein** [comment]
Closing as low priority for now
