### ISSUE TITLE
Show a notification when exp is toggled for Plots

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2045]
When the user toggles the circle. Show a notification that the exp was added (or removed?) to the Plots view. Related to [Show a notification if the user trying to toggle exp and 7 expS are already toggled #2041](https://github.com/iterative/vscode-dvc/issues/2041) (probably the same place can be used)

The video show something that is not clear to me. What is actually going on? Is there something happening? I would expect to be notified :)

https://user-images.githubusercontent.com/98249521/179294934-ad2b77de-7592-4df3-be7e-f301461aeec6.mov

**Comment by maxagin** [comment]
> or using tooltips (when you hover on circles it explains and may be even can show a link to the plots view)

This is a good solution @shcheklein . We can show something like "toggling exp will show it in the Plots". Should we reopen this ticket :)

**Comment by shcheklein** [comment]
No, let's create different one, please, since it's a different suggestion, etc.
