### ISSUE TITLE
Add max-width for the table columns

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2046]
I have noticed that if I resize the exp table the Timestamp column (for example) will have significant spacings on the left side. Q: why are we allowed to increase the width of the column? What are the advantages and use cases? I would expect to be able to reduce, but not increase columns.

This is sort of how by default the table should look like.

<img width="836" alt="1" src="https://user-images.githubusercontent.com/98249521/172298334-cf49184e-fe0a-42b2-9a2d-9b4b647af8e1.png">

I can understand if we want to reduce for example Timestamp column width.

<img width="774" alt="2" src="https://user-images.githubusercontent.com/98249521/172298353-b4929f56-7eb0-4d3b-a298-5ea2b68c0920.png">

But I do not really understand in what situation the user may want to increase the width. 

<img width="1078" alt="3" src="https://user-images.githubusercontent.com/98249521/172298369-8de8e64c-c5d4-46d4-b129-753c8b30d8a1.png">

I think we may want to use max-width (+ paddings). WDYT?

**Comment by maxagin** [comment]
https://github.com/iterative/design/issues/16

**Comment by shcheklein** [comment]
Don't see a strong reason complicating this tbh. People might have reasons doing this, it doesn't hurt and would require us implementing.

**Comment by maxagin** [comment]
> People might have reasons doing this

What can be the reason @shcheklein ? I can not really see one

**Comment by shcheklein** [comment]
> I can not really see one

Yep, it doesn't mean it doesn't exist, right? :)

Also, in this case it's just even implementing this takes time and doesn't give any visible benefits (or arguable even closes some options). So, don't see a reason implementing this tbh.
