### ISSUE TITLE
Add timestamp to the workspace column

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2047]
The workspace does not have a timestamp. Should it not be the last time I run an experiment. Anyway, it’s a bit strange to have it empty!

> @shcheklein We can potentially show the last modified time across all files involved. Not critical at all. 

Do we want to consider implementing it? Thanks

**Comment by maxagin** [comment]
https://github.com/iterative/design/issues/16

**Comment by shcheklein** [comment]
Don't see a reason for this. Semantics of it will be different from the rest of the column and might confuse people.

**Comment by maxagin** [comment]
> Semantics of it will be different from the rest of the column and might confuse people.

I thought we are displaying the time of the latest changes. Am I wrong @shcheklein ?

**Comment by shcheklein** [comment]
` latest changes` is not that obvious to define + for experiments we show there "create time" or "compete time".

**Comment by maxagin** [comment]
> + for experiments we show there "create time" or "compete time".

I thought we show Create Time. What do you mean by Compete Time? Thanks

**Comment by shcheklein** [comment]
Sorry, I meant "complete" - time of completion.

**Comment by maxagin** [comment]
Q: After the exp is completed to run, what do we display as a timestamp for this exp, create or completion time? My guess is completion time. 
However, for the Workspace, I would expect to have the creation time (trigger - pressing run exp button). Does not this make sense @shcheklein ?
