### ISSUE TITLE
EXPs table first column duplication or not?

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2051]
Hey, here I would like to raise this flag so we can discuss what our future plan is. Thanks

Our options as I see it:

### Option no. 1

Completely remove the EXPs section from the sidebar. This makes sense based on the fact that the user better sees some other parts of the table when working with Plots (split view as the ultimate working layout. Based on this the ribbon can be also removed from the plots webview https://github.com/iterative/vscode-dvc/issues/2051#issuecomment-1186640415). 

### Option no. 2

Make sure the EXPs block in the sidebar has the same information and actions as the table first column. 
Solution custom view. 
Downside: 
a. I may need more information here when I work with Plots, so EXPs in the sidebar may be useless
b. When exp is running user may want to see other table info.
c. Duplicating info

### Related - toggling plots

In the case of both scenarios, we can make the plots toggle mechanism more obvious to the user by starting using the standard eye icons for toggling plots. Instead of clearly confusing circles (we may need to implement a different way of showing the progress if we remove the circles - I have proposed it here {Discussion: https://github.com/iterative/vscode-dvc/issues/2043}).

**Comment by shcheklein** [comment]
I think the fate of ribbon should be discussed here also. It also duplicates this information.

I would prefer to have a panel that can play its role well enough that ribbon is not needed, or modified to serve only as entry point to the proper panel.

We need more ideas. We need to better understand the story from the plots perspective better - what do people need, etc. From the people who are changing their code now (not seeing the table) - what all of them would want to see in the tree.

**Comment by shcheklein** [comment]
Closing in favor of of https://github.com/iterative/vscode-dvc/issues/2457 . We'll do there the first step to try to improve this. For now we keep both and don't consider this as a duplicate.

**Comment by maxagin** [comment]
More feedback from Dmitry:

>Experiments on the sidebar. What is the use of this? We already have a beautiful table 🙂
https://www.notion.so/iterative/Dmitry-s-Codespace-talk-feedback-1e1cfb4f0ac34ba7a1daaca20c369b08#3d14ea8fd16042cea120c30ae5c1a835

@shcheklein, just in case reopening the ticket.
