### ISSUE TITLE
Remove the caret from the branch row

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2068]
Reasoning: if we can have only one branch, we don't really need to hide its content. WDYT?

<img width="975" alt="Screen Shot 2022-07-20 at 12 08 45 AM" src="https://user-images.githubusercontent.com/98249521/179895099-2bdfbea5-2254-4bf4-9cd4-2f6295bc5a88.png">

**Comment by shcheklein** [comment]
I would postpone till the https://github.com/iterative/vscode-dvc/issues/1966

**Comment by maxagin** [comment]
@shcheklein  the ticket you have mentioned seems like will involve some serious changes. Why do not we make this small improvement and then if we will decide to add multiple branches deal with it separately?

**Comment by shcheklein** [comment]
Since it's way to small to bother now.
