### ISSUE TITLE
Experiments table: improve styles

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2070]
EXPs table improvements. Original ticket https://github.com/iterative/design/issues/28

[Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1631%3A119506)

### Rest state

1. Add a bottom line to every row and remove even rows BG style
2. Keep the header BG colour the same as the table body BG colour
3. Use the same line style for header item separators
4. Keep the caret the same colour as the other icons on the left side

### Hover state

1. Show hover styles (column, row) when the cell is on hover 
2. "lr" on hover. Also, show the hover style for the column
3. "global" on hover. Also show the hover style for the  "seed", "lr", "weight_decay" and three columns
4. The first column cell on hover. Checkbox and Star rest styles (same like without hover)

### Resize columns

1. When resizing the cell sideline grows from 1px to 2xp and changes colour
2. When resizing the hover styles are applied the same way as if the block is on hover.
3. The resize is always applied to the right side of the column
4. The resize is activated only in the header of the table when hovering on the sidelines

### Select and star EXP/s

1. When a selected row is on hover, add a shadow to show the hovered row
2. New (lighter) color for the selected row background. One of the reasons: we do not want to have it similar to the color that is used for the buttons
3. Selected rows have different bottom borders and left/right for selected cell color

### Star and checkbox behaviour

1. Star 
2. Checkbox

**Comment by maxagin** [comment]
Note: In a composition with these changes, we may want to rethink the sticky panel shadow and implement one from the design. I think the best if we could see both examples. Screen recording (video) probably will do the job. cc @julieg18

**Comment by julieg18** [comment]
> Note: In a composition with these changes, we may want to rethink the sticky panel shadow and implement one from the design. I think the best if we could see both examples. Screen recording (video) probably will do the job. cc @julieg18

When you say "stick panel shadow", are you referring to the header shadow? Currently, the experiments column shadow should match the design on Figma while the header shadow is a little different from the Figma design :)

**Comment by maxagin** [comment]
> When you say "stick panel shadow", are you referring to the header shadow?

Yes @julieg18 . Thanks

> Currently, the experiments column shadow should match the design on Figma while the header shadow is a little different from the Figma design :)

Cool. I just wanted to say that it's going to be easier to decide about the shadow after other changes are implemented. However, if you want, you can implement it right now like in Figma :) 

Q: How actually does the shadow change from theme to theme? Just for example: `box-shadow: 3px 3px rgb(51 51 51 / 56%);` is just RGB value is different? Thanks @julieg18

**Comment by shcheklein** [comment]
Just to make sure that we are on the same page - we should be using the same shadows as VS Code already has (e.g. command palette).

**Comment by maxagin** [comment]
> we should be using the same shadows as VS Code already has

@shcheklein there is a variety of options. Here are just a few examples used in VSCode (Visual Studio Code Toolkit):

1.
<img width="682" alt="Screen Shot 2022-07-21 at 11 05 21 PM" src="https://user-images.githubusercontent.com/98249521/180357520-15b0b28d-ddb6-4555-9baa-9f636edff239.png">

2.
<img width="841" alt="Screen Shot 2022-07-21 at 11 08 24 PM" src="https://user-images.githubusercontent.com/98249521/180357541-fe1b3109-d51e-444f-a174-a3be0497763c.png">

3.
<img width="1257" alt="Screen Shot 2022-07-21 at 11 24 59 PM" src="https://user-images.githubusercontent.com/98249521/180357548-6ea647b6-7992-4419-af23-e5fe86f5d803.png">

Also, I would not be so strict, as the rules change all the time. If we want to be a real conservative we will have to change the table, rows and other interactive elements.

We do not follow this:

1.
<img width="1265" alt="Screen Shot 2022-07-21 at 11 48 09 PM" src="https://user-images.githubusercontent.com/98249521/180358639-ba685f38-c30e-44c9-a4e2-2c7edec9c1ee.png">

2.
<img width="984" alt="Screen Shot 2022-07-21 at 11 51 57 PM" src="https://user-images.githubusercontent.com/98249521/180359260-6cac8425-641a-401e-bdf4-3474125e21ec.png">

Apropos rounded corners. I think we can come down a bit and try to be reasonable. I must to say my obsession with the straight corners for VSCode was just an obsession :) I am trying to fix this 

1.
<img width="779" alt="Screen Shot 2022-07-21 at 11 52 48 PM" src="https://user-images.githubusercontent.com/98249521/180359277-1137b4c8-d887-40cd-b5b3-e95723d661e4.png">

2.

<img width="1168" alt="Screen Shot 2022-07-22 at 12 00 25 AM" src="https://user-images.githubusercontent.com/98249521/180359910-6c746a4c-7288-42f1-a9de-7aa036688059.png">

3.

<img width="1089" alt="Screen Shot 2022-07-22 at 12 00 41 AM" src="https://user-images.githubusercontent.com/98249521/180359918-2b5772f7-a1d2-4e13-9763-b8b1f8fb0acb.png">

**Comment by maxagin** [comment]
Bottom line I think we should use what exists as much as possible, but if we clearly have to use custom elements we should, for example, the errors, in this case, the usage of the X is wrong IMO. So this is a good example where we better use elements that are familiar to our users because we use them in other places (!).

**Comment by julieg18** [comment]
> Cool. I just wanted to say that it's going to be easier to decide about the shadow after other changes are implemented. However, if you want, you can implement it right now like in Figma :)

I don't think I have access to editing in Figma, but here is the box-shadow used for the header `0 5px 8px -2px var(--vscode-widget-shadow);` (`X: 0`, `Y:5px`, `B: 8px`, `S: -2px`).

> Q: How actually does the shadow change from theme to theme? Just for example: box-shadow: 3px 3px rgb(51 51 51 / 56%); is just RGB value is different? Thanks @julieg18

Yes! The other values stay the same with the RGB value changing depending on the theme.

**Comment by maxagin** [comment]
The changes in this ticket will dictate what shadow is going to be used. Let's keep for now the shadows you already have and make sure to discuss them again when new styles are implemented. Thank you @julieg18 ! Can not wait to see the progress on this one :)

**Comment by shcheklein** [comment]
@maxagin thanks, it has a lot of stuff that is not related (shadows, plots), but still doesn't answer basic questions - color schema (how do we pick color for borders?)

Let's simplify, restructure and think through the implementation a bit.

Things that come to my mind right away:

- the whole column selection on hover can make everything too noisy
- multiple columns selection can make it even more noisy
- color for when row is selected (checkbox) is not specified?

**Comment by maxagin** [comment]
> but still doesn't answer basic questions - color schema (how do we pick color for borders?

We have just figured out that the #000000 was deprecated, but it does not mean that the rest of the toolkit is outdated - this would be a small catastrophe :) The new spec in Figma answers all the questions about the colours (I hope).

> the whole column selection on hover can make everything too noisy

Do we want to try my version, would you like to discuss other options, or should I remove this?

> color for when row is selected (checkbox) is not specified?

It is mentioned in the spec that there are styles for Checkbox and Star in the row hover state.

**Comment by shcheklein** [comment]
> It is mentioned in the spec that there are styles for Checkbox and Star in the row hover state.

What are those styles exactly? I don't see where it's specified

> Do we want to try my version, would you like to discuss other options, or should I remove this?

we can try it if you feel it's reasonable

> The new spec in Figma answers all the questions about the colours (I hope).

I don't see the answers there tbh. Primarily about border colors for examples (that's where we were trying to apply #0000?)

**Comment by maxagin** [comment]
> What are those styles exactly? I don't see where it's specified

Here is an example of how to use the Inspect mode. In the spec you just point out what needs to be done, then the dev will use the Inspect mode to get all the values.

https://user-images.githubusercontent.com/98249521/183468665-6878064d-a854-40dc-9459-aa96f6f24785.mov

> I don't see the answers there tbh. Primarily about border colors for examples (that's where we were trying to apply #0000?)

This is the same as above. Please let me know if you would like to have more clarification. The color for the border in spec is  `1e1e1e`.
<img width="231" alt="Screen Shot 2022-08-08 at 12 32 38 PM" src="https://user-images.githubusercontent.com/98249521/183468039-644f05ca-4b67-49f8-a7f9-742910abd843.png">

The darkest color I can find in the default theme is Base 21 or `1e1e1e` - Julie. Friday Slack message

**Comment by maxagin** [comment]
@julieg18 hi, I have updated the TODO list with the latest fixes in the ticket description. The Figma spec was redesigned. Let's meet today a bit later as we planned to go thru everything.

**Comment by shcheklein** [comment]
>  Please let me know if you would like to have more clarification. The color for the border in spec is 1e1e1e.

Is it the same in the white theme? Green theme?

> Base 21 or 1e1e1e

curious - What is Base 21?

**Comment by maxagin** [comment]
> Please let me know if you would like to have more clarification. The color for the border in spec is 1e1e1e.

>> Is it the same in the white theme? Green theme?

The `Base 21 or 1e1e1e` in our case is a variable. For the default dark theme, it is a tint of black. In other themes, it will look different, but it will be a tint of the related base color. For example:

- VSCode dark theme: Border is dark, BG is a bit lighter dark
- Green theme: Border is green, BG is a bit lighter green

**Comment by shcheklein** [comment]
@maxagin where this variable is being used in the VS Code itself? (if it's used at all). Also, is there a way from Figma spec to understand that we should be taking `Base 21` var value?

**Comment by julieg18** [comment]
> @maxagin where this variable is being used in the VS Code itself? 

Looks like `1e1e1e` is being used in 9 variables, all have something to do with background:
`--vscode-breadcrumb-background`
`--vscode-editor-background`
`--vscode-editorGutter-background`
`--vscode-editorMarkerNavigation-background`
`--vscode-tab-activeBackground`
`--vscode-tab-unfocusedActiveBackground`
`--panel-view-background`
`--vscode-editorPane-background`
`--vscode-panel-background`

**Comment by shcheklein** [comment]
so, `1e1e1e` is not a variable itself, right? (sorry, I don't know how exactly we attach VS Code vars to our CSS). Does it mean we would have to pick one from the list you provided, @julieg18 ?

**Comment by julieg18** [comment]
> so, 1e1e1e is not a variable itself, right? (sorry, I don't know how exactly we attach VS Code vars to our CSS). Does it mean we would have to pick one from the list you provided, @julieg18 ?

Correct! Though I've started testing and I don't think we'll be able to use `1e1e1e` as a border color either :( All of the variables mentioned above turn into a white-like color in common white themes which is not visible at all in a white theme... Looking into some other color options that would work better!

**Comment by maxagin** [comment]
@julieg18 is this all we can use for the default dark theme or there are some more options? Thanks!

![image](https://user-images.githubusercontent.com/98249521/183486495-a7f957eb-489f-4865-a358-493415e812d7.png)

**Comment by julieg18** [comment]
> @julieg18 is this all we can use for the default dark theme or there are some more options? Thanks!

Well, those are all the variables that are commonly used for borders. While we could technically use a different variable and color (each theme has hundreds of variables), it's preferable that we use a border variable for the table borders since a border variable will most likely work best across all different kind of themes.

**Comment by maxagin** [comment]
@julieg18 is there more variables for borders that darker than ` --vscode-tab-border: #252526;` ? Thanks

**Comment by julieg18** [comment]
> @julieg18 is there more variables for borders that darker than --vscode-tab-border: #252526; ? Thanks

I think that's the darkest border variable!

**Comment by shcheklein** [comment]
I think we can always take a var value and also adjust it (e.g. make 10% darker). It can become too complicated with the different themes though, right? (e.g. on a light scheme we might want to make 10% lighter instead). We can try to come up with a formula that works though reasonably well ...

**Comment by maxagin** [comment]
> I think we can always take a var value and also adjust it (e.g. make 10% darker). It can become too complicated with the different themes though, right? (e.g. on a light scheme we might want to make 10% lighter instead). We can try to come up with a formula that works though reasonably well ...

Yes, but it is better to use existing variables. I will find the solution. Thanks

**Comment by maxagin** [comment]
Hey folks! I have updated the [Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1631%3A119506), fixed styles and added some more related requirements. Please review and comment. Thanks!

The updated TODO list:

### Rest state

1. Add a bottom line to every row and remove even rows BG style
2. Keep the header BG colour the same as the table body BG colour
3. Use the same line style for header item separators
4. Keep the caret the same colour as the other icons on the left side

### Hover state

1. Show hover styles (column, row) when the cell is on hover 
2. "lr" on hover. Also, show the hover style for the column
3. "global" on hover. Also show the hover style for the  "seed", "lr", "weight_decay" and three columns
4. The first column cell on hover. Checkbox and Star rest styles (same like without hover)

### Resize columns

1. When resizing the cell sideline grows from 1px to 2xp and changes colour
2. When resizing the hover styles are applied the same way as if the block is on hover.
3. The resize is always applied to the right side of the column
4. The resize is activated only in the header of the table when hovering on the sidelines

### Select and star EXP/s

1. When a selected row is on hover, add a shadow to show the hovered row
2. New (lighter) color for the selected row background. One of the reasons: we do not want to have it similar to the color that is used for the buttons
3. Selected rows have different bottom borders and left/right for selected cell color

### Star and checkbox behaviour

1. Star 
2. Checkbox

**Comment by julieg18** [comment]
> 1. Show hover styles (column, row) when the cell is on hover
> 2. "lr" on hover. Also, show the hover style for the column
> 3. "global" on hover. Also show the hover style for the "seed", "lr", "weight_decay" and three columns

Didn't we decide to avoid adding column styles on hover due to it causing a lot of rerendering on the last demo meeting?

**Comment by maxagin** [comment]
>Show hover styles (column, row) when the cell is on hover
"lr" on hover. Also, show the hover style for the column
"global" on hover. Also show the hover style for the "seed", "lr", "weight_decay" and three columns

>>Didn't we decide to avoid adding column styles on hover due to it causing a lot of rerendering on the last demo meeting?

@sroy3 didn't we planed to investigate this, before making any decisions? I am wondering how Weights & Biases managing this.

**Comment by sroy3** [comment]
> > Show hover styles (column, row) when the cell is on hover
> > "lr" on hover. Also, show the hover style for the column
> > "global" on hover. Also show the hover style for the "seed", "lr", "weight_decay" and three columns
> 
> > > Didn't we decide to avoid adding column styles on hover due to it causing a lot of rerendering on the last demo meeting?
> 
> @sroy3 didn't we planed to investigate this, before making any decisions? I am wondering how Weights & Biases managing this.

We can maybe do something like [this](https://codepen.io/davesantos/pen/mdZmyq), but style would be very limited as we would just place a huge box over the selected column (no style breaks between cells). The second we start calculating or adding stuff into Redux, that would make it not worth it, unless we virtualize the table rows and columns.

**Comment by maxagin** [comment]
@sroy3 great! So we can give it a try 👍 Yes?

**Comment by maxagin** [comment]
Or something like this:

https://user-images.githubusercontent.com/98249521/184995770-1b9a5228-5ced-4a21-a458-d5a121a37cbc.mov

Here is the Figma example:

<img width="987" alt="Screen Shot 2022-08-16 at 6 25 46 PM" src="https://user-images.githubusercontent.com/98249521/184995864-6bc01737-7b13-4b4c-8db5-4152d7d2dce9.png">

**Comment by sroy3** [comment]
@julieg18 if you want we can look at this during or next pairing session (we can move the meeting ahead also if you're not sure what else to do.
