### ISSUE TITLE
Collapse exps and checkpoints

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2071]
As a part of the task ["Help navigate in a lot of experiments"](https://github.com/iterative/vscode-dvc/issues/1720) I think that being able to fold not interesting EXPs can be useful. 

[Figma](https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments-table?node-id=1230%3A36058)

**Comment by shcheklein** [comment]
Related https://github.com/iterative/vscode-dvc/issues/1269 - should be the same style?

It's not clear what's inside that fold (stars, etc....)

I think if someone is not interested they can just delete tbh.

Feels like a rushed solution, Max.

**Comment by maxagin** [comment]
> Related https://github.com/iterative/vscode-dvc/issues/1269 - should be the same style?

By default, I would show all (exps and checkpoints) giving the user freedom to decide (after the review of the info) what to keep visible and what to hide (or delete).

> Related https://github.com/iterative/vscode-dvc/issues/1269

Also, we have filters, so I am not sure that #1269 is needed. Not 100% sure

> It's not clear what's inside that fold (stars, etc....)

Everything. If I want to hide it, I want to be able to do so. No?

> I think if someone is not interested they can just delete tbh.

DVC folks mentioned that they prefer not to delete info, but just hide it.

> Feels like a rushed solution

Maybe :)
