### ISSUE TITLE
Inform the user about hidden (plots, sidebar) or applied actions with table

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2075]
Below is a high-fidelity sketch of the concept and related adjustments to the sidebar.

### The panel

<img width="881" alt="Screen Shot 2022-07-20 at 11 36 48 PM" src="https://user-images.githubusercontent.com/98249521/180124747-a7573172-d6d6-4a32-8db1-07e1d56cb607.png">

### Overview

<img width="1215" alt="Screen Shot 2022-07-20 at 11 37 00 PM" src="https://user-images.githubusercontent.com/98249521/180124771-76eeb6ae-0965-464b-9d02-9954b79ed967.png">

### Sidebar-related changes for the section names

<img width="491" alt="Screen Shot 2022-07-20 at 11 37 58 PM" src="https://user-images.githubusercontent.com/98249521/180124847-8e8cb8fc-6b37-42ab-9d88-8b3522a942fb.png">

**Comment by shcheklein** [comment]
An interesting concept. Most likely we won't be able to avoid something like this. Questions to discuss later:

- Are there alternatives to this? Throw more examples on how they do this.
- Do we want to have run buttons here in this new "ribbon"?
- In VS Code we don't use round corners.
- Are there native toggles? 
- Native icons for everything first.
- What happens when we click on each item?

**Comment by maxagin** [comment]
> Do we want to have run buttons here in this new "ribbon"?

I do not think so. However, to be sure we will need more research on the experiments workflow, which is coming soon.
But in any case, I think those two are unrelated, we can implement the concept and if needed add to it more actions later.

The hierarchy concept (for now): 
1. Action related to the table
2. Run buttons related to the EXPs (first column)

---

> In VS Code we don't use round corners.

> Are there native toggles?

The UI does not matter for now. It is the information design stage.

---

> Native icons for everything first.

It is native icons in screenshot (only sort icon is modified native one), but not final, and will need some design work after we agreed that the information design is good

---

> What happens when we click on each item?

1. Hide columns, Filter rows, Sort - open/highlight the section in the sidebar
2. Plots - open Plots view (native split views)
3. Show only changed - highlight changes in the table. I think the user will be able to continue running the exps with this option toggled. https://github.com/iterative/vscode-dvc/issues/1994#issuecomment-1191006968

**Comment by shcheklein** [comment]
Okay, for now I would suggest to postpone this. We should go from a task first. If we decide to implement #1994 and we won't have enough space we can come back to this, wdyt?

**Comment by maxagin** [comment]
Good. Also can be unlocked by "Standardizing actions panel placement for both - EXPs and Plots webviews" https://github.com/iterative/design/issues/29

**Comment by maxagin** [comment]
In addition @shcheklein the panel also can include information about RAM, just for example.

<img width="1830" alt="Screen Shot 2022-08-22 at 9 18 46 PM" src="https://user-images.githubusercontent.com/98249521/186047437-65fd88ad-392b-4613-a7b0-fcdeedd3ea62.png">

**Comment by maxagin** [comment]
@shcheklein , I am quite not original here. Too bad :( 

<img width="1218" alt="Screen Shot 2022-09-07 at 12 43 33 PM" src="https://user-images.githubusercontent.com/98249521/188934155-7f982d77-4671-446f-8e72-23e57ef07de9.png">
