### ISSUE TITLE
Quick Pick + Star Experiments

### ISSUE THREAD

**Issue by wolmir** [iterative/vscode-dvc#2106]
From https://github.com/iterative/vscode-dvc/issues/1676#issuecomment-1191020240

In order to find noteworthy experiments quicker we want to integrate the stars feature with the quick-find experiments feature.

These two items were proposed by @maxagin :

- [ ] quick pick - show quick find a starred experiment and select it in the table
- [ ] quick pick - start / unstar. Possible scenario: show quick find exp + star this exp

**Comment by mattseddon** [comment]
Wouldn't it be more valuable to add a "filter to starred" action?

**Comment by maxagin** [comment]
> Wouldn't it be more valuable to add a "filter to starred" action?

@mattseddon add it to the quick pick. Right?

Why can not we have all of them, since "filter to starred" is slightly different from the initial two?
