### ISSUE TITLE
Keep the order of the plots when toggling their visibility on and off

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#2116]
Unless it's a new plot, a plot that's been toggled back on shouldn't be added at the end, but reappear where it was.

https://user-images.githubusercontent.com/3683420/181616679-c48b5398-36ba-4808-945f-824118fb0432.mov

**Comment by mattseddon** [comment]
I honestly use this as a feature to reorder things quicker than I can whilst using drag and drop. Can see why we would want to update it though.

**Comment by shcheklein** [comment]
May be we should reset those positions that we saved when other reorderings are happening?

This way if you just toggle it on-off-on it will be stable, will appear in the same place. If you toggle off - move things around - toggle on - we reset it?

> I honestly use this as a feature to reorder things quicker than I can whilst using drag and drop. Can see why we would want to update it though.

That might mean that DnD is still a bit broken tbh. It feels a bit of abuse to rely on this to get to a specific order. My take even if that works we should not guarantee this, and probably we should think how to improve other methods to be competitive with that.

**Comment by sroy3** [comment]
> May be we should reset those positions that we saved when other reorderings are happening?
> 
> This way if you just toggle it on-off-on it will be stable, will appear in the same place. If you toggle off - move things around - toggle on - we reset it?
> 

I think that's a great idea.

> > I honestly use this as a feature to reorder things quicker than I can whilst using drag and drop. Can see why we would want to update it though.
> 
> That might mean that DnD is still a bit broken tbh. It feels a bit of abuse to rely on this to get to a specific order. My take even if that works we should not guarantee this, and probably we should think how to improve other methods to be competitive with that.

Probably because dragging across multiple screen worth (especially with multiple sections) can be really long. Could we drag and drop from the tree to compensate for that? It was a pain for the experiments table, but plots do not really have this deeply nested structure.

**Comment by mattseddon** [comment]
> Probably because dragging across multiple screen worth (especially with multiple sections) can be really long. Could we drag and drop from the tree to compensate for that? It was a pain for the experiments table, but plots do not really have this deeply nested structure.

Biggest problem with introducing d'n'd into the tree is that we'll have a shared state. Moving plots around in the webview would need to change the tree. We also might have to split single/multi-view plots in the same way we do in the webview as well.

What I'm trying to say is that we would need a really good reason to do it.

**Comment by sroy3** [comment]
The other way to make reordering easier in a long list would be something like "Reorder Mode". Have an icon button in the header that lets you reorder the plots without drag and dropping. You select a plot and then click where you want it to be. That way, you can scroll down much faster to the new position instead of holding down your mouse and let it scroll for you. Drop target would react to the cursor just as it would when dragging.

@maxagin do you have any ideas on how to make drag and drop (or reordering) easier on the user? Problem here is mostly moving an item further than the current section.

**Comment by maxagin** [comment]
> Unless it's a new plot, a plot that's been toggled back on shouldn't be added at the end, but reappear where it was.

I think it is important to have it as @sroy3 mentioned above - in the same place it was. By toggling we just hide, not reordering.

Also in the [proposal](https://www.notion.so/iterative/Redefining-the-Plots-webview-6e152dabfd544cf38720df0b196ce2ca#1c1a4458566541f18bb9cfc52d257e63
), I have published, that the two Classic plots are inside one section, and can not have a Large plot in between unless by default we have 3 sections: 
1. Section with Classic plots 
2. Large Plot 
3. Section with Classic Plot

---

> May be we should reset those positions that we saved when other reorderings are happening?
This way if you just toggle it on-off-on it will be stable, will appear in the same place. If you toggle off - move things around - toggle on - we reset it?

Completely agree. I think that some of the proposal docs can be helpful here. See the [Resize behaviour. Viewport and plots resize (width)](https://www.notion.so/iterative/Redefining-the-Plots-webview-6e152dabfd544cf38720df0b196ce2ca#0346568680b3409a940b1be159346ce2)
