### ISSUE TITLE
Upgrade react-table to the newest version

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#2130]
React table was completely rebuilt and version 8 should have lots of breaking changes.

**Comment by sroy3** [comment]
https://github.com/TanStack/table/issues/4241 is pretty much a blocker for upgrading at the moment. It's the first step in recreating the table with version 8 and there is already a problem.

**Comment by sroy3** [comment]
Still hitting the same problem and does not seem like I'm the only one. Putting this back on ice.

**Comment by shcheklein** [comment]
@sroy3 when you get back, let's please review and see if it's still blocked

**Comment by sroy3** [comment]
Seems like the previous errors are no longer shown. It isn't blocked anymore. It should take a little while to convert everything since there is no documentation for upgrading and everything looks very different, it'll be easier to rebuild everything from scratch (while using the old code as reference).

**Comment by shcheklein** [comment]
Congrats @sroy3 🎉 :) Great effort.
