### ISSUE TITLE
Plots: change order of traces somehow

### ISSUE THREAD

**Issue by bobertlo** [iterative/vscode-dvc#2135]
I noticed that it seems like the main branch trace is hardcoded to be drawn after the workspace in the vscode extension, while in the studio the traces are ordered (from "bottom" to "top") in the same order they are enabled in the UI.

![image](https://user-images.githubusercontent.com/877465/182506911-480f1520-e8e2-4d02-af40-070acae5cbbe.png)

This use case is a little silly and the UI is (by my own doing) not super responsive when displaying plots like this, but I kind of enjoy this type of feedback while waiting for larger models to train, and I think you could see how it would be nice to control the order of the traces. I'm not sure what kind of technical work this would require and it is not a big issue, just something I noticed. If anything it would maybe be nice if the workspace and/or experiments were just "on top" of the main commit.

**Comment by shcheklein** [comment]
@bobertlo thanks ! this use case make sense. We can start by making "workspace" always at the top I think. A few questions:

- Do you have a repo to try? It would interesting to see and improve the performance?
- Have you seen this being done in some other tools for plots / experiment tracking?
- I wonder if need a way to smooth this, btw. Are you interested in seeing all datapoints or just a trend?

(also, a bit separate topic - would you mind sharing your experience with us? I would love to chat with you if you have a few minutes).

**Comment by bobertlo** [comment]
@shcheklein just having workspace always on top would be great!

This is something I threw together quickly with dvclive because the training session is 2 hours for 3 epochs and I wanted more feedback.

- I can't share this repo because the Kaggle competition goes a few more weeks. I might be able to share something similar soon.
- I have seen plots that *looks like* this in the Dalle-mini logs, which would be a more realistic example https://wandb.ai/dalle-mini/dalle-mini
- Honestly, I think smoothing could be either nice or not that useful, I am not sure. I like seeing the data points in the beginning because often I develop on a (slower) notebook server, start training and watch the dvclive report.html to make sure it is starting well, then spin up a server to run the pipeline properly. Either way it looks really cool watching the graph expand in realtime in the beginning ;)

I am loving the extension and the whole platform. I would love to chat sometime!

**Comment by mattseddon** [comment]
@bobertlo thanks for raising. Seems like there was a fairly straightforward fix. I've raised a PR. The update should be in product shortly.
