### ISSUE TITLE
Zebra Stripes in tables. What changed in 11 years?

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2141]
## 2011

When users scan a row, their eyes can easily trail off and accidentally fall into an adjacent row. The user needs a visual guide to help them stay on their row as they scan. Zebra strips help guide users as they move their eyes across each row. Each alternating row is a different shade so that users won’t mistake the row they’re looking at for an adjacent row.

&nbsp;
## 2022

Examples of not applying colour to alternate rows in popular product tables.
&nbsp;
Airtable

<img width="1254" alt="Screen Shot 2022-08-03 at 5 23 49 PM" src="https://user-images.githubusercontent.com/98249521/182726238-4148315b-4c40-4c54-9b0c-26ff472150d5.png">

&nbsp;
Monday

<img width="1203" alt="Screen Shot 2022-08-03 at 5 22 54 PM" src="https://user-images.githubusercontent.com/98249521/182726211-506e9dba-4fa7-42ed-a1e4-af7371dc9127.png">

&nbsp;
Google Sheets

<img width="1482" alt="Screen Shot 2022-08-03 at 5 23 04 PM" src="https://user-images.githubusercontent.com/98249521/182726195-8200c10b-1b97-45f8-b1ad-21af64ad87eb.png">

&nbsp;
Weights & Biases

<img width="1525" alt="Screen Shot 2022-08-03 at 5 23 25 PM" src="https://user-images.githubusercontent.com/98249521/182726262-0f9e3118-d272-4c0e-8adb-e85788838375.png">

<img width="1543" alt="Screen Shot 2022-08-03 at 5 23 37 PM" src="https://user-images.githubusercontent.com/98249521/182726286-47f16afa-ee3c-4d58-9705-c4c3a8178a0c.png">

&nbsp;

## Conclusion

We probably could go deeper and find an explanation for this phenomenon, but the purpose of this publication is just to lay down a few examples of how this is used in modern times.

By the way, my proposal is very similar (conceptually) to one that Weights & Biases using currently (2022). 
I hope that I did not steal it, but got to this concept myself, thru the tests and analysis.

<img width="300" alt="Screen Shot 2022-08-03 at 5 23 37 PM" src="https://user-images.githubusercontent.com/98249521/182726345-803c3243-0e2b-4920-854d-ceb750f6dd5b.png">

Thank you!

**Comment by shcheklein** [comment]
@maxagin thanks, good examples and research.

Max, it's good to put it into Notion and share the link, or discussions. Not the best format for the ticket (it's not actionable).

Going back to the question that was raised specifically about the demo (and may be, not sure about the Figma) - rows should be visible on hover and have a proper (VS Code style) selection color when checkbox is set. It was not so much about "zebra", it was more about "removing everything". Monday btw is a good example of colors and behavior.

Anyways, thanks, it's helpful.

**Comment by maxagin** [comment]
>  It was not so much about "zebra", it was more about "removing everything"

> rows should be visible on hover

Currently, we do not have a row hover style! And my plan was not about adding the hover but handling it differently. However...

> proper (VS Code style) selection colour when checkbox is set

We already have this implemented a couple of months ago.

> Monday btw is a good example of colors and behavior.

They are doing it very-very aggressive. The other two (airtable, wandb) is more close to what we need I think, but I may be wrong.

**Comment by shcheklein** [comment]
> We already have this implemented a couple of months ago.

yes, but from Figma it looks like it becomes less native in color

> They are doing it very-very aggressive. The other two (airtable, wandb) is more close to what we need I think, but I may be wrong.

we can it do it just less aggressively, any hints, or slight change in color help. Point here- it's better to have some hints vs not having anything.

**Comment by maxagin** [comment]
> yes, but from Figma it looks like it becomes less native in color

We are not changing it. Sorry, had no time to remove it from Figma, but will do:)

>we can it do it just less aggressively, any hints, or slight change in color help. Point here- it's better to have some hints vs not having anything. 

The PR will be ready soon. Let's review the work before adding anything new. I think we will have a good result, if not, we will change styles. OK?

**Comment by maxagin** [comment]
The original plan was to have this (so we can have a better focus on the cell):

<img width="1076" alt="Screen Shot 2022-08-04 at 1 35 41 AM" src="https://user-images.githubusercontent.com/98249521/182770686-fbaa7676-8ddf-4eb7-98c5-dbd10483a623.png">

Instead of this:

<img width="1076" alt="Screen Shot 2022-08-04 at 1 35 48 AM" src="https://user-images.githubusercontent.com/98249521/182770721-826cf65b-5e3c-4f8c-a121-76b11f582b79.png">

**Comment by maxagin** [comment]
Same as we will do for Classic plots - having horizontal lines and showing the vertical on hover. To have a cross pattern.

<img width="1768" alt="Screen Shot 2022-08-04 at 1 41 09 AM" src="https://user-images.githubusercontent.com/98249521/182771404-1f86f275-ffbf-46b1-bdc7-092d4ecf11f5.png">

**Comment by maxagin** [comment]
Something like this but a bit more elegant and matching our VSCode style vector:

https://user-images.githubusercontent.com/98249521/182772401-feacce98-419c-488c-aaf3-a49942cb9bd7.mov
