### ISSUE TITLE
Timestamp column information alignment inconsistency

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2166]
To fix:

- [ ] Timestamp label alignment
- [ ] Cell information alignment

![Screen-Shot-2022-08-09-at-12 06 32-PM](https://user-images.githubusercontent.com/98249521/183706932-8e4f0f63-9c3f-4906-84ff-85353b41ac8e.jpg)

**Comment by mattseddon** [comment]
Please combine with #2031
