### ISSUE TITLE
DVC is not picked up from conda environment

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2176]
Related to #1791 

DVC installed into Conda in not picked up by the extension (while Python extension activates is well).

To reproduce. Install mini conda, install `dvc` vis `pip install dvc`. Try to run a project in any DVC repo.

https://user-images.githubusercontent.com/3659196/184040749-4740d123-4348-40dc-8bf9-6ea1a2dc5e45.mov

**Comment by mattseddon** [comment]
I think that the Python extension returns something like `conda run` for the python executable for `conda` based environments. Hopefully should be a straightforward fix.

**Comment by mattseddon** [comment]
I am unable to recreate this issue. Steps that I went through:

1. Install miniconda from https://docs.conda.io/en/latest/miniconda.html
2. install dvc into `base` environment with pip  => `/opt/miniconda3/bin/dvc`
3. Try to auto activate extension (does not work).
4. Set `base` `conda` environment as the python interpreter for the workspace (works).

### Demo

https://user-images.githubusercontent.com/37993418/184560153-fe2c7516-7baf-4bad-948c-9f640fbc7d65.mov

Did you miss step 4 or have I oversimplified the problem?

**Comment by shcheklein** [comment]
Yep, I think I didn't do 4. Conda by default changes shell rc files to initialize itself, and it was not needed to do an extra setup. But I see that it would be needed if I had to run something more complicated (debug, etc).

I think what would be helpful is to show current Python interpreter in the error message?

**Comment by mattseddon** [comment]
How about this:

https://user-images.githubusercontent.com/37993418/184561231-07cff991-64db-40e6-8ad9-dd2a78a4895d.mov

**Comment by shcheklein** [comment]
Can we put an explicit message - DVC is not found in the currently active Python env: "<path>"?
