### ISSUE TITLE
When DVC is only initialized experiments and plots break

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2177]
Get project, uncommit or just copy all files to a new dir and initialize DVC there. Run experiments via CLI. Try to see them in the extension. 

For me experiments panel was empty (and basis message with the links to docs). Plots got stuck on "Loading plots" and nothing in the terminal.

Extension version: 0.3.16

DVC version:

```
DVC version: 2.17.0 (pip)
---------------------------------
Platform: Python 3.9.12 on macOS-12.4-arm64-arm-64bit
Supports:
        azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 9.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by mattseddon** [comment]
Yep, I hit this as well. Will need to put a safe guard in. It will be something to do with the experiments data not looking complete.

**Comment by shcheklein** [comment]
I also hit it again, now with an existing commit. Looks like if something is wrong with one of the commands (and I don't see actually what is happening in logs) based on the previous commit or an existing one- it fails and get stuck in some random state. Doing a few times `git commit` helps to cleanup the history.

**Comment by mattseddon** [comment]
Looks like a bug introduced in https://github.com/iterative/vscode-dvc/pull/2029. The code expects are `deps` to be constant across revisions and could not handle missing data. Working on a fix now.

**Comment by mattseddon** [comment]
I think this is a combination of a few things. The first two things that current jump out are 

1. Before the initial git commit we get `ERROR: unexpected error - Empty git repo`.
2. The bug that I fixed yesterday with #2187.

Unfortunately, 1 is going to be a little more difficult to fix. I will start working on it now.

**Comment by mattseddon** [comment]
Found a 3rd issue where newly created `deps` have no `hash/nfiles/size`, again the code falls over under these circumstances. Working on another fix.

**Comment by mattseddon** [comment]
This should be fixed now.
