### ISSUE TITLE
Right-click opens a context menu every other time when clicking on same row

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2235]
https://user-images.githubusercontent.com/98249521/186052763-72f4ea17-88ac-46e5-ba11-441f60d7b088.mov

**Comment by mattseddon** [comment]
The bug only applies to clicking multiple times on the same row:

https://user-images.githubusercontent.com/37993418/186064500-2bceadd4-776b-416f-8c6a-d63d1c1944ab.mov
