### ISSUE TITLE
Collect user stories

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2240]
### Motivation

We would like to start interviewing users to gather the information we can use to improve the product.

Q: How and where to find people?
A: We can start asking people to help us to improve the product.
 
### Sources

- Active people from GitHub
- The invitation (help us to improve the product) can be also added to the email campaigns
- We can show a message in VSCode for example after an update
- Discord
- Something else?

**Comment by shcheklein** [comment]
I'm not sure this should be a ticket here
