### ISSUE TITLE
Issue with plots: template: smooth

### ISSUE THREAD

**Issue by JohnTheDeere** [iterative/vscode-dvc#2248]
When building a plot with the smooth template and showing the results in VS-code the "smoothness indicator" shows on top of the plot(s) and cannot be modified. If I open the plots in the browser it works fine!

<img width="1081" alt="Screenshot 2022-08-24 at 12 00 50" src="https://user-images.githubusercontent.com/19154758/186398031-994c5b02-ab3a-4d79-87c4-59fa8d955ada.png">
<img width="946" alt="Screenshot 2022-08-24 at 12 01 48" src="https://user-images.githubusercontent.com/19154758/186398049-3aa90ed9-4a28-426a-b6de-56e73abb4af4.png">

**Comment by shcheklein** [comment]
Yep, I was able to reproduce it on the recent DVC (definitely on the one from the main branch), and the demo project. There was no need to change anything, except:

```
plots:
    - training_metrics:
        template: smooth
```

btw, @maxagin that's another a bit more involved example of a plot.

**Comment by maxagin** [comment]
Thank you @shcheklein , btw I was asking in the Notion if we would like to add the smoothing option :)
