### ISSUE TITLE
Table header improvements

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2256]
- [x] Remove sort menu option from the parent params column drop down. Check for metrics. (https://github.com/iterative/vscode-dvc/pull/2583)

<img width="313" alt="Screen Shot 2022-08-24 at 1 41 17 PM" src="https://user-images.githubusercontent.com/3659196/186519509-0ea912c2-d10e-4e1b-9629-a6618654f7f0.png">

- [x] Add hide columns / section there (and in every other menu) (https://github.com/iterative/vscode-dvc/pull/2593)
- [x] ESC must work to close context menu
- [x] The context menu in the header cells should appear only on the right click. Currently also works with the left click (https://github.com/iterative/vscode-dvc/pull/2603)
- [x] Context menu "Change height" should be available everywhere. Now it doesn't show on metric file column.
- [x] Add filter by to context menus
- [ ] Add hover styles to header cells
- [x] The sort arrow in the header cell does need to have BG on hover but needs to have a cursor (pointer)
- [ ] Click on the Sort arrow - the context menu appears - if you hover on the arrow again the tooltip will be shown on top of the context menu. Do not show a tooltip when the menu is opened
- [x] ~The D&D cursor appears when the header block has hovered. Blocks like "Create" have no active space on top. Let's make sure that all the space of the block can be used to D&D~
- [x] Context menu doesn't show on an empty stub on top of a column (e.g. `train.py` dependecy).

**Comment by maxagin** [comment]
> There must be a way to copy file names / section names. Full name and partial name.

Please see: Text selection in the table's header and body cells #2260

**Comment by maxagin** [comment]
> There must be a way to copy file names / section names. Full name and partial name.

It will be handled here https://github.com/iterative/vscode-dvc/issues/2260

**Comment by maxagin** [comment]
Some of the todo items were moved to #2241

**Comment by maxagin** [comment]
- The context menu in the header cells should appear only on the right click. Currently also works with the left click

The description was updated. The new task was included.

**Comment by maxagin** [comment]
Can “Open to the Side” params, but not training_metrics. Why? If I am not mistaken this should work for any file that can be opened on the side.

**Comment by wolmir** [comment]
> Add hide columns / section there (and in every other menu)

This one is deceptively tricky, I implemented a solution, and now I'm adding/fixing some tests. Still, it will need some manual testing during review to catch side-effects.
