### ISSUE TITLE
Image plots show proper message and disable button if image is not available

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2277]
<img width="773" alt="Screen Shot 2022-08-27 at 9 00 02 PM" src="https://user-images.githubusercontent.com/3659196/187056842-6956b726-ed90-449b-8a2a-4b702f7ffd5f.png">

This image doesn't exist at in the experiment, refresh doesn't make much sense here.

Might depend on plots error handing cc @mattseddon @pared

**Comment by mattseddon** [comment]
Depends on https://github.com/iterative/dvc/issues/7692 & https://github.com/iterative/vscode-dvc/issues/1649.

**Comment by shcheklein** [comment]
@shcheklein revisit this, try to reproduce.

We still need error messages, or a signal that plot doesn't exist in the commit.

**Comment by mattseddon** [comment]
Can we treat the directory more like a dataset and each image more like a datapoint?

**Comment by skshetry** [comment]
`dvc plots diff` does not know if there's an experiment running, and I don't think it should care. Displaying errors (or not) is contextual, so I think it's up to the extension to interpret.

**Comment by dberenbaum** [comment]
@skshetry I don't think it's related to whether an experiment is running. One revision contains the file `mispredicted/6599-...` and the other does not.

@mattseddon Is there an error returned here? I don't see one when testing this. I think we just need to show a different message here than 'No plot to display: refresh` (something like N/A or no image at this revision). I see an output like this:

```json
{
  "dir/img1.png": [
    {
      "type": "image",
      "revisions": [
        "workspace"
      ],
      "url": "/Users/dave/repo/dvc_plots/workspace_dir_img1.png"
    }
  ],
  "dir/img2.png": [
    {
      "type": "image",
      "revisions": [
        "workspace"
      ],
      "url": "/Users/dave/repo/dvc_plots/workspace_dir_img2.png"
    },
    {
      "type": "image",
      "revisions": [
        "main"
      ],
      "url": "/Users/dave/repo/dvc_plots/img1.png"
    }
  ]
}
```

@shcheklein What do you want to show in this scenario?

Some thoughts on what I'd expect:
* Grouping by directory paths. Seeing all cats, dogs, muffins, etc. together would help organize it.
* Showing the number of images per revision per directory. At least then I'd easily know whether there are more misclassified dogs or cats in each revision.

**Comment by mattseddon** [comment]
> @mattseddon Is there an error returned here? I don't see one when testing this. I think we just need to show a different message here than 'No plot to display: refresh` (something like N/A or no image at this revision). I see an output like this:

I completely fluffed this. Didn't check the new output. Everything seems to be behaving as it needs to. I will open a PR to close this issue.

> Some thoughts on what I'd expect:
> 
> * Grouping by directory paths. Seeing all cats, dogs, muffins, etc. together would help organize it.

I can sort the images before sending them to the webview.

> * Showing the number of images per revision per directory. At least then I'd easily know whether there are more misclassified dogs or cats in each revision.

We should have this already in the plots tree.

**Comment by dberenbaum** [comment]
Thanks @mattseddon! Not sure if we want a separate issue for the rest of the discussion for how to organize these images, which is probably not p1.

> I can sort the images before sending them to the webview initially but the user can reorder them which makes future updates more difficult.

I meant not just sorting, but making them collapsible by directory.

> > * Showing the number of images per revision per directory. At least then I'd easily know whether there are more misclassified dogs or cats in each revision.
> 
> ~We should have this already in the plots tree.~ Where should this be shown?

🤔 I was thinking if we have collapsible directories, then we could put the number of images per revision next to those. For example, imagine the paths below are directories (`cats`, `dogs`, etc.) instead of files (I'm not tied to this UI, it's just the first idea I had):

<img width="784" alt="Screenshot 2023-03-21 at 12 46 32 PM" src="https://user-images.githubusercontent.com/2308172/226684244-fa433cf8-a7c0-44c9-b1e0-267f408fb52c.png">

**Comment by shcheklein** [comment]
Sorry folks, just catching up a bit. It feels like grouping, etc is a separate improvement that can be done (or not) independently from this ticket? 

For this specific ticket - even an empty box (and we don't even need the border) is fine I think.
