### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2283]
This is very minor, however still worth to be mentioned. 

Experiment or Experiments? Singular or plural?

<img width="1313" alt="Screen Shot 2022-08-29 at 12 07 49 PM" src="https://user-images.githubusercontent.com/98249521/187246550-811162d4-b1fa-4572-b7b0-1c2aa510dad8.png">

**Comment by shcheklein** [comment]
I think it's fine in this case. Tab is called Experiments, it's fine to have column Experiment.

Let's not microoptimize this please :) If we decide that it's super important let's squeeze into one of the bigger updates.
