### ISSUE TITLE
Table: First row under the workspace

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2322]
## Motivation

Better, Better & Better

## Suggestions

1. There is no point to have a checkbox, star and chevron
2. If the first is correct: we can shift everything a little bit to the left
3. Make it sticky

(Max) To consider: Experiment Table UI: visually separate baseline from experiments for readability when sorting? #1820

**Comment by mattseddon** [comment]
Same answer: https://github.com/iterative/vscode-dvc/issues/2068#issuecomment-1189820450

**Comment by maxagin** [comment]
I think it is different now as we talking about a set of elements that are not useful. WDYT? @mattseddon , I would love to have this worked on. 

> Since it's way too small to bother now. - @shcheklein #2068

It is much bigger now. Does not it make sense?

**Comment by shcheklein** [comment]
It's the same still. We should go into direction of allowing multiple commits - see this ticket for example: https://github.com/iterative/dvc/issues/8236

**Comment by maxagin** [comment]
Multiple commits under the same header. Is this possible?

>After git commit, I have made some adjustments to the source files and now my table header has different names. --> I want to see both commits in the table, but the headers are different.
Can this happen? If yes, we probably won't be able to show multiple commits in the same table. 
#8236

If this is not possible, then maybe we could reopen this ticket :)

**Comment by shcheklein** [comment]
Yes, Studio does multiple commits under the same header.

**Comment by maxagin** [comment]
> Yes, Studio does multiple commits under the same header.

Can you change source files in the Studio?

>After git commit, I have made some adjustments to the source files and now my table header has different names. --> I want to see both commits in the table, but the headers are different.
Can this happen? If yes, we probably won't be able to show multiple commits in the same table.

**Comment by maxagin** [comment]
All the questions have been resolved here. Thank you !
