### ISSUE TITLE
Make the EXPs sidebar section a reflection of the first table column

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2324]
This is a high fruit, however, we could include it as a part of the new quarter planning. WDYT?

This is a major UX improvement and I think will be beneficiary for the product.

Basic row anatomy (https://github.com/iterative/design/issues/38) is a first/second attempt to approach this enhancement.

<img width="400" alt="Screen Shot 2022-09-02 at 6 12 21 PM" src="https://user-images.githubusercontent.com/98249521/188241997-5306131e-c235-4224-b2e4-bf9c06be1eb4.png">

Please share your thoughts. Thank you!

**Comment by shcheklein** [comment]
I hope checkboxes are not needed? VS Code tree supports select w/o checkboxes.

Eye icon - is not implemented yet, let's not complicate the ticket.

Progress - not implemented yet (and it's not easy, related to the eye icon also), again, let's not complicate the ticket.

So, only stars. And that's more than enough to start. It might happen we have troubles implementing even starts.

**Comment by shcheklein** [comment]
Let's rephrase and open it again please.
