### ISSUE TITLE
Story: Support running experiments on individual stages

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#234]
This has been discussed, though it may not be a high priority right now.

I would think this would be as simple as a new command that invokes a quickpick menu populated with DVC stages to run `dvc exp` against. The `dvc.yaml` target is handled by the default invocation, so I'm not sure there's any valid targets other than stages- at least common ones.

Implementing this would also require us reading `dvc.yaml` and keeping a list of its stages, but reading `dvc.yaml` was probably pretty inevitable for a DVC extension anyway so I don't count it against this feature.

**Comment by shcheklein** [comment]
Closing as not a priority for now.
