### ISSUE TITLE
Long text in labels cause overflow

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#2340]
<img width="803" alt="Captura de Pantalla 2022-09-06 a las 16 34 12" src="https://user-images.githubusercontent.com/12677733/188663751-6fd1640f-1d41-4504-9499-574907e358f4.png">

Depending on the selected zoom, which alters the grid layout, this can get better or worse.

**Comment by shcheklein** [comment]
@daavoo why does it have `\.` btw? is it expected?

**Comment by daavoo** [comment]
> @daavoo why does it have \. btw? is it expected?

It's expected but I have just noticed that it's unnecessary. I added a patch for escaping special characters that were breaking vega-lite rendering. However, it appears that only the `field` needs to be escaped and the `labels`/`title` can be unescaped.

**Comment by shcheklein** [comment]
Yep, I was asking specifically about `\` (escaping) - should it be visible in the titles or not, was it part of the name?

**Comment by mattseddon** [comment]
@sroy3 spotted another issue with some text overflowing on zoom:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/189015110-95f470d9-02de-4d05-ba1e-23000a6dea7a.png">

**Comment by daavoo** [comment]
> should it be visible in the titles or not, was it part of the name?

`dvc-render` needs to take care of not including the escaping in the title so it doesn't show on the UI

**Comment by mattseddon** [comment]
> > should it be visible in the titles or not, was it part of the name?
> 
> `dvc-render` needs to take care of not including the escaping in the title so it doesn't show on the UI

@daavoo do you have a ticket for that?

**Comment by daavoo** [comment]
> > > should it be visible in the titles or not, was it part of the name?
> > 
> > 
> > `dvc-render` needs to take care of not including the escaping in the title so it doesn't show on the UI
> 
> @daavoo do you have a ticket for that?

https://github.com/iterative/dvc-render/pull/82

Will be most likely available on next dvc release
