### ISSUE TITLE
Move to native context menu

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2350]
@shcheklein commented

>Context menus in VS Code look different (have borders that give them better contrast)

Let's compare the current menu style with the latest UI changes and see if there is a better solution.

**Comment by mattseddon** [comment]
This is coming soon: https://github.com/microsoft/vscode/issues/54285

We should invest some time into seeing if it will be possible for us to use it or not.

**Comment by maxagin** [comment]
Sounds great @mattseddon , so what would be the next step?

**Comment by mattseddon** [comment]
Allocate engineering resources to look at the API and decide whether or not we can migrate from our custom context menus.

**Comment by mattseddon** [comment]
This is what needs to be looked at: https://github.com/microsoft/vscode/issues/54285#issuecomment-1242267823

**Comment by shcheklein** [comment]
Way to much scope, not clear if it's needed atm.
