### ISSUE TITLE
Grouping plots by DVC pipeline stage (or folder-based)

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2370]
Initially published at Notion by @mnrozhkov 

---

https://www.notion.so/iterative/Mikhail-Rozhkov-VSCode-DVC-Ext-106392d8bb9d4b69b02755419b8fe823#0841f52778fb4ac8a8caa975e99812fe

We discussed this in respect to `plots.html` file long time ago, it’s probably suits VSCode extension for now.  
For justification: 

- it may be useful when we have many plots at different stages: `train`/ `evaluate`
- also, we may organize plots when we have multiple `train`/ `evaluate` stages for different models (algorithms) or have `foreach ... do`
- both stage-based and folder-based seem as feasible solution

![image](https://user-images.githubusercontent.com/98249521/189464281-3eec3077-c15d-4141-9897-679dbc7a5962.png)

**Comment by maxagin** [comment]
For simplicity, we probably could have more sections, that reflect the number of stages in the project. WDYT?

**Comment by sroy3** [comment]
I don't have a particular opinion on this. But anything we can hide (tab, section closing, filtering off stages...) is always good for performance.

**Comment by mattseddon** [comment]
Not a priority right now.
