### ISSUE TITLE
Plots: no clear connection between "circles" and plots view

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2373]
It is evident that users are confused about what the circle beside the EXPs is for. Also if the user opens Plots, but no EXPs are selected, the Plots view is empty and the user does not know how to add EXPs from the Table view. This issue is partially resolved with the ability to add experiments from the Command Palette. However, the education regarding how both views should accompany each other is missing.

References:

- https://www.notion.so/iterative/Dan-Martinec-feedback-for-VS-code-689d8945e5f54bdc8f6e064a06fccb28#c0b8c0d19ee943aea59af390cd169c71
- https://www.notion.so/iterative/Mikhail-Rozhkov-VSCode-DVC-Ext-106392d8bb9d4b69b02755419b8fe823#de2532d6020b43668de533f66eab07f1

I would like to propose a solution for both cases when the views are opened for the first time.

&nbsp;

## 👉 Show a short explanation tooltip beside the EXP's circle when the user first time opens the EXPs table view.

To display the EXP in the Plots view click the circle beside the EXP name.
Button text example: Got it

<img width="500" alt="Screen Shot 2022-09-12 at 4 53 23 PM" src="https://user-images.githubusercontent.com/98249521/189756979-6ef8b82e-9592-455e-88d7-eb114c92381e.png">

Do you have in mind any other functionality that we would like to show upfront?

&nbsp;

## 👉 If no EXPs are selected and the user opens Plots, show information (use illustration for better understanding) that explains how the user can add EXPs to the Plots view from the EXPs view along with the button that adds EXPs from the Command Palette.

To display EXP in the Plots view activate the circle beside the EXP title in the Table view.
You can add max 7 EXPs to the Plots.

Alternatively, click the button below to add EXPs from the Command Palette.

<img width="500" alt="Screen Shot 2022-09-10 at 3 19 28 PM" src="https://user-images.githubusercontent.com/98249521/189498847-0aa85598-43af-4046-b692-8663f7b0b7d7.png">

[Figma](https://www.figma.com/file/cOlfG6r9dFa8OvWkRRQFuK/Point-to-critical-functionality-upfront?node-id=1404%3A5882)

**Comment by mattseddon** [comment]
Related to #2041, #1958, #1383

**Comment by shcheklein** [comment]
We've introduced the ribbon to mitigate this. Users now should see it and be able to pick experiments there. (so, circles in the table become secondary or ternary after the side panel and the ribbon).

I also would try to avoid "first time show tooltips / overlays, etc" - it means that interface is bad in the first place. (thus e.g. ribbon was a better solution).

Saying that we can def keep implementing additional hints in VS Code style (when screen is empty for example), implement tooltips like we discussed, etc, etc.

**Comment by sroy3** [comment]
> We've introduced the ribbon to mitigate this. Users now should see it and be able to pick experiments there. (so, circles in the table become secondary or ternary after the side panel and the ribbon).

Probably a controversial idea, but since we have the ribbon, how about we completely drop the toggling from experiments? The bullet would be a simple indicator (the color is the same from plots to experiments). That way, there is no danger of someone could toggle/untoggle an experiment and then wondering what happened (especially if the plots webview is closed).

**Comment by maxagin** [comment]
> We've introduced the ribbon to mitigate this. Users now should see it and be able to pick experiments there. (so, circles in the table become secondary or ternary after the side panel and the ribbon).

Here we are covering a situation when no EXPs are selected.

<img width="1966" alt="Screen Shot 2022-09-12 at 4 36 34 PM" src="https://user-images.githubusercontent.com/98249521/189754007-63cf0163-b720-4cad-8ae5-09b25ce3291c.png">

---

> so, circles in the table become secondary or ternary after the side panel and the ribbon

The first view to open is the Table. The selection of EXP/s for Plots needs to be unable and clear enough from the Table view I think. This is why I have combined both views here.

---

> I also would try to avoid "first time show tooltips / overlays, etc" - it means that interface is bad in the first place.

This is something that you can find even on very well-crafted applications.

**Comment by maxagin** [comment]
Changing this:

![image](https://user-images.githubusercontent.com/98249521/189756715-f2e95115-3831-448a-b09d-25334011b4a5.png)

To this:
Added: "You can add max 7 EXPs to the Plots."

<img width="1072" alt="Screen Shot 2022-09-12 at 4 53 23 PM" src="https://user-images.githubusercontent.com/98249521/189756754-828b6232-5a66-432b-9da4-b501dd12cb1a.png">

**Comment by mattseddon** [comment]
#2382 will help with this problem.

**Comment by shcheklein** [comment]
> Probably a controversial idea, but since we have the ribbon, how about we completely drop the toggling from experiments?

I think we can do that. Since it's implemented it's fine probably to keep even though there is not enough value at the moment. Tooltips _after_ you toggle and when you hover on it can help a bit also.

> Here we are covering a situation when no EXPs are selected.

It means we can and should solve that first (show ribbon, show better empty screen etc) before we go and introduce band aids with overlays and guided tutorials.

**Comment by maxagin** [comment]
>#2382 will help with this problem.

How exactly @mattseddon , since the problem is that the behaviour of the visual elements is not clear?

**Comment by mattseddon** [comment]
Feedback was also received on April 29th before the "Experiments Selected for Plotting" indicator was added to the table.

**Comment by maxagin** [comment]
> It means we can and should solve that first (show ribbon, show better empty screen etc)

This is exactly what I am proposing - "show better empty screen"!

> show ribbon

Showing elements outside of context especially for the first time, won't bring any clarifications to the user. It is why I would like to believe that the proposal is good.

**Comment by maxagin** [comment]
> Feedback was also received on April 29th before the "Experiments Selected for Plotting" indicator was added to the table.

This is right @mattseddon , but I want to mention that the top section has really poor noticeability and for the new user that clicks on the circle/EXP name this won't help at all.

**Comment by maxagin** [comment]
> 👎 (@mattseddon )

Personally, when clicking on the circle I am looking at the same spot and do not see anything that changes on top. Tests now.

**Comment by shcheklein** [comment]
> This is exactly what I am proposing - "show better empty screen"!

right.

your suggestion looks too heavy. VS Code has empty screen and guides on them but usually they look softer.

+ if we introduce ribbon on the empty screen it might also mitigate this w/o making too heavy tooltips, guides, etc.

**Comment by mattseddon** [comment]
> How exactly @mattseddon , since the problem is that the behaviour of the visual elements is not clear?

See the demo in #2388

**Comment by sroy3** [comment]
> See the demo in #2388

It feels like this was the missing link between both webviews.

**Comment by shcheklein** [comment]
More feedback from Dmitry:


```
1. **Select plots.** How to get the plots that I need? I was miss-leaded by the checkboxes and end up using this trick - select the exps I need by checkboxes, right click on “Plot and Show”, then click to the “Plots” icon to finally see them. Just “Plots” does not work, it does not work for a single exp 🤪 Super confusing experience. Later, Ivan showed me that the checkboxes are not related to plots and I suppose to click to the small round icons instead 🤦‍♂️
    1. Another source of confusion - checkbox menu works differently for a single selected item and multipole items. I still do not understand why.
```

**Comment by maxagin** [comment]
>Another source of confusion - checkbox menu works differently for a single selected item and multipole items. I still do not understand why.

>>The context menu in case of a single EXP should have both Plots options - Plot/Plot and show. This also needs to work if the user just right-clicks on the EXP (without selecting it). Also, the right-click does not need to remove the row hover style.

**Comment by maxagin** [comment]
First of all, we can update the DVC: Get Started / Plots Dashboard, I think this will be already helpful.
We can explicitly mention and show the screenshot of how to select the EXP for Plots.

### The draft

Select ~~one or more~~ `up to 7` experiments `in the table view` to visualize in the Plots Dashboard. 
`screenshot`
Use DVC: Show Plots from the command palette to open it. `or table's row context menu`

<img width="1590" alt="Screen Shot 2022-10-06 at 9 59 17 PM" src="https://user-images.githubusercontent.com/98249521/194450541-6e9291c7-ed21-4991-b0ca-227b902b5c79.png">


Screenshot example:

<img width="1147" alt="Screen Shot 2022-10-06 at 9 57 35 PM" src="https://user-images.githubusercontent.com/98249521/194450399-0895976c-081d-4ca9-83f1-751b9198de19.png">

**Comment by dberenbaum** [comment]
> Probably a controversial idea, but since we have the ribbon, how about we completely drop the toggling from experiments?

This has my vote. What about going even further here and dropping the experiments section from the sidebar altogether?

More generally, between the sidebar and experiments table view, it’s not obvious what each of the radio buttons, checkboxes, and stars do and why there are so many for each experiment. Why are the radio buttons in the experiments section of the sidebar if they control the plots?

**Comment by shcheklein** [comment]
Thanks @dberenbaum .

Let's keep it for now. First of all I doubt it would change the adoption / experience much (we have a way bigger onboarding issue), but more importantly it was and it is important to have a glue between the table, experiments, and plots. It's important to see the color <> experiment. And I think we need to see this connection in multiple places. All this give additional information, helps navigate, gives flexibility in how users setup their workspace (split, or only side panel, etc). Do we want to allow toggle? Again, I would keep even as an extra way to get people into plots + if they use split it makes it easier.

I would say, the ribbon was made initially as a band aid. And if anything, I would at some point reconsider its existence in the first place.

-------

To make this ticket more actionable:

I think the only possible item that is left here - show some additional information "tips" under the table in the VS Code style about the plots panel and circles to toggle things.
