### ISSUE TITLE
Ability to compare plots of selected experiments

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#2382]
I'd like to see a "Compare Plots" option when right-clicking selected experiments.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/17241029/189721639-ab68ea09-97e9-44c6-87ef-373f5980c079.png">

**Comment by shcheklein** [comment]
@alex000kim would you be fine to reset the selection to these selected plots (that some experiments you were comparing before become inactive)? or would you want to _add_ them to the selection?

**Comment by alex000kim** [comment]
Personally, I'd expect the former i.e. seeing only the plots I selected, not adding them to the existing Plots view.

On a related note: when adding experiments to Plots, I'd like to see at least some info about the experiments I am adding because experiment names don't tell me anything useful.
Maybe we can display metrics next to the experiment names, and display more info (e.g. params) on hover?  

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/17241029/189727169-a2fd56fb-18db-4af0-998d-1435f18b575f.png">

**Comment by maxagin** [comment]
> On a related note: when adding experiments to Plots, I'd like to see at least some info about the experiments I am adding because experiment names don't tell me anything useful.

Absolutely agree with @alex000kim . I have raised the same concern couple of hours before on Notion:

>// I am afraid that currently there is not enough meaning in the EXP name. So showing just the EXP name in the plots view is not meaningful at all I think. The better would be to have a native split view (reference: Information Hierarchy), so user could have the context. 
https://www.notion.so/Redefining-the-Plots-webview-6e152dabfd544cf38720df0b196ce2ca?d=d9652e22ba984dca82c00923c737921d#4587239fe09c44bda1cbbf021556e95b

**Comment by shcheklein** [comment]
It should be a separate feature request I guess. It's a good idea to show tooltips + show more info - first mertic columns + first param columns + first dep / source. It's tough to show a lot of info though.

**Comment by shcheklein** [comment]
@alex000kim could you please create a separate issue for the quick pick panel?

**Comment by alex000kim** [comment]
Yup, done: https://github.com/iterative/vscode-dvc/issues/2395
