### ISSUE TITLE
Improve "Modify And" experiment commands

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#2394]
DVC has recently released a Hydra integration which enables grid search functionality. There are a couple of tasks here:

- [ ] Add the ability to submit a range/list for selected params depending on whether they are numeric/string (if possible).
- [x] ~Run "apply experiment" at the start of all of the "modify and" commands (so that the data is correct before starting the experiment).~ (#4094)
- [ ] From user feedback: If there are lot of parameters it’s very hard to find the right one in the quick pick. Either we allow editing right in the workspace / or when we create a new experiment right in the table. Or at least when we do right click on a cell open that param in the quick pick.

**Comment by mattseddon** [comment]
Depends on https://github.com/iterative/dvc/issues/8481

**Comment by shcheklein** [comment]
> Depends on https://github.com/iterative/dvc/issues/8481

Question to discuss / consider: do we even want to change semantics of the operation to apply the whole exp. Or should it be a separate command / option?

**Comment by mattseddon** [comment]
After #4094 experiments can now only be created using the workspace as a base.

**Comment by shcheklein** [comment]
> Add the ability to submit a range/list for selected params depending on whether they are numeric/string (if possible).

I think it's done? (if we talk about the queue). Also, related https://github.com/iterative/vscode-dvc/issues/4465
