### ISSUE TITLE
Exp info when selecting exps to display in Plots

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#2395]
When adding experiments to Plots, I'd like to see at least some info about the experiments I am adding because experiment names don't tell me anything useful.
An idea:
Maybe we can display metrics next to the experiment names, and display more info (e.g. params) on hover?

![](https://user-images.githubusercontent.com/17241029/189727169-a2fd56fb-18db-4af0-998d-1435f18b575f.png)

**Comment by mattseddon** [comment]
How about adding the first 3 metrics that are found in the table (by leftmost position) to the description in the quick pick:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/194985557-e733fcc1-ef32-447e-b998-acab9339231c.png">

**Comment by shcheklein** [comment]
Params and data information are equally important. We should pick first three columns in the table (any columns). Ideally we should be able to pin those columns we are interested in.

I think we should also include date (and ideally how long did it take to run, but that's a separate ticket). We can show those under the exp name for example in quick pick?

**Comment by mattseddon** [comment]
Suggested format for a new tooltip in the experiments tree: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/195001146-339a615b-c8d1-4864-958a-ed1c9ad2bd59.png">
