### ISSUE TITLE
Table DnD: scroll properly when table is too large

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2422]
When table is wide, it's very hard to move column to behind the viewport (area on which it scrolls is very small). Can it be made a bit more sensitive + scroll when mouse is beyond the borders?

On the left area is not correct (it's behind the checkboxes, not the shadow).

https://user-images.githubusercontent.com/3659196/190881320-db249599-43a8-4e45-8679-c799b490d8cf.mov

**Comment by mattseddon** [comment]
This would be a very involved fixed. Dropping for now. Can revisit if becomes a massive issue for users.
