### ISSUE TITLE
Images table DnD: header stuck in the "dnd" state

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2423]
https://user-images.githubusercontent.com/3659196/190881374-b774fe63-5ec7-4c37-9b6f-6a9e6dc38dd3.mov

I would also expect for ESC to cancel the operation and return everything into its initial state

**Comment by sroy3** [comment]
If this is what I think, it might not be super easy to fix. I looked into it for half a day and gave up because it seemed like a bug inside the drag and drop API itself and would only happen 1/3 of the time. I'll look into it soon, and even if it is what I think I might have a solution.
