### ISSUE TITLE
CLI version not accepted by extension

### ISSUE THREAD

**Issue by petergoodin** [iterative/vscode-dvc#2427]
Hi, 
I'm having issues with the extension. I have DVC version 2.26.2 installed but get an error saying I need between version 2.24.0 and 3?
![image](https://user-images.githubusercontent.com/7199436/190941632-661d94f1-3cfa-4fff-bd90-83fa55360e64.png)
![image](https://user-images.githubusercontent.com/7199436/190941618-21d48fef-0f4e-455f-aa21-a30d0d4df7e5.png)

**Comment by mattseddon** [comment]
Do you have multiple versions of the CLI installed on your machine? Potentially the extension is trying to run against a different version of the CLI than what you're expecting. Are you using a virtual environment for the workspace's project?

**Comment by petergoodin** [comment]
No multiple versions unfortunately. I removed the version that was installed and trying to run any dvc commands returns an unknown command error.

No virtual environment either

**Comment by mattseddon** [comment]
Thanks for coming back to me @petergoodin 🙏🏻
