### ISSUE TITLE
Table left scroll stuck and instead gets to the previous page

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2456]
Mind the arrow on the left screen edge. It appears when I'm trying to use pad gesture (scroll to the left). It means that during the day it kick you out of the space because you tried to scroll.

https://user-images.githubusercontent.com/3659196/192111505-c33ab365-f9a9-462b-902f-f00d8ff67a79.mov

**Comment by julieg18** [comment]
Weird, I can't seem to reproduce this so far. @shcheklein, what are your browser and OS versions? 


https://user-images.githubusercontent.com/43496356/196824470-dc5f01f2-35b4-4444-80ab-1917b2c41178.mov

**Comment by shcheklein** [comment]
I can't reproduce this either anymore. Let's close this and see if it appears again.
