### ISSUE TITLE
Extension shows experiments that don't exist

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#2476]
I am seeing two experiments that I am unable to remove and they also don't show up when I run `dvc exp show`
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/17241029/192366742-755ff92f-b28f-4154-a16c-25548ed889fa.png">

**Comment by sroy3** [comment]
These are the previous 2 commits. We are looking at how to make this more obvious (with more info) #2458

**Comment by alex000kim** [comment]
Oh ok, so this is due to a recent update. Some UI cleanup would definitely be welcome, otherwise, it looks confusing.

**Comment by mattseddon** [comment]
We'll cover this in https://github.com/iterative/vscode-dvc/issues/2458. Thanks @alex000kim.
