### ISSUE TITLE
Extension crashing vscode extension host

### ISSUE THREAD

**Issue by bobertlo** [iterative/vscode-dvc#2501]
I can't really troubleshoot this right now, but I am getting an error "Extension host terminated unexpectedly 3 times within the last 5 minutes." that stops when I disable the extension. This first happened on a linux ssh remote host when I logged in this morning at work, and is happening also on my MacBook which was working fine at midnight last night on the same project.

Another user reported the issue in discord and said it is effecting some projects and not others. In the project I am using I only have data tracked for ETL and no pipelines enabled at all, just some the `.dvc` tracked datasets and nothing else going on.

I am at work and can't troubleshoot this, but it sounds like it should be reproducible.

**Comment by shcheklein** [comment]
@bobertlo we are looking in this.

**Comment by mattseddon** [comment]
@bobertlo. 

Firstly, sorry for the terrible experience. Secondly, I've just queued up a release with a possible fix. If you have time can you do a few things for me:

1. When `0.4.10` is released please check to see if it works.
2. If it doesn't (and if possible) can you please share a project with me that the extension crashes?
3. Can you please confirm that `0.4.8` also crashes (just want to double check)?

🙏🏻 and sorry again.

**Comment by mattseddon** [comment]
`0.4.10` is available now.

**Comment by bobertlo** [comment]
It's resolved. Thanks!

**Comment by mattseddon** [comment]
@wolmir need a postmortem for this one.
