### ISSUE TITLE
Plots: modify plots from plots view

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2524]
I'd like to be able to change how the plots look without leaving the plots view. For now, I have to go to `dvc.yaml`, adjust properties, and then come back to the plots view.

**Comment by shcheklein** [comment]
You would still want changes to propagate back the `dvc.yaml`, right?

**Comment by dberenbaum** [comment]
Yes, although it's not that hard a requirement if there are other ideas for how to do it.

If it is saved to `dvc.yaml`, it could be like a lightweight alternative to a "Studio plots wizard" since I can configure in VS Code and then propagate to Studio.

**Comment by shcheklein** [comment]
Closing this since we can't get to it soon, also needs more clarification / steps.
