### ISSUE TITLE
Test and release LSP

### ISSUE THREAD

**Issue by wolmir** [iterative/vscode-dvc#2529]
- [ ] Regarding the possibility of the crashes coming from parsing the files, this can be done in the usual integration test in the server. An idea to do it is to send the same files a lot of times

- [ ] General smoke tests must be added to make sure the server is loading properly with the extension.

**Comment by shcheklein** [comment]
@wolmir let's please rename it to "Test and release LSP". Specifics (like stress testing, e2e, etc, etc) - can be checkboxes inside

**Comment by mattseddon** [comment]
Related to #1192
