### ISSUE TITLE
Cleanup `Plot` & `Plot and Show` in the context menu

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2539]
## Improvements

- Remove `Plot`
- Rename `Plot and Show` to `Plot`
- The context menu in case of a single EXP should have a `Plot` option.
- This also needs to work if the user just right-clicks on the EXP (without selecting it). 
- The right-click on EXP does not need to remove the row hover style (if possible).
-  If more than 7 EXPs are selected grey out `Plot` (always grey out the inactive options. For education the menu can show what is available).
- Make behavior additive
- Context menu on ESC don't remove checkboxes

## Consider

- Add unplot option (was #2448)

**Comment by mattseddon** [comment]
> Should we remove Plot/Plot and show from the context menu if more than 7 EXPs are selected? Need a good solution here.

The current behaviour is to only plot the multi-selected rows.

**Comment by shcheklein** [comment]
> Should we remove Plot/Plot and show from the context menu if more than 7 EXPs are selected? 

No, I think we need to grey out inactive options always. Menu can show what is available (education).

> Right-clicking on EXP shows the context menu with options: Plot / Plot and Show. I suggest removing the Plot option, as not essential.

Make sense. We can even rename it to `Plot` and make it default behavior to active the Plot webview.

**Comment by maxagin** [comment]
I have updated the description.

**Comment by math-alpha** [comment]
Hey @maxagin I would love to tackle this one

**Comment by shcheklein** [comment]
@math-alpha please give a try, let us know if you need a hand.

**Comment by math-alpha** [comment]
I am unsure what the "unplot" menu is supposed to do.
Is that unselecting from the experiments?

**Comment by shcheklein** [comment]
@math-alpha it should be doing the opposite from what the Plot option is doing (enables plots for an experiment(s) on the Plots view).

**Comment by math-alpha** [comment]
Update

- [x] Remove Plot
- [x] Rename Plots and Show to Plot
- [x] The context menu in case of a single EXP should have a Plot option.
- [x] This also needs to work if the user just right-clicks on the EXP (without selecting it).
- [ ] The right-click on EXP does not need to remove the row hover style (if possible).
- [ ] If more than 7 EXPs are selected grey out Plot (always grey out the inactive options. For education the menu can show what is available).
- [x] Add unplot option (was https://github.com/iterative/vscode-dvc/issues/2448)
