### ISSUE TITLE
Hard to distinguish stared and un-stared exps

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2540]
>Also, it is hard to distinguish stared and un-stared exps (un-stared icons look too solid 🙂). Some design change is needed. - Dmitry https://www.notion.so/iterative/Dmitry-s-Codespace-talk-feedback-1e1cfb4f0ac34ba7a1daaca20c369b08#a4d2b5008b8b4fdf863b0d5d794d437b

>This happened after one of the latest updates. Here is how it is supposed to look. Basically what is important, is clearly see the difference between stared and un-stared EXPs. 
For some reason, I am unable to share a screenshot, so here is a link with an example https://www.figma.com/file/kTErWSdnP5PVeU6UKdx0gR/Experiments?node-id=1807%3A124133 - Maxim

Related - https://github.com/iterative/vscode-dvc/issues/2241#issuecomment-1244479064

**Comment by mattseddon** [comment]
Feedback has been cherry-picked. This is the more general feedback on stars:

> Stars - it’s a smart idea limit “labels” (in wandb and mlflow) by stars only (a single label). But I have not find it useful at all 😟 What is the expected flow? Should I use it in filters? Filters are complicated experience (in zoom-in mode, not Studio mode) - see above.

**Comment by maxagin** [comment]
Here is the answer I have posted on the Notion:

> Stars - it’s a smart idea limit “labels” (in wandb and mlflow) by stars only (a single label). But I have not find it useful at all 😟 What is the expected flow?...

>> The main purpose is to be able to mark interesting experiments so you can find them faster.

**Comment by shcheklein** [comment]
I think it's a fair feedback and includes multiple things from simple (this ticket - bad style decision, hard to distinguish) to more complicated UX questions (toggle / filter only starred experiments). 

My take - both things can and should be addressed. I would probably make star stand out (yellow) and grey out inactive stars. See GMail experience.

**Comment by maxagin** [comment]
My two cents. The screenshot below is what we had before. The yellow - maybe (not sure we need more accent than on the screenshot)

<img width="316" alt="Screen Shot 2022-10-08 at 10 01 34 PM" src="https://user-images.githubusercontent.com/98249521/194734146-85a7f147-586f-4c55-a341-fd8e78991772.png">

**Comment by shcheklein** [comment]
Closed by #2604
