### ISSUE TITLE
It is very hard to find the table and the plots

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2541]
>It is very hard to find the table and the plots (even when table already exist like getting- started): —> DVC ext icon —> Experiments —> Small Icon —> the table. - Dmitry https://www.notion.so/iterative/Dmitry-s-Codespace-talk-feedback-1e1cfb4f0ac34ba7a1daaca20c369b08#aab4eb87bfb340099eac15be8bad007f

> Hmm... This is a very good point (usually I use the command palette, not small buttons). Maybe we can have a new sidebar section with a list of all views with the option to open them:
1. EXPs table
2. Plots
3. DVC settings
4. More?
WDYT?

**Comment by shcheklein** [comment]
I think it goes against the usual VS Code flow I think also it's quite extensively described in the Get Started.

Feels minor to me.

If we hear more feedback like this, we can introduce the Get Started panel.

Happy to hear other opinions on this.

**Comment by mattseddon** [comment]
Feels like overkill. I would not try to solve the onboarding problem this way. The view will be useful for 30 seconds of the entire product life cycle.

**Comment by shcheklein** [comment]
Thinking more on this. I feel like our extension is a bit unusual in a sense that it has two webviews that are not visible by default at all. Can / should we show them after extension is installed? Are there other options to let users know about their existence?

**Comment by shcheklein** [comment]
Closing in favor of #2683
