### ISSUE TITLE
User interviews

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2554]
We can include the sentence below in the: email notifications and VSCode Get Started (other places you can think of?) to start interviewing more users.

>Would you like to help us improve your loved DVC VSCode extension by taking an active part and sharing your thoughts in the interview sessions with the team? Click here to schedule...

**Comment by shcheklein** [comment]
Yes, it's a valid idea, we'll do this when we need more research. For now, let's not keep it in the issue tracker (it's more of a product management question).
