### ISSUE TITLE
DVC tab endlessly loading

### ISSUE THREAD

**Issue by gcoter** [iterative/vscode-dvc#2569]
Hello 🙂 I would like to use the DVC's VS Code extension (I have version v0.5.0 installed currently) on one of my projects. I upgraded DVC (because my current version was not compatible), here are the details about my environment (note that I am using WSL):

```
dvc version
DVC version: 2.30.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.17.1
        dvc_objects = 0.7.0
        dvc_render = 0.0.12
        dvc_task = 0.1.3
        dvclive = 0.12.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2022.6.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
```

With this setup, I am not able to use the extension because the view in the tab keeps on loading endlessly:

![image](https://user-images.githubusercontent.com/17814966/195285800-571274b7-2fc4-49e4-8d42-c9b43912c4b0.png)

Could you help me?

**Comment by gcoter** [comment]
Actually, I might have a beginning of explanation. When I run `dvc exp show` in a terminal, it asks me for the SSH password of the remote. I guess this is why the experiment view gets stuck like this?

Still, I don't understand why `dvc exp show` needs to connect to the remote. Is it not supposed to show me the experiments which are present locally?

**Comment by mattseddon** [comment]
Can you please share the output from `exp show --json`.

**Comment by gcoter** [comment]
Hi @mattseddon, thanks for your answer and your help 🙂 Unfortunately I cannot share the output of `dvc exp show --json` because it contains information related to a project that I work on for my company 😅 Is there something specific that you would like to look for?

I didn't know that a `train` stage was expected, why is it the case?

**Comment by gcoter** [comment]
Hi @mattseddon, I saw that a new version was released with your fix (`v0.5.1`), I got the update in my VS Code so I was able to test it. Unfortunately, I still have the same issue 😕

**Comment by julieg18** [comment]
> Hi @mattseddon, I saw that a new version was released with your fix (v0.5.1), I got the update in my VS Code so I was able to test it. Unfortunately, I still have the same issue 😕

Hello @gcoter, sorry to hear that the fix isn't helping. Have you tried to restart VSCode?

**Comment by mattseddon** [comment]
@gcoter 

> I didn't know that a `train` stage was expected, why is it the case?

You are correct, it is not required. This was a bad assumption made by me a while ago.

Can you please share any/all errors from the console from version `0.5.1`. 

Thank you and sorry for not getting it right the first time.

**Comment by gcoter** [comment]
> Hello @gcoter, sorry to hear that the fix isn't helping. Have you tried to restart VSCode?

@julieg18 Yes I have restarted VS Code but it does not help.

> Can you please share any/all errors from the console from version `0.5.1`.

@mattseddon Yes, I still see some errors in the console, please find them below:
```
mainThreadExtensionService.ts:79 [[object Object]]Cannot convert undefined or null to object
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 TypeError: Cannot convert undefined or null to object
	at Function.entries (<anonymous>)
	at p (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547289)
	at p (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547300)
	at p (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547300)
	at p (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547300)
	at c (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547396)
	at t.collectMetricAndParamChanges (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:547569)
	at t.collectChanges (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:545758)
	at l.transformAndSetChanges (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:552657)
	at l.transformAndSet (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:551676)
	at k.<anonymous> (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:569103)
	at Generator.next (<anonymous>)
	at /home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:566768
	at new Promise (<anonymous>)
	at r (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:566513)
	at k.setState (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:569030)
	at /home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:568465
	at p.invoke (/home/gcoter/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/gcoter/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at b.fire (/home/gcoter/.vscode-server/bin/d045a5eda657f4d7b676dedbfa7aab8207f8a075/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at c.notifyChanged (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:541985)
	at c.<anonymous> (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:565848)
	at Generator.next (<anonymous>)
	at o (/home/gcoter/.vscode-server/extensions/iterative.dvc-0.5.1/dist/extension.js:1:564622)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thanks to both of you for your help 🙂

**Comment by gcoter** [comment]
I have just realized something that might be worth mentioning. In this project, I don't track metrics anymore with DVC (in the current commit). I did track metrics before (and I can see it if I run `dvc exp show -A`) but currently there is no `metrics` entry in my dvc.yaml. Maybe that could explain the error?

I could try the extension with another project which is not in this case

**Comment by gcoter** [comment]
> I have just realized something that might be worth mentioning. In this project, I don't track metrics anymore with DVC (in the current commit). I did track metrics before (and I can see it if I run `dvc exp show -A`) but currently there is no `metrics` entry in my `dvc.yaml`. Maybe that could explain the error?
> 
> I could try the extension with another project which is not in this case

I tried with another project which has metrics, but I have the same issue

**Comment by gcoter** [comment]
Hi @mattseddon 🙂 

> Same or different error?

If I remember well, it was the same error.

> Can you share with me the project structure from exp show? I.e delete all of the data from underneath each key.

Here is the structure:
```json
{
    "workspace": {
        "baseline": {
            "data": {
                "timestamp": null,
                "params": {
                    "params.yaml": {
                        "data": {}
                    }
                },
                "deps": {
                    "my_project/utils.py": {},
                    "my_project/data/loading/loader.py": {},
                    "my_project/data/loading/mongo_parallel.py": {},
                    "my_project/stages/load_datasets.py": {},
                    "data/feather": {},
                    "my_project/stages/catboost_training_and_inference.py": {},
                    "my_project/models/neural_networks.py": {},
                    "my_project/stages/cnn_training_and_inference.py": {},
                    "data/feather/training_dataset.feather": {},
                    "my_project/stages/create_pandas_profiling_report.py": {},
                    "results/score_tables/cnn/testing_score_table.feather": {},
                    "my_project/stages/create_excel_report.py": {}
                },
                "outs": {
                    "data/feather": {},
                    "results/models/catboost.pkl.gz": {},
                    "results/plots/catboost": {},
                    "results/score_tables/catboost": {},
                    "results/models/cnn.tf": {},
                    "results/score_tables/cnn": {},
                    "results/pandas_profiling/training_dataset_report.html": {},
                    "results/metrics": {}
                },
                "status": "Success",
                "executor": null,
                "metrics": {}
            }
        }
    },
    ...
}
```

**Comment by mattseddon** [comment]
@gcoter we've released `0.5.3`. Can you please try it and let me know what errors you're now experiencing? Thanks

**Comment by mattseddon** [comment]
I managed to recreate the problem with an open-source project. The bug was caused by `null` having an `object` type in wacky Javascript land. Details in the above PR. 

`0.5.3` likely won't work but `0.5.4` released soon, should.

**Comment by gcoter** [comment]
Hi @mattseddon, indeed it works now! Thank you 🙂

**Comment by mattseddon** [comment]
Thanks for letting me know @gcoter. We would love it if you can give us some feedback once you've used the extension for a while 🙏🏻. Feel free to reach out on Discord if you need anything.
