### ISSUE TITLE
Change demo project to a submodule

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#2584]
We would like the demo repo to be more independent from the main repo. We would like to be able to commit inside of it without it affecting the rest of the project.

A good solution for this would be to convert it to a submodule.

We could also add multiple submodules if needed.

We previously moved away from submodules (#82) so we need to make sure the side effects are minimal.

**Comment by SoyGema** [comment]
This is actually a great idea.
To complement some thoughts bout this:

Maybe stating a main project for getting started - for me it was unclear if this was the [getting started ](https://github.com/iterative/example-get-started) or the [mnist demo](https://github.com/iterative/vscode-dvc/tree/main/demo) for the extension-   Right now the readme mnist demo is under [contributing](https://github.com/iterative/vscode-dvc/blob/main/CONTRIBUTING.md) and not under the [project demo](https://github.com/iterative/vscode-dvc/tree/main/demo) github link , found this is confusing. 

Let me know if I can help you somehow with this 👍
