### ISSUE TITLE
Replace `dvc exp gc` command with `dvc gc`

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#2607]
Background: https://iterativeai.slack.com/archives/C01APS0FHDM/p1665658700964949

Summary:

- Extension doesn't provide a way of cleaning up the DVC cache. Removing experiments (either manually or with `exp gc`) does **not** clear the cache. Users might not be aware of the implications of not cleaning the cache (disk space usage, etc) and be confused by thinking that `removing` an experiment also cleans up space.

The current UI for `exp gc` is good, IMO, and could be reused as-is for `dvc gc`.
We should find other ways to hint about cache cleaning (button in `Source Tree` view?)

- `dvc exp gc` will most likely be removed from DVC (https://github.com/iterative/dvc/issues/7991)
-  Users already have many different ways in the UI to remove multiple experiments, `exp gc` don't add much value.

**Comment by shcheklein** [comment]
@daavoo hey, is this deprecation happening for the 3.0? I guess on our end it's not a huge change, but it makes sense to do it when `dvc gc` takes care of those orphaned experiments, wdyt?

**Comment by dberenbaum** [comment]
@mattseddon If we want to do this, I think it would make sense to do `dvc gc --all-experiments`, but that will also gc data from old commits, so we would need to be careful to warn users of that.
