### ISSUE TITLE
Story: Onboarding for VSCode extension

### ISSUE THREAD

**Issue by SoyGema** [iterative/vscode-dvc#2608]
Hello there.
As a set of adoption actions for the extension , I would like to open a discussion about a couple of main actions that might help with product adoption, or going from the getting started to a customized implementation : 

1.  **Documentation page at DVC.org**  with follow up fundamental information . During exploration, found that [remotes](https://dvc.org/doc/command-reference/remote),  [experiments](https://dvc.org/doc/user-guide/experiment-management/running-experiments) , [pipelines](https://dvc.org/doc/start/data-management/data-pipelines) and [DVCLive metrics](https://dvc.org/doc/dvclive/ml-frameworks) understanding is key from going to getting started to building customized projects. It might be good to have a doc page that goes through this or at least **link and / mentions** the main building blocks, otherwise if you don´t know DVC it can be daunting . This page could be linked to the extension getting started demo, possible template, and close Walkthrough . 
Guiding user to the important building blocks for this might be key for adoption. 

3. **Create template for projects**. Unclear to be if this shall be a new repository, or to which extend shall be leveraged and linked to the [separation of the demo](https://github.com/iterative/vscode-dvc/issues/2584) from the repository , or as a different submodule . This template can be linked in a possible documentation page or added at the end of the Walkthrough. 

Feel free to move this  to [discussions](https://github.com/iterative/vscode-dvc/discussions) if  necessary 

Happy to help in these tasks. 
Have a nice day and keep up the great work! 🥇

**Comment by SoyGema** [comment]
As a follow up wih this, Im creating separate comments for 1 - documentation - and 2 - template - 
**Regarding 1 Documentation** 
As a proposal , the documentation page should at least include **3 main blocks** :

- **Setup the table and plots** . Page should link to useful DVCLive and pipelines documentation pages. There should be a clear statement that the Table will appear in the UI _once_ you run an experiment via `dvc exp run` and/or `dvc repro` . It might be also a good idea to point out to the main difference in between those. 

- **Run experiments** The user should have conceptual link in between the `params.yaml` file and the possible parameter iterations that can be produce from the table.

- **Sharing** Some roadblocks about remotes regarding sharing as a branch should be addressed from the DVC perspective , in both a verbose way from the CLI and useful links to docs. This might include links to remotes configuration from main cloud providers.

**Comment by SoyGema** [comment]
Regarding 2 **Create template for projects.**
- The **Demo project** and the template can at least be included in the same repository if there is a final decision of separate from VSCode repository . If it is as such , the template and the Demo can be in different branches but the recommendation is to include both so onboarding demo and adoption gets near from one another . 

The **Project template** should  be EXTREMELY verbose , and include :

- A **README** file with the overall explanation of the folder structure and how to place your code and reproduce it in order to get to the table , and some starting CLI commands for data versioning, pipelines, plots and experiments useful for getting things working. 

- **DVC project initialized** with config to  remote configuration ( thinking here AWS ) 
-  a **SRC folder** structure with verbose named scripts . This follows good practices coming from the [course ](https://learn.iterative.ai/). ( Discussion is open here from to which extend presenting a one-stage pipeline might be better or not for adoption ) 
- a `dvc.yaml` and `params.yaml` files . Including a description of what does inside the script with link to docs, a verbose example of how to setup the parameters and stages. The project might include one function and stage in order to make it easier to implement.
- a clear statement that running the experiment will setup the table and plots , even a video or small gif in the readme.md file. Include the command.

Please, help me prioritizing these bullet points . Thanks !

**Comment by dberenbaum** [comment]
With upcoming changes to DVC/DVCLive, it will be possible to generate populate the experiments and plots views by adding DVCLive methods to your Python code and running it. For example:

```
from dvclive import Live

with Live() as live: # Saves experiment on exit (no pipeline required)

	model = MyModelClass()
	hyperparameters = model.get_hyperparameters()
	for param_name, value in hyperparameters:
	    live.log_param(param_name, value) # Log parameters.
			
	for epoch in range(NUM_EPOCHS):
	    model.fit(train_data)
	    metrics = evaluate_model(model)
	
	    for metric_name, value in metrics.items():
	        live.log(metric_name, value) # Log metrics.
	
			live.next_step()
	
	predictions = model.predict(test_data)
	live.log_sklearn_plot("roc", test_data["y"], predictions) # Log plots.
```

Running that block of code will be enough to generate an experiment with parameters, metrics, and plots that show up in VS Code.

The only prerequisite for this is to run `dvc init` first. We are not prioritizing getting rid of this step in DVC, but it could make sense for VS Code to try to do this automatically or by a prompt to users.

Hopefully, these steps can simplify the structure of the template and make it less necessary to start from a template.

**Comment by dberenbaum** [comment]
> The only prerequisite for this is to run `dvc init` first. We are not prioritizing getting rid of this step in DVC, but it could make sense for VS Code to try to do this automatically or by a prompt to users.

I see this is already available for non-DVC repos, so looks like we are in good shape here. 

Another point raised by @shcheklein and @daavoo was that the DVCLive library will not be available when DVC is installed as a binary. I don't think installing the binary is too common for existing users, but it can be an issue if we plan to onboard users from VS Code by including the binary with the extension. It probably makes sense to suggest using pip or another Python package manager to install DVC or at least DVCLive (which comes with the DVC Python package) so they don't hit issues during onboarding.

**Comment by shcheklein** [comment]
Closing in favor of #2793
