### ISSUE TITLE
Plots show renders empty boxes when data doesn't exist

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2666]
In this case the `dvclive` group exists only in older commits. In the workspace (that is the only experiment that is selected) they do not exist.

<img width="1512" alt="Screen Shot 2022-10-22 at 7 10 48 PM" src="https://user-images.githubusercontent.com/3659196/197369787-c81f7d7e-3697-43b9-9457-975ff2c56145.png">

- We should not be showing in this case `dvclive` at all in the side panel.
- We not be showing empty boxes in such case.

**Comment by maxagin** [comment]
> We should not be showing in this case dvclive at all in the side panel.

Don't we want to show it anyway- for educational reasons? Even if it's empty, including some message?

**Comment by mattseddon** [comment]
Was closed by #2811
