### ISSUE TITLE
Multi-root-workspaces do not work

### ISSUE THREAD

**Issue by alkatar21** [iterative/vscode-dvc#2673]
dvc: 2.30.1
dvc VS-Code extension: v0.5.7

I am using a multi-root workspace and dvc works as expected on the console.

But the tracked data is not shown in the Explorer under DVC Tracked. There are also no changes shown in the Source Control tab and the extension tab is loading all the time after visiting the tab once:
![grafik](https://user-images.githubusercontent.com/61387986/197807032-ebd9a8f6-d475-462c-90d5-6859808532d2.png)

The output window shows the following:
```bash
[version: 0.5.7, ...] > /bin/python3 -m dvc root - INITIALIZED
[version: 0.5.7, ...] > /bin/python3 -m dvc --version - INITIALIZED
[version: 0.5.7, ...] > /bin/python3 -m dvc --version - COMPLETED (312ms)
[version: 0.5.7, ...] > /bin/python3 -m dvc root - FAILED with code 253 (443ms)
[31mERROR[39m: you are not inside of a DVC repository (checked up to mount point '/workspaces/<project>')
```

If I remove all other folders and only keep the one wich uses DVC and reloed the window everything works as expected.
If I add the folders again now, the extension still works as expected and simply adds the Project folder as additional hierarchy to the DVC Tracked window.
If I know reload the window everything is again like in the beginning and the extension does not work.

**Comment by sroy3** [comment]
@alkatar21 just to make sure I can reproduce things on my side correctly, how is you workspace built at the moment? Are the folders in the workspace all under the same folder and one of these folders is a DVC project? Or is it a custom workspace (saved as a file) with multiple folders added to it (folders that aren't all necessarily under the same folder)? Thanks.

**Comment by alkatar21** [comment]
@sroy3 I'm not sure I understand it correctly. It's a workspace that VSCode calls [Multi-root-workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces). So yes, there is an extra VS-Code file that organizes which folders are present. Does that help?

And here is the official source for extension authors with another link with a link to more docs about the API: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extensions

**Comment by sroy3** [comment]
@alkatar21 thanks it does help. Sorry I didn't know VS Code had an official name for this.

**Comment by alkatar21** [comment]
Another observation I just made:
I am working in a Docker dev container where DVC is installed. When I rebuild the container with `Rebuild Container` DVC works. But as soon as I restart VS-Code either with `Developer: Reload Window` or by restarting the application it does not work as described in the issue.

So it really seems to be just a bug during startup, where the extension does not startup fully.

**Comment by alkatar21** [comment]
This does now work as expected with `v0.5.14`. DVC TRACKED and Source Controll work as expected. Thanks 👍

Since the PR mentions that other things I don't use also don't work, presumably the ticket should still remain open?

**Comment by sroy3** [comment]
> This does now work as expected with `v0.5.14`. DVC TRACKED and Source Controll work as expected. Thanks 👍
> 
> Since the PR mentions that other things I don't use also don't work, presumably the ticket should still remain open?

Thanks for the quick feedback.

Yes, let's leave this open until I make sure that every other feature still works

**Comment by sroy3** [comment]
I think I found all of the places that could be affected by the multi root, but if you ever stumble on anything else, don't hesitate to raise an issue. Thank you for raising this issue, it's great to have users share different ways to work.
