### ISSUE TITLE
Add controls to the sidebar to help users understand what views we are offering 

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2683]
The problem we are trying to solve here is that the new user is not aware of two main views we have: EXPs and Plots. That means we need explicitly to point the user to this information. Along with the Get Started improvements we hopefully can have a better result.

---

Make the section first on top for better accessibility.

It should contain:

- Open experiments and plots in the split view
- Open experiments 
- Open plots

### V1.
Users can open and close the views from the sidebar (not sure it is possible. To check!)

<img width="619" alt="Screen Shot 2022-10-26 at 4 57 48 PM" src="https://user-images.githubusercontent.com/98249521/198136409-fa68c041-cdf8-4100-9aa5-a13a75a8f3da.png">

### V2.
Users can open and close the views from the sidebar.

<img width="599" alt="Screen Shot 2022-10-26 at 4 57 56 PM" src="https://user-images.githubusercontent.com/98249521/198136477-e8465ecc-4e84-4fb9-8e4d-94371fa69ec0.png">

### V3.
User can only open views (links).

<img width="602" alt="Screen Shot 2022-10-26 at 4 58 03 PM" src="https://user-images.githubusercontent.com/98249521/198136547-bc653d9a-7832-4b2f-9d0a-c95ec38718dc.png">

### V4.
User can only open views (buttons).

<img width="609" alt="Screen Shot 2022-10-26 at 4 58 09 PM" src="https://user-images.githubusercontent.com/98249521/198136598-05985af9-28e0-4ae7-8881-f18502a68ad2.png">

**Comment by shcheklein** [comment]
I'm fine with V4. @julieg18 we can take this as part of the story we discussed during the planning.

For now only when DVC and the extension are initialized. Next step (separate story) make those buttons visible (as a demo) when project is not initialized.

**Comment by shcheklein** [comment]
> but I still get confused with all the other sidebar sections, especially when most of them are duplicated within the experiments/plots views themselves.

I think this is common to have side panels with a summary of things + they give more flexibility in terms of your setup. Let's keep them, may be simplify (remove large button like add filter / sort), so they don't stand out that much.

**Comment by dberenbaum** [comment]
> I think this is common to have side panels with a summary of things + they give more flexibility in terms of your setup. Let's keep them, may be simplify (remove large button like add filter / sort), so they don't stand out that much.

It seems like the primary concern right now is onboarding over flexibility, so I'm focusing on what has made it hard for me to adopt the extension. It may be my specific preferences, or it may be that these are problems that are stopping others from adopting it.

The current sidebar includes:
1. Columns
2. Experiments
3. Sort by
4. Filter by
5. Plots
6. Support

"Experiments" and "plots" make sense and correspond to major features in DVC (similar to the Docker sidebar). "Columns," "sort by," and "filter by" to me are overkill, especially when they are subsections of "experiments" and can be done directly in the table. I also struggle to understand why "columns" is at the top and "plots" is so far down.
