### ISSUE TITLE
When the view opened first-time show overlay with helpful info

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2684]
Here I am trying to reflect on the user's feedback regarding the fact that the toggling of the exp for the plots is not clear.

---

The suggestion is to use overlays the first time the view has been opened.

In relation to https://github.com/iterative/vscode-dvc/issues/2373

### EXPs

<img width="1653" alt="Screen Shot 2022-10-26 at 5 48 11 PM" src="https://user-images.githubusercontent.com/98249521/198144944-ce3f6c9a-7fc2-4168-a3dd-ab927a6326b2.png">

### Plots

<img width="1654" alt="Screen Shot 2022-10-26 at 5 48 37 PM" src="https://user-images.githubusercontent.com/98249521/198144965-5204a0fe-85d1-42b6-9866-98210fffc2ee.png">

**Comment by shcheklein** [comment]
We are going in circle a bit. We discussed overlay already. Before we do them, let's try some other ideas. (e.g. space under the table, empty screent's etc)
