### ISSUE TITLE
Export "raw data" from plots

### ISSUE THREAD

**Issue by JohnTheDeere** [iterative/vscode-dvc#2713]
Small feature request. It should be possible to export the raw data from a dvc vscode plot as raw data to .csv or something similar. This would be useful if:

1. Somebody wants to share raw results with somebody who does not use dvc
2. You want to publish the plot in an article or similar and want to tinker with the "visual look" of the plot

![image](https://user-images.githubusercontent.com/19154758/199165586-777b837d-f794-4106-8368-f82166ca9a22.png)

**Comment by shcheklein** [comment]
Vega embed (lib that we use to render) doesn't have built-in functionality for custom actions, but there is a workaround to hook into DOM https://github.com/vega/vega-embed/issues/156

@sroy3 how bad that workaround it, from the top of your head (don't spend too much time on researching this pls).

**Comment by sroy3** [comment]
> Vega embed (lib that we use to render) doesn't have built-in functionality for custom actions, but there is a workaround to hook into DOM [vega/vega-embed#156](https://github.com/vega/vega-embed/issues/156)
> 
> @sroy3 how bad that workaround it, from the top of your head (don't spend too much time on researching this pls).

Since we add the dropdown only on zoomed in plots (not every plot and re-rendering is very low) it should be quite easy to add the workaround.

**Comment by julieg18** [comment]
Here's a demo of what I've got so far! Added an "Export as Raw Data" option that lets you save the data used to create the plot in a `json` format: 

https://github.com/iterative/vscode-dvc/assets/43496356/04373de8-3916-4075-a80e-50e141991fed

What do we think? cc @shcheklein

**Comment by JohnTheDeere** [comment]
Awesome
