### ISSUE TITLE
Capabilities based feature detection of dvc?

### ISSUE THREAD

**Issue by skshetry** [iterative/vscode-dvc#2728]
At the moment, the DVC extension sets a hard restriction on dvc's version and fails to work if it is not met.
It'd be nice if it could still partially work for the feature supported based on the capabilities of DVC (`dvc doctor --capabilities` perhaps?).

**Comment by skshetry** [comment]
In DVC, we use versioning based on the latest tag present, which locally we are always behind. The extension fails to initialize, forcing me to `git fetch --tags && pip install -e ".[dev]"`. Minor annoyance, but this would solve that as well. :)

**Comment by shcheklein** [comment]
> In DVC, we use versioning based on the latest tag present, which locally we are always behind.

@skshetry could you please give a specific example? which version it was failing to initialize with?

(overall, we've discussed this already and it feel a bit too complicated for now to maintain and implement this, too early)

**Comment by skshetry** [comment]
I only had tags upto `2.24.0` locally, and the extension requires `2.30`. Since I did not pull, `dvc --version` took the latest tag locally, increments it by 1 and considered `2.24.1` to be the installed version.

I have to `git fetch --tags` to pull in the tags and do `pip install -e ".[dev]` or  `pip install setuptools_scm && python -m setuptools_scm` to resync the version info. It's a minor annoyance and unrelated to vscode-dvc, and does not affect users.

**Comment by mattseddon** [comment]
This would require a lot of effort to implement and maintain. No capacity to do this any time soon.
