### ISSUE TITLE
Improve plots colors/legend

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2732]
In my experience, if there are too many lines to fit in a legend, there are too many lines on the chart. We can go with the approach you are working on and brainstorm other ways to help comprehend, like:

* Tooltips (mentioned above). They are limited in vega lite, but we could at least show some info when hovering over a particular line.
* Putting labels next to the lines in the plot and highlighting on hover: https://vega.github.io/vega-lite/examples/interactive_line_hover.html
* Highlighting on click:  https://vega.github.io/vega/examples/interactive-legend/

_Originally posted by @dberenbaum in https://github.com/iterative/vscode-dvc/issues/1757#issuecomment-1258619057_

**Comment by dberenbaum** [comment]
The filenames in the legend also take up a lot of space. There are some improvements that can be made in DVC (see https://github.com/iterative/dvc/issues/7830). In VS Code, maybe there could be some additional ways to address this. For example, toggle whether to show the filenames.

**Comment by shcheklein** [comment]
Closing this since we've changed a lot of things about this recently. @dberenbaum let me know if we need followups here.
