### ISSUE TITLE
Parameter types of input params.yaml not preserved when using "Modify & Queue"

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#2734]
I am using PyTorch Lightning, whose trainer has a `limit_num_batches` argument. Based on the type of the argument, this parameter is either interpreted as absolute number of batches or a ratio of batches from the dataset. For example, `1.0` means 100% of the dataset, i.e., all batches, whereas `1` (literal `int`) means one single batch.

In my `param.yaml` file, I have a `limit_num_batches` entry which I load with `dacite` and type annotation `Union[int, float]`. The default value in the configuration file is `limit_num_batches: 1.0`.

Using the DVC VS Code extension to modify *other* parameters, it also passes this unchanged parameter on the command line, however, using `-S limit_num_batches=1`. This changes the type from floating point to integral!

**Comment by aschuh-hf** [comment]
To work around this, I could rewrite my code to:

- Always expect `limit_num_batches` to be an `int` and using value -1 to indicate 100% (i.e., no longer be able to specify a ratio other than 0% (`limit_num_batches: 0`) and 100% (`limit_num_batches: -1`).
- Change type of `limit_num_batches` to `Union[int, str]` and use `limit_num_batches: X%`, e.g., `limit_num_batches: 20%` to specify a ratio instead of values in [0, 1].
- Given that `0` means both 0% and 0 num batches, and values in open interval (0, 1) must be serialized as string on the command-line with decimal point, it seems I would only need to introduce `-1` as meaning 100% instead of `1.0`.

**Comment by shcheklein** [comment]
Looks like this is the reason https://stackoverflow.com/questions/53005702/parse-float-with-decimals-to-json-in-javascript-also-for-1-as-1-00 ... Similar to the #2733 . Python + JS + JSON create a complete mess in handling basic things properly. We'll need to figure out something better.

Also, technically we can't probably even blame JS in this case? 1.0 is the same as 1. I would say that Lighting takes quite a strange way to determine things in this case also.

**Comment by shcheklein** [comment]
Unfortunately, I can't see how it can be solved at the moment :(. It looks like in JS (the lang extension is written in, since VS Code is also written in JS) it would be quite hard to preserve `.0`, JS has a single numeric type - `number` and rounds `.0`.

**Comment by aschuh-hf** [comment]
Yes, thanks for looking into it. Thought I'll leave it open if it's possible to preserve the decimal formatting of the input `params.yaml` file. The workarounds for dealing with how Lightning handles this described above work out fine actually. If chosen the third option, to simply use `-1` as parameter value if I want to say `limit_num_batches=1.0` and otherwise there is no ambiguity because `limit_num_batches=0` and `limit_num_batches>1` are clear, and `0 < limit_num_batches < 1` will always be formatted as `0.xxx`. I think we can close the issue?

**Comment by mattseddon** [comment]
Thanks for the issue @aschuh-hf. As @shcheklein stated we won't be able to solve this due to some limitations of the language we are working with. Will close this now.

Please come back to us with any further feedback/issues that you have 🙏🏻.
