### ISSUE TITLE
Watchers are not set on metrics, params files if there are errors

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2735]
Based on the #2733 . After I "fix" NaN to 1.0 experiments don't appear, it takes an edit to `dvc.yaml` to trigger this. 

To reproduce. Open the project with already broken table (`NaN`), and try to fix it.

https://user-images.githubusercontent.com/3659196/200188255-1b04b840-74ce-4182-9bca-ce9987f40f71.mov

Extension version: v0.5.10

DVC version:

```
DVC version: 2.30.0 (pip)
---------------------------------
Platform: Python 3.9.12 on macOS-12.6-arm64-arm-64bit
Subprojects:
        dvc_data = 0.17.1
        dvc_objects = 0.7.0
        dvc_render = 0.0.12
        dvc_task = 0.1.3
        dvclive = 0.10.0
        scmrepo = 0.1.1
Supports:
        azure (adlfs = 2022.9.1, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.14.0),
        gs (gcsfs = 2022.8.2),
        hdfs (fsspec = 2022.5.0, pyarrow = 9.0.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.7.0),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7),
        webhdfs (fsspec = 2022.5.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Comment by mattseddon** [comment]
We get the list of "extra files" to watch from the `exp show` output. We don't know which metrics files to watch until we have parsed the JSON.

From the demo: `in.json` is not covered under our default list of files. Therefore the watcher will not be triggered by any change until the JSON can be parsed and the file is added to the list. 

FWIW we watch `['dvc.lock', 'dvc.yaml', 'params.yaml', '*.dvc']` by default. This list is updated once we parse the JSON output.

I think we can close this.
