### ISSUE TITLE
this message may be unnecessary?

### ISSUE THREAD

**Issue by skshetry** [iterative/vscode-dvc#2746]
```
The located DVC CLI is at least a minor version ahead of the latest version the extension was tested with (2.33.1).
This could lead to unexpected behaviour.
Please upgrade to the most recent version of the extension and reload this window.
```

DVC should be backward compatible.

**Comment by mattseddon** [comment]
The APIs that we use are not always backwards compatible. Most recent example: https://github.com/iterative/vscode-dvc/pull/2521. We cannot implement https://github.com/iterative/vscode-dvc/issues/2728 for the same reason.

**Comment by shcheklein** [comment]
Yes, unfortunately we had examples where it led to a discrepancy.

I agree though that we are not updating fast enough the "MIN_TESTED_VER" variable quick enough. Can we automate this? As soon as new DVC version is available create a PR to review with an update + publish the extension after it is merged?

wdyt folks?

**Comment by skshetry** [comment]
I think we can be optimistic here? It might be better to validate the output of dvc with a schema and not raise any issue as long as it passes.

Also demand backward compatibility from DVC (maybe via new field, etc) at least for 5-10 minor versions.

**Comment by mattseddon** [comment]
> I think we can be optimistic here?

I don't think that either DVC or the extension are at the level of maturity required for this to be a viable option. Maintaining backward compatibility would be an unnecessary overhead for a small team.

Closing for now. We can revisit later.

**Comment by skshetry** [comment]
FYI dvc is in semver. Maintaining backward compatibility is required, even moreso for machine-readable formats (aka `—json`).
