### ISSUE TITLE
Live trainning experiment table broken.

### ISSUE THREAD

**Issue by karajan1001** [iterative/vscode-dvc#2755]
Training in the workspace the live experiment table is broken
![image](https://user-images.githubusercontent.com/6745454/201365596-fbb3b96d-cc37-4e61-a2b0-5370d2af44fe.png)
While at the same time, `dvc exp show` cli works well.
![image](https://user-images.githubusercontent.com/6745454/201365904-b8d51a9a-9b6a-4195-afbc-c8a55bed2e55.png)

How to reproduce. 
2. In demo repo https://github.com/iterative/vscode-dvc/tree/main/demo.
3. set epochs to a relatively big number (1000).
4. wait for it to run about 100 iterations.
5. you will see the problem above.

**Comment by mattseddon** [comment]
Possibly related to https://github.com/iterative/vscode-dvc/issues/1690 / https://github.com/iterative/dvc/issues/7693

**Comment by karajan1001** [comment]
> Possibly related to #1690 / [iterative/dvc#7693](https://github.com/iterative/dvc/issues/7693)

Yes related to https://github.com/iterative/dvc/issues/7693.

**Comment by julieg18** [comment]
> Yes related to https://github.com/iterative/dvc/issues/7693.

It does appear to be caused by the `dvc exp show` output described in https://github.com/iterative/dvc/issues/7693. Currently, I'm not sure what could be done on the VSCode side of things. @karajan1001, what's the status on fixing https://github.com/iterative/dvc/issues/7693?

**Comment by karajan1001** [comment]
> I'm not sure what could be done on the VSCode side of things. @karajan1001, what's the status on fixing [iterative/dvc#7693](https://github.com/iterative/dvc/issues/7693)?

The problem with this is that the `dvc exp show` can show an experiment table while the vscode-extension can't I need to know what's wrong with the JSON result.

**Comment by julieg18** [comment]
> The problem with this is that the dvc exp show can show an experiment table while the vscode-extension can't I need to know what's wrong with the JSON result. Are there any restrictions?

From what I'm understanding, there appears to be an issue with the JSON result of `dvc exp show`. The latest running checkpoint object usually has a `name` but it stops showing a `name` at some point, causing the rendered table to break. 

How the JSON output looks at around 15 epochs in (has a name key):

```
[
   ...,
   "f3370bf646c6d5d365c3ae6c34ee9d177bc94ee9": {
     "data": {
       "checkpoint_tip": "f3370bf646c6d5d365c3ae6c34ee9d177bc94ee9",
       "timestamp": "2022-11-16T18:13:14",
       "params": {
         "params.yaml": {
           "data": { "lr": 0.003, "weight_decay": 0, "epochs": 200 }
         }
       },
       "deps": {
         "data/MNIST": {
           "hash": "0aed307494600d178fbdc0d000d6db38.dir",
           "size": 66544866,
           "nfiles": 10
         },
         "train.py": {
           "hash": "d3cf46986f0faf10dba0404bec93e3a7",
           "size": 4620,
           "nfiles": null
         }
       },
       "outs": {
         "model.pt": {
           "hash": "fb18f51d8f3fdf9d637868fd02665417",
           "size": 439383,
           "nfiles": null,
           "use_cache": true,
           "is_data_source": false
         },
         "data/MNIST/raw": {
           "hash": "8c257df187855c681f88bde92d721ccd.dir",
           "size": 66544770,
           "nfiles": 8,
           "use_cache": true,
           "is_data_source": true
         }
       },
       "status": "Running",
       "executor": "workspace",
       "metrics": {
         "training/metrics.json": {
           "data": { "loss": 0.9102619886398315, "acc": 0.7672, "step": 16 }
         }
       },
       "checkpoint_parent": "8cd238b8915ef08e4cfbbfdbbde410aab4b78bfe",
       "name": "exp-78974"
     }
   },
   ...,
]
```

How it is about 100 epochs in (no name key):

```
[
   ...,
   "d731c3cf206ddadb6833d291842e20b235524973": {
     "data": {
       "checkpoint_tip": "d731c3cf206ddadb6833d291842e20b235524973",
       "timestamp": "2022-11-16T18:17:17",
       "params": {
         "params.yaml": {
           "data": { "lr": 0.003, "weight_decay": 0, "epochs": 200 }
         }
       },
       "deps": {
         "data/MNIST": {
           "hash": "0aed307494600d178fbdc0d000d6db38.dir",
           "size": 66544866,
           "nfiles": 10
         },
         "train.py": {
           "hash": "d3cf46986f0faf10dba0404bec93e3a7",
           "size": 4620,
           "nfiles": null
         }
       },
       "outs": {
         "model.pt": {
           "hash": "fe7d4465bf944cedc8ca1468302d0275",
           "size": 439383,
           "nfiles": null,
           "use_cache": true,
           "is_data_source": false
         },
         "data/MNIST/raw": {
           "hash": "8c257df187855c681f88bde92d721ccd.dir",
           "size": 66544770,
           "nfiles": 8,
           "use_cache": true,
           "is_data_source": true
         }
       },
       "status": "Running",
       "executor": "workspace",
       "metrics": {
         "training/metrics.json": {
           "data": { "loss": 0.34310898184776306, "acc": 0.8965, "step": 104 }
         }
       },
       "checkpoint_parent": "b80bd6e23af2a882abc028c32067daba075b8485" 
     }
   },
   ...,
]
```

**Comment by dberenbaum** [comment]
@julieg18 Awesome debugging! Hopefully that's enough for @karajan1001 to address it on the DVC side. AFACIT it seems consistent with his findings in https://github.com/iterative/dvc/issues/7693 that the exp ref points to a revision that hasn't been fetched yet.

Is it possible to also make the extension robust to situations where `name` doesn't exist so that if this ever happens again it won't break the extension?

**Comment by karajan1001** [comment]
Yes, on my screenshot we can also see that there is no `exp-xxxx` in it.
![image](https://user-images.githubusercontent.com/6745454/202333282-8706f940-7ced-42d9-9e69-b12ff3d3550a.png)

**Comment by dberenbaum** [comment]
> Is it possible to also make the extension robust to situations where `name` doesn't exist so that if this ever happens again it won't break the extension?

It looks to me like the issue on the VS Code side is here:

https://github.com/iterative/vscode-dvc/blob/6603de9c86d6ff7c96820517440c5f70047aa5c3/extension/src/experiments/model/collect.ts#L121

If the extension falls back to using `checkpoint_tip` when `name` doesn't exist, I think the extension would match the CLI that @karajan1001 showed above.

I tried to play around with this and it seems to work except for wanting to collapse constantly:

https://user-images.githubusercontent.com/2308172/202570190-ad19db87-535a-4a5c-8a9f-4896c0db3863.mov

I would submit a PR, but I think someone with better TypeScript skills and familiarity with the codebase could do a much better job much faster.
