### ISSUE TITLE
Error when trying to delete an experiment

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#2817]
I ran into an error when trying to delete an experiment:
<img width="1560" alt="image (2)" src="https://user-images.githubusercontent.com/17241029/203452329-8f9d59a3-b173-4c56-8b19-6c5f62f6bc61.png">

I did things in the following order:
- Ran a few experiments via UI
- Created a branch out of one of them
- Queued up a few experiments with CLI
- Tried to remove the experiment `exp-4f15d` and that's when the extension errored out

**Comment by mattseddon** [comment]
@alex000kim was this also on codespaces?

**Comment by alex000kim** [comment]
Yes, this is on codespaces

**Comment by mattseddon** [comment]
Likely caused by #2830

**Comment by mattseddon** [comment]
Will track under #2830
