### ISSUE TITLE
Test Jupyter Notebook extension onboarding as a "fresh" user

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#2829]
We want to test the Jupyter Notebook extension onboarding and see if we can use some of their techniques inside of our own extension.

**Comment by sroy3** [comment]
Here are my notes on the process of onboarding for the Jupyter Notebook extension:

Installing the extension and opening it in an empty project gives us empty views. None of the actions shown work.
<img width="1628" alt="Screenshot 2022-11-24 at 10 45 49 AM" src="https://user-images.githubusercontent.com/3683420/203850777-08e6153d-06c6-44b6-8cb5-bfdca81d3ff9.png">

Opening any random project will also give us the same result.

Only after creating a `ipynb` file and running it, we get an install prompt for the currently selected interpreter.
<img width="1631" alt="Screenshot 2022-11-24 at 1 24 14 PM" src="https://user-images.githubusercontent.com/3683420/203850841-9fc5056e-9df6-4f75-b9f3-1e3e5a2218a1.png">

Clicking install will install all the necessary python packages and result in the cell or file being able to run.

https://user-images.githubusercontent.com/3683420/203850876-280586a2-a9a9-4c4f-9d24-8b64f9261459.mov

Clicking cancel will result in an error message.
<img width="1634" alt="Screenshot 2022-11-24 at 1 24 46 PM" src="https://user-images.githubusercontent.com/3683420/203850926-26862a9e-25c0-4efa-afdd-53a7106ae0e8.png">

This concludes any onboarding I was able to find for the extension.

In my opinion this onboarding process is more about installing everything needed than setting up a project for you. It does not tell you how to use the extension either. I would compare it more to our “Setup the Workspace” workflow.
We could apply the same method to initialize a project (installing dvc), but for creating configuration files and setup everything needed, we’d need to find inspiration elsewhere.

What do you think @iterative/vs-code ?

**Comment by shcheklein** [comment]
@sroy3 thanks for the research 🙏 Yes I meant this as one of the first steps in the onboarding flow, not as a complete solution.
