### ISSUE TITLE
Extension does not work as expected in Codespaces

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#2830]
Among other things, to test:

- [ ] https://github.com/iterative/vscode-dvc/issues/2817

**Comment by mattseddon** [comment]
@shcheklein can you please set up codespaces for `vscode-dvc-demo`.

@alex000kim can you give me access to the remote and codespaces for a project that I can test against please? Maybe magnetic-tiles-defect? or the new one you've been working on.

**Comment by alex000kim** [comment]
You should already have access to it: https://github.com/iterative/magnetic-tiles-defect

**Comment by mattseddon** [comment]
Seems like for some reason the appropriate metrics files are not being watched but the watchers are otherwise working as expected for plots updates. Saving `dvc.yaml`:

https://user-images.githubusercontent.com/37993418/205004733-5c8d4017-8acd-4c98-8254-17e864a82221.mov

Still investigating.

**Comment by mattseddon** [comment]
Second attempt to recreate. Everything working as expected 🤦🏻:


https://user-images.githubusercontent.com/37993418/205022514-22927623-5214-4960-b30d-93d90a42c264.mov

except now custom icons are missing:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/205023001-3e92411d-3072-460d-b96e-98dc8c393164.png">

**Comment by mattseddon** [comment]
I can confirm when running [magnetic-tiles-defect](https://github.com/iterative/magnetic-tiles-defect) experiments in codespaces live updates for plots now consistently work:

### Demo


https://user-images.githubusercontent.com/37993418/206354485-992d61e0-cd8e-414c-b95d-9e20a9086948.mov

Deleting an experiment also seems to work fine:

### Demo

https://user-images.githubusercontent.com/37993418/206355575-3fb795d9-3740-4cae-8cdf-7c3494ffdcb0.mov
