### ISSUE TITLE
Revisions on the ribbon can be very slow to appear

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#2835]
This can result in a confusing screen for some time (I got stuck like this for a good 20 seconds).

<img width="1628" alt="Screenshot 2022-11-25 at 9 48 11 AM" src="https://user-images.githubusercontent.com/3683420/204009997-1fdd4e77-1aaf-4d38-8273-6457bb6be874.png">

**Comment by sroy3** [comment]
Not sure if this is because the extension sends the revisions much later or if it's something we should simply mitigate on the webview side with either staying in the whole loading state longer or adding a loading to the ribbon.

**Comment by shcheklein** [comment]
@sroy3 what is the DVC output in this case? could you share pls?

**Comment by shcheklein** [comment]
Also, when it's done - does it show any extra plots here or not?

**Comment by sroy3** [comment]
It took me a while to understand when the problem was happening. I think it's because we keep the old webview state when we re-open it while we're still waiting on `plotsDiff` to finish. On first load we get the loading screen, but in that case, plots are saved in a store outside of Redux and not effectively cleaned when closing the webview.

https://user-images.githubusercontent.com/3683420/204042810-6d8456bb-74e1-4dca-a6dd-07ecae71ee4d.mov

Reseting the state might not help too much for performance, but at least it'll look a little less buggy. It should be an easy fix.

**Comment by sroy3** [comment]
I was wrong, it's not the webview state that isn't being reset, it's actually reset. When re-opening the webview, the plots are set instantly, but the selected revisions are not. We should probably keep the current plots webview data into an object and send it back to the webview when re-opening before re-calculating everything.

**Comment by mattseddon** [comment]
#2831 should help
