### ISSUE TITLE
Sticky header broken in experiments table view

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#2840]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/204179736-ef06c237-67e4-4375-a9db-415df44998de.png">

After scroll: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/204179689-b07d7a4c-7218-4b32-9a78-13cd867f80be.png">

This is strange because we have a story for scrolling which doesn't appear to be broken.

**Comment by shcheklein** [comment]
Caused by https://github.com/iterative/vscode-dvc/commit/be2adc3880b4239aa778de705fa42501ffc56542#diff-b07cda7c57ea3d44e77847455b8a5fd5ec51ca179223b797e1324e095dd78bcfR3
