### ISSUE TITLE
 Persisting experiments from table: share as a branch  and commit and share

### ISSUE THREAD

**Issue by SoyGema** [iterative/vscode-dvc#2855]
# Context
 Running experiments from [workshop](https://github.com/iterative/VSCode-DVC-Workshop). Find a parameter that impacts model performance. Testing persistance UI table features.  In table , access to context menu, and then click in share as a branch

##  **Share as a branch** 
Pop up menu appears and `git checkout` is done
<img width="1436" alt="BRANCH" src="https://user-images.githubusercontent.com/24204714/204503991-1f19a119-33c4-48ee-9629-5fba28c5d5f4.png">

ISSUE : Inconsistency of branches from CLI and VSCode. CLI tells me that Im in that branch, but I can´t find it . Unclear if I have to publish first or if the extension does it for me . I´m probably missing something . Can you help ? 

<img width="1819" alt="BRANCH2" src="https://user-images.githubusercontent.com/24204714/204504553-43f8f065-8865-4901-b24b-b3ff0685699f.png">

**Comment by SoyGema** [comment]
## Commit and share (1)

From the UI under the `7f33f67` experiment, access to context menu and click Commit and share. VSCode shows a message . It pops p an error . Apparently is expecting the experiment above he one I want to commit . `479e5d3`

<img width="1804" alt="Captura de Pantalla 2022-11-29 a las 11 35 39" src="https://user-images.githubusercontent.com/24204714/204508424-17cc90eb-4eb0-41e8-97c9-c4a402242edf.png">

Don´t know if this helps , but I checked that I commited all things before this
Unclear if this is related, but under left menu I selected the experiment and clicked  apply to Workspace. The following error was displayed. 
<img width="1684" alt="APPLY TO WORKSPACE" src="https://user-images.githubusercontent.com/24204714/204509763-047322ec-94b8-4f00-a182-0ee2028b8e9b.png">


## Commit and share(2) 

From the UI under the `479e5d3` experiment, access to context menu and click Commit and share. VSCode shows a message . It pops p an error . Apparently is expecting the experiment  to derive from '67a731e' , one that I removed previously from the table .


<img width="1335" alt="error2" src="https://user-images.githubusercontent.com/24204714/204512349-bdb0d9cb-0bf8-428a-a7ef-d8ed0b4b4ec9.png">

**Comment by SoyGema** [comment]
Thanks for having a look at this! 
Please don´t hesitate to point me out in the right direction if I did something wrong .
And thanks for bringing persistance to machine learning experiments !

**Comment by mattseddon** [comment]
## Commit and share

From your screenshots it looks like you are trying to commit and share an experiment from the previous commit. It seems that it is not possible to apply an experiment from a previous commit onto the workspace using DVC. I'll do some more investigation before raise a bug there 👍🏻.

**Comment by dberenbaum** [comment]
> Commit and share

What are the steps for this action? I'm surprised that it runs `dvc exp apply`. It's not clear to me that this action will try to overwrite my workspace with the results of that experiment, especially since it's sandwiched between branching options.

<img width="214" alt="Screenshot 2022-12-02 at 1 24 24 PM" src="https://user-images.githubusercontent.com/2308172/205360633-a643b5d4-bd84-4d06-ad21-9821cc0ec9a5.png">

**Comment by mattseddon** [comment]
@dberenbaum 

What commit and share does (happy path) sequentially:

Applies experiment to workspace.
Pushes DVC data to DVC remote.
Git stage entire workspace.
Git commit.

Order of operation for share as branch: https://github.com/iterative/vscode-dvc/issues/2855#issuecomment-1334485196

**Comment by mattseddon** [comment]
[Q] @dberenbaum do you think we should limit these actions to the current commit or keep them available for any of the experiments displayed?

**Comment by dberenbaum** [comment]
> [Q] @dberenbaum do you think we should limit these actions to the current commit or keep them available for any of the experiments displayed?

How much work does that take?

@pmrowla @karajan1001 How much work would it take to address https://github.com/iterative/dvc/issues/8481?

I would rather do the latter, but if it's much easier to disable in VS Code in the short term, then it makes sense.

**Comment by shcheklein** [comment]
@dberenbaum do we know why we have this limitation? (what is the core reason). I'm not sure I understand what is the difference between commits tbh.

**Comment by dberenbaum** [comment]
Since the exp ref stashes changes from some baseline commit, it's safe to apply that stash on top of the commit from which it originated. If it is applied on top of some other commit, it could create conflicts or maybe even just unexpected results.

When experiments was first implemented, it was sufficient to apply on top of the baseline commit, and applying on top of other commits might have been considered too dangerous. Now that we see it used more, I think the pros outweigh the cons, especially since we should be able to rollback in case of conflicts.

That does complicate things for VS Code, though, since there's no guarantee the apply will work (the same could be true for a dirty workspace even on top of the baseline commit).

**Comment by shcheklein** [comment]
It's not a stash though, right? It's more or less a proper hidden commit? 

In this sense, there should be not difference to which ref to hard reset to to my mind. It's not like applying on top, it should be more like:

```
git stash

git revert <ref> # not sure this is the right way to do this, but I think you get the idea. We need to keep the history, but apply an experiment exactly, means change files back if needed
```

wdyt?

**Comment by dberenbaum** [comment]
Hey @shcheklein, I moved this discussion back into https://github.com/iterative/dvc/issues/8481.

In the short term, should we limit these actions to the current commit since it seems like there's still product questions on how `dvc exp apply` should work for other commits?

**Comment by karajan1001** [comment]
> > [Q] @dberenbaum do you think we should limit these actions to the current commit or keep them available for any of the experiments displayed?
> 
> How much work does that take?
> 
> @pmrowla @karajan1001 How much work would it take to address [iterative/dvc#8481](https://github.com/iterative/dvc/issues/8481)?
> 
> I would rather do the latter, but if it's much easier to disable in VS Code in the short term, then it makes sense.

about 1-2 days?

**Comment by shcheklein** [comment]
@karajan1001 @dberenbaum any thought / further actions on this?

**Comment by dberenbaum** [comment]
Nothing planned yet since @karajan1001 still has a few queue bugs he's working on AFAIK. I think there's still some product questions we can address in the meantime in https://github.com/iterative/dvc/issues/8481.

**Comment by mattseddon** [comment]
Should be fixed by https://github.com/iterative/dvc/issues/8481. More than likely that this functionality will either: 

1. Get pushed back into DVC
2. Get dropped completely.

Closing for now.
