### ISSUE TITLE
dvc exp save action

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2856]
In demo today, @alex000kim asked about having a way to add the new `dvc exp save` (https://github.com/iterative/dvc/pull/8599) functionality to VS Code. This would enable users to save any repo state to the experiments table without actually running a pipeline.

It could be useful for users who don't want to implement DVCLive but still want to save experiments outside of `dvc exp run` commands. On the other hand, not much will be shown in VS Code unless they have set up metrics, plots, etc. on their own, so it's potentially confusing for new users 🤔 .

It could also be useful if we want to focus on queuing and deprioritize workspace experiments. We can support one workflow of queueing and running experiments in temporary workspaces, and another workflow where users run `dvc repro` (through CLI or VS Code) in their workspace followed by `dvc exp save` when they are ready to save the result.

cc @daavoo @dtrifiro

**Comment by shcheklein** [comment]
so, it's kinda git stash? Does `dvc exp save` allow for that? What do we see in the `dvc exp show`? 

If it can be done in DVC I don't see any contradiction to being able to do this in VS Code tbh.  The simplest we can do is just expose `save` as part of the command palette or do you have in mind some button, context menu?

**Comment by dberenbaum** [comment]
No particular plans right now. Starting with the command palette sounds fine.

**Comment by dberenbaum** [comment]
Don't think we need this right now. Closing.
