### ISSUE TITLE
Move Views side panel to the very top

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2900]
I think it should be always above all the other panel cc @julieg18 

<img width="307" alt="Screen Shot 2022-12-07 at 6 58 51 PM" src="https://user-images.githubusercontent.com/3659196/206345408-bf6f272a-cdd0-422a-9f5f-271b4b36ee2c.png">

**Comment by julieg18** [comment]
From my research, when you first open up a new workspace the "views" is indeed on top, but VsCode doesn't offer a way for us to adjust the views order on workspaces that already have used the DVC extension. At that point, the order can only be adjusted by the user.

**Comment by shcheklein** [comment]
Thanks, @julieg18 ! Can someone try to run a fresh codespaces also? For me, even when I build it from scratch, I'm getting this: 

<img width="1507" alt="Screen Shot 2022-12-15 at 6 38 25 PM" src="https://user-images.githubusercontent.com/3659196/208009323-9f79d876-5de0-4c9d-8348-b1d477b50a97.png">

it might be it's saving some of my preferences globally, not sure.

**Comment by sroy3** [comment]
That is because the column tree is indeed before the views buttons. I'll switch the order.

**Comment by shcheklein** [comment]
Thanks @sroy3 !

Also, qq - was it always the case or did we disable the Discord / Github panel with this change? I think we want to show always show it, wdyt? (it's kinda quick help / support) at the very bottom of the side panel

**Comment by sroy3** [comment]
> Thanks @sroy3 !
> 
> Also, qq - was it always the case or did we disable the Discord / Github panel with this change? I think we want to show always show it, wdyt? (it's kinda quick help / support) at the very bottom of the side panel

It's still there. At the very bottom for me. I just didn't take a screenshot of the whole sidebar.

**Comment by shcheklein** [comment]
Hmm, but on my screenshot it's not here 🤔

**Comment by sroy3** [comment]
> Hmm, but on my screenshot it's not here 🤔

It's seems the sidebar is not scrolled to the bottom

**Comment by shcheklein** [comment]
Yes, you are right! And there is not easy way to scroll at all (pretty much manually only). Each small container has it's own scroll and intercepts it. That's weird. Too many panels I guess after all.

I'll think if we need to do anything with this. Thanks @sroy3 .
