### ISSUE TITLE
Bulk delete experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2922]
Can there be a way to delete experiments in bulk similar to `dvc exp remove --all` and/or `dvc exp remove -n/--rev`? Not an urgent priority, and maybe not as important in real life as in demoing when I frequently want to reset, but I imagine it's still helpful sometimes.

**Comment by shcheklein** [comment]
Just as a workaround for now you can Shift-select (select one first, keep shift down and select the last one) all experiments under a certain commit and remove them via context menu. Would that work for you?

**Comment by dberenbaum** [comment]
Nice! I didn't know about that. Feel free to close if you think it's unnecessary to go further.

**Comment by sroy3** [comment]
Maybe showing a taskbar with actions such as delete when selecting rows would make it even more obvious (same for other actions), right-clicking is not always an instinct.

**Comment by mattseddon** [comment]
Thanks, @dberenbaum. We can come back to this later.

**Comment by shcheklein** [comment]
Closing for now, we'll come back to this later. Certain improvements - GMail like checkbox with a dropdown, and what @sroy3 mentioned can be done here.
