### ISSUE TITLE
Onboarding to Git

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2947]
If I try to initialize DVC through the extension but I'm not in a Git repo, it fails and gives ugly error messages. Can it instead explain that this is a prerequisite and either initialize Git or instruct the users on how to do so?

<img width="555" alt="Screenshot 2022-12-15 at 9 32 11 AM" src="https://user-images.githubusercontent.com/2308172/207887278-1a1c9331-b157-44c1-863e-7f8738a9cb7b.png">

<img width="1066" alt="Screenshot 2022-12-15 at 9 32 22 AM" src="https://user-images.githubusercontent.com/2308172/207887286-f96e2e98-697a-451b-8935-3936da2b3a11.png">

**Comment by dberenbaum** [comment]
Also, after then initializing DVC, it might be helpful to guide the user to committing that setup, both as a general good practice and because the experiments onboarding experience will fail in a repo with no commits.

**Comment by shcheklein** [comment]
This is heavily depends on DVC (ugly message it's a bug in DVC I think cc @skshetry ). Being able to show something more reasonable - DVC should be returning it probably in a bit more structured way (error code?)

**Comment by dberenbaum** [comment]
DVC could structure the error more if that's the best way for the extension to detect if the user is in a Git repo, but can the extension detect the lack of `.git` earlier and suggest `git init` before `dvc init` (or do them in tandem when needed)?

**Comment by shcheklein** [comment]
> but can the extension detect the lack of .git earlier and suggest git init before dvc init (or do them in tandem when needed)?

Yes, that's a good idea. And yes I think we can and should do this

**Comment by mattseddon** [comment]
We can add a screen with a button that directs the user to the Source Control view using `workbench.scm.focus`.

https://user-images.githubusercontent.com/37993418/208325686-a9d81f56-9060-4e27-a77f-d0e6b9c2f7c7.mov

**Comment by shcheklein** [comment]
Can we do this w/o SCM support, on our end? Any additional step is additional friction ...
