### ISSUE TITLE
Change running directory

### ISSUE THREAD

**Issue by jan-pair** [iterative/vscode-dvc#3011]
Hi, is there a way to change the default running dir?

I have a mono-repo with the following structure:

```
.dvc
--train
----.dvc
```

where the global dvc only stores final models and datasets, while the ``train`` subfolder is used for experiments. How can I tell the extension it should run dvc in the ``train`` subdirectory, so that I can observe experiment logs?

I'm fine with setting this option once and for all, so it should be simpler than multi-project selection.

(Related to https://github.com/iterative/vscode-dvc/issues/1931#issue-1276755970)

**Comment by mattseddon** [comment]
Hi @jan-pair,

What does the experiments table look like at the top level of your mono-repo?

Does opening a VS Code workspace with `train` at the root give you the desired result?

**Comment by jan-pair** [comment]
At the top level it shows "no experiments to display". Changing the root to ``train`` gives me the desired result.

**Comment by mattseddon** [comment]
What would you expect to see at the top level? What is your use case for having the train folder as a sub-repo instead of just a folder? What do your pipelines (`dvc.yaml`s) look like?

Is the workaround of opening `train` as a separate workspace enough?

**Comment by jan-pair** [comment]
I don't expect to see any plots on top level out-of-the-fox, but I would like to tell the extension (by modifying some global parameter) that it should use dvc located in the subfolder.

My use case is that I have a single git project with two dvc instances. The global one tracks a lot of checkpoints that I don't want to pull every time I experiment with a particular model, while the dvc located in ``train`` subfolder tracks solely experiments on this particular model. There is a single dvc pipeline in the subfolder (basically runs ``python train.py`` and saves experiments), and no pipelines in the base folder.

I could open ``train`` as a separate workspace, but that's very inconvenient because I sometimes have to look at some code in the base folder and to jump back and forth between workspaces.

**Comment by mattseddon** [comment]
In order to make this work we would need to provide options to set the working directory for the three different components of the extension. I.e one for data, one for plots & another for experiments.

@dberenbaum what do you think about this use case?

**Comment by jan-pair** [comment]
Is there a reason to specify this for three different components?

At the moment it would be 100% fine for me if all of them are using the same (user-modifiable) working dir.

It can also help dealing with monorepos noticeably - suppose someone works within a global project where you're responsible for a single sub-folder only, but sometimes has to view/debug the global methods everyone uses.

Ideally, you would have an option to switch between different dvc-s conveniently within a command bar (like is mentioned here https://github.com/iterative/vscode-dvc/issues/1931#issue-1276755970), but as the first stage it would be nice for me to understand what piece of extension code should I change to hard-code the particular subfolder.

**Comment by mattseddon** [comment]
Try setting this: https://github.com/iterative/vscode-dvc/blob/main/extension/src/setup/index.ts#L53 to be `= [ 'your/special/working/dir' ]`

**Comment by mattseddon** [comment]
Try setting https://github.com/iterative/vscode-dvc/blob/main/extension/src/setup/index.ts#L53 to ` = [ '/your/special/working/dir' ]` and remove all logic from the method on https://github.com/iterative/vscode-dvc/blob/main/extension/src/setup/index.ts#L181

**Comment by jan-pair** [comment]
Sorry, I'm bad at extension development, does this approach mean that for each server where I need this customization I have to clone the repo, change those lines, build it, start debugging and only then I would have my customized extension in a novel Vscode instance?

I was hoping editing some files in ``~/.vscode-server/extensions/iterative.dvc-0.5.32`` can do the trick...

**Comment by dberenbaum** [comment]
@mattseddon Should the extension run DVC commands from `cwd` if it is set for the terminal or debugging environment (see https://code.visualstudio.com/docs/getstarted/settings and https://stackoverflow.com/questions/38623138/vscode-how-to-set-working-directory-for-debugging-a-python-program)?

@jan-pair Would this be enough for you, or is it important for DVC to run from a separate directory from other commands?

**Comment by jan-pair** [comment]
Yes, I believe that would be enough, since it's much simpler to cd outside instead of switching between workspaces

**Comment by shcheklein** [comment]
> https://stackoverflow.com/questions/38623138/vscode-how-to-set-working-directory-for-debugging-a-python-program
> if it is set for the terminal or debugging environment

There can be multiple debug / run configs with different `cwd`s. I don't think we can rely on them as a way to say what it is the default location.

> https://code.visualstudio.com/docs/getstarted/settings

@dberenbaum  do you mean this `terminal.integrated.cwd`? I think it also won't work in our case, it's might affect globally a lot of other things in some way people don't actually want. Feels too heavy handed.

> Try setting https://github.com/iterative/vscode-dvc/blob/main/extension/src/setup/index.ts#L53 to  = [ '/your/special/working/dir' ] and remove all logic from the method on https://github.com/iterative/vscode-dvc/blob/main/extension/src/setup/index.ts#L181

I'm not sure I understand your suggestion. Was the idea to build a customized version of an extension? Just to try? Or what is the idea?

---------------

If anything, we can do an option for the extension itself tbh, to explicitly let user set the current cwd for DVC commands. I think that is the most appropriate solution here? @jan-pair if we have a single option like this, are you fine that you won't see anything from the global `.dvc`? Even in the `DVC tracked` panel you won't be able to see models, etc.

**Comment by dberenbaum** [comment]
Yup, good correction @shcheklein. A dvc-specific cwd setting seems like a good starting point to me without getting into showing multiple projects at once.

**Comment by mattseddon** [comment]
> I'm not sure I understand your suggestion. Was the idea to build a customized version of an extension? Just to try? Or what is the idea?

This was the answer to this question: "the first step it would be nice to understand what piece of extension code should I change to hard-code some particular sub-folder."

**Comment by shcheklein** [comment]
Okay, yes, I see.  ... since there is no way to publish this extension, the only way would be to use build `.vsix` and move it around + keep updating (rebuilding) as main code changes. Quite cumbersome I would say, but might work ...

**Comment by jan-pair** [comment]
@shcheklein yes it's completely fine, I mostly use terminal for my global dvc anyway, the best thing for me in this extension is the ability to use it as an alternative to tensorboard in comparing experiments, which is by the way very cool)

O, I see, probably I could try distribution of a customized ``.vsix`` file across different servers for this and build it only once. I'll try that, thanks

**Comment by mattseddon** [comment]
@jan-pair, I've shipped a change to the way we auto-detect projects. We now not only detect mono-repo roots but also all of the sub-projects inside. I have also added a `dvc.focusedProjects` config option that takes an absolute path (or paths) to the subset of projects that you are currently working with.

**Comment by jan-pair** [comment]
Works like a charm! Thank you 🤗
