### ISSUE TITLE
Make sure that experiment buttons are properly handled in DVCLive-only case

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3021]
We need to think what do we do when pipeline is not available (DVCLive scenario).

- [x] Run button should be able to detect that pipeline is not available
- [x] Quick actions should be able to detect this also
- [x] Use Run to create pipelines - generate a template. Similar to creating launch config in VS Code
- [x] Stop button, etc - should be handled properly (#3027 )

What else I'm missing here?

**Comment by sroy3** [comment]
Tested and everything in this ticket is done.
