### ISSUE TITLE
Improve multiple commits feature

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#3036]
- [x] Fix bug with `dvc exp show -n 3` not always showing the last three commits (see [#3035 comment](https://github.com/iterative/vscode-dvc/pull/3035#discussion_r1060120952)) (#3053)
- [x] Make split between the "main" row and "past commit" rows more obvious (#3087) 
- [x] Add more commit information to table rows in a tooltip (full message, author, git tags, etc.)
- [x] Possibly show the commit messages in quick pick experiment selection (if we can show both columns and commits) 
- [x] Show the commit messages in the plots ribbon blocks
- [x] Incorporate the [git-commit](https://microsoft.github.io/vscode-codicons/dist/codicon.html) icon into commit messages 

Followup to #3016

**Comment by julieg18** [comment]
> Make split between the "main" row and "past commit" rows more obvious

Looked into some other tables but had some difficulty finding ideas since no table that I had a clear "split" between rows minus when the rows were in collapsible groups. But here's one idea I experimented with: 

<img width="1008" alt="Screenshot 2023-01-05 at 8 17 01 AM" src="https://user-images.githubusercontent.com/43496356/210804635-58f6f00e-568e-40ba-81ff-20ad452bfaa0.png">

Though it's hard for me to tell when something looks good or I've been staring at it for too long 😅 Any other ideas that we want to test out? cc @iterative/vs-code, @shcheklein

**Comment by shcheklein** [comment]
@julieg18 I like it! it's simple and explicit. We'll be able to add a dropdown of some other element to configure which commits to show as a next step, it's an obvious and good place for that.

I don't think we need ":"

**Comment by julieg18** [comment]
Two design ideas so far for commit tooltips on the experiment table! 

<img width="310" alt="Screenshot 2023-01-13 at 11 49 16 AM" src="https://user-images.githubusercontent.com/43496356/212388401-56b5a00e-fe5b-497f-84fd-10fdbc150a08.png">
<img width="261" alt="Screenshot 2023-01-13 at 11 58 00 AM" src="https://user-images.githubusercontent.com/43496356/212388405-c8ce0f96-ac52-45ed-93de-9aaa0a5cc6b0.png">

Any preference or other ideas/inspiration? cc @iterative/vs-code, @shcheklein

**Comment by shcheklein** [comment]
I think the first one is better! I can't make screenshot (it doesn't allow me for whatever reason), but take a look at how GitLens represents them in the COMMITS side panel. We can do something similar (simplify if some parts there take more than 10 minutes to implement :))
