### ISSUE TITLE
Story: Search experiments

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3043]
Replaces #2106

In the table users should be able to search an experiment or multiple experiments on certain criteria to then do actions - remove, star, plot, modify, etc.

- `Cmd-F` should probably work
- We should support search by fuzzy criteria (metric is approximately this or that)
- We should search by text in names, Git tags, hash
- After search is done we can highlight select them in the table, also support hot keys to jump to the next / previous

**Comment by mattseddon** [comment]
Can this replace https://github.com/iterative/vscode-dvc/issues/1720?

**Comment by shcheklein** [comment]
No, I don't think so, they feel quite different to me.

**Comment by mattseddon** [comment]
Consider against #3430

**Comment by mattseddon** [comment]
Related to https://github.com/iterative/vscode-dvc/issues/4229
