### ISSUE TITLE
Improve quick pick experiment selection

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#3044]
- [x] The commands "Modify Experiment Param(s) and Resume", "Modify Experiment Param(s) and Queue" , and "Modify Experiment Param(s) and Run" are only showing the branches instead of all experiments. 
- [x] The command "Remove Experiment" (possible some others as well) doesn't let you filter by description and detail
- [x] All quick picks for experiment selection should be showing the first three columns
- [ ] Change "Remove Experiment" to "Remove Experiments"

**Comment by mattseddon** [comment]
I think `Remove Experiment` should be `Remove Experiments` and moved to `canPickMany`
