### ISSUE TITLE
Onboarding feedback

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3057]
Hey, I took another shot at onboarding and it's getting smoother each time. I found a couple minor issues:

1. If starting from a fresh Git repo, experiments will break if there's not a commit already. Is there some way we can auto commit when initializing dvc or suggest to make a commit if there is none in the repo? IMO this should be part of the "Show Setup" workflow, and we should block any other workflows until there is a commit in the repo.
2. The first thing I see in the sidebar after initializing my repo but before running any experiments is "Columns" showing the column "Created." Can we move it down in the sidebar or hide it?

--------

Actions:

- [x] Check if this is about `dvc exp run` and `dvc exp show` in the first place. If they return a reasonable error we can and should show them.
- [ ] If there are not commits we can introduce a screen with a message and a button to focus users on the SCM panel.
- [x] Disable columns section (and other sections) if we can't show the table at this moment yet to make it consistent.

**Comment by shcheklein** [comment]
1. Check if this is about `dvc exp run` and `dvc exp show` in the first place. If they return a reasonable error we can and should show them.
2. If there are not commits we can introduce a screen with a message and a button to focus users on the SCM panel.
3. Disable columns section (and other sections) if we can't show the table at this moment yet to make it consistent.

**Comment by dberenbaum** [comment]
> * Check if this is about `dvc exp run` and `dvc exp show` in the first place. If they return a reasonable error we can and should show them.

I'll add issues to improve the errors in the CLI, but it doesn't really impact anything here since this is about the experience before even getting to `dvc exp run` or `dvc exp show`. 
* The table won't show at this point regardless of whether there is a commit, so that's handled well already. 
* You can try to run experiments, but it's a separate issue where we should disable this action until a pipeline exists (related to https://github.com/iterative/vscode-dvc/issues/3058). 

Regardless, encouraging a Git commit after `dvc init` or when starting the extension from an empty Git repo would help (similar to the `dvc init` message "You can now commit the changes to git").

**Comment by shcheklein** [comment]
> I'll add issues to improve the errors in the CLI, but it doesn't really impact anything here since this is about the experience before even getting to dvc exp run or dvc exp show.

@dberenbaum do we have an issue for this? Also, do we have something about commits for Studio (unless you do a commit you can't see metrics). Trying to consolidate my thoughts about this and also answer [this question](https://stackoverflow.com/questions/75306950/dvc-error-scmrepo-exceptions-scmerror-empty-git-repo)

**Comment by dberenbaum** [comment]
We have https://github.com/iterative/dvc/issues/7548, which is part of the current epic to improve experiments. Related: https://github.com/iterative/dvc/issues/8839, https://github.com/iterative/dvc/pull/8840.
