### ISSUE TITLE
Onboarding screen stuck on install DVC even after it's installed

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3101]
On Windows, latest VS Code 1.74.3, Python extension is installed.

https://user-images.githubusercontent.com/3659196/212571271-3f20b263-290f-4026-8fc4-5f5ade98856f.mov

Reloading the VS Code helped.

**Comment by sroy3** [comment]
This isn't a Windows bug. The issue appears when the Python path is different than the default one (`miniforge3/envs/hackathon` in this case). I can reproduce on Mac and it works as expected in Windows without changing the path. I'll look into this.
