### ISSUE TITLE
Add additional metadata about DVC repo to source control panel

### ISSUE THREAD

**Issue by skshetry** [iterative/vscode-dvc#3164]
Opening a `Source Control` panel, and then right-clicking on this brings a menu to select repositories to show/hide.

Right now, it's impossible to determine which is a Git repo or which one is DVC repo (except of using the order to decide, DVC repo is the last one for each repository).

Is it possible to add some metadata to it, so that it's easy to differentiate? 

Just creating an issue if it's possible. It's a minor annoyance though. 

![Screenshot from 2023-01-26 21-15-08](https://user-images.githubusercontent.com/18718008/214877327-586e7c60-4360-4839-9e43-5db0d5bab65e.png)

**Comment by mattseddon** [comment]
Hi @skshetry, thanks for raising the issue. I've checked the API and we have no control over how this list is generated. The DVC entries are simply lifted from the last folder of each repository's root. Luck that there is a workaround 🙏🏻.
