### ISSUE TITLE
Manual testing of updates React-table version 8

### ISSUE THREAD

**Issue by Nataliia10** [iterative/vscode-dvc#3189]
### This ticket is related to the manual testing of updates React-table version 8

VM characteristics:

OS:
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
Linux kernel version:
5.15.0-1028-aws

**Process:**

_Environment set-up_

- [x]  install [VScode](https://code.visualstudio.com/)
- [x]  install curl
- [x]  install Node.js -v 19.6.0
- [x] install npm -v 9.4.1
- [x]  install Yarn -v 3.4.1
- [x]  clone [repo](https://github.com/iterative/vscode-dvc.git)
- [x]  open repository as a project in VS Code 
- [x]  run yarn install from the Integrated Terminal
- [ ] Run Tasks: Run Build Task or comand: _yarn dev-server_ from the Terminal in VScode
- [ ]  Start Debugging (F5) to open the [Extension Development Host](https://code.visualstudio.com/api/working-with-extensions/testing-extension),
- [ ] open the DVC project in the Extension Dev Host

**Comment by Casyfill** [comment]
On @Nataliia10 ' s PC `yarn dev-server` runs with `failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. ` alert (and then falls with OOM, not sure if related)

**Comment by Nataliia10** [comment]
@shcheklein, problem with environment se-up in VScode.
Yarn installed,
while running command  `yarn dv-server` I get an error
sudo yarn dev-server
 ERROR  run failed: We did not detect an in-use package manager for your project. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
Turbo error: We did not detect an in-use package manager for your project. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
[https://www.loom.com/share/2333bc6458384fb8a4f60f379790f495](url)

**Comment by Casyfill** [comment]
I think this requires a bit more info but I can confirm that the same issue was raised [last time](https://github.com/iterative/vscode-dvc/issues/3189#issuecomment-1412804656) on PC. This time is Amazon Remote Desktop ubuntu, if I understood correctly

**Comment by shcheklein** [comment]
@iterative/vs-code any idea from the top of your head folks ^^?

**Comment by mattseddon** [comment]
What is the error here:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/37993418/217387354-abf7c274-2e83-4ad4-8942-a931b9e482d1.png">

I think you want to run either the build task or the dev-server. Not both.

**Comment by mattseddon** [comment]
This is the issue: https://github.com/vercel/turbo/issues/707

**Comment by mattseddon** [comment]
@Nataliia10 can you please test https://github.com/iterative/vscode-dvc/pull/3244 and LMK if that works for you.

**Comment by mattseddon** [comment]
From this:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/37993418/217753238-c148127f-8edc-4d7d-ac9c-4fd65d3d77e2.png">

We run on Node v16.14.2 as this is the version of Node that VS Code/electron uses:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/37993418/217753488-f38440aa-029d-46db-a91e-e5eafff64ca7.png">

We also use **v1** of Yarn. 

This could be why you are seeing some of the issues that you are.
