### ISSUE TITLE
DVC is currently unavailable

### ISSUE THREAD

**Issue by haimat** [iterative/vscode-dvc#3209]
I have installed DVC via snap on an Ubuntu 22.04 machine, which worked without errors. Then I created a new DVC project within my local Github repo clone and added+pushed some data, all from command line, following the [official docs](https://dvc.org/doc/start/data-management/data-versioning). Then I opened that project in VS Code and installed the DVC extension there. This has worked fine yesterday, however, today after rebooting the machine and opening VS Code again, I get the following message:

![image](https://user-images.githubusercontent.com/6633976/216556443-d8853a1a-ddfe-46d6-973e-c1c0a7fc8811.png)

I am using Ubuntu standard installation of Python 3.10 under `/usr/bin/python`, this is also set up accordingly in VS Code. I can run `dvc` on the command line just fine without errors. However, it seems the `dvc` Python module is not installed (or not visible to the interpreter):

```bash
$ python -m dvc
/usr/bin/python: No module named dvc
```

Is this a problem with snap, does that just install the command line tools but not the Python module?

**Comment by sroy3** [comment]
Closing as this was answered here https://github.com/iterative/dvc-snap/issues/99#issuecomment-1415911236

You can let the extension install DVC for you by clicking the "Install" button on the screen you've shared.

**Comment by efiop** [comment]
Related https://github.com/iterative/dvc-snap/issues/99

Probably you were not using snap before the reboot, maybe leftover dvc installation or something.
