### ISSUE TITLE
Show notification on a global plots failure

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3222]
If `dvc.yaml` is broken, or something else is happening with `plots diff` command, we should notify users. Not suggest to add an experiment even though an experiments is already selected, + it goes into a loop (expected?) of trying to get it:

https://user-images.githubusercontent.com/3659196/216793769-aff89a74-2b00-4591-b87f-ae4dacbc4afc.mov

**Comment by shcheklein** [comment]
@dberenbaum even after fixing the `dvc.yaml` command is breaking since `HEAD` is broken. We should fix `dvc plots diff` to be resilient to a failure in revision, wdyt?

**Comment by dberenbaum** [comment]
> @dberenbaum even after fixing the `dvc.yaml` command is breaking since `HEAD` is broken.

@shcheklein What do you meant here? What is breaking after you fix `dvc.yaml`?

Here's what I see:

https://user-images.githubusercontent.com/2308172/216996292-60b68bbf-0888-4c8e-8cca-9c33a9703643.mov

**Comment by shcheklein** [comment]
Okay, I can't reproduce this anymore. We can't get back to this if I hit it again.

**Comment by shcheklein** [comment]
I see it again:


https://user-images.githubusercontent.com/3659196/218173991-0e5bb6b9-f983-49a5-a35f-12ee62d0eb4f.mov

This time it's stuck on "Loading plots ..."

**Comment by dberenbaum** [comment]
@shcheklein I guess those failed revisions were before the dvclive 2.0 changes and have a different field name? So I guess we (VS Code) should show that error?

Also, do you know if the command returns the diff for the non-failed revisions? We should be able to show a plot for some revisions.

**Comment by shcheklein** [comment]
> Also, do you know if the command returns the diff for the non-failed revisions? We should be able to show a plot for some revisions.

No, it breaks in the middle. Generates a partial result, no HTML.

> I guess those failed revisions were before the dvclive 2.0 changes and have a different field name? So I guess we (VS Code) should show that error?

Yes, most likely. Yes, we should throw an error at least. At best we could show non-broken revision (but that depends on DVC).

**Comment by dberenbaum** [comment]
Opened https://github.com/iterative/dvc/issues/9025.

Possible steps to remediate:
1. Show the error in VS Code.
2. Parse the error and take action in VS Code -- for example, drop the broken revision and run `plots diff` again without it. Does it depend on https://github.com/iterative/dvc/issues/7692?
3. Have DVC return whatever plots it can -- this still requires good errors about what's missing so VS Code can inform the user about what's not showing and why.

**Comment by mattseddon** [comment]
After https://github.com/iterative/vscode-dvc/pull/3569 I need to add a global error screen to the plots webview to close this.

**Comment by mattseddon** [comment]
Was closed by #3627
