### ISSUE TITLE
Plots: Update legend suppression (smooth template)

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#3226]
Now that the default template is a smooth plot our (flaky) method of suppressing the legend and then reinstating it in a zoomed plot no longer works as expected/produces a nice result:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/216854144-b32db79b-f2b5-4526-94fb-13463f4d5b35.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/216854160-f5ebe608-5fe0-44f5-8c11-7a8dc9fab0b0.png">

We need to decide whether or not we are going to continue attempting to display the legend/data in the old way or if we are going to take a different approach. If we are going to change then we need suggestions for how to integrate the sidebar/rest of the app.

After deciding on the approach we will need to spend time updating the implementation.

Note: I have spent some time looking into a fix/patch for the change and it appears that the change will be non-trivial. I think we are going to have to start walking through the template hierarchy to update the different color/strokedash/shape entries.

**Comment by mattseddon** [comment]
Related to #3223

**Comment by shcheklein** [comment]
It should be fixed/researched along with https://github.com/iterative/dvc-render/issues/115

**Comment by shcheklein** [comment]
Looking into this. I'll try to remove the `legend` objects from the Spec as we do with titles.

**Comment by shcheklein** [comment]
Closing for now in favor of https://github.com/iterative/dvc-render/issues/115 (we can reopen if @dberenbaum decides other way).
