### ISSUE TITLE
Respect `.dvcignore` and update changed files numbering

### ISSUE THREAD

**Issue by yathomasi** [iterative/vscode-dvc#3237]
I just noticed extension is not respecting `.dvcignore` and showing `.DS_Store` as added. 

Also, the number appears misleading in my case it should be just `1` as shown in `dvc diff`. It seems like it's counting the folders as well.

![dvc-vscode](https://user-images.githubusercontent.com/20840228/217172367-8420504f-9267-48bf-9a1a-1bca23091fee.png)

**Comment by mattseddon** [comment]
@yathomasi we use `dvc data status --granular --unchanged` to populate that tree. What is the output of that command?

**Comment by yathomasi** [comment]
`dvc data status --granular --unchanged`

I see it's `dvc data` not respecting the `.gitignore`. Still, the numbering still appears misleading to me.

<img width="1117" alt="Screenshot 2023-02-10 at 11 47 15" src="https://user-images.githubusercontent.com/20840228/218015043-3101c368-8f7a-483d-8c0d-2890fd43193f.png">

**Comment by mattseddon** [comment]
I would raise a bug in the DVC repository for that issue (data status doesn't respect dvcignore).

The badge reflects the number of items with a status. There are 5 items in the screenshot. How is the number 5 misleading?

**Comment by yathomasi** [comment]
> I would raise a bug in the DVC repository for that issue (data status doesn't respect dvcignore).

Yeah, it makes sense.

> The badge reflects the number of items with a status. There are 5 items in the screenshot. How is the number 5 misleading?

I am taking reference to how git changes are shown on vs code. It would generally look into the file changes, not the folder. So, here is a clear example showing the difference as it's 3 for git and 4 for DVC. 
Do we interpret it differently in DVC? That may be the case I could be unaware of.

<img width="399" alt="Screenshot 2023-02-10 at 12 02 28" src="https://user-images.githubusercontent.com/20840228/218017205-768a4af6-74c5-4ad1-9d99-8f33e0e14c65.png">

**Comment by mattseddon** [comment]
Ah, ok. The difference here is that Git does not actually track directories, only files. DVC can and does track directories so in the screenshot there are 3 untracked files that Git could track. There are 3 untracked files + 1 untracked directory (4 total items) that DVC could track. Does that make sense?
