### ISSUE TITLE
Revisit apply filters and auto apply filters descriptions/logic

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3265]
A follow up on this https://github.com/iterative/vscode-dvc/pull/1076 . Since a lot of things have changed since that time, we can now try to improve this.

## Motivation

Even after reading the discussion it was quite hard to understand the details of how these features behave. There was also a recent Slack discussion of a potential bug: 

<img width="813" alt="Screenshot 2023-02-10 at 8 48 18 AM" src="https://user-images.githubusercontent.com/3659196/218231965-bad750d1-053c-4c7c-ba66-8adfc17dd96d.png">

Some questions:

- Is it a toggle? How can I see it's current state?
- Why does it trigger this bug?
- It's very hard to understand w/o extensive docs and experiments what this option does

## Ideas

- Get rid of it and get back the experiments button (since we have space now). Since we have badges in the table, is it enough?
- Get rid and make a button / toggle in the ribbon panel.

One thing that come to my mind - we don't want an experiment to disappear w/o any notice after it's done because of filters.

Any other ideas - @aguschin @daavoo @dberenbaum (and VS Code team of course)?

**Comment by mattseddon** [comment]
The functionality is complicated. I will happily remove it. When used all of the experiments that are visible after filters have been applied will be auto-selected for plotting. Here is a demo of how it works:

https://user-images.githubusercontent.com/37993418/218340605-91861ae5-0239-45f0-a682-2b32f79b0d98.mov

If we were to keep the feature a better name might be `Auto-plot all displayed experiments (max 7)` or `Auto-plot all unfiltered experiments (max 7)`.

> Is it a toggle? How can I see it's current state?
> Why does it trigger this bug?

It would be a toggle if there were < 7 experiments selected by applying the filters. The behaviour shown is not a bug. This is the only way that we can respect the max selection of 7.

> One thing that come to my mind - we don't want an experiment to disappear w/o any notice after it's done because of filters.

This is a separate issue but this will happen if filters are applied and an experiment does not meet the criteria specified.

**Comment by dberenbaum** [comment]
If I understand the intent correctly, could the same thing be achieved from the experiments table by having a "select all" button/action somewhere?

**Comment by mattseddon** [comment]
The next steps are to:

1. Drop filter icon from view/title of experiments in favour of beaker (show experiments)
2. Drop auto-filter functionality
3. Add select all to experiments table

**Comment by shcheklein** [comment]
> Drop auto-filter functionality

One question to decide - do we show show experiments that are filtered (not visible in the experiments table) or do we disable them? (not sure it's directly related to this, at least not to auto logic). Just trying to get a complete picture here.

**Comment by shcheklein** [comment]
Closing this, I think we are good for now.
