### ISSUE TITLE
DVC trees do not update properly after adding a file

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3285]
In this repo https://github.com/iterative/iterative.ai

I'm trying to add file this way:

https://user-images.githubusercontent.com/3659196/218895696-4487e09d-982b-499d-978c-27cd32f4d34a.mov

and it updates both trees properly.

But if I do it this way (just a different location):

https://user-images.githubusercontent.com/3659196/218895986-b79ebf2a-cde7-4f64-8725-c16055d59e4c.mov

It updates files around to ignored which is nor correct as far as I understand?

I hit an issue before but can't reproduce when it was not updating the tree at all (only one new greyed out file added), no modifications visible.

**Comment by shcheklein** [comment]
Managed to reproduce the second scenario:


https://user-images.githubusercontent.com/3659196/218898539-fa32860a-a604-4b7e-acc4-ca7c79370c70.mov

**Comment by shcheklein** [comment]
Might be fixed, we need to try it again.

**Comment by mattseddon** [comment]
I have confirmed that this is fixed.
