### ISSUE TITLE
Commit action doesn't work in SCM tree

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3286]
This repo / Codespace: https://github.com/iterative/iterative.ai

https://user-images.githubusercontent.com/3659196/218896789-4d4c1d7d-cce7-4ec8-804c-6256661550a1.mov

More weird examples:

(after reloading the container, bad error message + we are not trying to repeat + it doesn't allow to do it again):

https://user-images.githubusercontent.com/3659196/218897342-b7a28527-b2db-457e-82bd-6522edfee1a0.mov

Finally, when it works, the message is "ERROR", but also a warning. Something about stage - it's all very scary and confusing (cc @dberenbaum )

https://user-images.githubusercontent.com/3659196/218898967-25226cfd-297d-482c-bdd4-9554949df4f9.mov

**Comment by shcheklein** [comment]
Make it p1 since it breaks the experience severely when we deal with blog.

**Comment by mattseddon** [comment]
What does `dvc data status --granular --unchanged --json` output under these circumstances?

**Comment by mattseddon** [comment]
@shcheklein, this should be fixed with the latest version. Please reopen if I have misunderstood or missed something 🙏🏻.
