### ISSUE TITLE
`scatter` plot doesn't render properly

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3335]
Following https://github.com/iterative/vscode-dvc-demo/pull/49, there should not be a `field` legend and all points should be regular (non-dashed) circles since there's only one field being plotted.

<img width="985" alt="Screenshot 2023-02-21 at 1 38 57 PM" src="https://user-images.githubusercontent.com/2308172/220431036-8cd17efc-44c1-4286-b1b5-974316da7d40.png">

Here's what it looks like in DVC CLI:

![visualization(33)](https://user-images.githubusercontent.com/2308172/220430842-38064652-d1be-4a59-92f2-24d91ea447ad.png)

And in Studio:

![visualization(34)](https://user-images.githubusercontent.com/2308172/220430903-9da0bd36-b0d1-4614-8ddf-34f3734067a8.png)

**Comment by mattseddon** [comment]
@dberenbaum this is what I am seeing:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/220780204-356bc9dd-6333-4776-a791-dd5861d68d5d.png">

Is your virtual environment up to date? I've got `dvc-render` 0.2.0 & `dvc`  2.45.1.... or maybe my templates are out of date?

**Comment by dberenbaum** [comment]
Sorry -- not sure how that plot was generated. Not able to reproduce now, so closing the issue.
