### ISSUE TITLE
VSCode-DVC only runs for dvc.yaml in root directory

### ISSUE THREAD

**Issue by legendof-selda** [iterative/vscode-dvc#3478]
The VSCode extension doesn't account for the experiments/pipelines which are not written in the root folder.

The setup I have is like this

```
- data/
- cml/
  - exp1
    - dvc.yaml
    - dvc.lock
    - metrics.yaml
  - exp2
     - dvc.yaml
    - dvc.lock
    - metrics.yaml
- src/
```

I this case, VScode doesn't detect the experiments inside the `cml/` directory and gives an error saying "the dvc.yaml is invalid"

Add an option or dropdown under "Run Experiments" where you can select the experiment you want to run.

Or we can have an interface somewhat similar to [Tests Extension](https://code.visualstudio.com/docs/python/testing) which will provide us a list of pipelines created along with the tests tracked inside it
![image](https://user-images.githubusercontent.com/44336699/225555633-72e19bdf-a103-4ab5-abb8-09c618190000.png)

**Comment by mattseddon** [comment]
@legendof-selda do you have to call `dvc exp run` with the `<targets` option from the CLI? What does `dvc exp show` produce in this project?

**Comment by legendof-selda** [comment]
Unfortunately I am not able to run `dvc exp run` due to open issue #8817

**Comment by mattseddon** [comment]
Does the extension correctly reflect what is shown in `exp show`?

**Comment by legendof-selda** [comment]
> Does the extension correctly reflect what is shown in `exp show`?

Yes it does!

**Comment by mattseddon** [comment]
@legendof-selda can you let us know exactly why you have your project setup like this? What is the use case? Thanks.

**Comment by shcheklein** [comment]
Closing this for now. @legendof-selda please, feel free to open it again and provide us a bit more context. Thank!
