### ISSUE TITLE
Display DAG as a nice chart

### ISSUE THREAD

**Issue by legendof-selda** [iterative/vscode-dvc#3485]
Display a nice DAG graph for each pipeline created to view them better perhaps using `dvc --mermaid` or `dvc --dot` output

**Comment by mattseddon** [comment]
@legendof-selda this is on the roadmap for Q2 but not prioritised at the moment.

In the meantime there is a live preview extension that you can use with `dvc dag` in the interim:

[tomoyukim.vscode-mermaid-editor](https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor)

Here is a demo of how you could put everything together:

https://user-images.githubusercontent.com/37993418/226212048-24d3c3a1-a31f-47f1-bfb0-55800f05021b.mov

**Comment by legendof-selda** [comment]
Hey, this is how I currently view my dag. Logged it here so it can be considered as a feature we can add as well as make it interactive so it can be connected with the dvc.lock file to see the hash its used, have timeline option to see how the dag has changed, etc.

**Comment by mattseddon** [comment]
For the record [bierner.markdown-mermaid](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) appears to be a better option as it "Adds [Mermaid](https://mermaid-js.github.io/mermaid/#/) diagram and flowchart support to VS Code's builtin Markdown preview and to Markdown cells in notebooks."

I think we will try and utilise this functionality soon.

**Comment by mattseddon** [comment]
This functionality will be available via the command palette in the next release. We will find some more places to make it available over the next few sprints.
