### ISSUE TITLE
Share to Studio: Include `experiment_rev` field.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#3486]
The post request doesn't include the [`experiment_rev` ](https://github.com/iterative/dvc-studio-client/blob/485b2d8baf056882f6c7cb59438208390a045998/src/dvc_studio_client/post_live_metrics.py#L88-L90) field:

https://github.com/iterative/vscode-dvc/blob/3c421346f0b699808a759e48bdeedfb8ad208eab/extension/src/patch.ts#L125-L132

Which is used by Studio for rendering (and, in the future, for matching against parsed experiment revisions):

The 2 experiments only displaying the name are from VSCode `Share to Studio` action:

<img width="590" alt="Captura de pantalla 2023-03-17 a las 13 23 46" src="https://user-images.githubusercontent.com/12677733/225903767-5a8ad636-50e6-48cf-abc6-19348bf2dfb9.png">

The `experiment_rev` should be the **full** SHA

**Comment by mattseddon** [comment]
Is this a new requirement or something that I missed?
