### ISSUE TITLE
Extend/Reuse `Custom Plots` for building `Top-Level` plots

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#3539]
I really like the existing UI for `Custom Plots` and it feels that it could be extended/reused to allow users to build custom [Top-Level](https://dvc.org/doc/command-reference/plots/show#multiple-data-series-plot) plots. 

The current UX for `Top-Level` plots requires manually editing the `dvc.yaml`, which requires understanding the syntax, and sometimes you would want to build the top-level plot on demand for exploration from a UI without having to serialize it in the dvc.yaml (i.e. this is how the MLFlow UI for compare works).

For example, the plots used in the `example-get-started`:

https://github.com/iterative/example-get-started/blob/471811e866f414ffa08c5acd9eed380ec5d165b1/dvc.yaml#L48-L66

Could be built from a context menu by selecting a `name`, `template`, `x`, and `y` sources.

For the `x` and `y` sources, VSCode should display all the existing columns in all existing plot files.

---

It would be nice to have feature to be able to serialize the definition of the generated top-level plot to the `dvc.yaml` file.

**Comment by shcheklein** [comment]
> For the x and y sources, VSCode should display all the existing columns in all existing plot files.

Should we allow selecting a source file as well, though? Even registering a source file can be tedious a bit.

**Comment by shcheklein** [comment]
The bottleneck here can become actually the code that generates those plot files, not the `dvc.yaml` update. How can we simplify getting those files?

**Comment by dberenbaum** [comment]
> The bottleneck here can become actually the code that generates those plot files, not the `dvc.yaml` update. How can we simplify getting those files?

We could add dvclive methods to dump tabular or hierarchical data to help here, but I think we could start with the lower-hanging fruit of assuming the user already has the data files (either from dvclive or manually generated) and wants to change how the plots look.

**Comment by mattseddon** [comment]
Would this kind of flow be useful for plots onboarding?:

1. Plot icon is shown in the UI when dvc.yaml is open
2. User prompted to pick a file when clicked (can pick any file)
3. User prompted to pick from a given list of templates
4. Extension attempts to parse data in the picked file
5. Extension tries to offer up options for x/y or template requirements
6. Modal shown warning that dvc.yaml will be updated (actually overwritten)
7. Extension writes dvc.yaml with new plot definition included.

E.g 

https://github.com/iterative/vscode-dvc/assets/37993418/1f6289d1-105d-4fa9-a8aa-f4dfb479a142

**Comment by daavoo** [comment]
> Would this kind of flow be useful for plots onboarding?:

Overall, looks good direction to me.
Also feels like steps 3 and forward could be reused for the original use case in this issue.

> 2. User prompted to pick a file when clicked (can pick any file)

Not sure how much it is from being a quick draft but:

- Should only allow files with supported extensions (https://dvc.org/doc/command-reference/plots#description)
- Should only allow files inside the DVC repo.

> 4. Extension attempts to parse data in the picked file

Do you use DVC for parsing? The expected format is somehow restricted for some cases like JSON

**Comment by mattseddon** [comment]
> Not sure how much it is from being a quick draft but:
> 
> * Should only allow files with supported extensions (https://dvc.org/doc/command-reference/plots#description)
> * Should only allow files inside the DVC repo.

It was a (very) quick draft but thanks for the heads up. I will add these criteria.

> Do you use DVC for parsing? The expected format is somehow restricted for some cases like JSON

I wasn't intending on using it. What command(s) could I use?

**Comment by dberenbaum** [comment]
> > Do you use DVC for parsing? The expected format is somehow restricted for some cases like JSON
> 
> I wasn't intending on using it. What command(s) could I use?

I think the expected format is described in https://dvc.org/doc/command-reference/plots/show#example-hierarchical-data. 

Is this still being worked on?

**Comment by julieg18** [comment]
> Is this still being worked on?

Yes, working on a first iteration now!
