### ISSUE TITLE
Clean up Experiments Table SCSS

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#3597]
As discussed in the retro, when working on #3591 I noticed that the `scss` associated with the experiments table has organically grown unruly.

<p align=center>
<img src=https://user-images.githubusercontent.com/37993418/229031339-75a58389-bf62-4404-a360-769e9ff3def7.png width=500 />
</p>

We should take a few hours to clean up `webview/src/experiments/components/table/styles.module.scss`. 

We should also spend some investigating linters. E.g 
- https://stylelint.io/
- https://www.npmjs.com/package/stylelint-scss
- https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint

**Comment by sroy3** [comment]
I was thinking about this and I think that the main problem is that we are using CSS modules, but our stylesheets aren't modular enough. We basically have one big module per webview. If we were to create a stylesheet (module) per component or per component group (table head, table body...). That way, we can see much more easily what styles are used / unused, overwritten, and know exactly where to find them. @julieg18 I think you already did a great job in cleaning up everything and especially grouping stuff. If we decide to move things to their own module, that'll streamline thing a lot. I guess we can talk about this in the next retro, or just start slowly moving things.
