### ISSUE TITLE
Allow to create `Custom Plots` even without DVC plots.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#3611]
If I have a repo with `metrics` and `params`, I would like to be able to create `Custom Plots` even if I don't have any "regular" DVC plots in the repo.

I can see the `Experiments` table but I can't create `Custom Plots` because the `Plots` panel displays:

<img width="1394" alt="Captura de pantalla 2023-04-03 a las 11 47 14" src="https://user-images.githubusercontent.com/12677733/229474706-28d44b37-14de-4ebf-a9b2-e97b3a1e770d.png">

Without giving me the option to create a `Custom Plot` from the metrics and params in the table.

**Comment by julieg18** [comment]
Mentioned in #3373 and being worked on in #3523!
