### ISSUE TITLE
Headers DnD is broken for groups

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3679]
There is a weird behavior happening with DnD of a header group:

https://user-images.githubusercontent.com/3659196/231642331-97c87e0a-391a-4448-be32-3bc75b6afbcd.mov

It's happening since react table's `leafColumnIds` always returns all children for the group no matter how this group is split. And we use this to determine what exactly we are moving around and when we are landing things: 

```js
    if (displacerHeader) {
      draggingIds.current = leafColumnIds(displacerHeader)
      fullColumnOrder.current = allColumns.map(({ id }) => id)
    }
```

```js
      const leafs = leafColumnIds(displacedHeader)
      newOrder = reorderColumnIds(fullOrder, displacer, leafs)
```

```js
export const leafColumnIds = (
  header: Header<Experiment, unknown>
): string[] => {
  return header.column.getLeafColumns().map(col => col.id)
}
```

It leads to different weird behavior.

I'm not sure if this is a regression from the react table migration (@sroy3 ), or it was always the case (`header.column.getLeafColumns()` always returns the full list of, no matter the order in the table). I haven't had time to look yet, but will try to fix it. @sroy3 if you know something about this from the top of your head - please let me know.

**Comment by shcheklein** [comment]
Something like this seems to be working better, but not quite yet (anyways, I think it's the right way to do this - use `getLeafHeaders` vs `getLeafColumns`).

```js
export const leafColumnIds = (
  header: Header<Experiment, unknown>
): string[] => {
  return header.getLeafHeaders().map(header => header.column.id)
}
```

**Comment by sroy3** [comment]
It's highly possible that it was broken by the react-table upgrade. The function was changed a little to be simpler (https://github.com/iterative/vscode-dvc/pull/3095/files#diff-6763d308e659bd641c34eddce054279f375eac5f68986af441b5f761a7d957b0R37), but if I remember right, I tried getting the same output as before so it could have been broken for a while as well. I just tried `getLeafHeaders` and it seems to work fine. Hopefully no breaking changes in the future for the table, but a test for this case will be highly welcomed so that we don't break it again.

**Comment by shcheklein** [comment]
@sroy3 `getLeafHeaders()` still returns some strange values to me. I'm looking into this, but it doesn't work out of the box for me. It returns something like this:

`metrics:evaluation/metrics.json:best_test_loss,metrics:evaluation/metrics.json:best_test_loss,metrics:evaluation/metrics.json`

(note three IDs, one of them is a duplicate, second one is top-level)

**Comment by sroy3** [comment]
Maybe it does need to be recursive after all (might not be out of the box from react-table as previously though). We could return something like `return header.subheaders.length ? header.subheaders.map(h => recursiveCall(h)) : header.id`.
