### ISSUE TITLE
Improve project's CSS 

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#3760]
- [x] Add stylelint into pre-commit hook (webview/.lintstagedrc.js)
- [x] Enable `stylelint` `camelCase` selector rules (https://github.com/iterative/vscode-dvc/pull/3736#discussion_r1174131527)
- [ ] Move `stylelint` packages into `webview/node_modules` instead of the root `/node_modules` (https://github.com/iterative/vscode-dvc/pull/3736#discussion_r1176801423)
- [ ] ~Remove `table/styles` disabled comments (https://github.com/iterative/vscode-dvc/pull/3736#discussion_r1174127415)~ - won't do

Followup to #3736

**Comment by julieg18** [comment]
> Follow up on this: https://github.com/iterative/vscode-dvc/pull/3736#discussion_r1176801423

Yes, that's the second item on our task list, "Move stylelint packages into webview/node_modules instead of the root /node_modules". Though I see I've pasted the wrong comment link, I'll update it. 

> Add stylelint into pre-commit hook (webview/.lintstagedrc.js)

Good idea!

**Comment by mattseddon** [comment]
I actually meant this:

> I tried to install stylelint packages inside of webview via the stylelint.stylelintPath config option, but stylelint kept getting installed inside the root for some reason, even after moving packages inside of webview/package.json, deleting node_modules, and starting out of a fresh install. I even tried to revert yarn.lock to a previous commit and fresh install the packages but stylelint still appeared inside of /node_modules instead of /webview/node_modules. Kept the packages installed in the root for now but can revisit this later

**Comment by julieg18** [comment]
> I actually meant this:
> 
> > I tried to install stylelint packages inside of webview via the stylelint.stylelintPath config option, but stylelint kept getting installed inside the root for some reason, even after moving packages inside of webview/package.json, deleting node_modules, and starting out of a fresh install. I even tried to revert yarn.lock to a previous commit and fresh install the packages but stylelint still appeared inside of /node_modules instead of /webview/node_modules. Kept the packages installed in the root for now but can revisit this later

...Yes, that is the exact comment I'm referring too 🤔 The packages should be installed inside of `/webview` instead of the root since they're only used in the `webview` but I was having issues moving them... Is there something I'm misunderstanding?

**Comment by julieg18** [comment]
> I got as far as 

> > Yes, that's the second item on our task list

Whoops! I think it was the second item at the time when I wrote the comment... Or I just made a type 😄
