### ISSUE TITLE
push: only allow pushing completed experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3806]
The extension allows me to push experiments that are still running:

<img width="344" alt="Screenshot 2023-05-02 at 2 55 45 PM" src="https://user-images.githubusercontent.com/2308172/235761611-bdde43c0-0ceb-46aa-b2bc-bfe42ba863b1.png">

This will fail because the experiment commit has not yet been generated. Can we disable pushing for experiments unless they have successfully completed?

**Comment by mattseddon** [comment]
This was an accident and not a conscious decision. Thanks for raising. Will be fixed in the next release.
