### ISSUE TITLE
File Watcher watches home directory when DVC is enabled

### ISSUE THREAD

**Issue by david-waterworth** [iterative/vscode-dvc#3816]
I've been having issues with vscode reporting `Unable to watch for file changes in this large workspace folder. Please follow the instructions link to resolve this issue.` and it only seems to occur after I enable DVC.

I disabled all addons, then used https://github.com/microsoft/vscode/wiki/File-Watcher-Issues to diagnose.

When I enabled DVC, I initially see

``` console
TRACE [File Watcher (parcel)] Request to start watching: /home/david/.config/dvc
TRACE [File Watcher (parcel)] Started watching: '/home/david/.config/dvc' with backend 'inotify'
```
It's then followed by

``` console
TRACE [File Watcher (parcel)] Request to start watching: /home/david 
```

which then (not unexpectedly) produces the error

``` console
ERR [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /home/david)
```

I'm not 100% sure DVC is doing this, but it only happens after DVC is enabled so its the most likely cause.

Also, this is a git repository that is not enabled for DVC tracking. I have in the past seen other DVC error messages that imply that it seems to walk up from the current workspace to my home folder if the current workspace is not tracked by DVC. As a workaround I've disabled the DVC addon for this workspace.

**Comment by mattseddon** [comment]
Hi @david-waterworth,

Thanks for reporting. Hopefully we can get this fixed ASAP.

We did intentionally start watching `$HOME/.config/dvc` so that we can provide updates when the global config has been changed. However, we are not intentionally watching the `$HOME` directory. 

Is a path returned if you run `dvc root` in the aforementioned Git folder or do you see `ERROR: you are not inside of a DVC repository (checked up to mount point '/')`? By any chance have you inadvertently/purposefully added a `.dvc` folder under `$HOME`? 

Thanks,
Matt

**Comment by david-waterworth** [comment]
Hi @mattseddon 

Yes I do have a `.dvc` folder in `$HOME` - I created it a while back when I was thinking I wanted to share the dvc cache between projects. Since then I've migrated back to the standard setup but haven't deleted `~\.dvc`. I'm not at my PC now but tomorrow I'll see if removing it fixes the issue.

`dvc root` returns `../..` in this case.

**Comment by mattseddon** [comment]
I'm pretty sure that under these circumstances the extension will identify itself as being inside a DVC monorepo. It then (mistakenly) will try to watch the entire folder. LMK whether or not that change fixes the issue. We can investigate further if needed.

**Comment by david-waterworth** [comment]
Thanks @mattseddon, removing the `.dvc` folder in my `$HOME` folder results in dvc root returning

```console
ERROR: you are not inside of a DVC repository (checked up to mount point '/home')
```

Since then I've not seen it attempt to add a watch to `$HOME`

**Comment by mattseddon** [comment]
👍🏻 I think we're good to close this now. 

Please let us know if have any feedback on the extension or feel like there are missing features 🙏🏻.
