### ISSUE TITLE
sharing: bring back sharing via studio api

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3820]
Thanks for all the great work on #3574 and #3781 to consolidate the sharing actions and make them all rely on `dvc exp push`, but I may have pushed it too far 😬 . Maybe it makes sense to keep two sharing actions like:

1. Push to share full experiment (`dvc exp push`)
2. Share metrics/experiment summary (studio api)

Reasons:
1. Pushing the full experiment takes too long when pushing to the dvc remote and isn't always needed. We could have another option to push only the Git ref, but what's the benefit over the lighter studio api?
2. Live sharing from anywhere. Now, you can only use live sharing in the extension if you have pipelines and run experiments through the extension. Since the extension collects all the info for each experiment as it runs, it could auto-share experiments run from notebooks or elsewhere outside the extension.
3. Sharing any experiment anytime. Now, you can only share via the studio api by checking a box globally before running experiments. Again, since the extension already collects all the needed info, users could choose individual experiments and choose to share before, during, or after it runs.

**Comment by dberenbaum** [comment]
@mattseddon @shcheklein @daavoo Would be great to hear your thoughts (and others).

**Comment by mattseddon** [comment]
> Pushing the full experiment takes too long when pushing to the dvc remote and isn't always needed. We could have another option to push only the Git ref, but what's the benefit over the lighter studio API?

The benefit is that the Git remote isn't out of sync with Studio. We could bring the `--no-cache` option in but I think we should avoid that because we are trying to help users with reproducibility (the same reason Thoughtworks moved DVC to adopt). Information (data) that is only available locally for one team member does not make an experiment reproducible for the team.

> Live sharing from anywhere. Now, you can only use live sharing in the extension if you have pipelines and run experiments through the extension. Since the extension collects all the info for each experiment as it runs, it could auto-share experiments run from notebooks or elsewhere outside the extension.

Is this really needed? Is the hypothesis that users will come with a notebook and try to connect to Studio straight away? I would assume that it is more likely they would investigate that route after they've graduated to pipelines and don't we want to nudge users in that direction?

> Sharing any experiment anytime. Now, you can only share via the studio api by checking a box globally before running experiments. Again, since the extension already collects all the needed info, users could choose individual experiments and choose to share before, during, or after it runs.

I think this will cause the same issues as the first point but if it is important why wouldn't this be available via the CLI?

I also think that we need to take into account the cognitive load that we'll be adding to the UX. They will have to juggle which option to use and when, whether or not they need to later update a "partially shared" experiment. How to tell whether or not an experiment is partially shared. 

Maybe we will need to implement this functionality in the future but I do not think we should rush into throwing the kitchen sink at the experience until we get some user feedback.

**Comment by shcheklein** [comment]
(just to explore this a bit and brainstorm)

>  but what's the benefit over the lighter studio api?

I think to have at least one type of workflow. Having two types of experiments in Studio is also not very good to be honest. It will be hard to explain to users I'm afraid.

> Live sharing from anywhere. 

Like sharing even from a different language (not Python) as an extreme example? Sounds like a good scenario, doesn't feel like a major item to me to prioritize now. Or do you mean even sharing things that are not even DVCLive instrumented?

> to share before

what does it mean? could you clarify please?

**Comment by dberenbaum** [comment]
@mattseddon 

> The benefit is that the Git remote isn't out of sync with Studio. We could bring the `--no-cache` option in but I think we should avoid that because we are trying to help users with reproducibility (the same reason Thoughtworks moved DVC to adopt). Information (data) that is only available locally for one team member does not make an experiment reproducible for the team.

Agreed, but IMO that's how we differentiate -- studio api for typical experiment tracking/visibility, exp push for full experiment sharing/reproducibility.

> Is this really needed? Is the hypothesis that users will come with a notebook and try to connect to Studio straight away? I would assume that it is more likely they would investigate that route after they've graduated to pipelines and don't we want to nudge users in that direction?

We have increasing evidence that users are happy to use dvc experiment tracking from notebooks and pipelines aren't always a next step. We even have users who already have pipelines say they want to use the dvclive experiments for when they do more lightweight exploration.

> I think this will cause the same issues as the first point but if it is important why wouldn't this be available via the CLI?

It probably should be, but it just feels like a better workflow in VS Code, so I decided to start here. It's harder for me to imagine how to do this from the CLI, but open to ideas.

**Comment by dberenbaum** [comment]
@shcheklein 

> I think to have at least one type of workflow. Having two types of experiments in Studio is also not very good to be honest. It will be hard to explain to users I'm afraid.

👍 Need to keep thinking about this. My worry is that the studio api, which IMO is more obvious/intuitive/expected way to share, feels more hidden and less flexible. Exp push is more powerful and unique to us but has a steeper learning curve, more setup/moving pieces, and is slower.

> Like sharing even from a different language (not Python) as an extreme example? Sounds like a good scenario, doesn't feel like a major item to me to prioritize now. Or do you mean even sharing things that are not even DVCLive instrumented?

I mostly mean from notebooks or python scripts without pipelines. Agree those others don't feel like major priorities to me. This issue partly came from setting up live sharing in a notebook and realizing how awkward it is in the extension (I already saved my token, but now I have to get it again and manually set an env var in my notebook).

> > to share before
> 
> what does it mean? could you clarify please?

I partly wrote that just because it sounded good, but I think it sort of makes sense 😄. For a queued experiment, we could mark ahead of time that we want to share it and then it would be shared once it starts.

**Comment by daavoo** [comment]
> My worry is that the studio api, which IMO is more obvious/intuitive/expected way to share, feels more hidden and less flexible. Exp push is more powerful and unique to us but has a steeper learning curve, more setup/moving pieces, and is slower.

I feel like I am missing the reasons behind the descriptions of each option.

IMO, studio API for _completed_ experiments could/should be replaced by `exp push --no-cache` in a totally transparent way for users. How would people notice that we are pushing a git ref vs a POST request.

The reason we don't currently follow this approach is that, during the early implementations of live experiments, there was a pushback against adding support for git refs in Studio (as it was not prioritized at that time and Studio backend estimated that it would introduce significant overhead).
