### ISSUE TITLE
The `.dvc` folder remains when switch between branches with DVC plugin enabled 

### ISSUE THREAD

**Issue by ZhiliangWu** [iterative/vscode-dvc#3841]
DVC version: `2.56.0`
DVC extension version: `0.8.7`

Two different `.dvc` projects are created, one in the root directory (branch `data`) and the other in a subdirectory (branch `main`). They remain independent with each other. The `main` branch is used for `raw` data, while the `data` branch is to save only processed data.

When I switch between them in command line, everything works fine. However, when I open the project with VS Code and DVC plugin enabled, the switch between them would cause troubles stated in the title. I.e., the `.dvc` folder remains (or is copied) when I switch to the other branch. When I want to switch back, I have to use `git switch -f main` to force remove the `.dvc` folder in the subdirectory.

Steps to recreate:
* Prepare a git-initialized directory
```console
$ tree dvc-plugin
dvc-plugin
├── .git
└── raw
```
with the following commands
```console
$ mkdir dvc-plugin
$ cd dvc-plugin
$ git init
$ mkdir raw
```
* Initialize DVC in the `main` branch within a subdirectory and commit the changes
```console
$ cd raw
$ dvc init --subdir
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
$ git add .
$ git commit -m "Initial commit"

```

* Initialize DVC in the `data` branch within the root folder
```console
$ cd ..
# Now within the root folder
$ git switch --orphan data
Switched to a new branch 'data'
$ rm -r raw
$ dvc init
Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
$ git commit -m "Initial commit for the data branch"

```
* To this end, the switch between `data` and `main` has no problems. 
* Meanwhile, if we use VS Code to open the project with DVC plugin enabled, the problems occur. E.g., when switching from the `data` branch to the `main` branch, we have 

```
$ git switch main
Switched to branch 'main'
$ git status     
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dvc/

nothing added to commit but untracked files present (use "git add" to track)
$ git switch data
error: The following untracked working tree files would be overwritten by checkout:
        .dvc/.gitignore
Please move or remove them before you switch branches.
Aborting
```
* When the DVC plugin is disabled, everything works as expected.

**Comment by sroy3** [comment]
> Thanks for your quick reply @sroy3.
> 
> > I do not think you meant to create the `.dvc` directory in different location on each of your branch.
> 
> I do mean to create the `.dvc` directory in different locations on different branches. I want different branches to be independent with each other, where I explicitly used `git switch --orphan`.
> 

In that case, you can add the directory in your repo for each branch. That might cause some conflicts down the line when merging, but I guess you'll know how to handle this. If you really do not need to track the directory, you could also add it to your `.gitignore` file. Out of curiosity, what is the use case of creating a different `.dvc` for each branch?

> > By the way, the reason it works fine without the extension enabled, is that the extension uses the directory which creates untracked changes in your repository.
> 
> Can you elaborate on this a bit? I didn't quite get it but sounds very interesting to understand the issue.

The `.dvc` folder is where DVC stores its cache and temporary files. When running an experiment, displaying plots, or doing other DVC actions, files in that directory will change.

**Comment by ZhiliangWu** [comment]
> Out of curiosity, what is the use case of creating a different `.dvc` for each branch?

I don't plan to merge these two branches. The use case is that I want to set up a monorepo, where the raw data is saved in the `main` branch and the processed data are saved in the `data` branch. With that, I can work on code for pre-processing the raw data in the `main` branch while save the processed data in the `data` branch. Since I used `git switch --orphan`, the `data` branch would not contain any code but only the processed data. Does that make sense to you?

> The `.dvc` folder is where DVC stores its cache and temporary files.

Do you mean that the VS Code extension will cache the `.dvc` in all subdirectories? Even it is removed by `git switch`, it will still be copied to another branch so that the extension could continue to work?

**Comment by mattseddon** [comment]
I have followed the provided steps. The issue is not caused by the extension but by DVC itself. Running `dvc data status --granular --unchanged --json` on the `data` branch causes the `.dvc` folder to be checked out with `main`:


https://user-images.githubusercontent.com/37993418/236960294-d6019260-c663-4a73-b585-293ce902c47b.mov



However, 

> The use case is that I want to set up a monorepo, where the raw data is saved in the main branch and the processed data are saved in the data branch. With that, I can work on code for pre-processing the raw data in the main branch while save the processed data in the data branch. Since I used git switch --orphan, the data branch would not contain any code but only the processed data. Does that make sense to you?

The code used to create the data should be versioned (saved) alongside that data. If you separate the code and data into disparate branches and DVC projects then you are essentially removing the link between the two and limiting DVC's ability to help you with reproducibility.

Take a read of the following from [basic uses of DVC](https://dvc.org/doc/use-cases#basic-uses-of-dvc):

-----

If you store and process data files or datasets to produce other data or machine learning models, and you want to

- track and save data and machine learning models the same way you capture code;
- create and switch between [versions of data and ML models](https://dvc.org/doc/use-cases/versioning-data-and-models) easily;
- understand how datasets and ML artifacts were built in the first place;
- compare model metrics among experiments;
- adopt engineering tools and best practices in data science projects;

DVC is for you!

----

I do not think that DVC is set up to correctly support this use case but I could be wrong. What do you hope to gain by separating out your code and data into disparate/divergent branches and projects? 

Maybe try checking out [this tutorial](https://dvc.org/doc/use-cases/versioning-data-and-models/tutorial).

**Comment by skshetry** [comment]
Looks like a bug to me, we should not create .gitignore for a repository that’s not there.

**Comment by mattseddon** [comment]
Raised https://github.com/iterative/dvc/issues/9426

**Comment by ZhiliangWu** [comment]
Thanks for your investigation. @mattseddon 

> I do not think that DVC is set up to correctly support this use case but I could be wrong. What do you hope to gain by separating out your code and data into disparate/divergent branches and projects?

The main use case here is to build a data registry, where non-main branches keeps different versions of pre-processed data. E.g., the same raw data needs to be pre-process differently to be consumed by different model APIs (PyTorch vs. sklearn).

Separating the data into an independent branch allows pulling (`dvc import`) only the data from that branch without the code. As stated above, this would be helpful when I want to keep differently pre-processed data in different branches. And this would not lose the link between the code and the data if I include the commit ID of the `main` branch when I update the `data` branch. The data push and committing step is automated by CI jobs. 

WDYT?

**Comment by shcheklein** [comment]
@ZhiliangWu from the top of my head it should be fine, but what would be the difference of creating a second "data-registry" repository? My personal experience it's a bit unusual to have two completely non-overlapping branches in terms of their code, etc. 

> if I include the commit ID of the main branch when I update the data branch. 

could you clarify this please?

**Comment by ZhiliangWu** [comment]
> but what would be the difference of creating a second "data-registry" repository?

Both should work, and eventually it might be a matter of design choice. I feel it looks cleaner, if I keep raw data and differently pre-processed data in a single registry. I.e., `main` branch for raw data; `data-pytorch` branch for pre-processed data which can be consumed directly by PyTorch; `data-sklearn` branch for pre-processed data ready to be consumed directly by sklearn API; .... 

> could you clarify this please?

In the `main` branch, one can include the code for pre-processing the data for different model APIs. Pre-processing the raw data, saving to the remote storage, and push to `data-*` branches are done through respective CI jobs. At the end of the CI job, one can use the commit ID of the `main` branch for the data pre-processing code as the commit message. I.e., for a bunch of `.dvc` files, they will be committed with the message such as `main@1234abc`. With that, one can link which code is used to generate this data. Does that make sense to you?

**Comment by shcheklein** [comment]
@ZhiliangWu thanks for giving more color to this.

> With that, one can link which code is used to generate this data. Does that make sense to you? @shcheklein

Makes sense. I think you can also use the `dvc import` command to track the source of data in the API branches. It should be cleaner I think.

>  I.e., main branch for raw data; data-pytorch branch for pre-processed data which can be consumed directly by PyTorch; data-sklearn branch for pre-processed data ready to be consumed directly by sklearn API;

It can be done this way. Or you can still keep everything in one branch, create directories to keep `data-pytorch`, etc. And merge commits via CI/CD into that main branch.

Even if you keep multiple branches, you can merge main into them before running the preprocessing. This way you would also have data in them and the code that corresponds to the data that was produced.

I hope that makes sense.

**Comment by mattseddon** [comment]
The underlying issue relating to the OP can be tracked at https://github.com/iterative/dvc/issues/9426. Thanks for raising.
