### ISSUE TITLE
Simplify Studio onboarding screen and workflow

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3864]
Two things that I found recently trying it:

Related https://github.com/iterative/vscode-dvc/issues/3434

- [x] I think we should have a single button Get Token (Studio can redirect to the right page, and even if doesn't now I think we should be fine for now). @iterative/studio-frontend can Studio redirect now? What is the complexity of this? To clarify - if I sign up I want it to immediately open the page with my token. We next need to think about also creating a project automatically or semi-automatically since we know the repo URL potentially and can pass it in the studio URL.
- [ ] If an ENV variable with a token detect we need to at least say something about it. ENV var in Codespaces is enough to log metrics actually, and some options on this page can contradict with it. E.g. should we show that checkbox enabled it token ENV var is found and if ppl disable it then unset the env?
- [x] After https://github.com/iterative/dvc/pull/9433, live sharing will be enabled by default when the studio token is saved to the dvc config, although it can be disabled with studio.offline = true. To comply with this, we need to make the "Share new experiments live" checkbox correspond to the studio.offline config value and stop setting the environment variable.

<img width="1248" alt="Screenshot 2023-05-10 at 10 48 22 AM" src="https://github.com/iterative/vscode-dvc/assets/3659196/fb0b0389-f1ea-4d00-aed6-c9fbbca7a880">

**Comment by mattseddon** [comment]
The first item is covered by the last item in https://github.com/iterative/vscode-dvc/issues/3574.

> Drop the sign-in button from Studio setup page (https://github.com/iterative/vscode-dvc/issues/3574#issuecomment-1513949115 - related to https://github.com/iterative/studio/issues/5715)

The Studio issue for frontend redirects is https://github.com/iterative/studio/issues/5715.

We can remove the original action item from https://github.com/iterative/vscode-dvc/issues/3574 if you like.

**Comment by shcheklein** [comment]
@mattseddon thanks, yep. Dropped it in that ticket (making it closer to close that one).

**Comment by dberenbaum** [comment]
> I think we should have a single button Get Token (Studio can redirect to the right page, and even if doesn't now I think we should be fine for now). 

👍 

> @iterative/studio-frontend can Studio redirect now? What is the complexity of this? To clarify - if I sign up I want it to immediately open the page with my token. We next need to think about also creating a project automatically or semi-automatically since we know the repo URL potentially and can pass it in the studio URL.

Should we first focus on the part about creating a project? If it's about onboarding, I think first priority needs to be to create the project and token only matters after that.

**Comment by dberenbaum** [comment]
From #3898:

> After https://github.com/iterative/dvc/pull/9433, live sharing will be enabled by default when the studio token is saved to the dvc config, although it can be disabled with studio.offline = true. To comply with this, we need to make the "Share new experiments live" checkbox correspond to the studio.offline config value and stop setting the environment variable.

**Comment by mattseddon** [comment]
>  ENV var in Codespaces is enough to log metrics actually, and some options on this page can contradict with it. E.g. should we show that checkbox enabled it token ENV var is found and if ppl disable it then unset the env?

@shcheklein do you mean you can set an environment variable when starting codespaces which will log metrics to Studio if any experiments are run through the extension?

**Comment by shcheklein** [comment]
> @shcheklein do you mean you can set an environment variable when starting codespaces which will log metrics to Studio if any experiments are run through the extension?

Yes, exactly.

**Comment by mattseddon** [comment]
> > @shcheklein do you mean you can set an environment variable when starting codespaces which will log metrics to Studio if any experiments are run through the extension?
> 
> Yes, exactly.

This seems like a strange/advanced use case now that the token is managed via a user's DVC config(s). I think the smartest thing to do would be to block it off and remove `STUDIO_TOKEN` from the environment variables we pass to a new process.

**Comment by shcheklein** [comment]
> This seems like a strange/advanced use case now that the token is managed via a user's DVC config(s).

Yes, agreed.

> I think the smartest thing to do would be to block it off and remove STUDIO_TOKEN from the environment variables we pass to a new process.

Hmm, sounds like too magical and a bit too intrusive to me. How about we show a message if it's detected (in the Setup screen) or as a notification?

**Comment by mattseddon** [comment]
> Hmm, sounds like too magical and a bit too intrusive to me. How about we show a message if it's detected (in the Setup screen) or as a notification?

There is only a passing reference in the docs to using the token in the way that we are discussing:

- https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots#provide-access-token-to-experiment
- https://dvc.org/doc/user-guide/project-structure/configuration#studio

I feel like it is more magical that it actually works and that we don't need to come up with a workaround to cater for this edge case.

**Comment by shcheklein** [comment]
It's still a valid setup (otherwise we would have deprecated it). I agree though that it's a minor / advanced and we can deprioritize it. (I would not ignore / remove the env variable though, let's user do what they want).

**Comment by julieg18** [comment]
Studio has implemented a way to get a token with Device Authentication (see https://github.com/iterative/studio/issues/5158#issuecomment-1772610546). I'll start looking into using the method out in VSCode.

**Comment by julieg18** [comment]
Researched how other extensions handled authentication like this and posted findings in Studio (https://github.com/iterative/studio/issues/5158#issuecomment-1783088262). TLDR is that with the current flow, two issues I noticed were that we need to repeatedly poll a studio endpoint for a token and the user doesn't get redirected back to vscode after authentication. 

I also created a quick demo of how things would work with the current Studio flow:

https://github.com/iterative/vscode-dvc/assets/43496356/c72fbbdc-e2e6-471a-821a-3ae03010bd12

We could either keep working on this and push a first iteration with the current Studio flow, or hold off until we have another iteration on Studio's auth flow. Personally, I think the current flow is good enough to release, but what does everyone else think? cc @shcheklein 

Either way, I'll keep working on the pr, since a good chunk of the logic should stay the same.

**Comment by julieg18** [comment]
With https://github.com/iterative/vscode-dvc/pull/4931 merged, we now use studio's auth flow in VSCode! What's left:

- [ ] Add some kind of sign (probably just a loading screen) to the Studio section when were fetching the token after the user has authorized (https://github.com/iterative/vscode-dvc/pull/4931#issuecomment-1804564653)
- [ ] Confirm that authentication flow works in different environments (Codespaces and windows come to mind)
- [ ] Test and update once [studio#8227](https://github.com/iterative/studio/pull/8227) has been merged

**Comment by julieg18** [comment]
Going to close this since all tasks have been done, minus this: 

>  If an ENV variable with a token detect we need to at least say something about it. ENV var in Codespaces is enough to log metrics actually, and some options on this page can contradict with it. E.g. should we show that checkbox enabled it token ENV var is found and if ppl disable it then unset the env?

As discussed synchronously, it is extremely difficult for the extension not detect ENV variables.
