### ISSUE TITLE
Multicolor plots cannot be nicely displayed

### ISSUE THREAD

**Issue by temper3** [iterative/vscode-dvc#3869]
Hello! 😁 

I am currently trying to create a plot with `Live.log_plot`, which has multiple traces for different labels.  Currently custom template is

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "mark": {
        "type": "line",
        "point": {
            "filled": false,
            "fill": "white"
        },
        "tooltip": {
            "content": "data"
        }
    },
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative"
        },
        "y": {
            "field": "<DVC_METRIC_Y>",
            "type": "quantitative",
            "scale": {
                "domain": [
                    0,
                    1
                ]
            }
        },
        "color": {
            "field": "color",
            "type": "nominal"
        }
    },
    "autosize": "pad"
}
```

This works neatly for displaying the plot in normal html if I add the label as a field `color` in each entry of `Live.log_plot:datapoints`; however, the Visual Studio Code extension seems to overwrite the color. So essentially, my question is: how would you best display a line-plot with multiple traces per experiment (~12) in the VS Code extension? Different stroke lengths are essentially indiscernible.

**Comment by shcheklein** [comment]
@temper3 qq - do you want to show multiple experiments on the same plot thought (like 24 lines if 2 experiments are selected). If not, I would recommend looking into `facet`-ed template (e.g. https://github.com/iterative/dvc-render/blob/main/src/dvc_render/vega_templates.py#L191 ). Those templates are not modified and will look like you define them. If you select multiple experiments you will see multiple plots side-by-side. 

Would that work for you? Could you try please (or let me know, I can try to hack something together).

**Comment by mattseddon** [comment]
@temper3 did you get a chance to try the above suggestion? How did you go?

**Comment by shcheklein** [comment]
Hey @temper3 , I'm closing since we were not able to get more feedback. But please feel free to reopen it if you still have this issue / question.
