### ISSUE TITLE
Table context menu show plots when single item is selected 

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#3875]
https://github.com/iterative/vscode-dvc/assets/3659196/0ea0b099-bbb0-4d32-ae81-0a605e77c49f

+ at then when you click ESC to hide the context menu it disables all checkboxes. I think it's too aggressive. I would disable ESC on checkboxes at all (not sure if some other products do this?)

**Comment by mattseddon** [comment]
Plot/Plot and Show are for multi-select purposes only. IIRC the reason for this implementation was that if you want to plot a single experiment you can simply click on the radio button.

**Comment by mattseddon** [comment]
FWIW Plot/Plot and Show are also not additive, they unselect all other experiments. E.g:


https://github.com/iterative/vscode-dvc/assets/37993418/2915de06-c4d0-4605-96bf-d26ea96380cd

Behaviour was under discussion in https://github.com/iterative/vscode-dvc/issues/2539 (ticket is very likely stale now)

**Comment by shcheklein** [comment]
Okay, I see that it's a duplicate pretty much. I agree with everything in the #2539. Current behavior feels not intuitive to me. I'll add items to that ticket.

**Comment by shcheklein** [comment]
Closing in favor of #2539, updated it a bit.
