### ISSUE TITLE
DVC extension's setup picking up wrong version of DVC from a wrong env 

### ISSUE THREAD

**Issue by erykml** [iterative/vscode-dvc#3878]
Hi! 

I encountered a weird issue while working with the extension. I wanted to see the setup prompts that help new users set up an experiment. 

First, I created a new project (no git, no dvc, new conda env with no libraries installed). I opened the extension. You can see the screenshot below. 

<img width="1945" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/ff5262c7-625a-4d11-9fac-872e8d1f3de0">

It picked up the DVC version from the base env, even though I used the select interpreter command from the prompt on the screen (next to configure option).

Then I removed all DVC libraries from the base environment. I checked again, and now it seems to be picking it up from somewhere else. You can see below that DVC is not installed (in the terminal output) but it is still picking something up.

<img width="1949" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/b2d6bbb3-c40a-4a53-8100-27dd7ed2a984">

For reference, I am using the following version of the extension: v0.8.11

**Comment by mattseddon** [comment]
@erykml how did you create the `dvc_blank` environment? And how did you install/uninstall `DVC` (via pip or conda?).

This should be the command that is being run to try and locate `DVC`:

![image](https://github.com/iterative/vscode-dvc/assets/37993418/fc57bbaa-07de-46ef-8cc8-c5d44fccd4c3)

If you deactivate all of your conda/pip environments and run `/opt/homebrew/Caskroom/miniforge/base/envs/dvc_blank/bin/python -m dvc doctor` what result do you get? 

Can you isolate where you have version `2.33.0` installed?

**Comment by erykml** [comment]
Hi @mattseddon 

1. I created `dvc_blank` using conda.
2. I uninstalled them using pip.
3. After deactivating the env (so being in the base one), once I run the command you sent I get: 
`/opt/homebrew/Caskroom/miniforge/base/envs/dvc_blank/bin/python: No module named dvc`
4. It might be in one of the multiple conda env I currently have on my machine. I checked (using both pip and conda) that that version is neither in the base env nor in the `dvc_blank` one.

Hope this helps!

**Comment by mattseddon** [comment]
Do you have DVC installed globally with `homebrew` or another tool? If so what version is that?

**Comment by julieg18** [comment]
@erykml, a couple questions:

**What is your currently selected python interpreter path? Is it different from the one shown in in the DVC command?**
You can check by running the `Python: Select Interpreter` command and looking at the current text in the input: 

<img width="607" alt="Screenshot 2023-05-19 at 7 07 17 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/e9cc3026-01f6-4d20-8dd6-1a3663782bc4">

**Can you show your DVC output logs?** Example:

<img width="1330" alt="Screenshot 2023-05-19 at 7 14 04 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/3aff7730-445a-40ee-a52e-16d80e333925">

**Are you seeing any errors in the developer tools console?** You can check by running the command `Developer: Open Webview Developer Tools`

**Comment by erykml** [comment]
Hi!

Sorry for the late response, I was away from my machine with the envs.

@mattseddon, I checked using `brew list` and I do not have dvc installed there.

@julieg18, please find the answers below:

1) 

<img width="732" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/fc3f6e91-d0b9-4a8b-b96c-865d70a9a318">

<img width="728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/684a162e-aeb2-4f45-9e3b-effdfb098ed3">

2)

<img width="1527" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/6fb9109c-0c4e-4418-b39b-c6d8b38769fc">

3) When I open the console (while DVC setup screen of the extension is open), I see 42 errors. Tbh, not sure if all of them (or any of them as a matter of fact) are related to DVC, but I can share more details if you tell me how. 

Hope this helps! If you need any more details, happy to help :)

**Comment by julieg18** [comment]
Thanks for the response, @erykml! Looking at your logs, it does seem that the extension, while displaying the wrong information in setup, is picking up some kind of global version of DVC. Have you already tried running `dvc --version` with `conda` completely deactivated (not even in your `base` environment) or running `dvc --version` in your `base` conda environment?

**Comment by julieg18** [comment]
A fix was released in `0.8.21` that should correct the setup page showing wrong information. @erykml, is the extension now showing more accurate information in the setup with the latest release?

**Comment by erykml** [comment]
Hi @julieg18, apologies for the late reply.
I have updated my extension and now I correctly see that `dvc` is not found.

<img width="693" alt="image" src="https://github.com/iterative/vscode-dvc/assets/30637137/3ee2a0d6-79a0-49d0-90c3-85b38e6f88f6">

Thanks for looking into it!

**Comment by julieg18** [comment]
> I have updated my extension and now I correctly see that dvc is not found.

Great to hear! Going to close this issue
