### ISSUE TITLE
experiments table unstable after running experiment

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#3913]
I am seeing this behaviour after running an experiment:

https://github.com/iterative/vscode-dvc/assets/37993418/4ba8b997-c444-465c-860a-654ca2e413fc

**Comment by mattseddon** [comment]
Also seeing lots of duplicate entries after running an experiment:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/00e3ae89-4ff3-411e-8058-6a60547dba85">

Can recreate weird behaviour in a non-submodule version of the project as well:


https://github.com/iterative/vscode-dvc/assets/37993418/2e94fd49-7b58-440a-bed8-a359ee0344f5

**Comment by mattseddon** [comment]
PTAL @sroy3

**Comment by mattseddon** [comment]
Looks like the error is here:  https://github.com/iterative/vscode-dvc/blob/7af45f8004213733fe4bb46d176b57c9b1a77279/extension/src/experiments/data/index.ts#L82-L95

When an experiment gets run `HEAD` is moved into a detached state. Which means that we end up with `getCurrentBranch` returning:

- `main` (before experiment) 
- short sha (during experiment) 
- `main` (after experiment) 
 
We get what are essentially duplicate commits set into `experiments.branchesToShow`. Which in turn duplicates all of the entries from `exp show` and the table can start convulsing.

**Comment by sroy3** [comment]
I'll look into this

**Comment by sroy3** [comment]
These seem related to the cleanup when changing branches. `8c3902f` is still present while on the main branch. Working on this today so hopefully that stabilize things.
