### ISSUE TITLE
Plots: make it easier to identify exp info

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#3942]
When looking at plots, I find it hard to identify information about the experiments from which it came. I can hover and see some of the metrics like this:

<img width="948" alt="Screenshot 2023-05-19 at 10 32 19 AM" src="https://github.com/iterative/vscode-dvc/assets/2308172/836d2259-c603-40d5-b125-4427c9ee7ff7">

A couple minor suggestions to improve it:

1. Add an icon or something to make it more obvious this exists.
2. Show params rather than metrics on hover. The plots likely already give an idea about the metrics. I'm more likely interested in which parameters are associated with each experiment.

**Comment by mattseddon** [comment]
You can reorder the experiments table to get params into that tooltip. It displays the first 3 columns from the left. This is also not obvious.

**Comment by dberenbaum** [comment]
Okay, that's helpful to know. That's flexible but maybe not a great default. For most people, it means they waste at least one column on the creation time. I also would like to keep the order of columns in the table, because metrics there are paramount, but here I would rather see the params. 

WDYT about showing the first 3 params columns? That's even less obvious but is probably a more useful default.

**Comment by shcheklein** [comment]
we can show the combination first params and first metrics I guess

**Comment by julieg18** [comment]
> Add an icon or something to make it more obvious this exists.

What if we added an `info` icon on the left of the ribbon items? Example:

<img width="1123" alt="Screenshot 2023-05-19 at 6 23 10 PM" src="https://github.com/iterative/vscode-dvc/assets/43496356/d15ce2a9-86b9-4c0e-9a7c-8ccb400fe3c2">

**Comment by mattseddon** [comment]
@dberenbaum do you think that would be useful to show created + both the first 3 params and the first 3 metrics from the table?

**Comment by dberenbaum** [comment]
I think the most useful action is to drop `Created`. I don't see why I would care about it in this view.

Overall, showing the first columns in the table seems like a nice, simple layout, it just wasn't obvious to me that's what it was doing. What do you think about putting info somewhere (maybe in place of `Created`) to indicate that it's showing the top columns from the table? Not sure the best way to do that, and not a strong opinion, so feel free to suggest other ideas.

It's hard to say how much is personal bias. I am used to having parameters before metrics always since I usually only care about the metrics once I know the differences between experiments, but I can understand why some people might want to show metrics first (and it's better for demos).
