### ISSUE TITLE
Modify and run experiment not working as expected with dvclive params

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4088]
When I try to modify and run an experiment, it looks like the extension tries to modify all parameters, including those which haven't changed and those which are not dependencies of the pipeline (`results/train/params.yaml` are outputs of dvclive). This is from a fresh clone of https://github.com/iterative/example-get-started-experiments:

https://github.com/iterative/vscode-dvc/assets/2308172/90315710-9cfb-4183-b159-57a100420927

Here's the error output:

```
Running: dvc exp run -S params.yaml:train.img_size=1025 -S params.yaml:train.batch_size=512 -S results/train/params.yaml:model=DynamicUnet -S results/train/params.yaml:batch_size=8 -S results/train/params.yaml:batch_per_epoch=8 -S results/train/params.yaml:frozen=false -S results/train/params.yaml:frozen_idx=0 -S results/train/params.yaml:transforms=[Pipeline: PILBase.create, Pipeline: partial -> PILBase.create] -S params.yaml:base.random_seed=42 -S params.yaml:data_split.test_pct=0.15 -S params.yaml:train.valid_pct=0.1 -S params.yaml:train.arch=shufflenet_v2_x2_0 -S params.yaml:train.fine_tune_args.epochs=8 -S params.yaml:train.fine_tune_args.base_lr=0.01 -S params.yaml:evaluate.n_samples_to_save=10

ERROR: unexpected error - LexerNoViableAltException: transforms=[Pipeline: PILBase.create, Pipeline: partial -> PILBase.create]
                                                                                    ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details
```

Besides this error, we should not show `results/train/params.yaml` parameters in the dropdown at 0:05 since these are not modifiable dependencies of the pipeline.

**Comment by mattseddon** [comment]
> it looks like the extension tries to modify all parameters,

All of the parameters are passed to `exp run` as that is how we reflect the experiment that was used as a base. This is how we get around having to apply the experiment before kicking off a run. Do you have any suggestions on how to workaround that problem? Applying the experiment first would mean that the data from the base would also be used (related to https://github.com/iterative/vscode-dvc/issues/2394). WDYT?

> Besides this error, we should not show results/train/params.yaml parameters in the dropdown at 0:05 since these are not modifiable dependencies of the pipeline.

How would we exclude these? We are currently using the `exp show` data to grab all of the parameters for an experiment.

**Comment by mattseddon** [comment]
I can fix the error by making sure that I wrap all string values in single quotes. E.g the command for `example-get-started-experiments` becomes something like:

```
dvc exp run -S params.yaml:base.random_seed=43 
-S results/train/params.yaml:model='DynamicUnet' 
-S results/train/params.yaml:batch_size=8 
-S results/train/params.yaml:batch_per_epoch=8 
-S results/train/params.yaml:frozen=false 
-S results/train/params.yaml:frozen_idx=0 
-S results/train/params.yaml:transforms='[Pipeline: PILBase.create, Pipeline: partial -> PILBase.create]' 
-S params.yaml:data_split.test_pct=0.15 
-S params.yaml:train.valid_pct=0.1 
-S params.yaml:train.arch='shufflenet_v2_x2_0' 
-S params.yaml:train.img_size=256 
-S params.yaml:train.batch_size=8 
-S params.yaml:train.fine_tune_args.epochs=8 
-S params.yaml:train.fine_tune_args.base_lr=0.01 
-S params.yaml:evaluate.n_samples_to_save=10
```

Still unsure of how to exclude the unmodifiable dependencies of the pipeline.

**Comment by mattseddon** [comment]
> I never thought enough about it before, but this seems dangerous since the baseline may have changes that aren't just different hyperparameters. How important is this functionality? I'm wondering if we should drop it and only allow the current workspace as the baseline like the CLI does. If it's crucial for something, we could think about whether we can handle this correctly inside the CLI.

Only 60 users have used the 2 commands (modify and run + modify and queue) in the last 90 days:

<img width="1467" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/6af32e03-860b-46dc-9274-ed8eede5ebff">

We can drop the functionality for all non-workspace records and consider bringing it back later. I still need to correctly handle strings as if a user wants to modify a param like `results/train/params.yaml:transforms` they'll currently run into issues.

I'll raise a couple of PRs. 

> Besides this error, we should not show results/train/params.yaml parameters in the dropdown at 0:05 since these are not modifiable dependencies of the pipeline.

I guess this becomes less of a priority?

**Comment by dberenbaum** [comment]
> I guess this becomes less of a priority?

Yeah, it's less severe then, although I still think it is confusing for users (here and in Studio), so I'd like for the DVC team to take a look at how to do this. I'll open an issue.
