### ISSUE TITLE
Custom Plots: `name` property is undefined.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#4097]
I assume it should be the experiment name?

![Screenshot 2023-06-13 190134](https://github.com/iterative/vscode-dvc/assets/12677733/73bdc2ef-2fd3-422c-8931-edd9a737cff0)

Example setup in https://github.com/iterative/dvc/discussions/9593#discussioncomment-6162250

**Comment by mattseddon** [comment]
Thanks for reporting 🙏🏻.
