### ISSUE TITLE
quoting causing grid search to fail

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4114]
Probably due to the new quoting behavior, we now don't handle grid search syntax correctly in some cases. See here how `train.arch` takes `resnet18,shufflenet_v2_x2_0` as a literal instead of splitting into 2 comma-separated values: 

https://github.com/iterative/vscode-dvc/assets/2308172/43e5204e-7f5f-4d14-8b20-a9f9c91c5342

The output channel shows `dvc exp run --queue -S params.yaml:train.arch='resnet18,shufflenet_v2_x2_0' -S params.yaml:train.fine_tune_args.base_lr=range(0.001,0.01,0.001)`

**Comment by mattseddon** [comment]
I can revert the behaviour. It will mean that when a user wants to modify a parameter like `transforms: '[Pipeline: PILBase.create, Pipeline: partial -> PILBase.create]'` they will have to pass the quotes themselves. In the case of running a grid search, they will need to quote each entry and separate them by commas. Which is actually (probably) simpler to understand behaviour.

Sorry for the breakage.

**Comment by dberenbaum** [comment]
Looks good now, thanks!
