### ISSUE TITLE
Setup screen is stuck on Loading ...

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4129]
Fresh install, the latest extension release (1.0.6). Windows. 

![Screenshot 2023-06-15 184245](https://github.com/iterative/vscode-dvc/assets/3659196/5596468b-28d4-49bd-8a2d-4fd3ba5a50d0)

```
......
[version: 1.0.6, 2023-06-16T01:44:27.165Z, pid: 12564] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:27.197Z, pid: 12564] > dvc --version - FAILED with code 1 (47ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:32.229Z, pid: 3956] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:32.267Z, pid: 3956] > dvc --version - FAILED with code 1 (59ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:32.287Z, pid: 16252] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:32.316Z, pid: 16252] > dvc --version - FAILED with code 1 (48ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:37.342Z, pid: 6300] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:37.371Z, pid: 6300] > dvc --version - FAILED with code 1 (46ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.


[version: 1.0.6, 2023-06-16T01:44:37.388Z, pid: 4420] > dvc --version - INITIALIZED
[version: 1.0.6, 2023-06-16T01:44:37.421Z, pid: 4420] > dvc --version - FAILED with code 1 (48ms)
'dvc' is not recognized as an internal or external command,


operable program or batch file.
```

**Comment by mattseddon** [comment]
Looks like dvc cannot be found by the extension but the page should still load. I won't be near my computer for a few hours but I'll take a look when I get home. 

Is this broken under normal circumstances?

**Comment by mattseddon** [comment]
Yeah, I'm tipping the issue is around here:

https://github.com/iterative/vscode-dvc/blob/e8ee2f8e822fe35266b019697a3925187c6c6794/extension/src/extensions/python.ts#L68

**Comment by mattseddon** [comment]
I'm unable to recreate the issue locally (I haven't set up a Windows environment). Can you please post a screenshot of the entire window with the DVC sidebar open and give me any dvc related errors from the developer tools console:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/d7e22cbe-1680-4e14-a0e5-fab639a36c35">

**Comment by mattseddon** [comment]
FWIW I setup a codespace without a `.devcontainer.json` (no extensions, no DVC) and could not recreate this in that environment either:

<img width="1725" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/79863245-d6eb-48a7-8663-c72907376863">

**Comment by shcheklein** [comment]
It looks like this for me:

![Screenshot 2023-06-16 192305](https://github.com/iterative/vscode-dvc/assets/3659196/2444f76a-df04-4382-9ded-ec3b9266f50f)

**Comment by shcheklein** [comment]
Managed to get through the noisy telemetry issue:

![Screenshot 2023-06-16 193252](https://github.com/iterative/vscode-dvc/assets/3659196/03d1f791-fc37-4754-b0ae-d7ae57174f4c)

**Comment by mattseddon** [comment]
Do you have git on that machine?

**Comment by shcheklein** [comment]
Yes, VS Code SCM can see, PowerShell outside can see it, Terminal inside (also PowerShell) in VS Code can't see it ... 🤔 (also clearly extension can't see it).

(we still should handle it gracefully I think)

**Comment by shcheklein** [comment]
Also, the telemetry issue - is it related to us? It generates a lot ...

**Comment by shcheklein** [comment]
Okay, I think I launched it before I installed Git - it explains why in VS Code's terminal it was not visible. But VS Code SCM was able to pick it w/o restarting. 

Making it p2 since it's an edge case clearly.

**Comment by mattseddon** [comment]
I'll fix the telemetry issue. I will also handle git failures gracefully.

**Comment by mattseddon** [comment]
FWIW the errors being [thrown](https://github.com/iterative/vscode-dvc/issues/4129#issuecomment-1595583731) are being caused by the internals of VS Code. In order to stop those errors we need to ensure that our code does not throw. See https://github.com/microsoft/vscode-extension-telemetry/issues/156.
