### ISSUE TITLE
ERROR: unknown Git revision 'exp-name'

### ISSUE THREAD

**Issue by feltena5** [iterative/vscode-dvc#4167]
Hello Everyone,
I can run experiments on its own, but after queueing them ( `dvc exp run --queue` ) and doing `dvc queue start` I obtain the following error `ERROR: unknown Git revision 'exp-name'`.

I can also obtain this error from the output terminal 
`[version: 1.0.10, 2023-06-23T08:37:36.176Z, pid: 10997] > git rev-list -n 1 --all - INITIALIZED`
`[version: 1.0.10, 2023-06-23T08:37:36.179Z, pid: 10997] > git rev-list -n 1 --all - FAILED with code 128 (8ms)`
`fatal: not a git repository (or any of the parent directories): .git`

I don't know if I am missing some stepes between queues.
When I do `dvc exp run` everything works correctly and I have full info on my experiments.

Thanks in advice

**Comment by mattseddon** [comment]
Hi @feltena5 which version of DVC are you using? 

Can you please provide the output of `dvc doctor`. 

Are you queuing experiments through the extension of using the CLI?

Can you please also provide the verbose output for `dvc queue start`.

Thanks

**Comment by feltena5** [comment]
Hi @mattseddon , I am using the 3.1.0 version. And I am using the CLI.
`dvc queue start --verbose`

`2023-06-26 08:48:47,100 DEBUG: v3.1.0 (pip), CPython 3.10.9 on Linux-5.19.0-45-generic-x86_64-with-glibc2.35`
`2023-06-26 08:48:47,100 DEBUG: command: /home/feltena/anaconda3/envs/qypSemi/bin/dvc queue start --verbose`
`2023-06-26 08:48:47,263 DEBUG: Spawning 1 exp queue workers`
`2023-06-26 08:48:48,273 DEBUG: Worker status: {}`
`2023-06-26 08:48:48,279 DEBUG: Spawning exp queue worker`
`2023-06-26 08:48:48,280 DEBUG: start a new worker: dvc-exp-worker-1, node: dvc-exp-798cb0-1@localhost`
`Started '1' new experiments task queue worker.`
`2023-06-26 08:48:48,283 DEBUG: Analytics is enabled.`
`2023-06-26 08:48:48,305 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpv3u7g7af']'`
`2023-06-26 08:48:48,306 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpv3u7g7af']'`

`dvc doctor`
`DVC version: 3.1.0 (pip)`
`------------------------`
`Platform: Python 3.10.9 on Linux-5.19.0-45-generic-x86_64-with-glibc2.35`
`Subprojects:`
`        dvc_data = 2.0.2`
`        dvc_objects = 0.23.0`
`        dvc_render = 0.5.3`
`        dvc_task = 0.3.0`
`        scmrepo = 1.0.4`
`Supports:`
`        azure (adlfs = 2023.4.0, knack = 0.10.1, azure-identity = 1.13.0),`
`        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),`
`        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)`
`Config:`
`        Global: /home/feltena/.config/dvc`
`        System: /etc/xdg/dvc`
`Cache types: hardlink, symlink`
`Cache directory: ext4 on /dev/nvme0n1p2`
`Caches: local`
`Remotes: azure, azure`
`Workspace directory: ext4 on /dev/nvme0n1p2`
`Repo: dvc, git`
`Repo.site_cache_dir: /var/tmp/dvc/repo/ad3e72932b5d71f9ef1e0ce379ab23ee`

**Comment by feltena5** [comment]
I found the error. The thing is that my working directory changed so when y queued the experiments it couldn't run my script, but it should be nice to print the script errors, because the terminal complains about Git and, at the end, that was not the problem.
