### ISSUE TITLE
exp show error

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4176]
<img width="1047" alt="Screenshot 2023-06-26 at 10 21 09 AM" src="https://github.com/iterative/vscode-dvc/assets/2308172/c5008a9b-8d7b-4045-a5ec-46056b11c7ab">

How to reproduce:

1. Use https://github.com/iterative/example-get-started-experiments/ (clone and pull)
2. Queue experiments that will fail with `dvc exp run --queue -S "params.yaml:train.arch='resnet18,shufflenet_v2_x2_0'" -S 'params.yaml:train.fine_tune_args.base_lr=range(0.001,0.01,0.001)'`
3. Start the queue and the error should appear

**Comment by julieg18** [comment]
I can reproduce! Looking at the logs `dvc exp show --rev {HASH} --rev {HASH} --rev {HASH}` fails once in our calls to update the table. Not sure why DVC is failing that one time, but the VSCode table shouldn't be getting stuck showing that error (Not even hitting the "Refresh" button is working).
