### ISSUE TITLE
Story: Remote experiments execution functionality

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4180]
Since VS Code comes with the option for remote development via SSH, it would be good to:

1. QA how it works in this setup
2. Better promote this workflow and its benefits
3. Identify anything else we can do to improve the experience

Sorry for the vagueness here -- just opening an issue to start discussing/tracking it.

**Comment by mattseddon** [comment]
This is the thread from the last time this came up: https://iterativeai.slack.com/archives/C01APS0FHDM/p1676500041452109

**Comment by mattseddon** [comment]
This is an even older thread: https://iterativeai.slack.com/archives/C01APS0FHDM/p1656356022254989
