### ISSUE TITLE
Add targets to "run experiment"

### ISSUE THREAD

**Issue by BradyJ27** [iterative/vscode-dvc#4222]
Currently, hitting "run experiment" will prompt for a stage in ./dvc.yaml. A user should be able to specify a path and or a stage for the target of "run experiment". This will allow to run an entire dvc.yaml through the UI, along with allowing to run a dvc.yaml that exists in a subdirectory of the current working directory. 

An example of using this with the CLI would be `dvc exp run sub-dir/dvc.yaml` or, `dvc exp run sub-dir/dvc.yaml:stage`

**Comment by mattseddon** [comment]
@BradyJ27 do you have an example project that you can share?

**Comment by BradyJ27** [comment]
> @BradyJ27 do you have an example project that you can share?

@mattseddon I currently do not. I can see if I can throw together a quick example project that follows a "mono-repo" style.

**Comment by mattseddon** [comment]
For the record the extension supports multiple projects being available in the workspace in a mono-repo (i.e each project is initialized with `--subdir`). As far as the extension is concerned a project is denoted by an individual `.dvc` folder. Under these circumstances when starting an experiment the extension will ask the user which project they want to run the experiment against. This can be bypassed by setting the `dvc.focusedProjects` option to a single project or opening the individual project at the workspace's root. 

What we don't currently support is multiple pipelines underneath a single project (i.e. a single `.dvc` directory and nested `dvc.yaml`s without a `dvc.yaml` at the project root). We will be working through this setup shortly though and we should be able to come up with a solution that gives extra flexibility without breaking the experience for users with less complicated setups.

**Comment by shcheklein** [comment]
@mattseddon I've created a repo to try the scenario - https://github.com/shcheklein/monorepo-slices-example . It has two directories with the same project inside. It might be confusing a bit test bc of this, but I hope that still should be enough to test. Let me know.

**Comment by mattseddon** [comment]
@BradyJ27 the new functionality will be in the next release. LMK how you go and if you have any feedback 🙏🏻.
