### ISSUE TITLE
Have a way to see information about an experiment (or many?) by hovering / clicking on them

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4229]
Based on user feedback. If there are two many parameters, table becomes too long and it's hard to navigate it. It's a usual story for a repo like YOLO. 

We need a way for users to be able to see a preview of an experiment, or some summary etc.

It reminds me the compare panel in Studio (table pivot), we can take that an idea (multiple experiments, pivot, highlight differences, etc), but we need a better UX for that + I think we can do better tooltips, etc. 

As an idea for UX - can we use the preview panel in VS Code for this? (besides tooltips).

**Comment by mattseddon** [comment]
I think that some way of moving columns/groups of columns to the left of the table might be low-hanging fruit. I think we also need a way to make this quick pick more obvious/get people to use it:

<img width="1726" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/ee364761-203f-4cfc-aff9-f78faf7d6ac9">

We could expand on the "leaderboard" idea/usage from #4269 and show a condensed version of the table that can be sorted by not only columns but a formula. We would have to limit the number of columns that can be shown to < 20 or users would run into the same issue. The main difference would be that records would be shown outside of the usual commit/experiment hierarchy.

#1994 would also be a potential solution for this issue (or at least help with the problem).

**Comment by shcheklein** [comment]
- Followup if user was aware about DnD cc @shcheklein 
- Check other trackers - how do they show / do they show this information?

**Comment by shcheklein** [comment]
DnD - yes, it was known. It doesn't solve the issue. What is needed is a side panel (like in MD preview) that could be open and update when we select experiments.

**Comment by mattseddon** [comment]
As discussed in last week's planning meeting. We could add another tree view which shows "focused" experiments transposed. Here is a screenshot with a prototype view moved to the "secondary sidebar":

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/cb6f8972-e69b-4a48-bb22-e274fd70fd22">

It should be noted that these views can be searched/filtered for/to specific values:

https://github.com/iterative/vscode-dvc/assets/37993418/3f42c0de-c865-45ba-9890-7173dd122f43

**Comment by shcheklein** [comment]
@mattseddon thanks! Can it be open / close automatically or on a button click on the "right" side (similar to MD previews)?

**Comment by mattseddon** [comment]
Yes, we can open. No, we cannot close. I cannot find a way to programmatically move a view to the secondary sidebar and we cannot contribute a view directly to the secondary sidebar: 

<img width="771" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/f5aeda46-b369-4119-9bd9-d2af0090479e">

**Comment by shcheklein** [comment]
> Yes, we can open. No, we cannot close. I cannot find a way to programmatically move a view to the secondary sidebar and we cannot contribute a view directly to the secondary sidebar:

means probably that if someone would switch to their code they would still see that sidebar?

(if it's significantly easy to implement - let's go for it, otherwise feels like a suboptimal UX tbh)

**Comment by mattseddon** [comment]
There are hotkeys to open/close the sidebars but still up to the user what they want to do.

https://github.com/iterative/vscode-dvc/assets/37993418/b5be84a8-3a2f-425b-97a6-1d2644450daf

Markdown preview also does not close itself when the focus is taken away.

I am not advocating for this solution but there will be limitations with whatever gets put in.

**Comment by mattseddon** [comment]
We could try and squeeze as much information as possible into the tooltip. The drawbacks of this are that there isn't much space, the tooltip cannot be interacted with and it is not obvious that the functionality might be there:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/2381327d-d246-4398-89ee-4f3609c379f5">

**Comment by mattseddon** [comment]
https://github.com/gitkraken/vscode-gitlens/issues/2537 and https://github.com/microsoft/vscode/issues/151681 are related.

**Comment by mattseddon** [comment]
> DnD - yes, it was known. It doesn't solve the issue. What is needed is a side panel (like in MD preview) that could be open and update when we select experiments.

@shcheklein can you please ask the user know about "Move to Start" as well.

**Comment by mattseddon** [comment]
and show only changed.

**Comment by shcheklein** [comment]
Closing this for now, we'll come to the proper side panel implementation a bit later. For now there is a workaround with moving things to the start.
