### ISSUE TITLE
Table: better way to show most important information

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4269]
Based on the customer feedback:

- [x] Filter branches by prefix (e.g. show only branches like "dvc-exps/%")
- [x] Setting to show only the top of each branch
- [x] Remove all records where one column is not defined (only-changed?) @shcheklein to confirm if this is about experiments or columns.
- [x] Add a way to reset number of commits per branch. As a first step show a reset action per branch + we agreed to spend some time on the performance of these actions (especially `-` since we don't have to send any commands). That should mitigate the issue with being able to quickly see only HEADs.

**Comment by mattseddon** [comment]
Filtering branches by a prefix is already possible:


https://github.com/iterative/vscode-dvc/assets/37993418/41d094cf-6857-47df-acd9-f2b154d38414

**Comment by mattseddon** [comment]
> Remove all record where one column is not defined

This cannot currently be done via filters because of https://github.com/iterative/vscode-dvc/pull/1732. I think we should reverse that decision. I am not sure what the effort is without looking but we could potentially only apply that logic to queued experiments.

**Comment by mattseddon** [comment]
I've added a "not missing" filter which will be available in the next release

https://github.com/iterative/vscode-dvc/assets/37993418/93a3b8a9-c3e5-4c2f-865b-75282d665c00

I've also limited the number of commits for selected branches to 1.

**Comment by shcheklein** [comment]
Feedback:

1. Old commits are still there and the extension lags a lot (it's almost impossible to use it because I'm waiting for several seconds for every single action)
2. Non-null filtering does not help. I filtered the output by final_score is not null, but it seems that the filtering is done on branch level rather that commit level

Can it be for some branches that we hit +/- we remembered their state? Should we have a reset to defaults or something similar?

**Comment by mattseddon** [comment]
> Old commits are still there and the extension lags a lot (it's almost impossible to use it because I'm waiting for several seconds for every single action)

Lag/performance is a separate story that we need to address.

> Non-null filtering does not help. I filtered the output by final_score is not null, but it seems that the filtering is done on branch level rather that commit level

Yes, my mistake. Filters only work on experiments not commits/branches. If we wanted to change this we could go back to the logic that we used for checkpoints. I.e we filter commits/branches but if a commit/branch does not meet the filter criteria but a single experiment under the parent meets the criteria then we would continue to show the parent as well as the unfiltered experiment.

> Can it be for some branches that we hit +/- we remembered their state? Should we have a reset to defaults or something similar?

Yes, we only set the default value if the branch has never been seen before. We even save this value between sessions. We could use reset defaults or we could introduce an option that only shows the current commit for each selected branch (including the current one). The behaviour should change to only show the most recent commit for new branches. 
There is also a command that is already available to flush the persisted state:

<img width="638" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/686c38e6-03f7-4d55-9b59-7064e72d8109">

After running that command new branches should be shown with a single commit.

**Comment by mattseddon** [comment]
> There is also a command that is already available to flush the persisted state:

☝🏻 a note on this. It will nuke all persisted state for the extension. That includes selected branches, experiments, etc.

**Comment by mattseddon** [comment]
> Non-null filtering does not help. I filtered the output by final_score is not null, but it seems that the filtering is done on branch level rather that commit level

Branches/commits will now be filtered as well

### Demo


https://github.com/iterative/vscode-dvc/assets/37993418/4d93a784-c3f7-4644-9460-6ef45010642e

**Comment by mattseddon** [comment]
@Danila89 we've implemented/made the first iteration of the original list. Please LMK if there is anything outstanding.

@shcheklein will follow up.

**Comment by Danila89** [comment]
Finally it started to work fine in our scenario, thank you very much for the improvement!
