### ISSUE TITLE
'.../plots/metrics/metrics' - file type error

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4275]
Using the `dvclive.lightning.DVCLiveLogger` with `dir="data/train/dvclive"`, I can see the plots of the metrics in the "Plots" view of the VS Code DVC extension. But at the top where it shows the selected experiments, it displays an error with message:

> 'data/train/dvclive/plots/metrics/metrics' - file type error
Only JSON, YAML, CSV and TSV formats are supported.

The summary metrics are stored in `data/train/dvclive/metrics.json` and the `.tsv` files of the logged metrics are in `data/train/dvclive/plots/metrics/`. There exists no file named `metrics` without extension inside this folder.

**Comment by mattseddon** [comment]
@aschuh-hf can you please post a screenshot of the issue. Does `plots diff --json` return any errors for those revisions? What version of DVC are you using?

**Comment by aschuh-hf** [comment]
After working more on my repo, some PRs pushed and merged, etc. I don't actually see this error any  longer. But also because I changed the `train` stage in my `dvc.yaml`.

I am using DVC 3.5.1 and was using the latest DVC extension as of two days ago (just now updated to v1.0.19.

As I may not be able to help reproduce this error, we could close this issue for now until it pops up again.

**Comment by aschuh-hf** [comment]
I deleted the `train` stage from my `dvc.lock` file and removed the stage outputs from my working directory. After running `dvc exp run train` anew with the modified stage in `dvc.yaml`, I see the error again.

<img width="617" alt="Screen Shot 2023-07-18 at 12 41 54 AM" src="https://github.com/iterative/vscode-dvc/assets/77496589/e49f10bd-6d97-4b8c-85fe-c13110d95848">

**Comment by aschuh-hf** [comment]
```
DVC version: 3.5.1 (conda)
--------------------------
Platform: Python 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.5.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /home/aschuh/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/764b1d03f8b416f032df6c50c3809e7f
```

**Comment by aschuh-hf** [comment]
Screenshot of DVCLiveLogger output files under `data/train/...`:

<img width="279" alt="Screen Shot 2023-07-18 at 12 44 59 AM" src="https://github.com/iterative/vscode-dvc/assets/77496589/e3e61a26-f150-442d-8f87-4e2c3cad6d21">

**Comment by mattseddon** [comment]
@aschuh-hf do you mean the `dvc.yaml`? Direct changed to the `dvc.lock` are not advised.

**Comment by aschuh-hf** [comment]
I edited the `dvc.lock` to remove the stage. I thought one choice for YAML and the way DVC works was to make it quite straightforward to edit these files manually (e.g., I never used `dvc stage add`, `dvc run`, etc. in my few years of using DVC).

**Comment by aschuh-hf** [comment]
Once `dvc exp run` completed (now), the `dvc.lock` file was updated with the new `train` stage entry and the error is gone.

**Comment by mattseddon** [comment]
You should remove the stage from the `dvc.yaml` if you do not want it to run again. The `dvc.lock` is automatically maintained by dvc and manually making changes will result in unexpected errors.

Take a look at these docs: 
- https://dvc.org/doc/user-guide/project-structure/dvcyaml-files
- https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dvclock-file

**Comment by aschuh-hf** [comment]
The error I am reporting is unlikely caused by me editing the `dvc.lock` file because I would get the exact same behavior if I would simply use `git restore dvc.lock` after running `dvc exp run` for the first time (with `core.autostage=false`). All I did is revert the change `dvc exp run` does after completion.

**Comment by mattseddon** [comment]
`git restore dvc.lock` is equivalent to manually updating the `dvc.lock` file.

**Comment by aschuh-hf** [comment]
> git restore dvc.lock is equivalent to manually updating the dvc.lock file.

Does `git checkout` not also touch the `dvc.lock` file? The file is tracked by Git, not DVC, so I should be allowed to use `git` commands such as `git restore` to modify its contents. Besides, there is no "undo `dvc exp run`" command in the list of DVC commands. Because IMHO that command is `git restore` / `git reset`.

Would it make sense to focus on the error rather than how it was elicited? Clearly the error message refers to a file path that never existed (`data/train/plots/metrics/metrics`), neither on the file system nor in my `dvc.yaml` file (I also did not make any such change to `dvc.lock`). That should hint that there is indeed something awry.

**Comment by aschuh-hf** [comment]
Yes, `dvc plots diff` also reports this error. Though both in the CLI output and VS Code Extension "Plots" view the path is now "data/train/plots/metrics" (which is the correct path) after I merged some code and run some trial experiments to test my DVC + Ray + AWS setup.

```
$ dvc plots diff --json
DVC failed to load some plots for following revisions: 'workspace, HEAD'.                                                                                                                                                                                                                                                                                                                         
{
  "errors": [
    {
      "name": "data/train/plots/metrics",
      "rev": "workspace",
      "source": "data/train/plots/metrics",
      "type": "PlotMetricTypeError",
      "msg": "'data/train/plots/metrics' - file type error\nOnly JSON, YAML, CSV and TSV formats are supported."
    },
    {
      "name": "data/train/plots/metrics",
      "rev": "HEAD",
      "source": "data/train/plots/metrics",
      "type": "PlotMetricTypeError",
      "msg": "'data/train/plots/metrics' - file type error\nOnly JSON, YAML, CSV and TSV formats are supported."
    }
  ],
  "data": {
    "data/train/plots/metrics": []
  }
}
```

This was after I started a new run with `dvc exp run` (using the extension's "Run Experiment" button). My base commit has no valid `train` stage output as I just set up the experiment pipeline with DVCLive.

**Comment by dberenbaum** [comment]
Thanks @aschuh-hf! I'm going to transfer this to DVC then since it doesn't seem like the issue is specific to the VS Code extension. Do you know how to reproduce the error by any chance?
