### ISSUE TITLE
Experiments params.yaml columns not grouped

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4290]
I disabled, then enabled parameters in a `env` section of my `params.yaml` file and was surprised to see the columns not grouped in the table. Note that the entry `env.RAY_ADDRESS` was only added recently before executing these test runs.

I was expecting `env.CUDA_VISIBLE_DEVICES` and `env.RAY_ADDRESS` columns to be grouped.

<img width="1246" alt="Screen Shot 2023-07-17 at 10 37 12 PM" src="https://github.com/iterative/vscode-dvc/assets/77496589/238bb406-d266-47af-982c-06d35526465b">

DVC Extension v1.0.19.

**Comment by mattseddon** [comment]
I think the underlying logic is that if columns are moved whilst one is disabled then the disabled column will be moved to the end of the column list.

You can drag and drop the columns to regroup them.

**Comment by aschuh-hf** [comment]
Ah, nice, I was not aware one can drag and drop the columns. Thanks!

**Comment by mattseddon** [comment]
Here is a demo of what I am talking about:


https://github.com/iterative/vscode-dvc/assets/37993418/dc534a4c-7b55-4c4c-91c0-29e2a8435a6a

**Comment by mattseddon** [comment]
There is also a column picker, hope this helps:


https://github.com/iterative/vscode-dvc/assets/37993418/1e60dddf-d0e5-4d83-abbb-cb548aab59af

**Comment by aschuh-hf** [comment]
Thanks, that is convenient. I used the check boxes in the side panel to select only the columns shown in the screenshot. Only the order was off, which I didn't know I was able to adjust as I suppose some time back this wasn't possible yet.
