### ISSUE TITLE
If dvc fails to initialize (CLI fails) show experiments doesn't get to setup

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4323]
(Sorry, typing this fast. Can give more details. This is first to not forget to discuss and fix this)

It open an empty page with a broken state. Which is also fine, after refresh button click it works (since DVC is fixed now). But it's now on the empty screen with some link to the docs.

We also need a refresh button in the side panel, data tree. (I had to open experiments to get to the refresh in the first place).

**Comment by julieg18** [comment]
Not able to reproduce so far 🤔 

* What OS are you on?
* Any errors in the console or web developer tools?

**Comment by shcheklein** [comment]
OS - I think it was Mac OS.

Errors - don't know in this case, sorry. 

Did you manage to reproduce a state where it's an error in the side panel? You would need to make DVC to throw some unexpected error may be.

**Comment by shcheklein** [comment]
> But you're saying that after you clicked refresh, you saw an empty screen with doc links despite having experiment data? Did the webview stay on this doc link page or did it resolve itself?

I think I didn't have experiments in that repo. What I was expecting though is it to take me to the Setup page, the experiments section. As it usually happens when you don't have any experiments and trying to open the panel.

Error page is totally fine an expected (since if it's broken we don't even know if we have experiments or not).
