### ISSUE TITLE
Switch TreeViews to newly introduced native checkboxes?

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#4326]
In version 1.80 of VS Code, [the TreeItem checkboxState API was finalized](https://code.visualstudio.com/updates/v1_80#_tree-checkbox-api). This means that native checkboxes are now available for us to use. 

### Demo

See below for a demo of our current checkboxes side by side with the new native ones

https://github.com/iterative/vscode-dvc/assets/37993418/b6cd9980-015c-4925-9f1c-34330035042a

Pros 

1. VS Code mostly manages state.
1. Reduction in code complexity
1. Native look and feel
1. Colors update when the theme is changed
1. Can drop the custom SVGs 

Cons

1. Users will have to update to the latest version of VS Code
3. Some work to implement the change
4. No indeterminate checkbox

cc @dberenbaum @shcheklein @daavoo @julieg18 

What does everyone think? Personally, I think we should make the switch.

**Comment by julieg18** [comment]
Definitely agreeing with making the change! 

> Users will have to update to the latest version of VS Code

We could wait a bit before implementing, giving users time to update.

**Comment by daavoo** [comment]
> Users will have to update to the latest version of VS Code

I have no idea how version management works in vscode extensions.
Can users of an older version of VSCode install an older version of the extension?

**Comment by shcheklein** [comment]
Was the previous checkbox also managed / provide by the VS Code library? 

If it requires some work it doesn't feel like a high priority to me tbh.

**Comment by mattseddon** [comment]
> I have no idea how version management works in vscode extensions.
Can users of an older version of VSCode install an older version of the extension?

Yes, they could use an older version of the extension with previous versions of VS Code. Version `1.64.0` (January 2022) will support ~a lot of old~ nearly all previous versions of the extension.

The main issue here is situations like [this](https://iterativeai.slack.com/archives/C01APS0FHDM/p1666704115405309).

> Was the previous checkbox also managed / provide by the VS Code library?

No, the state is managed completely by us and we have to walk up and down the tree after updates to make sure everything is in order. Migrating should give us an increase in performance. We also currently carry 3 custom SVGs that we could get rid of.

> If it requires some work it doesn't feel like a high priority to me tbh.

I don't estimate this to be a large task but we can close this as not a priority for now if that is the general feeling... come back to it in a year (or never).

**Comment by mattseddon** [comment]
Come back to this later
