### ISSUE TITLE
remote system gdrive Authentication

### ISSUE THREAD

**Issue by PythonFZ** [iterative/vscode-dvc#4436]
If you open a repository with a gdrive remote on a remote system, VS Code will try to ask you to open the url to authenticate.
On success it will forward you to `ocalhost:8080/?code=4/0Ad....` which won't be available.
If VS Code forwards port `8080` from the remote machine the authentication should succeed.

**Comment by PythonFZ** [comment]
My suggestion would be to automatically forward the port. Could the port be different if 8080 is already in use?

**Comment by shcheklein** [comment]
I think it's trying to bind 8080 and 9090 on the machine. We can try forward both, not sure. Not sure also yet, how can we make it part of the extension. Does it mean it needs to detect DVC using GDrive on a remote machine automatically somehow and only in case of a remote machine?

**Comment by PythonFZ** [comment]
I haven't used GDrive before and I opened it on the remote machine. VS Code asked me to open the url to authenticate. I thought maybe that already provides the information that the port forwarding is required? The setup is only required once so this is more a suggestion than an issue.

**Comment by mattseddon** [comment]
I've checked and there is no VS Code API for the extension to access this information from VS Code. We won't be able to do anything with this for the foreseeable future. Closing for now.
