### ISSUE TITLE
Irrelevant DVCLive autocomplete snippet suggestions in Interactive Window

### ISSUE THREAD

**Issue by lainisourgod** [iterative/vscode-dvc#4455]
Hi! Not sure why it happens, but when I use Interactive Window I sometimes get autocomplete suggestions for DVCLive snippets. E.g. this one happened when indexing dataframe: `data["|"]`

<img width="1323" alt="CleanShot 2023-08-09 at 12 16 23@2x" src="https://github.com/iterative/vscode-dvc/assets/24773652/990a1008-3a76-47a3-a8c8-952eca23a723">

The snippet suggested :)
<img width="646" alt="CleanShot 2023-08-09 at 12 20 25@2x" src="https://github.com/iterative/vscode-dvc/assets/24773652/5d9ac678-24cf-4e8d-be80-f8ce6bfd82a7">

DVC extension version: 1.0.36
VSCode version: 1.81.0
Pylance version: 2023.8.10
Jupyter extension version: 2023.7.1002162226
Python version: 3.10

**Comment by mattseddon** [comment]
The snippets can only be scoped to a specific language which in this case is Python. I can't explain why all the snippets are showing up for this particular example but `data` will lead to two of the snippets being suggested as those letters show up in that order in the "prefix" of the snippet:

https://github.com/iterative/vscode-dvc/assets/37993418/5ecda236-4532-4c5c-9048-475e8dcc7746

Note: Pressing esc will dismiss the suggestion.

If you do not want to see these snippets suggested then you can [remove them from intellisense](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_can-i-remove-snippets-from-intellisense). A demo of how to do this is shown below (took me a while to work it out):

https://github.com/iterative/vscode-dvc/assets/37993418/f2ba14af-cf9b-40f0-97ae-e3e9867658d6

**Comment by lainisourgod** [comment]
I don't use snippets anywhere else in my VSCode, so it even took some time to understand what's happening here.

Also it was strange that my IntelliSense hasn't suggested anything except these snippets. I guess it's VSCode bug for randomly refusing to give suggestions it previously gave :)

I understand that reason here is to suggest user to use DVCLIve and giving fast track into it. But maybe we can better scope when it's predicted (I don't have DVCLive in my project). Or enable these snippets only after user approved it (e.g. in the Walkthrough).

Thank you @mattseddon !

**Comment by mattseddon** [comment]
> But maybe we can better scope when it's predicted (I don't have DVCLive in my project). Or enable these snippets only after user approved it (e.g. in the Walkthrough).

Thanks for the suggestion @lainisourgod, this is not currently possible with the API provided by VS Code.

Closing as this has a workaround.
