### ISSUE TITLE
Queue: run a specific experiment(s)

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4464]
In a context menu for a selected queued experiment(s) I would expect to have a run button. Also, tbh, when I have some experiments selected even the default button should probably run them vs a new one.

**Comment by mattseddon** [comment]
IIUC this is not possible via the CLI. `dvc queue start` and `dvc exp run --run-all` do not provide an option to run specific experiments.

**Comment by dberenbaum** [comment]
Correct although there is a workaround in https://github.com/iterative/dvc/issues/8121
