### ISSUE TITLE
Can't setup virtual env from a setup screen

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4466]
Despite Python ext installed and doesn't give me an option to setup an env. Buttons are disabled.

https://github.com/iterative/vscode-dvc/assets/3659196/21d91570-a354-42f2-8870-5933de6cc5d4

**Comment by shcheklein** [comment]
Also, after I created the env manually the screen stays in the state, not detecting changes.

**Comment by shcheklein** [comment]
Was it supported at all? I thought we had a way to let people activate the Python extension?

**Comment by mattseddon** [comment]
Was the Python extension installed recently and is this in Codespaces with a new Codespace or an existing one?

**Comment by shcheklein** [comment]
No, it was local, on my machine.

**Comment by shcheklein** [comment]
I update the VS Code a bit before that if that is relevant.

**Comment by mattseddon** [comment]
The webview is using a variable called `isPythonExtensionUsed` it should be checking to see if the extension is installed (`isPythonExtensionInstalled`).
