### ISSUE TITLE
Studio connection status is "green" even if Studio is not connected

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4488]
On a fresh Codespaces environment:

<img width="1148" alt="Screenshot 2023-08-12 at 11 05 13 AM" src="https://github.com/iterative/vscode-dvc/assets/3659196/e3764653-6276-4ec5-a8be-e2cfce80a6ec">

The icon should be "grey" (or yellow?)

**Comment by shcheklein** [comment]
Probably this is by design, I mean the green info icon. I think it's a bit misleading. I would make it a grey circle.

**Comment by mattseddon** [comment]
The color is due to the theme you are being provided with by Codespaces. In the default theme the icon is blue:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/4fc878c8-92cc-4d91-873f-d03265eb5101">

And in the default light theme:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/46d428bf-7b65-47f0-90d3-7d8800074413">

**Comment by shcheklein** [comment]
Yep, thanks, Matt. I think it makes sense to make grey / neutral / deactivated on all themes. There should be a predefined vscode color.

**Comment by mattseddon** [comment]
The purpose of having an info icon there is not to demonstrate the status of the section but to encourage the user to hover for more information. We have these info icons throughout the setup page and app. 

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/58d167c0-9890-418a-9832-322d4730b1a3">

<img width="883" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/9947d827-652d-4174-a9f3-ff18648ce90d">

<img width="526" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/4efeee21-16ea-4ce1-bd97-8a91f047ae38">

**Comment by shcheklein** [comment]
Yep, in this case since it overlaps with the status icon it becomes misleading / confusing.

**Comment by mattseddon** [comment]
Setting the icon to a different color, e.g. deactivated will be confusing for different reasons. 

Why not remove it?

**Comment by shcheklein** [comment]
Primarily since all other sections have a status icon and since we also should "know" an actual status in this case?
