### ISSUE TITLE
Wrong plots group in the side panel

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4489]
On Codespaces. `dvc.yaml::dvclive` doesn't exist as a directory. Repo is this one (can be changing as do other things): https://github.com/shcheklein/ultralytics (branch `dvc` + run an experiment with a regular launch action, it doesn't have dvc.yaml in the root). 

<img width="285" alt="Screenshot 2023-08-12 at 11 38 17 AM" src="https://github.com/iterative/vscode-dvc/assets/3659196/347f2910-2093-4bbf-a71a-25533f78db87">

but that's what I'm getting in the plots section:

<img width="299" alt="Screenshot 2023-08-12 at 11 36 41 AM" src="https://github.com/iterative/vscode-dvc/assets/3659196/55e259f5-4053-4be5-901e-b8a29508f8a6">

## Bonus

A general UX issue. In the same section (and other section) - things should be copy-pastable. Either via context menu / or via some select + hot key or with some other mechanism.

## Environment

Extension: v1.0.38
DVC: 

```
DVC version: 3.15.1 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-5.15.0-1042-azure-x86_64-with-glibc2.36
Subprojects:
        dvc_data = 2.13.1
        dvc_objects = 0.25.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.2.1
Supports:
        http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
        Global: /home/vscode/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/loop3
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/loop3
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/ae31ab50ca6008737617db73d448c512
```

**Comment by mattseddon** [comment]
What does `plots diff` return for the repo?

**Comment by shcheklein** [comment]
Here: https://gist.github.com/shcheklein/7f9c20b116d71a61b3c9a1eb43b0daad

**Comment by mattseddon** [comment]
> On Codespaces. dvc.yaml::dvclive doesn't exist as a directory

We rely on the keys provided by `plots diff` to construct the "paths" shown in the plots tree. All of the keys contain `dvclive/dvc.yaml::dvclive`.

**Comment by shcheklein** [comment]
Should we create an issue on the DVC side then?

**Comment by mattseddon** [comment]
I assume there is a valid reason for this pattern. @dberenbaum can you give your opinion/some info before an issue gets raised?

**Comment by shcheklein** [comment]
One thing to add here (not visible on screenshot), here is how the complete output looks like:

<img width="364" alt="Screenshot 2023-08-13 at 3 43 23 PM" src="https://github.com/iterative/vscode-dvc/assets/3659196/c15e4cd1-8866-4f86-9cb1-479c3559d305">

Since plots != files (e.g. plot can have multiple files, and one file can be in a few plots)- it's a good product question (we can think / brainstorm a bit) on how we want to actually group them in the side panel. But the current approach is cryptic and confusing to me.

**Comment by mattseddon** [comment]
Would updating the tree to look like this be acceptable?

<img width="359" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/65d5a4ee-1ddd-4f09-93db-02d2e7f72c25">

`dvc.yaml` path is the top level key then all plots are underneath.

**Comment by shcheklein** [comment]
Yes, I think so. A bit unrelated to the dvc.yaml position in the tree - need to double check plots with multiple files in them.

**Comment by mattseddon** [comment]
Should be covered by https://github.com/iterative/dvc/issues/8601

**Comment by shcheklein** [comment]
I meant a plot with two files, or two plots with different IDs that use the same file.
