### ISSUE TITLE
"Show Logs" of failed experiment

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4524]
When an experiment failed, I can use `dvc queue logs <task>` to see the logs of the failed run to figure out what went wrong. The VS Code extension has the "Show Logs" context menu entry on the Experiments tab disabled, however, for the same experiment. It would be nice if I could use the context menu to open the logs of the failed experiment without resorting to the DVC CLI.

**Comment by mattseddon** [comment]
This should be covered by https://github.com/iterative/vscode-dvc/issues/4332

**Comment by mattseddon** [comment]
Closing as duplicate. See the other issue for more context and feel free to subscribe if you want updates on when the feature will be implemented 🙏🏻.
