### ISSUE TITLE
Plots: Ability to zoom and maybe pan

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4530]
Is it possible to zoom the metrics plots within a selected local rectangular window as in TensorBoard? I couldn't figure out how if. Selecting a rectangular zoom window and zooming out again fully via a simple interaction (e.g., double click as in TensorBoard) would be quite useful. Also being able to then pan that window would be nice (SHIFT + left click drag in TensorBoard).

**Comment by mattseddon** [comment]
This is not currently possible.

@daavoo @dberenbaum is this behaviour something that Plotly will be able to provide?

**Comment by dberenbaum** [comment]
It looks to be possible: https://plotly.com/chart-studio-help/zoom-pan-hover-controls/

**Comment by shcheklein** [comment]
@dberenbaum do we have an epic / story for the Plotly migration? so that we can put the requirements like this into that story.

**Comment by dberenbaum** [comment]
Added a tasklist in https://github.com/iterative/dvc-render/issues/7 to keep track, although I think the first step will be just trying to reach parity with the current vega-lite implementation.

**Comment by mattseddon** [comment]
We can do this with a simple update to the Vega template. The plot can be zoomed in with the mouse wheel. For the extension, I would suppress the behaviour unless the plot is focused/zoomed:

https://github.com/iterative/vscode-dvc/assets/37993418/31c404a5-328a-423b-8402-c1f2d5d35c24

WDYT?

cc @daavoo 

Note: I cannot currently get the zooming behaviour to work for the smooth template but I will spend a little bit of time trying to make it work before raising a PR.

**Comment by mattseddon** [comment]
Further demos available at https://github.com/iterative/vscode-dvc/pull/4629

**Comment by aschuh-hf** [comment]
Great, thanks for adding this!

Unfortunately it isn't yet working for me when using a custom `template` based on https://github.com/iterative/vscode-dvc/issues/4532#issuecomment-1685483245. Even after I commented the `stages.<stage>.metrics.template` line in the `dvc.yaml` in the workspace, it is still using the previously used template. I guess it's cached somewhere as part of an experiment run?

**Comment by mattseddon** [comment]
If you can share your template with some dummy data in a Vega editor then I should be able to get it working for you.

**Comment by aschuh-hf** [comment]
> If you can share your template with some dummy data in a Vega editor then I should be able to get it working for you.

I believe I figured out the tooltip related issue (cf. https://github.com/iterative/vscode-dvc/issues/4532#issuecomment-1711518022). Will need to wait until I run another experiment it seems before I can get DVC CLI to use the updated template and test out the zoom and pan feature within the extension. Unless there is another way I can tell DVC which template to use? It ignores the `template` specified in the `dvc.yaml` of the workspace, even after committing it with Git.

**Comment by shcheklein** [comment]
> It ignores the template specified in the dvc.yaml of the workspace, even after committing it with Git.

It it the same in the DVC - `dvc plots show`?

**Comment by aschuh-hf** [comment]
> It it the same in the DVC - dvc plots show?

Yes, this was also the case when using the CLI.

**Comment by aschuh-hf** [comment]
FYI With the template provided by @mattseddon at https://github.com/iterative/vscode-dvc/issues/4532#issuecomment-1712964405 and zoom and pan works like a charm!
