### ISSUE TITLE
Plots: View tooltip with table of metric values across selected experiments

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4532]
When hovering over a metric plot, I can see tooltips of the metric value for the curve under the cursor (though this takes some patience to get the cursor in the right place also due to lack of zoom, cf. #4530). What I often use and find quite useful with TensorBoard is that this would show me the metric values of all curves either at this or the latest available step (x coordinate). This is quite useful to compare the curves at different timepoints. Would be great if this was also supported by the DVC Plots towards replacing my use of TensorBoard.

Example screenshot from TensorBoard:
<img width="673" alt="Screen Shot 2023-08-18 at 12 02 24 PM" src="https://github.com/iterative/vscode-dvc/assets/77496589/31c8e132-6162-4958-95a2-ff81b5f69a57">

**Comment by mattseddon** [comment]
@daavoo @dberenbaum the on hover vertical line was dropped from `dvc-render` in https://github.com/iterative/dvc-render/pull/99. Do you remember the reason for that change?

@aschuh-hf you should be able to achieve this by using a custom template. In order to achieve this add the template to your project and specify the custom template in your `dvc.yaml`. I've provided a quick example below. I am sure you'd be able to extend this to get the desired behaviour.

<details>

<summary>custom template</summary>


```{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": { "values": "<DVC_METRIC_DATA>" },
  "title": "<DVC_METRIC_TITLE>",
  "width": 300,
  "height": 300,
  "layer": [
    {
      "encoding": {
        "x": {
          "field": "<DVC_METRIC_X>",
          "type": "quantitative",
          "title": "<DVC_METRIC_X_LABEL>"
        },
        "y": {
          "field": "<DVC_METRIC_Y>",
          "type": "quantitative",
          "title": "<DVC_METRIC_Y_LABEL>",
          "scale": { "zero": false }
        },
        "color": { "field": "rev", "type": "nominal" }
      },
      "layer": [
        { "mark": "line" },
        {
          "selection": {
            "label": {
              "type": "single",
              "nearest": true,
              "on": "mouseover",
              "encodings": ["x"],
              "empty": "none",
              "clear": "mouseout"
            }
          },
          "mark": "point",
          "encoding": {
            "opacity": {
              "condition": {
                "selection": "label",
                "value": 1
              },
              "value": 0
            }
          }
        }
      ]
    },
    {
      "transform": [{ "filter": { "selection": "label" } }],
      "layer": [
        {
          "mark": { "type": "rule", "color": "gray" },
          "encoding": {
            "x": {
              "field": "<DVC_METRIC_X>",
              "type": "quantitative"
            }
          }
        },
        {
          "encoding": {
            "text": {
              "type": "quantitative",
              "field": "<DVC_METRIC_Y>"
            },
            "x": {
              "field": "<DVC_METRIC_X>",
              "type": "quantitative"
            },
            "y": {
              "field": "<DVC_METRIC_Y>",
              "type": "quantitative"
            }
          },
          "layer": [
            {
              "mark": {
                "type": "text",
                "align": "left",
                "dx": 5,
                "dy": -5
              },
              "encoding": {
                "color": {
                  "type": "nominal",
                  "field": "rev"
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```


</details>


<details>

<summary>dvc.yaml entry</summary>


```
plots:
  - training/plots/metrics/train/acc.tsv:
      template: ./template.json
      x: step
      y: acc
      y_label: accuracy
```

</details>

<details>

<summary>plot</summary>


https://github.com/iterative/vscode-dvc/assets/37993418/fe9724c6-750b-4a39-9ee1-5e91916c0c2b



</details>

**Comment by aschuh-hf** [comment]
Now that flexibility of customizing the plots is pretty neat! I'll give it a try.

**Comment by shcheklein** [comment]
Related repo and an issue in the Vega repo https://github.com/vega/vega-tooltip/issues/215. Overall we could try to utilize the `vega-tooltip` repo to do custom TB-like tooltip (which I agree are important). Most likely though we'll prioritize the migration / additional support for the Plotly engine (since Vega is too complicate to customize based on the user feedback and has some limitations in ML scenarios). So, let's us get back to this issue a bit later please @aschuh-hf as soon as we migrate to Plotly.

**Comment by dberenbaum** [comment]
AFAICT from the PR, it was an attempt to copy tensorboard's ability to show multiple values per point, but it looks like it came at the expense of showing multiple points at once. From a quick look I'm not sure how easy it is to do both simultaneously even in plotly.

**Comment by aschuh-hf** [comment]
> Most likely though we'll prioritize the migration / additional support for the Plotly engine (since Vega is too complicate to customize based on the user feedback and has some limitations in ML scenarios). So, let's us get back to this issue a bit later please @aschuh-hf as soon as we migrate to Plotly.

Sure, I can work with the template @mattseddon provided for now (and anyway often still use TensorBoard in parallel).

I also find Vega (or Lite), despite how powerful it may be quite difficult to get used to. So far I stayed away from it. I found https://vega.github.io/vega-lite/examples/interactive_multi_line_pivot_tooltip.html to be closest to what I would like, though I wasn't able to figure out how to have the `tooltip` list populated by the experiment `revs` rather than a hard-coded list of experiments as in the example.

> show multiple values per point, but it looks like it came at the expense of showing multiple points at once

Indeed, I was wondering if that was possible. Maybe it's not the highest priority to have that ability, though I did find it quite useful to have the last available metric for any curve prior to the selected timepoint listed alongside others. One might interrupt training runs because its clear they won't perform as expected, especially in case of a hyper-parameter search (e.g., using Ray Tune). Or during live training runs compare the current metric with later times of other curves.

**Comment by shcheklein** [comment]
@aschuh-hf added to the same task list / requirements https://github.com/iterative/dvc-render/issues/7

**Comment by mattseddon** [comment]
WDYT about the tooltip shown [here](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoCJjg40IAAyKQSKFEtXKAJgDstgGY1BcWUgQ4S0wAJyQaWQJ7KEpMCGIvGjhBZUto2xC4BPQcJApZfhwGWQMlTOJ+b19-QMtc-MLi-FRQ8Mjo2PiQAF8FEzMLdABGW3T0ZwAWFzExROqAoPRWiKiHToSlb2TU9HSyrLq8pAKikoysyp8-BcOG0+bl9rW4hN7+80sXUYcnSjEhoYuABsINBYJBc2utSWYRWHReiW2aR++2yIHqx0aZ1Rl3m0PRRxOTVQLVhTxiCLeIFMH3QAGZvo5xpQgXSAJxWAAcdJ5vL5DM2VxqixAj1WFK6gqRuxRIHKt0x93OFSqUJFGKJJRJYvhXSpNMGIAmjN+EyBbjc3P51shwuCZPF60RKWRjlRCs1pTlF1VdpyhKxDwdutefWpA0ssyUY2sLLEbLE1ptgrxIp1z0lIC2Lplbu9aI1geVuLVHsD2uDGdD70NQJNzKBEzpEyG4LbtpuMLajoRUpzdll8v9dyaxd9nYJI61pO7IZ6YYNlg80Z+DbcUazQon6YlG030oHeaHk8Vo5x4-xhfuFdnVfnNcsnPrsbcAKBG4vacru+dO0PyrLJVzy3S8A2vGc4TvfUI3QNln2cd83DpD8QK-W8fz7P89nzQCz3zEs-RPT0b0gn9oNpEAhhsFcmRfKw2wY5dN1Te10KdTDXQA4dT2xfDP1w6cdydcjDQBeCWTcFw3wYkEmP4rtSPY-d+2w48rzw8oCIndTBO-YSFxgyivho34kPomTQTk1DWMU3tlKwwcDm4z0x2s5zywg8l9IfYYBX-Bs2UbVsLKsliFK8uzswco8nKIotgLCuLwKEykDIooZjRM5k3AmNk2WCmTQtLcKe0zKLOPddygL4tykuJTzSurcMKOo-zY3cEYU2K0V9EwRrfwqnCqo0n1ap0h5ev6kTLE6trJhcNlMuY7qzFMfqONzLi6t4zT5O2ia1rnab0GMua-kBFDEtWvq5w2-9Kv21zEvG7VJqOtLDT8mMELpTlTr2671vswa1LAkaVTGsHBLeqCPssJbvsoM18o7fFAdu4HNoe8anu6l6Whhsi4fQDdEffRbUbTQmlPKrGhsehK8ahg6bthnyQDrLLY0bJDKeCanIqSFTHILZnccI-H0bZ5rDSYsnOSsf7aqljDMfu+mccZiXmdew7pcXdAny55xX1fPmlgFsqheirbNZq56dYJvWifZuDjbjNw3eWwiVZp62Qdiu3dshqcWam4nKNaxHXzy82eudv2D1UwOxa17THd91L2bE93zWmOPM6tpORYEr1g4d0PddZl2ZZm07o7pXmup9y291p9XQdD8X08rp3q+82vfPEoE2V+gvW4GunO54svRormeq-D7OEdXF8xFy8eE8F4uYtFru09A3vC6ag3rHE9wC707fhd3ywZBwHAAE9+GUOAmFniHEvvp+X7foM2KzoPSi4kpgTHMhZd8l8AFFxvltb+z9X7v27vieBv934kQinqCO9dV7OH+O+CBEJm7bivjAm2D1UGII-lpFBbAH4IL-hgpeQCvq4JZHSVkBUZJQNsmQgOaJKF-2QSKQR6CGrvXZivWikwR6BUIUtAGpC27+ynrFUR1C9rqKYRIoBpM2EgkVjwzByid5wLoT-Khwi77mIYWIlKWD2aczOqyUeXCGJGKBu3ZOAibFoI0bVLR4j9aGTlvotwQJORuPbMQtGSjJ4dzUb4yxB8RFJMYUEmup8jZnVfBMCYVokzNg8RjLxJd0DqKseUtJdi4nHRAF7Mm65OSEKcYo6BJjYEUOqf4r+3TtHBPSlHNhbgrBDETIU3kxS7x3W8dY+hfjKnUj6Rkgep8c7OIiVE8ERUfZxJmWUpZ8zkn226oE+xJ9DKAnEpJFsUzValNvlUo5QiUlzIsek8594gFDFYdIlknJml3MTp0+mFTXlPPeTU9pXy1lSNMv8S6K09lq1mRC2xPTTnLM+XUoZfyOo7O3BPfZjzDmQoxYRM5E86mzURlMTkCjlZEpRQcsFJyKVYqpdg8S-wvYAyZQ8sxzykHgtJeixeOjT6-N+KyMQrTGVbz4aonxQryUTkpQqi5FE4XMgmKbTe-dr7kNBd0xZ6qDUON0cPMQ9L9WeJUQk5VZLTUco1TCwyTiyYtgZVdfl9rUWioWSKs1zDT6hL+ZsuVPrXXEsFU6oNLrzWasNNk6OQxOQErRr60xXSVXOpVeKgZhoGn6Mid6laWaQXHlZeXTF+a+4hsubi0ygIlZRsTfE-11a561rJQWzJlyaX6JHrakpfqWUmvjXW4+br0o4L+UhRuI7pnMpJV2z+PaxX1olZcqVDZmmRvLdGldsb0V5t7VuwtM1tVr2yXyo9Aqc1xrZWqhNDaWrnxGQuiZfk2m8I6Ua48AB3NgIQADWEBchQCCCK4DYGIP2DgP0-t6UQH0TkRAstuzoUxoerB8DkHoPPvxHh+DUGkOrMMnO00eU03fp-crZFD76YkYI4sljCHyOAMlVav6hCM1oT-R2g57GoNsZA-hjjKyuOGWvXgpsX6JlAsNfwywInCM1sImpzjFrT56PDeaTDJDsPHtw+J0j6nu2abMwR7TSbLAeqHXkpTiqHWqeswhsTcGbNSZ0yE4eVotmWWc-+lT6A1OeYk2RnzdnDbXPcK2pFxmmNAfc6JmDqXEPRZnUW-zbJOSIqw4JnDzGMsRfM7Z7LM0m3ZSbOMiZhnYlJbHSS8L6WvOSexRHdZ8sI0QOC0JlrpW2uRcy517OVHspAlbAVozRWTMlfa2lojIotNZepbuuibJLR0f68VlLi2LPrqswdir1LZOUHCRTGJAnjEDa2q15bbmTtrYjtV9qr4Est3vc1+7Q3HthYy32ijKH3YtisA1qm33s0LZG2V7z066kTdjGIKwYhPuEqh5W2KD2NMTlWwjiOG2ELmlvfK9te3sd-dx8RwHF7kOGnO+vMQ-H+aY4A5Tg7cOOucvZnp6V74Ies-J-N-bsPhvlbp8D2sw8Im8rJ3a6HovzNc6iwT9mYbpX0tmne4XyWOdi-+yAfHPOgEpuGXSfO12hcK6x2iHHlm8e07V0A4t4bR4zczWz0LRuqcO5p8953ay3sm3+ILi2XulVPYN9TlbTuTdrMHW77X8vR2K-18r8X8P4+XKRybD7S77k-dM5zzP3PXXreuVRD3kPddF5hxnw3xvy9dfOxaZCBfgXs7t77o7juA9UoALq9FFHQXwlhlDEBiI-AIggSQAEEHAMDCFAR+thAM0GUPQSwUA5DqAiHAEIth4A0DIFgbfu+2gH9sLkMICADCoGMCAClCA2BsC30obQuhFjOCsKMpQTAIgdhQAIgihMBLAwhZAyBCMEAIg0Af8-8QBkAAAPNAIYJQA2eAoYboboAfJQQQJAR+K-B-UAVoEoTwEDBAIwUAHAGgYgN-cAv3QjT-PQQaMgEINgBgHAJgVfB-WuIfXAxApAMDNAEgx+HAEUEIBgMfJQTAV-QQTAGgQYUAHfWQMwVQ8fNQFAbApQPwHfZQCIMgEQkAOhewOgHg5QuQfQhQuQIw5g7-SgOkJQG-AISwGANgUgQ-HQhAHATAHgzwHQCAOAYfOwuA7QgkW-e-R-QiNwjw2wQI3wKAMAzQUUMQ9UNgCIMAzCSIvgpQWQOAIQ3qNAUIPQJQGw9AF-BgQI9wq-JQKAXwIQywCoqohgMA7AofMMXQtgfQyAow8w+bXw8QywAARwYGOAUPUAUNIFsHGLH1zCX3sFX3QKgB0EWFAAAC8D82A0B-DBBAiwid9BAQMjD255QZDUjLBZA2AYD-BBAehh98DCDD9iDBDhD0BhA8ivlSCIByCQhKDniqgzAnjqChCXD0AYiaiQBEAfC-CAigicClBkBXj0R0j1D4TRQIDviKCqCQBDj9B791Yyja4lA2COCuCeDDAcIrdXkOJrsSRyoBCmBjhlB19N8YAjCIAT8bi74X8382S2iqRETQMjCBiRR3jCMTCoAzC4DXBh9OjujDDkiUDkj25FwzjBj0ARixi6A1BaDCMZiREIxh8+imMRThjRjVDtTJi9TR8RRoh5iV84jljZj1jNjtjYT9i2BDigS1ZTiUj1Sn8riIgdA7iBShChTkjTT0BJSQg6jCMOSNjUCrBZTZA9CDCjClTQA8g2C+AzBGikAUC7pVS-SRRNSLSJjdTpibS75DSlA+iszMgKBczkihCyBkDqyPhh8TTziNTzTxidSpiZCqy5jl9FjqQnTViQANj2C3Tdi4TajPSjjlT7VfTIyAzrjgzsC0S5S0zFTjj7UizVzSy+yrTKzMBZja5h8DjFzQBfAoDZAgCVAaAIAkAmBZidi9iliVijDlAri2gjAGYA1jlwsBCICoD-yABiRaMQZQZQJxcCn5JAZQKAJicCzwM0bkDwIfYfUwdg0DOAAAESQAgDZKXIPH4k-OdJUF-NgN4OnRkLiRAuODAof0MDQKsFwMME5AUE5AH3aJxPID8AfP0OfNfMWHfLgHQMfgQCYE9IADEfBBAABhBcp49E44eDTIdQyS6Sz0gAZVCDYDwuUq9MsGzNXzCOIqQHVJvIEvvO-KfJfLfNhO0pksEHksECUpUtMsyHMs3KAA):



https://github.com/iterative/vscode-dvc/assets/37993418/241bda30-046a-4cad-a2a0-c7e7d0dd87e9

**Comment by aschuh-hf** [comment]
This looks great!

**Comment by aschuh-hf** [comment]
Is it correct, though, that similar to the template I found in the Vega-Lite examples, this requires to be able to set the list of `rev`s in the template. Is there a `<DVC_*>` variable that can be used for this?

I.e., to replace this hard coded list of experiment revs in your example:
```
"encoding": {
    "x": {"field": "step", "type": "quantitative", "title": "step"},
    "color": {
      "legend": {"disable": false},
      "scale": {
        "domain": ["pagan-puns", "soppy-debs", "workspace"],
        "range": ["#945dd6", "#13adc7", "#f46837"]
      }
    },
    "strokeDash": {
      "field": "filename",
      "scale": {
        "domain": ["test/acc.tsv", "train/acc.tsv"],
        "range": [[1, 0], [8, 8]]
      },
      "legend": {
        "disable": false,
        "symbolFillColor": "transparent",
        "symbolStrokeColor": "grey"
      }
    },
```

I tried to adapt this to a `template`, and replaced the `color` specification above by
```
"color": {
    "field": "rev",
    "type": "nominal"
}
```
but I only get a single row with "undefined" in the tooltip. Also the numerical value displayed doesn't match the y axis / expected value. Could you help me adapt the template to get the result you show in your example? Thanks!

<img width="708" alt="Screen Shot 2023-09-08 at 11 36 54 AM" src="https://github.com/iterative/vscode-dvc/assets/77496589/36adfd6c-6a5a-4db8-8e43-d638ab027eb6">

<details>
  <summary>Adapted metrics plot template</summary>

```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": "<DVC_METRIC_TITLE>",
    "width": "container",
    "height": "container",
    "params": [
        {
            "name": "smooth",
            "value": 0.001,
            "bind": {"input": "range", "min": 0.001, "max": 1, "step": 0.001}
        }
    ],
    "layer": [
        {
            "transform": [
                {
                    "pivot": "rev-filename",
                    "value": "<DVC_METRIC_Y>",
                    "groupby": ["<DVC_METRIC_X>"]
                }
            ],
            "mark": {
                "type": "rule",
                "tooltip": {
                    "content": "data"
                }
            },
            "encoding": {
                "opacity": {
                    "condition": {
                        "value": 0.3,
                        "param": "hover",
                        "empty": false
                    },
                    "value": 0
                }
            },
            "params": [
                {
                    "name": "hover",
                    "select": {
                        "type": "point",
                        "fields": [
                            "<DVC_METRIC_X>"
                        ],
                        "nearest": true,
                        "on": "mouseover",
                        "clear": "mouseout"
                    }
                }
            ]
        },
        {
            "encoding": {
                "y": {
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            },
            "layer": [
                {
                    "mark": "line"
                },
                {
                    "transform": [
                        {
                            "filter": {
                                "param": "hover",
                                "empty": false
                            }
                        }
                    ],
                    "mark": "point"
                }
            ],
            "transform": [
                {
                    "loess": "<DVC_METRIC_Y>",
                    "on": "<DVC_METRIC_X>",
                    "groupby": [
                        "rev",
                        "filename",
                        "rev-filename",
                        "field",
                        "filename::field"
                    ],
                    "bandwidth": {"signal": "smooth"}
                }
            ]
        },
        {
            "mark": {
                "type": "line",
                "opacity": 0.2
            },
            "encoding": {
                "x": {
                    "field": "<DVC_METRIC_X>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_X_LABEL>"
                },
                "y": {
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            }
        },
        {
            "mark": {
                "type": "circle",
                "size": 10
            },
            "encoding": {
                "x": {
                    "aggregate": "max",
                    "field": "<DVC_METRIC_X>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_X_LABEL>"
                },
                "y": {
                    "aggregate": {
                        "argmax": "<DVC_METRIC_X>"
                    },
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            }
        }
    ],
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative",
            "title": "<DVC_METRIC_X_LABEL>"
        },
        "color": {
            "field": "rev",
            "type": "nominal",
            "legend": {
                "disable": false
            }
        },
        "shape": {
            "legend": {
                "disable": false,
                "symbolFillColor": "grey"
            }
        }
    }
}
```

</detail>

**Comment by aschuh-hf** [comment]
Also note that with the template above, when I click on a plot to show the detail and test the new zoom and pan (which wasn't working for me with the previous template yet using v1.0.52 of the DVC extension), no plot is shown, just an empty canvas. Certainly because there's something off with my attempt to adjust the template.

**Comment by aschuh-hf** [comment]
I checked the output `index.html` of `dvc plots show` / `dvc plots diff` when using the `--open` flag and  realized that `rev-filename` as used in the example is not a `data` field of `<DVC_METRIC_DATA>`. So I replaced it with `rev`. The tooltip works when I view this index HTML page in the browser (there is an odd `undefined` rev, but that's likely a different issue).

I wasn't yet able to test it in the extension because `dvc` still uses the wrong template (not the one in the current modified `dvc.yaml` in the workspace). For the other `dvc plots` commands, I used the `--template` option to force a specific one I wanted to test.

<img width="987" alt="Screen Shot 2023-09-08 at 12 23 29 PM" src="https://github.com/iterative/vscode-dvc/assets/77496589/10733ca8-35f0-47ee-acb9-2642705a7c93">

<details>
  <summary>Plot template</summary>

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "title": "<DVC_METRIC_TITLE>",
    "width": 800,
    "height": 600,
    "params": [
        {
            "name": "smooth",
            "value": 0.001,
            "bind": {"input": "range", "min": 0.001, "max": 1, "step": 0.001}
        }
    ],
    "layer": [
        {
            "transform": [
                {
                    "pivot": "rev",
                    "value": "<DVC_METRIC_Y>",
                    "groupby": ["<DVC_METRIC_X>"]
                }
            ],
            "mark": {
                "type": "rule",
                "tooltip": {
                    "content": "data"
                }
            },
            "encoding": {
                "opacity": {
                    "condition": {
                        "value": 0.3,
                        "param": "hover",
                        "empty": false
                    },
                    "value": 0
                }
            },
            "params": [
                {
                    "name": "hover",
                    "select": {
                        "type": "point",
                        "fields": [
                            "<DVC_METRIC_X>"
                        ],
                        "nearest": true,
                        "on": "mouseover",
                        "clear": "mouseout"
                    }
                }
            ]
        },
        {
            "encoding": {
                "y": {
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            },
            "layer": [
                {
                    "mark": "line"
                },
                {
                    "transform": [
                        {
                            "filter": {
                                "param": "hover",
                                "empty": false
                            }
                        }
                    ],
                    "mark": "point"
                }
            ],
            "transform": [
                {
                    "loess": "<DVC_METRIC_Y>",
                    "on": "<DVC_METRIC_X>",
                    "groupby": [
                        "rev",
                        "filename",
                        "field",
                        "filename::field"
                    ],
                    "bandwidth": {"signal": "smooth"}
                }
            ]
        },
        {
            "mark": {
                "type": "line",
                "opacity": 0.2
            },
            "encoding": {
                "x": {
                    "field": "<DVC_METRIC_X>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_X_LABEL>"
                },
                "y": {
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            }
        },
        {
            "mark": {
                "type": "circle",
                "size": 10
            },
            "encoding": {
                "x": {
                    "aggregate": "max",
                    "field": "<DVC_METRIC_X>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_X_LABEL>"
                },
                "y": {
                    "aggregate": {
                        "argmax": "<DVC_METRIC_X>"
                    },
                    "field": "<DVC_METRIC_Y>",
                    "type": "quantitative",
                    "title": "<DVC_METRIC_Y_LABEL>",
                    "scale": {
                        "zero": false
                    }
                },
                "color": {
                    "field": "rev",
                    "type": "nominal"
                }
            }
        }
    ],
    "encoding": {
        "x": {
            "field": "<DVC_METRIC_X>",
            "type": "quantitative",
            "title": "<DVC_METRIC_X_LABEL>"
        },
        "color": {
            "field": "rev",
            "type": "nominal",
            "legend": {
                "disable": false
            }
        },
        "shape": {
            "legend": {
                "disable": false,
                "symbolFillColor": "grey"
            }
        }
    }
}
```

</details>

**Comment by mattseddon** [comment]
I'm sorry, the linked template was not designed to be reused or adapted. I was looking for feedback on the appearance/contents of the tooltip. 

Seeing as you are only using `rev` and not `filename` or `field` in the template this one should work for you:

<details> 

<summary>Custom template</summary>

```json

{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": "<DVC_METRIC_DATA>"
  },
  "title": "<DVC_METRIC_TITLE>",
  "width": "container",
  "height": "container",
  "params": [
    {
      "name": "smooth",
      "value": 0.001,
      "bind": {"input": "range", "min": 0.001, "max": 1, "<DVC_METRIC_X>": 0.001}
    }
  ],
  "layer": [
        {
      "encoding": {
        "y": {
          "field": "<DVC_METRIC_Y>",
          "type": "quantitative",
          "title": "<DVC_METRIC_Y_TITLE>",
          "scale": {"zero": false}
        },
        "color": {"field": "rev", "type": "nominal"}
      },
      "layer": [
        {"mark": "line"},
        {
          "transform": [{"filter": {"param": "hover", "empty": false}}],
          "mark": "point"
        }
      ],
      "transform": [
        {
          "loess": "<DVC_METRIC_Y>",
          "on": "<DVC_METRIC_X>",
          "groupby": ["rev"],
          "bandwidth": {"signal": "smooth"}
        }
      ]
    },
    {
      "transform": [
        {"pivot": "rev", "value": "<DVC_METRIC_Y>", "groupby": ["<DVC_METRIC_X>"]}
      ],
      "mark": {"type": "rule", "tooltip": {"content": "data"}},
      "encoding": {
        "opacity": {
          "condition": {"value": 0.3, "param": "hover", "empty": false},
          "value": 0
        }
      },
      "params": [
        {
          "name": "hover",
          "select": {
            "type": "point",
            "fields": ["<DVC_METRIC_X>"],
            "nearest": true,
            "on": "mouseover",
            "clear": "mouseout"
          }
        }
      ]
    },
    {
      "mark": {"type": "line", "opacity": 0.2},
      "params": [{ "bind": "scales", "name": "grid", "select": "interval" }],
      "encoding": {
        "x": {"field": "<DVC_METRIC_X>", "type": "quantitative", "title": "<DVC_METRIC_X>"},
        "y": {
          "field": "<DVC_METRIC_Y>",
          "type": "quantitative",
          "title": "<DVC_METRIC_Y_TITLE>",
          "scale": {"zero": false}
        }
      }
    },
    {
      "mark": {"type": "circle", "size": 10},
      "encoding": {
        "x": {
          "aggregate": "max",
          "field": "<DVC_METRIC_X>",
          "type": "quantitative",
          "title": "<DVC_METRIC_X>"
        },
        "y": {
          "aggregate": {"argmax": "<DVC_METRIC_X>"},
          "field": "<DVC_METRIC_Y>",
          "type": "quantitative",
          "title": "<DVC_METRIC_Y_TITLE>",
          "scale": {"zero": false}
        },
        "color": {"field": "rev", "type": "nominal"}
      }
    }
  ]
}

```

</details>

☝🏻 the above template should have zoom on scroll and the previously shown tooltips. Something similar should be the default template soon.

> I wasn't yet able to test it in the extension because dvc still uses the wrong template (not the one in the current modified dvc.yaml in the workspace)

The only way to force DVC to use the updated template is to select the `workspace` as a revision for plotting.

**Comment by aschuh-hf** [comment]
Just FYI, I had to update one occurrence of `acc` in the provided [template](https://github.com/iterative/vscode-dvc/issues/4532#issuecomment-1712964405) by `<DVC_METRIC_Y>`:

```
"transform": [
                {
                    "pivot": "rev",
                    "value": "<DVC_METRIC_Y>",
                    "groupby": [
                        "<DVC_METRIC_X>"
                    ]
                }
            ],
```
