### ISSUE TITLE
Error in Experiments table when using dvc hydra integration to generate params.yaml

### ISSUE THREAD

**Issue by lainisourgod** [iterative/vscode-dvc#4552]
Hello! I'm using dvc hydra integration and dvc generates correct params.yaml file from my config dir. But in the Experiments table, error says file isn't present. It's strange because I can crealy see generated params.yaml at the root of project.

<img width="478" alt="image" src="https://github.com/iterative/vscode-dvc/assets/24773652/66edf83e-cd3e-48a0-ac72-454960ad0e03">

Also, may be irrelevant, but error and info windows overlap here.
<img width="407" alt="SCR-20230822-riyx" src="https://github.com/iterative/vscode-dvc/assets/24773652/d20402d7-7072-4971-91a8-cccc07a8d8a9">

**Comment by mattseddon** [comment]
Does this error occur in the CLI version of the table? I.e. `dvc exp show`?

**Comment by mattseddon** [comment]
This seems relevant: https://github.com/iterative/dvc/issues/8486#issuecomment-1301312312

**Comment by shcheklein** [comment]
@lainisourgod could you please check if the generated `params.yaml` is tracked by Git in your case?

**Comment by shcheklein** [comment]
@dberenbaum @daavoo @pmrowla anything rings the bell for you folks? (as you are more familiar with Hydra-related workflow).

**Comment by dberenbaum** [comment]
Agreed that it seems most likely that `params.yaml` is not tracked by Git. @daavoo Do you remember if we are force adding `params.yaml` as part of the work done in https://github.com/iterative/dvc/issues/8972?

**Comment by lainisourgod** [comment]
yeah, it sure was a problem with not tracking params.yaml. for a second I thought it would be ok to delete params.yaml as I store my configuration in hydra, but it's not entirrely determenistic:
- we can override hydra conf param with cli `+param=val` syntax
- we can override param that is defined in multiple config files
