### ISSUE TITLE
Story: Show other branches in experiments webview

### ISSUE THREAD

**Issue by aguschin** [iterative/vscode-dvc#456]
Right now "Show experiments" webview doesn't show other branches but master:
![image](https://user-images.githubusercontent.com/6797716/118955676-95be9f80-b967-11eb-8919-367fbc3a5709.png)

It would be great to see other branches here as well, because sometimes we could be interested in comparing to one of them instead of master or current workspace version.

**Comment by mattseddon** [comment]
Closing in favour of #1966
