### ISSUE TITLE
[Feature Request] Verbose Flexibility in Table Features from W&B

### ISSUE THREAD

**Issue by SoyGema** [iterative/vscode-dvc#4567]
Hello there.
Im trying W&B and finding interesting capabilities that might be useful for the extension. Not super important, but I found really great the flexibility that it offered . Somehow they give me options for customizing the table in a more UX and verbose manner.
I´ve missed a few releases so unclear to me if this is on roadmap or done already.
Naming it here prioritized by usefulness

- [ ] Renaming runs/experiments
- [ ] Notes as column (brief note with changes in between experiments) without the need of having another column or add a brief sentence about the experiment iteration

In the video at first Im also experimenting with dropping UI . I remembered that I could do it in the extension at first when I entered show experiments , Im assuming that also once they are finished.

https://github.com/iterative/vscode-dvc/assets/24204714/ceb59cf2-3ff5-4e15-95ef-9457f57b2f38

Thanks for the time dedicated to think about this
Cheers

**Comment by mattseddon** [comment]
Same discussion came up in #4330

**Comment by SoyGema** [comment]
Hey `True`
I remember going through the issue but didn´t follow up.
Is that okay if I close this one to remove duplicates? LMK if I might share some things there then.
