### ISSUE TITLE
Experiments: Option to combine filters using OR instead of AND

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4613]
Is it possible to apply multiple filters and get the union of the filtered experiments rather than intersection?

For example, to create a filter such as "starred=True OR Created after", where I may have starred past experiments already, but newly added ones I might also want to see and thus select them by date.

**Comment by shcheklein** [comment]
It's not possible atm. We'll discuss this and see if we can do it next few sprints. Do you need both - AND and OR semantics simultaneously? Would a single toggle work for you?

**Comment by aschuh-hf** [comment]
This is not an urgently needed feature. I was mainly coming across wanting to filter as described, i.e., based on two criteria (starred OR created after). For this use case, a toggle would suffice.

Would be great if one could combine AND and OR logic more generically, though I also couldn't tell how often it would be used or how not to make it confusing. One immediate idea may be to have in the "Filter By" window the ability to create an OR filter, which as children has the filters to be combined (one could add filters by dragging them to make them children if a filter allows that). At the top-level, AND would be applied. Just a thought.
