### ISSUE TITLE
`Custom Plots`: honor selected revisions and colors.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#4624]
When adding a `Custom Plot`, _all_ the experiments in the table are included in the plot, but there is no signal of which revision is which (except for the tooltip).

![Screenshot 2023-09-06 130013](https://github.com/iterative/vscode-dvc/assets/12677733/120a0d9e-12b5-45e6-b249-cc94c5ad83b2)

I was expecting the `Custom Plot` to be linked to the selected revisions and to include color and legend, matching the behavior of `Data Series` plots:

![Screenshot 2023-09-06 130003](https://github.com/iterative/vscode-dvc/assets/12677733/899e23d0-383c-442f-9f07-fb76639f9b88)

**Comment by julieg18** [comment]
I think adding colors/legend would get hard to manage since the idea of custom plots is that you're able to see all experiments/commits while data series only have a max of 7. If a user had a lot of exps/commits a legend would look strange 🤔 

Maybe we could add an always visible label to each scatter point? Would need to test how that looks, though.

**Comment by mattseddon** [comment]
Could we try coloring/highlighting the selected revisions with the appropriate colors?

**Comment by mattseddon** [comment]
Something like this:

<img width="513" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/47749c96-5bd7-4ae1-813d-f2c8a173826d">

[Vega editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUMSSCGcCGgDaoGsrQgADFCgBOAIwA2B4pAI4mAE40oaC5RtiNg4ATBYAHDYAzBYWdmJiDgAsSjhIHkgIvpQxkQC+CiZm6Mg08kpunt5ZAUGhEdGx8UkpaRlZOfmF5g6RDgBmdol9LhVePqh+NSHhUTFxCckgqemZE9kWeQUgpuYyODgAnvzKcEwG5e5j1WKJYWJ2YQ5iAOwOYYmRwQ4tK+0bCZ1tkUlkgKLJ+DgGLJzq5LlU1kFHpFEs93sFgo5EjZgj82mscmJATt0Kkwfw4FcLpVxpNnpE7ljArE7BZns8bLjVn4YsEicCIDQAB6YI4yBiCEZwmn+OkMmrM1nszl-XlbYkgDwMBAII5kOCyBiS6nVZ6hYIomxhSJRc0BZX4jbomz2DF88wAdzoMCOfQ8bDgRquCNNFnN7KtNsZ9u5juCzrsqq66CYNEkbAY-Hd-pho3htLNFojnyjIN+Ds+cZdbvQEEwULI-FkNAQOalJuCzwszrEkVRWMSX2j6wr8erIBkwmU-AAXjQ8IG8zLEjdgvEwnYbRY3kOck6bGOIDg2B5MPwmGkANYL6U2Z7LgdrjefLdhHex51jtiCODefhQL+tsawb3quYjrpu26lniMYjvuAC6+QgPq-7KKUZBoKA-6CMeGEgH0NBwIIwI7Eo0A6AGmgqGwJTyKghjjkKIr8GKEpKCmaYZlm+guHshzHKcMKkkg4KQtCLhWLYjjOOUSClC4PT9IMwwtGSFJVEomrarq+qGkonr0D6foBqRdayA2TYtjxX6mDOc4woex6nueHhXkoX4-lAf4ASAcEacJepGCAADENjLsoyjScFdiREgyhQM8LhBX0iRvL2iV2H0bJMIk6WZc82W5VlOVKEFGVFYV+XFVFeUFSVZWVRVtXVeVdU1VVpVtT5uSIYKuFIIKNAGJRghIEwhEADLNnQaDPGISiYHQ34AAqxahZloNEiH4YRwLLG0pFQORuHThSbBoH0OgQHAiELZg37mHtLaUAcGSCKgggeC4Io4BRIAAI4MMJt1qDQpAgIhBx9QNQ2gCNY2CJNCDTags3zYtcAreFaEbRYW0EUR5i5j4B1HZRJ1+udl3XWjd2-Z4slNmZBBExAUgyLIqCYPomCUNhEAwt9v0A0DdAg2D3VKPANBkFg5j-rI6ilBSLgjQcyt0aAyFsGt6GUZgbBfgtOBGKA20E+gJEgLd90W2YgJm8CRNfej5j06UaHM1KrPSHInPc7zbD8+DWwOw9rSZDTNtQU9L0IG9H3gwhMkubh+GCN+RSeHopE0CdaAOBY80HD9D1sKUmDg7kvkgJ6yj0HLciK7Iyu5EAA)
