### ISSUE TITLE
`Plots`: Fail to render custom vega template.

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#4638]
- `train.py`

```py
import random
import numpy as np
from dvclive import Live

random_generator = random.Random()

with Live(report=None, save_dvc_exp=True) as live:
    datapoints = [
        {"category": "feedback", "group": "deck", "macroF1": random_generator.random()},
        {
            "category": "feedback",
            "group": "deck shift",
            "macroF1": random_generator.random()
        },
        {
            "category": "feedback",
            "group": "earliest quint",
            "macroF1": random_generator.random()
        },
        {"category": "planning", "group": "deck", "macroF1": random_generator.random()},
        {
            "category": "planning",
            "group": "deck shift",
            "macroF1": random_generator.random()
        },
        {
            "category": "planning",
            "group": "earliest quint",
            "macroF1": random_generator.random()
        }
    ]
    live.log_plot(
        "custom_bar", 
        datapoints, 
        x="group", y="macroF1", template="custom_template.json",
        title="Classification Metrics"
    )
```

- `custom_template.json`

```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
    "data": {
        "values": "<DVC_METRIC_DATA>"
    },
    "width": 600,
    "height": 300,
    "title": {"text": "<DVC_METRIC_TITLE>", "anchor": "middle"},
    "encoding": {
      "column": {"field": "category", "header": {"orient": "bottom"}},
      "y": {"field": "<DVC_METRIC_Y>", "type": "quantitative"},
      "x": {"field": "<DVC_METRIC_X>", "axis": null},
      "color": {"field": "<DVC_METRIC_X>"}
    },
    "config": {"view": {"stroke": "transparent"}},
    "mark": "bar"
}
```

- `dvc plots show`

![Screenshot 2023-09-07 202739](https://github.com/iterative/vscode-dvc/assets/12677733/74295514-c387-4dab-96f5-967027c4110a)

- Extension

![Screenshot 2023-09-07 202800](https://github.com/iterative/vscode-dvc/assets/12677733/57115fb3-d498-4397-984e-6e2f6ea9a459)

**Comment by mattseddon** [comment]
Thanks for the report. I'll take a look.

**Comment by daavoo** [comment]
> One question. How would this graph render for multiple experiments or it can't/shouldn't?

In DVC/Studio it gets rendered like a confusion matrix or an image , completely separated per revision

**Comment by mattseddon** [comment]
Can you provide an example project/screenshot of the behaviour in Studio? I can check the HTML produced by DVC.

**Comment by daavoo** [comment]
> Can you provide an example project/screenshot of the behaviour in Studio? I can check the HTML produced by DVC.

![image](https://github.com/iterative/vscode-dvc/assets/12677733/3b65d287-542c-4777-a61c-123d7b635582)

**Comment by mattseddon** [comment]
The problem is that the extension is not set up to handle plots that cannot be grouped for revisions at all.

A quick look in Studio yielded this function:

```
/*
 * If Vega spec contains "rev" field,
 * a plot will display data from different commits
 */
const isMultiCommitDataPlot = (template: TopLevelSpec): boolean =>
  JSON.stringify(template).includes(`"${PLOT_REV_FIELD}"`)
```

Really these plots should appear under the current `images` section (section will need a new name, description, etc) to match the behaviour in Studio:

![image](https://github.com/iterative/vscode-dvc/assets/37993418/996d1fc1-96c7-494d-a5cd-0d2dbea768b0)


There is a bit of work here to fix this correctly.

cc @shcheklein

**Comment by shcheklein** [comment]
Should it be though the same as confusion matrix?

**Comment by mattseddon** [comment]
> Should it be though the same as confusion matrix?

Not if we respect the user-defined template.

**Comment by dberenbaum** [comment]
The problem is specific to a template that is missing `rev`, right?

**Comment by mattseddon** [comment]
> The problem is specific to a template that is missing `rev`, right?

That is correct.

**Comment by shcheklein** [comment]
@daavoo did it happen while you were trying to solve some customer issue? (we need to prioritize this)

**Comment by daavoo** [comment]
> @daavoo did it happen while you were trying to solve some customer issue? (we need to prioritize this)

No, I just noticed it because is one of the plots I have in a fixture repo.
