### ISSUE TITLE
Stale secret deletion

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/vscode-dvc#4661]
It looks like the following GitHub Actions secrets aren't being used in any of your workflows, at least on the default branch:
* CC_TEST_REPORTER_ID

Please ping @iterative/security before 2023-09-22 if you'd like to preserve them.

**Comment by mattseddon** [comment]
It is used here: https://github.com/iterative/vscode-dvc/blob/main/.github/workflows/continuous-integration.yml#L47

**Comment by mattseddon** [comment]
@iterative/security do not delete that secret.

**Comment by 0x2b3bfa0** [comment]
Sorry, @mattseddon! I saw the issue “closed as completed” and thought I closed it myself. 🙈

**Comment by 0x2b3bfa0** [comment]
Can you please set that secret again?

**Comment by mattseddon** [comment]
Yep done.
