### ISSUE TITLE
[BUG] Plot disappearing : zooming , smoothing & minimizing Data Series Section

### ISSUE THREAD

**Issue by SoyGema** [iterative/vscode-dvc#4671]
### Bug Description
After Zooming the plot and doing some smoothing, I minimized Data Series section.
The plot disappeared. Tested it a few times and it seems to happen when I use the smoothing feature in Zoom and min/max Data Series.
If I restart VSCode the plot reappears.
DVC VSCODE `v==1.0.54`

https://github.com/iterative/vscode-dvc/assets/24204714/e8bd7621-6ee6-4c47-b4e6-c63f76d87673

### Expected Behaviour
Not disappearing plot

**Comment by mattseddon** [comment]
Thanks for the report. I'll take a look next week.
