### ISSUE TITLE
custom plots issues

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4725]
I ran into a couple unexpected issues with custom plots. Here's what I saw using https://github.com/iterative/example-get-started-experiments/:

<img width="994" alt="Screenshot 2023-09-27 at 8 22 07 AM" src="https://github.com/iterative/vscode-dvc/assets/2308172/6f9b39b8-e045-4563-8ef8-cd120a9bb9c0">

There are two unexpected behaviors:

1. It shows unselected revisions (all of the revs with the same color were not selected for plots).
2. The x-axis only shows one value for this string/categorical parameter. Here are the actual values for that parameter:

<img width="638" alt="Screenshot 2023-09-27 at 8 26 47 AM" src="https://github.com/iterative/vscode-dvc/assets/2308172/a03b8271-6716-42b0-9b05-3d4b05a11ea6">

**Comment by julieg18** [comment]
> It shows unselected revisions (all of the revs with the same color were not selected for plots).

This is expected. Custom plots are supposed to show all experiments in the table. 

<img width="482" alt="image" src="https://github.com/iterative/vscode-dvc/assets/43496356/91715d5a-fc4e-4b69-bc78-bf6d12cf4ff0">

> The x-axis only shows one value for this string/categorical parameter. Here are the actual values for that parameter:

Looks to be a bug, let me see if I can reproduce 👀

**Comment by julieg18** [comment]
> Looks to be a bug, let me see if I can reproduce 👀

Hmmmm, x-axis is showing correctly on my end:

<img width="1718" alt="image" src="https://github.com/iterative/vscode-dvc/assets/43496356/6ec8729b-52b5-41b9-8a02-85064a269317">

@dberenbaum, can you:
* check what the `dice_multi` metric value is for your `podgy-sima` experiment? 
* export the plot as json? I'd like to see what experiments/values are inside the `json` file.

**Comment by dberenbaum** [comment]
My mistake @julieg18! I think I must have chosen the wrong `dice_multi` column that only appeared in one experiment. Now it looks like expected:

<img width="990" alt="Screenshot 2023-09-27 at 9 25 44 AM" src="https://github.com/iterative/vscode-dvc/assets/2308172/ad63ad23-cc07-4615-976d-26640eec0edb">
