### ISSUE TITLE
Improve Table Flattening on Sort

### ISSUE THREAD

**Issue by julieg18** [iterative/vscode-dvc#4746]
- [x] Remove possible duplicate rows (https://github.com/iterative/vscode-dvc/pull/4685#discussion_r1338040254)
- [ ] Make "Parent" and "Branch/Tags" columns sticky (https://github.com/iterative/vscode-dvc/pull/4691#discussion_r1338145437)

Followup to #4685

**Comment by mattseddon** [comment]
Will come back to this once we get feedback from the user 🙏🏻.
