### ISSUE TITLE
Experiments: Table did not update after "dvc exp rename" CLI use

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/vscode-dvc#4778]
I renamed an experiment using DVC CLI 3.22.1 using `dvc exp rename` in the Terminal. I can see with `dvc exp show` that the experiment was successfully renamed. However, the Experiments table of the VS Code extension v1.1.2 did not update and continued to show the previous experiment name.

PS: After clicking on the "+" button to show more commits to trigger an update of the table, the new name shows up.

**Comment by mattseddon** [comment]
I'm 95% sure that the root cause of this will be the same as for #4779. We will track the issue there.
