### ISSUE TITLE
Update WebdriverIO

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#4804]
Here is a summary of what's been going on with the WebdriverIO update (#4760).

- E2E tests fail when updating
- It is possible to get the tests to pass locally by running them more than once
  - They usually get stuck on `dvc pull` on the first run (it might have to do with how we check for progress bars or if dvc is working to continue)
  - Tests have a better chance of passing when we run them directly from the "extension" directory (`yarn run test-e2e` instead of `yarn test:e2e`)
  - The best way to test to see if the tests are passing is to delete the demo project and to run `yarn && yarn test:e2e` again (while setting `cache: false` to `test-e2e` in `turbo.json`.
  - VS Code version needs to be on "stable" in order for the tests to pass.
- Sometimes there is also a timeout on `runModifiedExperiment`. This might be solved by simply increasing the timeout for that test (or reducing the number of epochs in `params.yaml` for the tests).
- Simply increasing timeouts (even to very large numbers) does not seem to work
- It is unclear why updating webdriverio monorepo cause the tests to fail. The likely reason is that we are still on Node v16.

The recommendation is to wait for new versions of either VS Code or WebdriverIO to be release, or for us to move to a new version of Node before trying again.

**Comment by mattseddon** [comment]
potentially this is related: https://github.com/webdriverio/webdriverio/pull/11172

**Comment by mattseddon** [comment]
There is definitely something/a bug wrt timeouts. The timeout for the failing test is 21000ms but the whole suite finishes in < 3 minutes:

![image](https://github.com/iterative/vscode-dvc/assets/37993418/37c17c7e-9787-4592-8c51-d1fc737f9ca1)

**Comment by mattseddon** [comment]
Update on this:

I'm looking at upgrading to v6. Seems like we get unexpected behaviour whenever we use `browser.keys` in combination with `workbench.executeCommand`.

I will take this as part of the node 18 upgrade.... 🤸🏻
