### ISSUE TITLE
Feature request: Filter the experiment table by tag

### ISSUE THREAD

**Issue by francesco086** [iterative/vscode-dvc#4878]
## Short description

In the context of an model/artifact registry set with gto, it would be very handful to be able to filter the experiment table by tag.

## Example

For example, imagine that I have a model registry with the following artifacts

- base-churn-time-series
- base-churn-hierarchical-model
- acquisition-time-series

and therefore I have git tags created by gto, like

- base-churn-time-series@v1.0.0
- base-churn-time-series@v1.0.1
- base-churn-time-series#prod#1
- base-churn-hierarchical-model@v1.0.0
- base-churn-hierarchical-model@v2.0.0
- acquisition-time-series@v1.0.0
- acquisition-time-series#prod#1

and when I look at the experiment table, I would like to focus on type of artifact at a time. It would be nice to be able to filter by a regex or substring, e.g. "base-churn", or "acquisition", or "base-churn-time-series".

## Workarounds

Of course I could get around this issue by adding this information in the params.yaml, but it is somewhat redundant, I think.

Perhaps there are other ways I could not think of...

**Comment by mattseddon** [comment]
Hi @francesco086,

Thanks for raising. I've opened #4882 to address this.

Here is a demo of the feature:

https://github.com/iterative/vscode-dvc/assets/37993418/1ab9a3e7-dd26-40f3-b8d9-7f170cf58b61

Please let me know if you have any feedback or would like any changes.

Thanks

**Comment by francesco086** [comment]
Wow! That was fast!
And very good too! 

I have only one small suggestion for something to check, perhaps it's already implemented but I don't know the base code enough to tell. If you open the "Command Palette", and select "DVC: Add filter to experiments table", will you be prompted to filter by tag too?

**Comment by mattseddon** [comment]
> If you open the "Command Palette", and select "DVC: Add filter to experiments table", will you be prompted to filter by tag too?

Yep, that is covered.

**Comment by francesco086** [comment]
Then that's it, I'd say! 

Thank you so much, really impressive to see how fast this was addressed.

**Comment by mattseddon** [comment]
The feature went out with `1.1.11`
