### ISSUE TITLE
Review context menus and remove items that are never available

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#5051]
From Discord (and I hit also a few times).

<img width="455" alt="Screenshot 2023-11-30 at 1 15 41 PM" src="https://github.com/iterative/vscode-dvc/assets/3659196/68c59632-d7f5-4e86-aec9-e1ec3783f8df">

If actions are _never_ possible we should hide those actions.

**Comment by mattseddon** [comment]
https://github.com/iterative/vscode-dvc/pull/3808#issuecomment-1532126703

**Comment by shcheklein** [comment]
Yep, I remember the context and a few discussions. I think we overdid it a bit. With items that are _never_ available, no matter what is happening around (other commands are running ,etc). I still believe that if it's temporary disabled we can show it. If there is a way to explain why it is disabled - even better.
