### ISSUE TITLE
Plots sections is not responsive when exp push is happening

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#5052]
Experiments pushing should not be blocking any operations

<img width="628" alt="Screenshot 2023-11-30 at 1 29 48 PM" src="https://github.com/iterative/vscode-dvc/assets/3659196/7200c3d4-ed4f-4d57-a88c-ddb964b2ef72">

**Comment by mattseddon** [comment]
Can you please give some more context. Was the webview open before you started pushing the experiment? Did it previously contain plots? What is going on?

**Comment by shcheklein** [comment]
Yes, it was open. Yes it had some plots on it. 

After I initiated push and opened the plots back that what I saw.

I don't have much more details atm. I can try to reproduce and get more details.

Btw, even after push was done, the screen was staying still in that state.

**Comment by mattseddon** [comment]
The error is likely unrelated. If it happens again can you please check developer tools for errors:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/3d4e1a00-8371-4da1-9a74-22c5568dfc02">

**Comment by shcheklein** [comment]
I've shared the video directly in Slack for this issue (too large to put here): https://iterativeai.slack.com/archives/C01RB7BTG4C/p1701386048xxxx65
