### ISSUE TITLE
Error is not handled in remote add operation in non DVC repo

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#5095]
When I'm trying to add a remote in a repo that is not DVC in the setup DVC workflow
I'm getting Operation Successful, while actually DVC is complaining in the DVC Output
We should show a proper error message there

**Comment by julieg18** [comment]
What command(s) were producing errors in the DVC Output? If `dvc remote add --project <NAME> <URL>` produced an error, the Toast should be showing the error.

**Comment by shcheklein** [comment]
I think it was `remote add`, but it was not showing the toast for me.

A few things for the context. I was running a bit older version of the extension there (1.4.1). Also, I was adding a local remote.

name - storage
url - /tmp/storage
