### ISSUE TITLE
DVC is not initialized

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#5119]
I'm getting this error when running the [example notebooks](https://github.com/iterative/dvclive/tree/main/examples) inside dvclive.

<img width="1338" alt="Screenshot 2023-12-14 at 1 12 34 PM" src="https://github.com/iterative/vscode-dvc/assets/2308172/e03e2fb7-0d3d-497e-9e64-f5a039f1e30d">

Any ideas why?

**Comment by mattseddon** [comment]
I think the fact that you're using a dev version is what's messing with the extension

**Comment by dberenbaum** [comment]
It might be specific to dvclive. We have `.dvc` in `.gitignore` for that repo. The extension works fine when I run the same example notebook in another repo, so I'm fine to close this.
