### ISSUE TITLE
plots wizard: indentation issue

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#5122]
When I used the `Add a plot` functionality, I ended up with an invalid dvc.yaml due to wrong indentation:

https://github.com/iterative/vscode-dvc/assets/2308172/c3298657-1031-4de0-9f9f-fb96a09dc1bd

**Comment by julieg18** [comment]
Our `yaml` library doesn't work with list items that have an indentation level of 0. I think I can add a solution that checks for this and updates the yaml text manually. Will be a little hacky though :)
