### ISSUE TITLE
*DVC* Studio name correction to Authentication Flow

### ISSUE THREAD

**Issue by jendefig** [iterative/vscode-dvc#5139]
🎨👮🏼‍♀️(branding police 😬) 
I just went to put up the @julieg18's Connecting to DVC Studio with Authentication Flow video and saw that we are missing the "DVC" in the DVC Studio name.  Can we please fix that?

<img width="844" alt="image" src="https://github.com/iterative/vscode-dvc/assets/34289199/97db1b80-5707-4b7d-8c43-b0f151f723c1">

Once it's complete I can just take a screen shot and edit the video, so there's no need to re-record it.  I just don't want to put it up this way. (I can't do that kind of editing in YouTube.)

**Comment by julieg18** [comment]
#5131 has been released which updated titles and #5142 will take care of text instances once merged.

**Comment by jendefig** [comment]
Thanks @julieg18! 🙏 🙇‍♀️
