### ISSUE TITLE
Plots modify wizard

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#5153]
Now that we have the plots wizard to create new plots, it would be great to also be able to choose an existing plot and modify it using the wizard. In other words:

1. When viewing a plot, have an option to modify it.
2. When you choose to modify it, we open the plots wizard but preselect the existing options for it.

**Comment by julieg18** [comment]
I don't think this is easily doable since it's hard to alter `yaml` file lines without possibly breaking things. The solution would most likely be flaky 🤔

**Comment by dberenbaum** [comment]
In DVC CLI, we already have lots of tooling to try to modify yaml in-place, so this could depend on CLI support first (see https://github.com/iterative/dvc/issues/7753).
