### ISSUE TITLE
Reduce the number of branches in the switch / case that feed the webviews stores

### ISSUE THREAD

**Issue by sroy3** [iterative/vscode-dvc#5182]
We should reduce the number of branches in the switch/case by having an enum instead:

```
const actionToDispatch = {
  ...
  [PlotsDataKeys.PLOT_ERRORS]: updatePlotErrors
  [PlotsDataKeys.SELECTED_REVISIONS]: updateSelectedRevisions
  ...
}
```

and a simple `dispatch(actionToDispatch[key](data.data.key))`

_Originally posted by @sroy3 in https://github.com/iterative/vscode-dvc/pull/5165#discussion_r1446163741_

**Comment by mattseddon** [comment]
Taking this just to get back into my IDE
