### ISSUE TITLE
Auto push experiments

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#5201]
Related to https://github.com/iterative/dvc/issues/10137. In that issue, there is a proposal to:
1. Auto push experiments that have been completed
2. Enable auto pushing as part of Studio login

VS Code could start doing this without DVC CLI support if it can detect when experiments complete. To do this, the extension should:
1. Enable auto pushing experiments when setting up the connection to Studio. We can enable auto push by default, and have an option to disable it with an explanation of what it does.
2. When detecting that an experiment has finished, push that experiment.

We may run into lock issues if we are pushing multiple experiments and running other dvc operations simultaneously. In manual testing, I found that I ran into lock issues running `dvc exp run` while `dvc exp push` was running. @pmrowla Thoughts on whether `dvc exp push` needs the lock?

**Comment by pmrowla** [comment]
`dvc exp push` needs to lock the git repo. If we are automating the push we should do it through DVC since we can control when the push happens (and we will know when its possible/safe to acquire the lock)

So vscode would just set something like `core.exp_auto_push = true` or an env var to do the same thing

**Comment by dberenbaum** [comment]
The idea is that it would be nice if pushing could happen "in the background." It might be fine if this is blocking if we show that it's happening and provide a way to cancel it in both CLI and VS Code.

@pmrowla If we do it through the CLI, how can VS Code know when the experiment has finished and pushing the experiment has started?

**Comment by mattseddon** [comment]
> a way to cancel it in both CLI and VS Code

When running an experiment through the extension a terminal instance shows the output from DVC. The user can cancel by either closing the terminal or hitting the big stop button:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/f968b36a-db06-445a-a168-3c22ba2ade73">

If an additional value (e.g. "pushing") was added to the executor state that should be enough for the extension to update the UI when the experiment has finished running and started being pushed. A user would be able to differentiate and cancel if they feel the need.

**Comment by dberenbaum** [comment]
I'm not sure we even need an additional state. If `exp show` shows the experiment as completed once the push step starts, I think that would be enough since the CLI output can already explain that it's pushing and it's safe to stop the experiment if you don't want to wait for the push to complete.

**Comment by mattseddon** [comment]
Without the extra status we will either have to make assumptions on the extension side or not show a spinner whilst the experiment is being "auto pushed". I.e. the behaviour shown below:


https://github.com/iterative/vscode-dvc/assets/37993418/ceedaf57-6ebf-430f-b393-fc760463645e
