### ISSUE TITLE
DVC . The located version has not been tested against the extension. If you are experiencing unexpected behaviour, first try to update the extension. If there are no updates available, please downgrade DVC to the same minor version as displayed and reload the window.

### ISSUE THREAD

**Issue by YaznonovMirzabek** [iterative/vscode-dvc#5292]
i dont know is it error or not. if it is error then how to solve it?

The located version has not been tested against the extension. If you are experiencing unexpected behaviour, first try to update the extension. If there are no updates available, please downgrade DVC to the same minor version as displayed and reload the window.

![111](https://github.com/iterative/dvc/assets/133767941/37b4e35e-8340-47cd-a85a-a10a8ca251b5)

please help

**Comment by efiop** [comment]
@YaznonovMirzabek So are you experiencing any unexpected behaviour? Have you tried downgrading dvc as suggested in the message?

**Comment by mattseddon** [comment]
Hi @YaznonovMirzabek the message you are seeing is a warning. 

If you are not experiencing unexpected behaviour then please disregard it. 

The message will disappear with the next release of the extension.
