### ISSUE TITLE
Remove DVC from Source Control Tab

### ISSUE THREAD

**Issue by RaW-Git** [iterative/vscode-dvc#5471]
Hi,
I would like to remove the DVC tracked files from the Source Control Tab in VS Code. In my setup I have two machines: my local one for development without the complete data and just some experiments, and a remote server with all data. This leads to the VS Code source control tab being completely overloaded and sometimes breaking down when I click on it:
<img width="55" alt="Screenshot 2024-04-17 at 11 17 47" src="https://github.com/iterative/vscode-dvc/assets/27215944/f35eb85d-5e72-45da-afa0-2f1935926e7a">
Is it possible to use the DVC extension, but disable it for the Source Control Tab, couldn't find any option for that.
Best,
Ramon

**Comment by shcheklein** [comment]
@RaW-Git could you give more details? what exactly does it show in the source control tab and why?

**Comment by RaW-Git** [comment]
It kind of fixed itself (I think it was a indirect DVC checkout or pull caused by `dvc exp run`), not 100% sure though, but I can't see that huge diff anymore. 
I think it started when I did a `dvc pull` on a subdirectory of a dvc tracked directory.

For example:
`/data/a` -> tracked by `a.dvc`
and I did `dvc pull /data/a/b`.

**Comment by shcheklein** [comment]
okay, thanks! I'll close it then and let us know if that happens again, we can take a look.
