### ISSUE TITLE
Handle gracefully DVC-tracked/SCM actions when DVC is already busy

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#606]
## Details

<img width="437" alt="Screen Shot 2021-06-29 at 2 49 56 PM" src="https://user-images.githubusercontent.com/3659196/123876551-626d1a00-d8f0-11eb-91b4-03681b4354af.png">

## Reproduce

Take a repo with large DVC-tracked directories, pull one, while it's running trigger the second pull.

## Expected

I think we should handle this gracefully. Block actions? Show that something else is running? Other ideas?

## Extension version

`0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5`

## DVC Version

```
DVC version: 2.4.2+61835f
---------------------------------
Platform: Python 3.8.9 on macOS-10.15.6-x86_64-i386-64bit
Supports: azure, gdrive, gs, hdfs, webhdfs, http, https, s3, ssh, oss
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

## Logs

<details>
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:29:53.477Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc -h 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:29:56.053Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:29:56.577Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list .  --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:29:58.356Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json failed. ERROR: failed to show experiments - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:29:59.063Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:00.346Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:00.824Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:02.865Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:03.122Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:04.999Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . --dvc-only -R --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:09.145Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . models --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:09.223Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json failed. ERROR: failed to get diff - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:10.380Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:12.958Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:13.871Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:15.869Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . --dvc-only -R --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:30:20.438Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . --dvc-only -R --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:35.389Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc pull data/prepared 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:36.058Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:36.232Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:37.906Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:37.993Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:42:47.575Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/raw --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:44:18.435Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc commit data/raw/t10k-images-idx3-ubyte.gz failed. ERROR: failed to commit data/raw/t10k-images-idx3-ubyte.gz - unable to commit changed stage: 'data/raw.dvc'. Use `-f|--force` to force.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:45:44.668Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:45:44.805Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:45:46.831Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:45:51.203Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared/new.file --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:46:18.360Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared/new.file/new.file --dvc-only --show-json failed. ERROR: failed to list '.' - The path 'data/prepared/new.file/new.file' does not exist in the target repository '/Users/ivan/Projects/get-started-experiments' as an DVC output.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:46:30.120Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:46:31.454Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:46:32.137Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:05.227Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:07.059Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:07.884Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:48.700Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:50.424Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:55.446Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:47:56.252Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:05.745Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json failed. ERROR: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:05.763Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp run 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:06.095Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json failed. ERROR: failed to get diff - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:06.325Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list .  --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:06.348Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:08.355Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:08.368Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . models --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:08.492Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:10.315Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:10.509Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:10.862Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/raw --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:11.067Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:13.408Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:14.260Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:48:21.069Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . --dvc-only -R --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:03.593Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:05.772Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json failed. ERROR: failed to get diff - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:06.251Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:08.333Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:09.915Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:12.206Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp run 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:12.682Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:14.059Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json failed. ERROR: failed to get diff - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:14.628Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:14.994Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc exp show --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:16.534Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:18.235Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:20.189Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:21.834Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:25.601Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared/new.file --dvc-only --show-json failed. ERROR: failed to list '.' - The path 'data/prepared/new.file' does not exist in the target repository '/Users/ivan/Projects/get-started-experiments' as an DVC output.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:48.233Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc pull data/prepared failed. ERROR: failed to pull data from the cloud - Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:51.826Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc pull data/raw 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:52.292Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:52.597Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc diff --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:54.263Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/prepared --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:54.337Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc list . data/raw --dvc-only --show-json 
[version: 0.1.0-7ed06bac1b0a1cbce9454d566a53a3f53c1056b5, 2021-06-29T21:49:54.491Z] > /Users/ivan/Projects/get-started-experiments/.env/bin/python dvc status --show-json
</details>

**Comment by mattseddon** [comment]
We can start by blocking further actions when any SCM action is running.
