### ISSUE TITLE
exp --queue and --run-all can hang and cause future exp show runs to hang

### ISSUE THREAD

**Issue by rogermparent** [iterative/vscode-dvc#828]
The original Issue has since been solved, but there's still a related problem which this Issue now tracks. See [this comment](https://github.com/iterative/vscode-dvc/issues/828#issuecomment-996437072) for info on the still open issue.

---

**Original issue:**

I had mentioned this when working on plots, but it seems this is more of a general problem that occurs on master as well.

After running one experiment, live updating experiments ~stops working~ delays for at least 5 and up to 15 checkpoints before dumping all of them at once, sometimes crashing VSCode in the process. You can see the output changes as well, showing nothing until the experiments finishes and pushing all the checkpoints at once. It almost looks like it could be a dvc issue, but I don't know how it would be considering it's related to the vscode session.

https://user-images.githubusercontent.com/9111807/134056404-8ef0d288-4184-446d-8d8c-c21f7678245b.mp4

This issue also happens when running `dvc exp show` on the CLI outisde of VSCode, with slightly different symptoms on the table itself where updates don't happen until a bit after the command is finished

https://user-images.githubusercontent.com/9111807/134057377-608bd480-3600-4cde-9ed9-7d88dbe8f12d.mp4

I've also check combinations of running from both CLI and VSCode, in both CLI -> VSCode and VSCode -> CLI. Table symptoms reflect the command run second.

**Comment by karajan1001** [comment]
I hadn't noticed any hanging caused by `exp --queue` recently. For the `exp run --run-all` the fetching progress might cause `exp show` to freeze a few seconds, at the result collections progress.
