### ISSUE TITLE
Investigate alternative DVC integrations

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#967]
This ticket will serve as a container for all investigation into alternative DVC integrations.

Options to investigate (incomplete):

- [x] 1. Transpile Python to Javascript (e.g [Transcrypt](https://www.transcrypt.org/), [PyPy.js](https://pypyjs.org/))
- [x] 2. Use bridge library (e.g [Boa](https://github.com/imgcook/boa), [Pythonia](https://github.com/extremeheat/JSPyBridge/))
- [ ] 3. Improve existing integration
- [ ] 4. Typescript rewrite
- [ ] 5. Message passing through files
- [ ] 6. Python-js IPC with named pipes (https://github.com/iterative/vscode-dvc/issues/967#issuecomment-955976810)
- [ ] 7. RPC

Investigations will go in the comments and each comment can / will be updated over time.

**Comment by shcheklein** [comment]
Closing this as we exhausted the ideas for now and can come back later
